### ISSUE TITLE
Cannot reorganize file hierarchy 

### ISSUE THREAD

**Issue by Kersheh** [mozilla/thimble.webmaker.org#1002]
I created a folder and titled it images to upload a simple background image. Upon upload I noticed I cannot drag and drop the png into the images folder. Right-clicking the png also only gives me the options for New File, New Folder, Rename, and Delete.

**Comment by gideonthomas** [comment]
This issue is now morphed into dragging around folders in your file tree to re-arrange them. This means allowing users to move folders into folders, files into folders, etc.

**Comment by humphd** [comment]
I wonder if we should try https://github.com/torinpascal/brackets-duplicate-extension

**Comment by borisrorsvort** [comment]
:+1:  :tada:
