### ISSUE TITLE
Add favicon to published projects.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1009]
Right now, we don't.

![image](https://cloud.githubusercontent.com/assets/25212/9593036/bfb045ba-4ffe-11e5-91cf-00975598c31c.png)

**Comment by humphd** [comment]
http://stackoverflow.com/questions/28594514/favicon-for-amazon-s3-bucket

**Comment by humphd** [comment]
@jbuck can you help with this?

**Comment by jbuck** [comment]
Yep, this is quick and easy

**Comment by humphd** [comment]
Merci!

**Comment by jbuck** [comment]
What favicon am I adding?

**Comment by humphd** [comment]
@flukeout what should @jbuck use as a favicon for published thimble makes on s3?

**Comment by hannahkane** [comment]
should it be the same green Thimble that we use for the editor and homepage? question - can the user override our favicon?

**Comment by humphd** [comment]
Yes, they can do it in their page (e.g., http://stackoverflow.com/questions/260857/changing-website-favicon-dynamically/260876#260876)

**Comment by humphd** [comment]
@jbuck it's this one https://thimble.mozilla.org/img/favicon.png

**Comment by jbuck** [comment]
Uploaded! I think it's working correctly, but would not mind a confirmation...

**Comment by humphd** [comment]
@jbuck I tried publishing and viewing a project: https://d157rqmxrxj6ey.cloudfront.net/humphd/14954/

It doesn't seem to have it.

**Comment by jbuck** [comment]
I see it working for me on that project in Firefox:

![screenshot 2015-11-18 19 39 49](https://cloud.githubusercontent.com/assets/578466/11259008/3694ceec-8e2c-11e5-8693-8f3a413d6e4c.png)

**Comment by humphd** [comment]
Not for me (Firefox or Chrome) so maybe a timing thing with cloudfront?  Let's test tomorrow.

**Comment by humphd** [comment]
Still doesn't work for me in these browsers, but does work in Safari, so I'm going to call this "cache" and say this is fixed.
