### ISSUE TITLE
[crash] thimble.mozilla.org crash SyntaxError: Unexpected token < 

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1011]
@gideonthomas, can you look at this? From Heroku logs on thimble.mozilla.org

```
PUT /projects/276/files/1404 - - ms - - 
Aug 31 18:34:55 bramble-production app/web.1:  undefined:1 
Aug 31 18:34:55 bramble-production app/web.1:  <!DOCTYPE html> 
Aug 31 18:34:55 bramble-production app/web.1:  ^ 
Aug 31 18:34:55 bramble-production app/web.1:  SyntaxError: Unexpected token < 
Aug 31 18:34:55 bramble-production app/web.1:      at Object.parse (native) 
Aug 31 18:34:55 bramble-production app/web.1:      at IncomingMessage.<anonymous> (/app/routes/files/create-update.js:78:21) 
Aug 31 18:34:55 bramble-production app/web.1:      at IncomingMessage.emit (events.js:129:20) 
Aug 31 18:34:55 bramble-production app/web.1:      at _stream_readable.js:908:16 
Aug 31 18:34:55 bramble-production app/web.1:      at process._tickCallback (node.js:355:11) 
Aug 31 18:34:56 bramble-production heroku/web.1:  Process exited with status 1
```

The app also didn't self restart, which would be something nice to have (cc @jbuck).

**Comment by humphd** [comment]
@sedge is manually restarting the prod app now.

**Comment by humphd** [comment]
@gideonthomas it might be good to audit all the routes, and harden them against bad data taking the whole process down.  We should never crash on bad data, undefined, etc.

**Comment by humphd** [comment]
It's a `JSON.parse()` that's crashing us.  Every `JSON.parse()` that isn't wrapped in a `try...catch` is a timebomb waiting to go off.

Find them all via:

```
git grep -C 6 JSON\.parse
```

And let's get them wrapped and returning `500`s instead of crashing

**Comment by gideonthomas** [comment]
Will do! That's weird that it received such a response from publish though! We'll need to investigate that!

**Comment by jbuck** [comment]
@humphd Heroku will [restart](https://devcenter.heroku.com/articles/dynos#restarting) the process automatically once, but if it crashes again it'll delay the restart by 10 minutes and scale that cooldown time up as more crashes happen:

> The first time a dyno crashes, it will be restarted immediately. If the dyno crashes again, it will be subject to a cool-off period before a restart is attempted. The first cool-off period is 10 minutes, the next one is 20 minutes, then 40 minutes, 60 minutes, 180 minutes and 320 minutes. After the 320 minute cool-off period is reached, restart attempts happen every 320 minutes.
> 
> The cool-off period will be reset when the dyno starts correctly, or when you push a new release to your app, or when you restart your app (for example, by typing heroku restart), or when you scale your dynos to 0 and then scale them back up again.
