### ISSUE TITLE
Switch over to promises

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1014]
I was initially very apprehensive about using promises but I'm starting to find issues with the callback system that are making the code messy. Using callbacks lets us mix async and sync code in the same module making it look very different.

For e.g.: 
I wanted to create a utility function that would "safely" parse JSON data (log if it fails instead of throwing). The goal was to avoid doing ```js try { JSON.parse(); } catch(e) { sendResponse(500); }``` everywhere and just do it once. Although this is sync code, I wanted to take advantage of error handling node.js conventions by doing something like:
```js
// Callee
function safeJSON(json, callback) {
  var err = null, result = null;
  try {
    result = JSON.parse(json);
  } catch(e) {
    err = e;
  } finally {
    callback(err, result);
  }
}

// Caller
safeJSON(myJson, function(err, obj) {
  if(err) {
    sendResponse(500);
  } else {
    // Use obj
  }
}
```

But this is really ugly and has way too many lines of code for something that is fairly straight-forward. However, if we use promises (bluebird here), the code ends up looking something like this:
```js
// Callee
function safeJSON(json) {
  return Promise.try(function() {
    return JSON.parse(json);
  });
}

// Caller
safeJSON(myJson).then(function(obj) {
  // use obj
}).catch(function(err) {
  sendResponse(500);
});
```
This seems to be a much cleaner solution. And, in the interest of not mixing Promises, callbacks and sync code, I suggest we switch over completely to promises, including promisifying our express app.

**Comment by sedge** [comment]
+1

**Comment by humphd** [comment]
I don't think this is likely to happen.  If you want to do it, open a PR with the change.  Closing.
