### ISSUE TITLE
Use 'monospace' as a fallback before 'fixed'

### ISSUE THREAD

**Issue by flannelhead** [mozilla/thimble.webmaker.org#1019]
On my Linux system, the X11 [Fixed](https://en.wikipedia.org/wiki/Fixed_%28typeface%29) bitmap font gets selected as the font for the editor. This is caused by the `.CodeMirror` element having a `font-family` with `fixed` as the last fallback font. A standard alias for the default monospace font (at least on Linux systems) is `monospace`, which normally points to some antialiased font (see `fc-match monospace`), which would be a better fit for the editor font.

**Comment by flukeout** [comment]
Thanks @flannelhead - can you paste in a screenshot of what you're seeing?

**Comment by flannelhead** [comment]
Sure.
This is what I see before any modifications:
![2015-09-01-215712_1366x768_scrot](https://cloud.githubusercontent.com/assets/5001906/9613514/7cf3d81c-50f4-11e5-8f4f-219798798bc2.png)
After adding `monospace` before `fixed` to the `font-family` list:
![2015-09-01-215645_1366x768_scrot](https://cloud.githubusercontent.com/assets/5001906/9613525/902d8ed2-50f4-11e5-9bd4-cee4f44cfa38.png)
The second screenshot is what I'd except to see as a monospace font in a code editor.

**Comment by humphd** [comment]
Thanks for filing.  I've patched Brackets in https://github.com/humphd/brackets/pull/453

**Comment by humphd** [comment]
@flannelhead I pushed my fix to our staging server, if you want to take it for a spin:

https://bramble.mofostaging.net/

**Comment by flannelhead** [comment]
Thank you for the fix, it now works as expected :)
