### ISSUE TITLE
404 page has broken images

### ISSUE THREAD

**Issue by err0** [mozilla/thimble.webmaker.org#1021]
poking around it looks like the 404 page has broken images: https://d157rqmxrxj6ey.cloudfront.net/

<img width="170" alt="Thimble by mozilla" src="https://thimble-beta.webmaker.org/img/thimble-logo.svg">
should be 
<img width="170" alt="Thimble by mozilla" src="https://thimble.webmaker.org/img/thimble-logo.svg">

**Comment by gideonthomas** [comment]
@flukeout can you take a look at this? It seems like with the domain switch, all the `thimble-beta` urls are now broken. The fix would be to change them to `thimble.mozilla.org`

**Comment by gideonthomas** [comment]
I can probably fix this

**Comment by gideonthomas** [comment]
@sedge (once you're back) or @jbuck I don't have permissions to edit the 404 page, would one of you be able to make the change?

**Comment by jbuck** [comment]
@gideonthomas Okay, fixed!
