### ISSUE TITLE
Get analytics for first week of new Thimble

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#1022]
@adamlofting - can you please grant me access?

**Comment by adamlofting** [comment]
I will do asap, but we've not been collecting any data yet (the domain name changed and GA was setup to look for traffic to thimble.*webmaker*.org).

Once the GA account is updated (bug below) and I have further permissions, I can share access with the team.
https://bugzilla.mozilla.org/show_bug.cgi?id=1200562

Can we start a list in this ticket of who would like access (they have to have a mofo email address).

**Comment by adamlofting** [comment]
GA is wired up correctly and collecting data now. :+1: 

Anyone else who needs access can ping me and I'll add them.

**Comment by hannahkane** [comment]
Thanks, @adamlofting.

@HPaulJohnson - wondering if you'd want to see Thimble analytics?

**Comment by humphd** [comment]
@jbuck also has some pretty incredible server graphs of the amount of traffic and data we've pushed this week.  It's epic.
