### ISSUE TITLE
You should be able to Drag 'n Drop into a folder vs. the root of the file tree

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1023]
Taken from https://github.com/mozilla/thimble.webmaker.org/issues/1002

When we dnd anything into the file tree, it is put directly into the project root. However, we should also support dnding into a folder that is visible in the file tree

**Comment by humphd** [comment]
This is in Bracket's "IceBox" https://trello.com/c/xwNIcxO6/347-drag-drop-from-os-to-file-tree-copy-move-file btw

**Comment by bonyboy** [comment]
If we can't create custom folders, would it be possible to preload the session with some popular folders (js, css)?

**Comment by humphd** [comment]
You can create custom folders, and put files in them. Just right-click, "New Folder" and then right click on the folder to put a new file in there.  Not as good as it could be, but it will all work.

**Comment by bonyboy** [comment]
Ah! I see that now, thanks.  Would it be possible to add that to the (+) dropdown?  I doubt I'll forget it now, but for someone coming in new, having 2 ways to create files/folders that don't offer the same options might be confusing?

**Comment by humphd** [comment]
We've compromised on a "Move To..." option in the right-click context menu, which has landed.  I'm going to close this.
