### ISSUE TITLE
Explore UX options for moving files between folders.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1024]

**Comment by flukeout** [comment]
Here's a spec for moving files around with the right-click menu...

![image](https://cloud.githubusercontent.com/assets/25212/9750611/ec21d860-564e-11e5-8796-a5fbea5b0ddb.png)

@gideonthomas @humphd Let me know if you have thoughts and questions.

**Comment by humphd** [comment]
I love this.  Simple, yet gives us what we need without ripping out the entire file tree.  I'd say +1 to implementing it.  @gideonthomas, do you want to add to your list?

**Comment by gideonthomas** [comment]
Sure, as soon as I finish one of the other P1s, I can take this on

**Comment by gideonthomas** [comment]
@flukeout is it a good idea to include "Project root" in the Move to list? Can we avoid it altogether? What does it do if we click on it can can we substitute that functionality with something like "Copy to"? I would vote to eliminate that option completely

**Comment by humphd** [comment]
@gideonthomas, his point is that if you have some file deep in a dir, how do you get it to `/`?  You need some way to put it in the root.  It would only show if the file/folder *isn't* already in the root.

**Comment by humphd** [comment]
Something I noticed today on the GMail Android app when I wanted to move an email to a new folder is that it created a flat list of the entire folder structure in my mailbox, allowing me to scroll to what I wanted right away without haivng to go really deep:

Instead of doing:
```
a
  b
    c
  d
```

It did:
```
a
a/b
a/b/c
a/d
```

When  name was really long, it would shorten it in the middle: `/some/long/..../path` such that you could see the start and end clearly.  It seemed kind of nice.

**Comment by gideonthomas** [comment]
@humphd I actually think that @flukeout's suggestion might be a better fit here because I feel like users might find it more familiar to work with.

**Comment by flukeout** [comment]
Another alternative that might be worth doing is building a flat but indented list.

**Comment by gideonthomas** [comment]
@flukeout brackets doesn't support submenus unfortunately :(
@humphd and I were discussing this and found that it might be a but complicated to implement submenus on our own. We figured it might be easier to just do a modal that shows you a set of folders that you can move a file to, when you click on the "Move to" option in the file menu. 
Do you have any suggestions/design prototypes for what this should look like? I'd be happy to implement.

**Comment by flukeout** [comment]
@gideonthomas Sure thing - you're talking about the regular old popup that we use for the file upload feature, right?

**Comment by flukeout** [comment]
Here is a slightly fancy solution in the style of the mac's finder...

![image](https://cloud.githubusercontent.com/assets/25212/10140830/23716ca6-65cf-11e5-8d82-8a5378531fad.png)

Each column would have to scroll vertically if there were too many folders to fit, and the whole thing would have to scroll horizontally to accomodate a very deep folder structure.

@gideonthomas Do we have control over the height and with of the popup?

I think i'll create a simpler option as well.

**Comment by flukeout** [comment]
Simpler, flat version. Shows all nested folders in one scrollable list.

![image](https://cloud.githubusercontent.com/assets/25212/10141619/2cd40700-65d3-11e5-8590-cb9bf8cf824f.png)

**Comment by gideonthomas** [comment]
@flukeout what would this look like for the dark theme?

**Comment by flukeout** [comment]
@gideonthomas Good Q - I'm not really digging that we have themes for the popups in general. I don't mind if it stays white.

**Comment by humphd** [comment]
This landed, closing.
