### ISSUE TITLE
Explore & ideate on social features in Thimble.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1025]
There are lot of opportunities to make Thimble more social...
* Comments on published Thimble projects 
* Favorites
* User profiles with projects
* Browsable Remix history from within a Published project
  * Like Remix tennis or something like that
* Notifications for authors on how many time something they made was remixed, and links to see it
* Stats! How many times was my project viewed.
• Screen share / collaborative editing Together JS

@Pomax and I had a nice interaction where he remixed my project and we both had a chuckle. Exposing that remix history and keeping track of it within Thimble would be awesome and would encourage further activity.

Anyway - just leaving this as an open issue for when I get back - drop your thoughts in. Also, what worked well in old Thimble?

**Comment by jgmac1106** [comment]
In old Thimble you had to chase back the remix trail. There would be a link
over a user profile pic that brought you back to that make. You can follow
this make back to degrees to get to original:
https://jgmac1106.makes.org/thimble/LTU5NjE4MDQ4MA==/zoe-sheri-and-ariels-comic-strip

As I had said earlier I think a cool feature would be having a Thimble
Discourse or a category in TLM's Discourse just for Thimble and code helps.
As educators and clubs start picking it up we could build the community
capacity for something like the code help on stack exchange.

What would be really neat would be if I could arrange my projects in my
profile. There could be a featured spot for two to three makes and a place
for me to categorize my projects.

**Comment by jgmac1106** [comment]
I left this in a comment on another issue when @hannahkane was asking about wireframes for the member directory pages on teach.mozilla.org. Is there a way a club could maintain their directory in Thimble and have an API push it to the teach site?

That's probably fraught with security issues but just trying to think about ways to build in social into the community as well as code. We should develop a club toolkit that could be remixed and downloaded.

For self-directed learners make profile page an intro level tutorial into html. Go over links, images, an headers.

cc ?@chadsansig

**Comment by hannahkane** [comment]
Just wanted to remind ppl of the Thimble Roadmap: http://bit.ly/1Q9yokU

Many of the features above are on it, grouped into thematic releases. Would love feedback on that document.

**Comment by hannahkane** [comment]
/cc @ldecoursy re: @jgmac1106's idea above about a Thimble-specific thread in Discourse

@jgmac1106 - I really like the idea of making the projects on the profile curate-able. I added that to the roadmap (in the "related work on teach.mozilla.org" section of v2.2)

Still a bit confused about the "Club directory." Not sure we're talking about the same thing. When I talk about the "Directory," I mean a Directory *of* Clubs, but I think you're talking about a Directory *for* each Club. Is that right? If so, could you open a separate ticket (in teach.webmaker.org repo) where you describe the need for that?

**Comment by jgmac1106** [comment]
@hannahkane Just because I wrote it does not make it a good idea. O nly get two of those a month. I will go hunt down your original ticket in the other repo.
