### ISSUE TITLE
Explore ways to auto-include common JS libs, CSS frameworks, etc.

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1026]
From https://news.ycombinator.com/item?id=10154418

<blockquote>This is pretty awesome though I would like to see the ability to pull in JS and CSS libraries and frameworks into a project. This could gear some tutorials around certain technologies.</blockquote>

I agree, I'd love that too.  Needs UX.

**Comment by gideonthomas** [comment]
cc @flukeout
