### ISSUE TITLE
Can we have less.js support?

### ISSUE THREAD

**Issue by windinsky** [mozilla/thimble.webmaker.org#1027]
it's so common you know~

**Comment by humphd** [comment]
Are you thinking in terms of syntax highlighting, automatic .less -> .css compilation, or something else?  We actually have all that code in the editor, we just haven't turned it on at the moment.

**Comment by Badestrand** [comment]
Both would be insanely great!

**Comment by humphd** [comment]
Connected to #1104, in terms of implementation.

**Comment by humphd** [comment]
Backend work is underway in https://github.com/humphd/brackets/pull/465

**Comment by humphd** [comment]
I've landed a first pass at this, which you can test at https://bramble.mofostaging.net.  For now, what I've done is to automatically generate a CSS file for a given LESS file.  See what you think.  You can link to the generated CSS file in your project, and it will "just work".

**Comment by jgmac1106** [comment]
I tired doing it from a zip file and got this error: I
![unnamed image 3](https://cloud.githubusercontent.com/assets/10534566/10060090/ac517a86-621c-11e5-96a3-f5e04621de6e.png)
 will try if I unzip locally and upload each file.

**Comment by humphd** [comment]
Is that file doing an import of other LESS files?  That will break atm.  I'd have to write more code to allow it to find those files...

**Comment by jgmac1106** [comment]
Probably it was just a template from:
http://startbootstrap.com/template-overviews/freelancer/

I don't even really know what a LESS file is. I just knew that the template
 had one and I wanted to see what happened with the auto unzip.

**Comment by humphd** [comment]
OK, perfect, thanks for the link.  It's doing:

```less
@import "variables.less";
@import "mixins.less";
```

Which is a special LESS directive to pull the contents of `variables.less` and `mixins.less` into this file.  I'll need to add a rewrite step for these.

**Comment by humphd** [comment]
Talked to @flukeout about this, and our partial support for LESS is probably "good enough," since what he really wants is the easier selector syntax.  I'm going to close this, since it's in and landed.  If we ever decide to expand it so that it works with external file imports, we'll need to make it a manual process you run via UI.
