### ISSUE TITLE
Custom [sub]domains

### ISSUE THREAD

**Issue by c0nfused** [mozilla/thimble.webmaker.org#1028]
Would like an option to create an A or CNAME DNS record for a custom url when publishing projects. Similar to how GitHub Pages works would be fantastic!

**Comment by humphd** [comment]
It's an interesting idea, thanks for suggesting it.

cc @simonwex, @davidascher, @jbuck

**Comment by jbuck** [comment]
This would be cool, but how would we do SSL?
