### ISSUE TITLE
Create a new Thimble project starting from an existing Github repository

### ISSUE THREAD

**Issue by pditommaso** [mozilla/thimble.webmaker.org#1029]
Thimble is awesome however is extremely unpractical having to upload files from the local computer, specially for projects with many files. 

It would be spectacularly useful the ability to create a new project starting from an existing Github repository.

**Comment by jgmac1106** [comment]
If you can pull this off it will be amazing. I started last night trying to
get website templates from git to Thimble for my classes. Downloaded and
expanded the zip files now I need to upload.

**Comment by humphd** [comment]
Yeah, it's an interesting idea.  Until then, you can do the following right now:

![import-from-github](https://cloud.githubusercontent.com/assets/427398/9632345/9f2be1d0-5154-11e5-8f44-703eea9009e0.gif)

You can also select multiple files at once and drag them in, if you don't have a zip file.  The only thing you can't do is drag a folder in--browsers won't allow this.  But if you zip it all up, folders are fine.

**Comment by jgmac1106** [comment]
So cool!

**Comment by humphd** [comment]
I think importing the zip file is a close as we're going to get right now, closing.
