### ISSUE TITLE
Is using the same email address multiple times a violation of ToS or privacy

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#1030]
I have had some teachers ask how to sign up for Thimble if there students do not have email addresses. I want to suggest using their own gmail account and adding name+(n+1) for every student.

Before I did a write up on how to use this strategy I wanted to make sure it was in compliance.

**Comment by hannahkane** [comment]
This is not a violation of our ToS, though please know that, according to our terms, Webmaker accounts are not available to users under the age of 13, and users between 13 and 17 can only create accounts with parental consent and supervision.

Closing this for now. Feel free to get in touch if you have more questions about this.
