### ISSUE TITLE
Unable to Remix or Start a new Project without Logging-in or Signing-up on Thimble website

### ISSUE THREAD

**Issue by m-hasan-ahmed** [mozilla/thimble.webmaker.org#1031]
If a user does not Log-in or Sign-up on the [Thimble](https://thimble.mozilla.org/) website, he/she cannot Remix any of the projects provided on the Thimble homepage or "Start a project from scratch".

When I tried to remix all those projects without signing-in first, it went to a new empty page where the thimble icon in the middle of the page just kept loading forever, as shown below:

![thimble loading forever](https://cloud.githubusercontent.com/assets/14093427/9633976/e1619b2c-51a8-11e5-93a5-4d92bd260a6d.png)

However, when I signed-in to the Thimble website and then tried to Remix those projects, it worked.

![thimble working](https://cloud.githubusercontent.com/assets/14093427/9634220/12db805e-51aa-11e5-96f6-d506e4e4c0fa.png)

I hope this bug will be resolved soon.

**Comment by humphd** [comment]
This is interesting, thanks for filing.  Can I ask, when you try to remix and are *not* signed in, what do you see on the web console?  Are there any error messages showing?

We've had word of similar issues for a few people in Firefox, but can't reproduce this, so having your help to track it down would be great.  Also, which version of Firefox are you running?

**Comment by m-hasan-ahmed** [comment]
I am using latest Firefox 40.0.3 on Windows 8.1.

**Comment by m-hasan-ahmed** [comment]
**1) Web Console on "Start a project from scratch" page:**

Filer error:  Object { name: "EINVAL", code: "EINVAL", errno: 18, message: "IndexedDB cannot be accessed. If pr…", stack: "e@https://mozillathimblelivepreview…" } bramble.js:3:4004

[Bramble] Failed to load Project state, with Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:1:244

[Thimble Error] Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } bramble-editor.js:38:11

[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
@https://mozillathimblelivepreview.net/bramble/production/dist/main.js:8:21477
i/jQuery.fn.init@https://mozillathimblelivepreview.net/bramble/production/dist/main.js:39:10980
n@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/thirdparty.min.js:4:17337
@https://mozillathimblelivepreview.net/bramble/production/dist/extensions/default/brackets-paste-and-indent/main.js:1:567
ga/i.execCb@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:11615
ga/Z.prototype.check@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:6010
ga/Z.prototype.enable@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:8511
ga/Z.prototype.init@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:5170
E@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:3750
ga/i.completeLoad@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:10922
ga/i.onScriptLoad@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:11740
 main.js:8:21535
Registering for deprecated event 'currentDocumentChange'. Instead, use MainViewManager.currentFileChange. u@https://mozillathimblelivepreview.net/bramble/production/dist/main.js:8:13981
@https://mozillathimblelivepreview.net/bramble/production/dist/extensions/default/brackets-paste-and-indent/main.js:1:567
ga/i.execCb@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:11615
ga/Z.prototype.check@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:6010
ga/Z.prototype.enable@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:8511
ga/Z.prototype.init@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:5170
E@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:3750
ga/i.completeLoad@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:10922
ga/i.onScriptLoad@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:11740
 main.js:8:13965
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011

**Comment by m-hasan-ahmed** [comment]
**2) Web Console on "Remixing the 'Keep Calm' project" page:**

InvalidStateError bramble.js:3:0
Filer error:  Object { name: "EINVAL", code: "EINVAL", errno: 18, message: "IndexedDB cannot be accessed. If pr…", stack: "e@https://mozillathimblelivepreview…" } bramble.js:3:4004

[Bramble] Failed to load Project state, with Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:1:244

[Thimble Error] Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } bramble-editor.js:38:11

[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
@https://mozillathimblelivepreview.net/bramble/production/dist/main.js:8:21477
i/jQuery.fn.init@https://mozillathimblelivepreview.net/bramble/production/dist/main.js:39:10980
n@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/thirdparty.min.js:4:17337
@https://mozillathimblelivepreview.net/bramble/production/dist/extensions/default/brackets-paste-and-indent/main.js:1:567
ga/i.execCb@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:11615
ga/Z.prototype.check@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:6010
ga/Z.prototype.enable@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:8511
ga/Z.prototype.init@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:5170
E@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:3750
ga/i.completeLoad@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:10922
ga/i.onScriptLoad@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:11740
 main.js:8:21535
Registering for deprecated event 'currentDocumentChange'. Instead, use MainViewManager.currentFileChange. u@https://mozillathimblelivepreview.net/bramble/production/dist/main.js:8:13981
@https://mozillathimblelivepreview.net/bramble/production/dist/extensions/default/brackets-paste-and-indent/main.js:1:567
ga/i.execCb@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:11615
ga/Z.prototype.check@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:6010
ga/Z.prototype.enable@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:8511
ga/Z.prototype.init@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:5170
E@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:3750
ga/i.completeLoad@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:10922
ga/i.onScriptLoad@https://mozillathimblelivepreview.net/bramble/production/dist/thirdparty/require.min.js:1:11740
 main.js:8:13965
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011
[Brackets Filesystem] Unknown I/O error Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:12:21011

**Comment by humphd** [comment]
This looks like https://bugzilla.mozilla.org/show_bug.cgi?id=944918 to me.

**Comment by m-hasan-ahmed** [comment]
Update: Forgot to mention that for me, this issue is occurring while using Firefox in Private Browsing Mode.

Working fine in a normal Firefox session using **Options** -> **Privacy** panel -> **Remember History** setting.

**Comment by m-hasan-ahmed** [comment]
Facing the same issues as described above on latest Firefox 40.0.3 on Android Kit Kat 4.4.4 as well.

**Comment by humphd** [comment]
If you're in private browsing mode, that makes sense.  I think Firefox disallows JS to touch the db in that case.

**Comment by humphd** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=781982
