### ISSUE TITLE
Allow users to access browser console

### ISSUE THREAD

**Issue by mejackreed** [mozilla/thimble.webmaker.org#1032]
When teaching new JavaScript students, using the console to debug is a basic tool that should be taught. Could thimble be modified to allow console access to global JavaScript scope?

**Comment by humphd** [comment]
We've talked about it (see https://github.com/mozilla/thimble.webmaker.org/issues/427), and I've started a patch to make it possible.

For now you can experiment by adding this code to your `index.html`:

```html
<script src="https://getfirebug.com/firebug-lite.js#startOpened"></script>
<script>
window.onerror = function(msg, url, line) {
  console.error(msg, "at", url, "line", line);
};
</script>
```

**Comment by mejackreed** [comment]
Great thanks! :smile_cat:

**Comment by humphd** [comment]
I'm going to close this for now, and maybe follow-up in #427.  I'm unclear if we'll go this route yet or not, but at least it's filed with a workaround.
