### ISSUE TITLE
Investigate frequent crashes due to publish.wm.org sending html vs. JSON

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1033]
We have gotten into this a couple of times now where the express app crashes because `JSON.parse` fails. We have a fix in that surrounds every `JSON.parse` with a try/catch so that we don't crash.

However, the issue still remains that we shouldn't be failing to `JSON.parse` anything. We get an error resembling this:
```
Sep 02 08:25:57 bramble-production app/web.2:  undefined:1 
Sep 02 08:25:57 bramble-production app/web.2:  <!DOCTYPE html> 
Sep 02 08:25:57 bramble-production app/web.2:  ^ 
Sep 02 08:25:57 bramble-production app/web.2:  SyntaxError: Unexpected token < 
Sep 02 08:25:57 bramble-production app/web.2:      at Object.parse (native) 
Sep 02 08:25:57 bramble-production app/web.2:      at IncomingMessage.<anonymous> (/app/routes/files/create-update.js:78:21) 
Sep 02 08:25:57 bramble-production app/web.2:      at IncomingMessage.emit (events.js:129:20) 
Sep 02 08:25:57 bramble-production app/web.2:      at _stream_readable.js:908:16 
Sep 02 08:25:57 bramble-production app/web.2:      at process._tickCallback (node.js:355:11) 
```

Seems like publish.webmaker.org is somehow sending us HTML (probably due to a crash) and we fail to `JSON.parse` it.

**Comment by humphd** [comment]
cc @ashleygwilliams, @jbuck 

As @jbuck said, it's probably the Heroku 500 HTML page being sent back.  Do we have a crash stack for Publish?

**Comment by gideonthomas** [comment]
It doesn't seem like publish is "crashing" per se because we haven't restarted it when this happens.

**Comment by humphd** [comment]
Jon said that heroku will automatically restart an app on crash.

On Sep 2, 2015 12:13 PM, Gideon Thomas <notifications@github.com> wrote:

It doesn't seem like publish is "crashing" per se because we haven't restarted it when this happens.

**Comment by sedge** [comment]
@gideonthomas It should be pretty easy to see if Publish is crashing. The `papertrail` heroku addon we have lets you search all the logs.

**Comment by gideonthomas** [comment]
@sedge unfortunately the free version has a limit on the number of logs and we keep running into that

**Comment by sedge** [comment]
Luckily there's a more direct source of this information [here](https://dashboard.heroku.com/apps/publish-webmaker-org-prod/metrics/web)

**Comment by humphd** [comment]
I'm going to close this, and we can file new bugs as we find things with the improved logging.
