### ISSUE TITLE
Explore sending DIFFs vs. complete files

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1039]
@jbuck was showing us some graphs of traffic the other day, and there's a lot of data going over the wire.  I'd be interested to figure out if it's worth altering how we send data from the browser to Thimble/Publish when we save files.

Right now we autosave the files every ~5s (when dirty) into the filesystem, and then do a POST with the complete file.  Files that don't change often won't get sent, but files you're working in will get sent over and over.  So far I haven't heard users complaining about this, but if it becomes a problem, we could consider doing DIFFs instead.

I don't think we should do rsync style syncing, due to complexity, but doing a fail-fast approach with sending a diff and hash might work.  Basically you'd send a diff + the hash of the file you diffed against (the last version the server *should* have).  The server would look at the hash, compare to what it has, and either take the diff and apply it, or reject it and ask for the full file again.

In the case that a user is just working+saving over and over, this should work fine, and would mean we only need to send diffs 99% of the time, which would be small.  If more complex cases arise, and for some reason the versions aren't linear, we'd just reject the diffs and do full files, which is no worse than what we have now.

Let's start by figuring out if we need this or not, from a bandwidth point of view.

**Comment by gideonthomas** [comment]
I don't think we're gonna be doing this anytime soon, closing
