### ISSUE TITLE
Remix Bug

### ISSUE THREAD

**Issue by cathyatseneca** [mozilla/thimble.webmaker.org#1040]
When you make your own project and publish it, the remix button changes the index.html back to the default index.html content.

https://d157rqmxrxj6ey.cloudfront.net/umleung/3508/

**Comment by humphd** [comment]
@cathyatseneca, can you get me some more idea on what you did, and what you're expecting?  That page you link to isn't the default page for me.  I wonder if you got a caching issue?

**Comment by cathyatseneca** [comment]
My index.html should have had:

<!DOCTYPE html>
<html>
<head>
  <script src="p5.min.js"></script>
  <script src="tree.js"></script>
</head>
<body>
<h1>
  Hi
  </h1>
</body>
</html>

**Comment by humphd** [comment]
This is only happening on production, it seems.

**Comment by humphd** [comment]
https://d157rqmxrxj6ey.cloudfront.net/humphd/3640/ is me remixing, pasting in the proper HTML, it worked for me.  So this isn't all the time:

https://d157rqmxrxj6ey.cloudfront.net/humphd/3640/
