### ISSUE TITLE
Bundle the homepage to serve one js file

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1041]
When we serve the homepage, we make multiple requests to get main.js, uuid.js, cookie.js...
We should build them into one main.js file and serve that instead

**Comment by sedge** [comment]
This is all set up in [the](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/Gruntfile.js#L187-L213) [gruntfile](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/Gruntfile.js#L159-L174). All you need is to specify an entry point and it should be easy to get going.
