### ISSUE TITLE
Can't delete non-empty folder

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/thimble.webmaker.org#1042]
Expected non-cli filesystem usage: folders should delete whether or not they have stuff inside them.

**Comment by humphd** [comment]
Interesting.  We can easily make it work that way.  I wonder if that's what people would expect?

cc @xmatthewx, @flukeout

**Comment by secretrobotron** [comment]
That's what I'd expect from the Finder, or even Sublime.

**Comment by humphd** [comment]
In the absence of "no, don't do that!" from our designers, I'm going to assume this is fine.  I'll fix in Bramble.

**Comment by flukeout** [comment]
Sounds good!

**Comment by flukeout** [comment]
@humphd Sorry for the late entry here, but yes, we should be able to delete folders with content!

**Comment by humphd** [comment]
Cool, we landed a fix for this in Bramble to make it possible.  I'll add this to my list.

**Comment by humphd** [comment]
I've got a fix up for review in https://github.com/humphd/brackets/pull/490 that builds on code @gideonthomas landed already.

**Comment by humphd** [comment]
Fixed and landed on staging in Brackets.  This will find its way into production soon.

**Comment by secretrobotron** [comment]
woohoo!
