### ISSUE TITLE
Imported Webmaker projects don't render properly, CSS style attributes parsed incorrectly.

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/thimble.webmaker.org#1043]
A webmaker project (e.g. https://beta.webmaker.org/#/project?user=488656&project=24202) and uploaded to thimble won't render properly. It looks like css files are always missing (main.css).

**Comment by humphd** [comment]
How do I get that app's content so I can try uploading and debug?

**Comment by secretrobotron** [comment]
I just Command+S in Chrome to save the page locally (which renders fine). Then, zip (lol), and upload.

**Comment by humphd** [comment]
I think it's messing up Bracket's DOM instrumentation, see how the `style` attribute is HTML (this is from inspecting the live preview's dom)?

```
<body data-brackets-id="239" style="<div data-brackets-id=&quot;240&quot; id=&quot;player-
```

**Comment by humphd** [comment]
My guess is that this will also break Brackets on Desktop.  I'll test that next week and see, in which case it should get filed upstream.

**Comment by humphd** [comment]
I've got a patch for this upstream in Bramble.  Thanks for finding/reporting it.  I'll try and get it onto production this week.
