### ISSUE TITLE
Inserting image links between 2 quotemarks was not very easy

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/thimble.webmaker.org#1045]
cc @Saallen can provide details if needed

**Comment by humphd** [comment]
@Saallen any chance you can add some details to this?

**Comment by Saallen** [comment]
Sure @humphd 
When we were swapping a new img text onto the Timble page on Safari we had some issues.
If there was no space between the two " "  we couldnt paste the image info in.
There was no issue with this on Chrome or Firefox browsers.
I realise that Thimble was not optimised for Safari at this stage though.
