### ISSUE TITLE
Command + E does not work everywhere

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/thimble.webmaker.org#1046]
When teaching with Thimble today, we would tell the learners to click on cmd+E to edit something. 
But this was not effective all the time, for example, it works for changing colors but it does not work for changing fonts.

=> Is there anyway to know when it is implemented or not?

**Comment by humphd** [comment]
Fascinating idea, to have it work with fonts too (cc @Pomax).  I have also wondered about how to surface info to the user that there is the potential to use an editor, get docs, etc.  This is something we need to figure out for sure.  cc @flukeout

**Comment by humphd** [comment]
We have other bugs on this, closing.
