### ISSUE TITLE
Changing fonts is difficult 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/thimble.webmaker.org#1047]
When remixing Keep Calm and carry on, we wanted to change a font. 
- Go into style CSS 
- Click on the font 
- do Cmd+E 

there is no option to change 
- Clicks on Cmd+K 
- Reads text 

Tries to replace Calibri and other things by Comic Sans for example. not working 

==> What is the correct process?

**Comment by humphd** [comment]
Out of scope, closing.
