### ISSUE TITLE
cmd + K Gives you information about an element, but you actually expect some tips

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/thimble.webmaker.org#1048]
When using Thimble, you end-up doing cmd+K when you are lost and looking for an advice. 
What happens is that the text displayed does not really help you. It tells you what is a class, what is XYZ, but it does not tell you HOW to change it.

It's informative, but today we were 4 mentors, and we did not find answers in cmd+K. 

It would be awesome to revisit it and have some tips for example:
- You are looking to change the font ? Then you should do XYZ ...

cc @Saallen

**Comment by humphd** [comment]
This should be solved via curriclum/tutorials.  Closing.
