### ISSUE TITLE
UI randomly broken on startup

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1053]
I've seen a few screenshots from users, and also experienced this myself.  I suspect it's a combo of restoring state from `localStorage` and just bad CSS in our front end.  A refresh fixed it for me.

![screenshot 2015-09-06 13 38 43](https://cloud.githubusercontent.com/assets/427398/9705747/e9fd12b0-549c-11e5-8fad-be5cc1e691d3.png)

cc @flukeout

**Comment by humphd** [comment]
![screenshot 2015-09-09 16 49 29](https://cloud.githubusercontent.com/assets/427398/9773877/0c5fa412-5713-11e5-9419-a3937db37652.png)

Here's a recent one on prod.  This time I was smart enough to look at the things stored in `localStorage`.  You can see the `firstPaneWidth`, `secondPaneWidth`, and `sideBarWidth` and they all seem sane.  What is going on in our Thimble UI though?

**Comment by flukeout** [comment]
@humphd Good question - can you inspect the CSS values for the Preview column header next time you see this? I'll keep an eye out as well - I haven't run into it myself.

**Comment by sedge** [comment]
I saw this too:

![screen shot 2015-09-10 at 10 12 47 am](https://cloud.githubusercontent.com/assets/1616860/9790544/9e39e604-57a4-11e5-9c34-aec462c6226a.png)

**Comment by humphd** [comment]
I really want to see if we still get this after we land all the UI changes we're doing for Safari/IE on prod.  Let's keep watching what happens with this.  I'm moving to P1.

**Comment by humphd** [comment]
I haven't seen this in quite a while.  I'll file again if I see it happen.
