### ISSUE TITLE
Remix bar overlapped by content

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1055]
Published projects containing css that messes with positioning can make the published version look kinda crappy. I noticed this when making a project that has a big pane with
```less
position: absolute; 
top: 0;
z-index: 5;
```
style rules. This made the pane overlap the remix bar (even if it is under, it looks kinda ugly)  and I couldn't click the remix button because of this.

cc @flukeout

**Comment by flukeout** [comment]
@gideonthomas Do you have a link to the project, would like to see it.

I ran into similar issues myself, the way we push down the content via a padding on the body isn't reliable enough.

**Comment by gideonthomas** [comment]
Hey so the link to the project is: https://d157rqmxrxj6ey.cloudfront.net/gideonthomas/6113/
Or here is a screenshot: of each screen:
**What I see**
![screen shot 2015-09-08 at 3 45 54 pm](https://cloud.githubusercontent.com/assets/5816130/9745983/f6694e36-5642-11e5-882d-cc456c9b258f.png)


**The HTML**
![screen shot 2015-09-08 at 3 46 47 pm](https://cloud.githubusercontent.com/assets/5816130/9745990/07c1de3c-5643-11e5-90a4-71e858344897.png)


**The CSS**
![screen shot 2015-09-08 at 3 47 56 pm](https://cloud.githubusercontent.com/assets/5816130/9745992/1095dc48-5643-11e5-8a42-e43caf25e55d.png)

**Comment by humphd** [comment]
We're fixing this in #1107, closing.
