### ISSUE TITLE
Safari - Unable to see editor after signing in locally

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1060]
After dismissing the browser warning, I'm stuck in this spot after signing in and attempting to load a project...

![image](https://cloud.githubusercontent.com/assets/25212/9746238/b1e41c62-562b-11e5-8f31-721a1200e04e.png)

@humphd What about you?

**Comment by gideonthomas** [comment]
I can reproduce this...it seems like project upgrades aren't happening correctly in safari

**Comment by humphd** [comment]
This is due to `String.prototype.endsWith` being too new for some browsers, including IE and Safari.  I'll do a PR.

```
TypeError: undefined is not a function (evaluating 'path.endsWith('/')')
```
