### ISSUE TITLE
Safari - Loading spinner doesn't spin!

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1063]
This guy just sits here.. motionless..

![image](https://cloud.githubusercontent.com/assets/25212/9747062/44effd7e-5630-11e5-9b08-9ecd3b2dca79.png)

**Comment by flukeout** [comment]
Closing as adding the animation creates a lot of visual glitches - not worth figuring it out at this point.

**Comment by humphd** [comment]
I notice too that the loading spinner for Bramble shows through, which is odd.  Here is what we do with that iframe:

```js
            div.innerHTML = "<iframe id='" + _id +
                            "' frameborder='0' width='100%' height='100%'></iframe>";

            _iframe = document.getElementById(_id);
            if (options.hideUntilReady) {
                _iframe.style.visibility = "hidden";
            }
```

Is there a better way to do this in Safari?

**Comment by humphd** [comment]
This turns out to be https://bugs.webkit.org/show_bug.cgi?id=125565

**Comment by humphd** [comment]
We can't fix this, it's a Safari bug, closing.
