### ISSUE TITLE
non fatal error on start up: Bad locale=[th_TH] missing .json files

### ISSUE THREAD

**Issue by ashleygwilliams** [mozilla/thimble.webmaker.org#1070]
on branch `bramble` fresh clone and set up, i get this on `npm start`:

```
Bad locale=[th_TH] missing .json files in [/Users/ag_dubs/Projects/thimble.webmaker.org/locale/th_TH]. See locale/README (Error: ENOENT, no such file or directory '/Users/ag_dubs/Projects/thimble.webmaker.org/locale/th_TH')
```

server starts fine and appears to operate appropriately

**Comment by humphd** [comment]
cc @alicoding

**Comment by alicoding** [comment]
@ashleygwilliams basically we are expecting `th_TH` inside that `locale` directory, but for some reason it doesn't seem to be there and I guess it's not pulling it when you do `npm install` which should run `npm run download-locales` for you... I don't know what changes there, but to fix this you can just change your `.env` for this line https://github.com/mozilla/thimble.webmaker.org/blob/bramble/env.dist#L97 to be `*` and it should fix it.
