### ISSUE TITLE
Safari: Cannot view list of projects

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1074]
Clicking on "Your Projects" in the dropdown menu does not take you to the project list. Instead, it opens the editor with god knows what project (My guess is that it is creating a new one)
![safari](https://cloud.githubusercontent.com/assets/5816130/9770752/f684e836-56ff-11e5-969e-ce8870f77067.gif)

Seems like I can access the list of projects by typing `https://localhost:3500/projects` in the URL bar though!

**Comment by humphd** [comment]
This works for me on staging.  Can you confirm you are still hitting it?  I'm pretty sure it's fixed.

**Comment by gideonthomas** [comment]
This has been fixed!
