### ISSUE TITLE
Admin access to published Thimble projects

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/thimble.webmaker.org#1077]
Is there a way to access a database or export a list of published URLs from Thimble makes/remixes? 

Specifically, it would be nice to see some remixes of the three featured activities on the Thimble homepage, or original content created in the first few weeks since launch. 

Also good to know if we have this kind of access and get review this periodically until we have a public gallery function.

cc @hannahkane @chadsansing

**Comment by humphd** [comment]
This would need to happen via the publish server.  cc @ashleygwilliams

**Comment by humphd** [comment]
See also https://github.com/MozillaFoundation/mofo-devops/issues/191

**Comment by hannahkane** [comment]
Duped by #1165
