### ISSUE TITLE
Unable to load editor locally in emulated Windows

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1078]
I'm able to hit the localhost via the ip of my mac machine and see this...

![image](https://cloud.githubusercontent.com/assets/25212/9774840/fe90cbe4-56ff-11e5-9edf-b74be85ed4b3.png)

**Comment by flukeout** [comment]
@humphd Were you able to resolve this somehow for your own environment?

**Comment by humphd** [comment]
from irc:

```
17:16 < humph> flukeout: yeah, that's almost certainly cors
17:16 < humph> I did a patch for this in brackets, but not landed yet
17:16 < humph> flukeout: https://github.com/humphd/brackets/pull/459 might fix it
17:16 < humph> IE won't let that bramble script load cross-origin
```

**Comment by flukeout** [comment]
@humphd I'm running your ``dist-cors-fix`` branch of brackets locally, but am still getting the same behaviour in IE - are there any other steps I should try?

**Comment by humphd** [comment]
Depending on your network setup, you probably need to change your `env` file to not use `http://localhost` and instead use `http://<your mac IP address>` everywhere.

**Comment by flukeout** [comment]
@humphd That fixed it.
