### ISSUE TITLE
IE Testing & Bugs

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1079]
As far as I can tell, our UI now works in Edge on IE. Here's a little screengrab from my machine.

![ie-edge](https://cloud.githubusercontent.com/assets/25212/9776065/6aa2a3bc-5709-11e5-8070-9d2bd012f907.gif)

@humphd You found some bugs that you showed me earlier, but I can't find an issue for them.

**Comment by humphd** [comment]
We need this one too: https://github.com/mozilla/publish.webmaker.org/pull/147
