### ISSUE TITLE
Link to style guide in default `tutorial.html` file is broken on production

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#1084]
STR: Add a tutorial file to a project that doesn't have one and click the "style guide" link:

---------------------------

![screen shot 2015-09-10 at 10 17 18 am](https://cloud.githubusercontent.com/assets/1616860/9790643/2a1a5d0c-57a5-11e5-84bd-49cd0fc0a98f.png)

-------------------------

![screen shot 2015-09-10 at 10 17 27 am](https://cloud.githubusercontent.com/assets/1616860/9790653/369d654c-57a5-11e5-9070-964438c93305.png)

**Comment by humphd** [comment]
What's the URL it uses if you inspect that?  Is it absolute?  It should be.
