### ISSUE TITLE
Sanitize text input in Thimble

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1085]
I realized today that we have a few places where we allow users to enter text, and that they could potentially use this to do XSS attacks if we don't sanitize it, specifically:
* project title
* publish description

I think that's all of them.  Let's clean these values so we don't get sec bugs filed against us.

I'm not sure what MoFo's best practices are for this atm.  cc @jbuck for tips.

**Comment by jbuck** [comment]
Don't do sanitization. Seriously!

All you need to do is make sure that you're setting the project title and publish description as text nodes, which can't run any scripts. Also, make sure you have a CSP policy that doesn't allow `'unsafe-inline'`.

**Comment by gideonthomas** [comment]
Hmm, so, in the editor, the title is either text in a `<span>` or the value of an `<input>` tag. The description is a `<textarea>` so they should all be text nodes (although the value of the `<input>` tag is not a textnode right?)
Also, we don't really have a proper CSP policy

**Comment by gideonthomas** [comment]
cc @Pomax
