### ISSUE TITLE
Adding title does not trigger option to update published version

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/thimble.webmaker.org#1089]
STR:
 - create a project
 - publish it
 - view published version
 - edit the title
 - attempt to update under publish
 - only option to unpublish appears
 - refresh published version
 - still appears untitled

**Comment by gideonthomas** [comment]
https://github.com/mozilla/thimble.webmaker.org/issues/751

**Comment by xmatthewx** [comment]
tracking in #751
