### ISSUE TITLE
[IE] Project title pencil icon goes small after saving a change

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1097]
![screenshot 2015-09-11 12 44 58](https://cloud.githubusercontent.com/assets/427398/9820691/7b98119a-5883-11e5-99d6-4b5586ab8a92.png)

STR:
* click the pencil icon to change the title (notice its size)
* make a change, click Save button
* notice pencil icon is tiny

**Comment by flukeout** [comment]
lol

**Comment by flukeout** [comment]
I can't reproduce it, here's the pencil icon in IE11 after saving...

![image](https://cloud.githubusercontent.com/assets/25212/9856013/f4009482-5ac6-11e5-9f64-737d54440152.png)

@gideonthomas Do you have a way to test IE11? If so - can you double-check this when you get a chance?

**Comment by gideonthomas** [comment]
Uhh, I can reproduce on prod! I can't load a project on staging...it seems to be broken!

**Comment by errietta** [comment]
Can't reproduce, I tried both in IE 11 and Edge with IE 11 emulation (Windows 10)

**Comment by errietta** [comment]
@humphd i can't reproduce on win 10, i'm thinking maybe it's version specific since people are getting it on win 7 ...

**Comment by errietta** [comment]
Hi,

managed to reproduce. Apparently it's win 7 only - looks like win 10 has a newer IE 11.
It also happens when you mouse over pencil button, not after editing :smile:

**Comment by humphd** [comment]
Great, so if it's just a Win7 thing, let's close it.  Thanks for your research and testing, @errietta.
