### ISSUE TITLE
Relative links don't work in the preview pane

### ISSUE THREAD

**Issue by my2iu** [mozilla/thimble.webmaker.org#1099]
When I create a

     <a href="index-1.html">link to file</a>

link in a document, the link doesn't work. (Actually, I had it work once, but I don't know why). This is annoying because the main advantage of the new Thimble over the old Thimble (and, say, Khan Academy) is that it can be used to teach how to build multi-page websites.

**Comment by humphd** [comment]
This depends on https://github.com/humphd/brackets/issues/447, which I agree would be nice to get working.

**Comment by humphd** [comment]
I went ahead and fixed this https://github.com/humphd/brackets/pull/463.  I'll get it in next week.

@gideonthomas, can you review that patch when you have time next week?

**Comment by humphd** [comment]
Fixed, and landed on staging and production.
