### ISSUE TITLE
Publishing things without an index.html

### ISSUE THREAD

**Issue by my2iu** [mozilla/thimble.webmaker.org#1101]
If you publish a website but you don't have an `index.html` (I'm porting some lessons over to Thimble that involve creating an `about.html` first), then the link it produces doesn't go anywhere. It took me a while to figure out that I can manually alter the link to point to the other pages on the site. Still, just to avoid the confusion, it might be nice if Thimble generated a link that pointed to the first html file it finds instead of simply to the root of the website.

**Comment by humphd** [comment]
Changing how web servers prioritize loading when no explicit resource is specified isn't easily done (i.e., nginx is going to look for something called `index.html` by default).  Having said that, projects that lack an `index.html` could be given a pre-generated one.  When you say "a link that pointed to the first html file it finds" are you imagining a client-side redirect?  Another thing would be to create a static directory listing, something like http://www.linickx.com/files/2008/05/apachedirlisting_before.png.

**Comment by my2iu** [comment]
No. I'm suggesting that when you click on the Publish button, if WebMaker doesn't find an index.html, it generates a link to one of the other files instead. So instead of a link to

``` https://d157rqmxrxj6ey.cloudfront.net/coderdojo-ming/6237 ```

you get a link to

``` https://d157rqmxrxj6ey.cloudfront.net/coderdojo-ming/6237/about-me.html ```

**Comment by humphd** [comment]
We're discussing adding the ability to show dir listings in #1203.  I'm going to dupe this on that.
