### ISSUE TITLE
Remix id # in URL is different from id # of the project

### ISSUE THREAD

**Issue by my2iu** [mozilla/thimble.webmaker.org#1102]
It's a minor quibble, and I don't know if it's actually possible, but it might be nice if the "remix" URL was related to the project URL in some way.

e.g.

```
https://thimble.mozilla.org/user/coderdojo-ming/6237
https://thimble.mozilla.org/projects/1387/remix
```

Couldn't 6237 be used as both the project id and the remix id (1387)?

**Comment by humphd** [comment]
I agree this is confusing, and we're exploring improvements to this in #1120, closing this particular issue.
