### ISSUE TITLE
Support both tutorial.html and tutorial.md

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1104]
[From twitter](https://twitter.com/sunnydeveloper/status/642742767030960128), the request is that we support tutorial.md or tutorial.html, and automatically convert markdown to html.  We already have the markdown parser in Bramble, we just need to teach the tutorial stuff and HTMLServer to use it.

**Comment by humphd** [comment]
Backend work is underway in https://github.com/humphd/brackets/pull/465

**Comment by soapdog** [comment]
Oh, this is great! :-D

Also, there is [prosemirror](http://prosemirror.net/) which could be integrated and allow us to provide a rich editor experience for *tutorial.md*

**Comment by jgmac1106** [comment]
Is it wrong to not want a rich text editor? Almost want to force users
using html or markdown.

**Comment by soapdog** [comment]
I think you can add some toggle on the interface so that the user can switch between markdown/rich, this reduces friction. After all, its not about writing markdown but passing knowledge forward! :smiley_cat: 

This way they can see how markdown and rich behave and may end up using markdown for speed and productivity.

**Comment by humphd** [comment]
I've landed a first pass at this, which you can test at https://bramble.mofostaging.net.  I talked to the author of ProseMirror (who also wrote CodeMirror), and swapping one for the other in Brackets is a huge job.  I don't forsee doing that in Thimble.  For now, what I've done is to automatically generate an HTML file for a given markdown file.  See what you think.  It will work for `tutorial.md` too, which will then generate `tutorial.html`.

**Comment by hannahkane** [comment]
Was trying to test this, but am unable to add a file to a project on staging right now. Getting this error: "Uncaught TypeError: Cannot read property 'stopPropagation' of undefined"

Is that a known issue?

**Comment by humphd** [comment]
@hannahkane that's unknown for sure.  This is on staging?  Do you remember what you did?

**Comment by humphd** [comment]
It's working for me.  The places where we call `stopPropagation` relate to login, and the userbar menu.  Is what you're seeing related to that?

**Comment by hannahkane** [comment]
On bramble.mofostaging.net -> "Start from scratch" -> clicked green "+" symbol at top of file tree -> selected Tutorial. Got this error:
![screen shot 2015-09-28 at 3 43 05 pm](https://cloud.githubusercontent.com/assets/8389648/10150966/c1c39668-65f7-11e5-8cc2-fc1443c48cc3.png)

**Comment by humphd** [comment]
OK, got it.  I see @flukeout filed it too https://github.com/mozilla/thimble.webmaker.org/issues/1155.  I'll debug and fix there.

**Comment by hannahkane** [comment]
@humphd - maybe, though I'm not intentionally doing anything related to logging in. I'm not logged in. I get the error each time I try to add any type of file.

**Comment by humphd** [comment]
This is fixed now, and pushed to production.

**Comment by emmairwin** [comment]
Thanks!
