### ISSUE TITLE
Allow for more than one tutorial file

### ISSUE THREAD

**Issue by emmairwin** [mozilla/thimble.webmaker.org#1105]
In scenarios I'm teaching, it would be helpful to have more than one tutorial file, to avoid along scroll or overload of information.

Current Scenario: tutorial.html is loaded and displayed in the 'tutorial' tab.

Proposed (something like):

1) tutorial.hmtl remains default
2) additional tutorials can be associated with files.  For example gallery.html has a gallery_tutorial.html  and when those files are selected, their tutorial files are loaded. I think replacing the default, but there may be a reason to have both.

Mostly I'm thinking of Participation curriculum design right now, but also creating a teaching kit for Grace Hopper Open Source Day that helps people move through a series of steps, or jump to a specific contribution scenerio which will include coding samples to try as pre-work.  http://systers.org/wiki/communities/doku.php?id=wiki:ghc:ghc15:osd:mozilla

**Comment by humphd** [comment]
@flukeout is doing some more work on tutorials in other tickets, I'm going to close this for now.
