### ISSUE TITLE
Explore UX around user Project List

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1106]
We shipped our MVP with a super basic project list:

![screenshot 2015-09-14 11 00 39](https://cloud.githubusercontent.com/assets/427398/9853084/e644006e-5acf-11e5-9c81-c953a5e9378f.png)

We've filed a bunch of bugs to improve things: #834, #806, #770, #552.  However, we could really do a lot more.  Today I opened Google Docs and was met with this:

![screenshot 2015-09-14 10 51 32](https://cloud.githubusercontent.com/assets/427398/9853106/fef159fe-5acf-11e5-9aa3-cd7b87a82377.png)

In some ways they are similar: a list of projects you've made by title (Google Docs also has a "screenshot" view).  But the emphasis in the two is quite different.  Where Google Docs draws my attention to the top, with some lovely templates, ours seems to repeatedly hit you with a "Delete" button, as though that were the action we wanted to corral you into.

It struck me that we could easily do something like the top template bar: blank, a "blog post," a few common column layouts, something that focuses on images, etc.  You could also rotate various popular remixable projects in here, too.  I don't think the templates in any app (Word is another example) are necessarily that important for what they are, but rather for cuing the user to what's possible: "here's what you *could* do."

@cassiemc asked me what I thought needed UX and design thinking in Thimble, and how we do project management is one of my top wish-list items.

cc @flukeout, @hannahkane, @ldecoursy

**Comment by hannahkane** [comment]
cc @chadsansing as well

**Comment by humphd** [comment]
This never really got anywhere, but in the meantime, @flukeout has done some neat work on the Thimble Dashboard.  Can I suggest that we expand on what he's done with the user page and just show that vs. what we do now?

![screenshot 2015-10-31 11 32 19](https://cloud.githubusercontent.com/assets/427398/10864416/ddc615c6-7fc3-11e5-941f-07ec515de7bf.png)

We can probably dupe #1145 on this.

**Comment by hannahkane** [comment]
C/P'ing my comment from #1145: "As discussed at today's stand, this solution works, but we'd need to add unpublished projects and related perms."

Also, I like what we have on the Your Projects page now: last edited date + option to Delete.

There may be other functionality we'd want to add, too, like sorting / filtering.

Do we know how this page scales - is it paginated or do we do infinite scroll?

**Comment by hannahkane** [comment]
Note from @jgmac1106: "It takes me too many clicks to share a project. From "My projects" I have to open the project, click publish, and then copy the url.

There should be a share button or a copy url button from the my project page."

**Comment by flukeout** [comment]
I moved this to #1289 where I've summarized the main points.
