### ISSUE TITLE
Details bar UX options

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1107]
The way we're currently injecting the details bar into published projects isn't the most reliable. We're adjusting the body padding to make room for the bar, but that doesn't take into account projects that have absolutely positioned (or position: fixed) content. People could also adjust their own body padding in the project CSS, which would conflict with ours. Here's a proposal for a lighter version of details bar...

![details-bar-proposal](https://cloud.githubusercontent.com/assets/25212/9855545/beba8092-5ac3-11e5-998f-c2fb89bf5b02.jpg)

This version is a small "button" that sits overtop of the content and expands when hovered or clicked. We don't really have to make changes to the published project to accomodate it, we just have to make sure it has a high enough z-index.

I'm not sure about the positioning though, and am worried that it de-emphasizes the brand & editor.

**Comment by hannahkane** [comment]
This looks really nice, but I definitely worry that it de-emphasizes Remix too much. Could we do some usability testing on this?

**Comment by humphd** [comment]
Let me add another thing to consider.  I was reading this great post from @jgmac1106 on my phone: http://quickthoughts.jgregorymcverry.com/2015/our-edu106-makermonday-challenge-we-made-memes-to-teachtheweb

Here's roughly what things look like with our injected header:

![screenshot 2015-09-15 10 14 49](https://cloud.githubusercontent.com/assets/427398/9878834/b919c3da-5b92-11e5-8a11-b33cf8da03c5.png)

Everything gets mashed together, and the header over takes the content.  While Thimble itself will never work well on a phone, I think published projects should so that people can share them.  We should prioritize the case of a mobile user for the header injection.

**Comment by jgmac1106** [comment]
Could we just go with a single remix button top center? Or does that still
mess up fixed positions? Maybe an image of the Thimble logo with Remix
included?

If we decide to go with @flukeout's design I would agree with @Hannahkane
and just suggest replacing the thimble logo with the word remix.

**Comment by flukeout** [comment]
Good thoughts everyone. I'll provide some more options for the remix button & thimble logo placements and configurations shortly. Agreed that whatever we produce should be responsive.

**Comment by flukeout** [comment]
Here's an update that incorporates some of the feedback above for published projects on a large screen..

![image](https://cloud.githubusercontent.com/assets/25212/9889925/e6b15fd2-5bb1-11e5-9635-3b6d562ae274.png)

**Comment by flukeout** [comment]
Try it out here http://flukeout.github.io/thimble-home/stay-calm-2/

![scrollin](https://cloud.githubusercontent.com/assets/25212/9891814/1a5f36fe-5bbe-11e5-8a92-dae69c1bc9c7.gif)

**Comment by humphd** [comment]
I really like where you're going with this.  One thing I notice is that on small screen sizes (e.g., mobile), it doesn't fit, and the Thimble logo section gets mostly cut off:

![screenshot 2015-09-15 19 12 50](https://cloud.githubusercontent.com/assets/427398/9892549/e77b5022-5bdd-11e5-92df-261cd5fc25de.png)

Also, on mobile you have to scroll before it vanishes, which is somewhat harder to do than on desktop, especially in embedded contexts like social media.  It's also interesting to consider what should even happen on a mobile device if you click this.  Opening the full editor doesn't seem right.  Should it offer to email you a link so you can do it at home?

**Comment by flukeout** [comment]
@humphd Not only that, but the hover to expand effect won't work on mobile. I think we need a totally different solution / style for tablets / mobile and we should probably ditch the remix button. Maybe just a small "made with thimble" somewhere will suffice for now.

For appmaker, we used the email-me-the-remix-link solution you suggested.

Let's see how bit our mobile audience is before we make mobile-specific features.

In the meantime, I'll design a simpler mobile style.

**Comment by humphd** [comment]
<blockquote>Let's see how bit our mobile audience is before we make mobile-specific features.</blockquote>

That's a self-fulfilling prophecy.  If we don't build something that works in mobile, we won't have mobile users.

**Comment by flukeout** [comment]
I see your point - but I meant more in the way of, lets see if we get mobile views on published projects before we invest in an email-me-the-remix-link feature, which might be time consuming.

**Comment by flukeout** [comment]
I thought I'd posted this already, but here are some updates, including a mobile mode when the window is narrower.

http://flukeout.github.io/thimble-home/stay-calm-2/

**Comment by humphd** [comment]
Here's what I encounter when I open that:

![screenshot 2015-09-17 20 40 46](https://cloud.githubusercontent.com/assets/427398/9949570/78ededea-5d7c-11e5-8069-c72e9eb0d904.png)

To me it seems heavy handed of us to cover your content like this, and all so we can show you the project's title.  Why don't we drop the title, and confine ourselves to something that is much smaller and less intrusive to the experience of the work?  Beyond the utility of providing a field in our db, what is the point of the title?  I think we're losing the point of what publishing is about.  I would argue that there are two key benefits:

* being able to publish a web site freely
* being able to remix a web site I like

The prevalence we give the title does nothing to achieve either goal.

**Comment by hannahkane** [comment]
I think I agree with @humphd that the title isn't that important, but I do think the thimble and the username are needed, so don't want to lose that. 

@chadsansing, @omnignorant and other frequent Thimble users: any input on whether displaying the title is a key part of the Thimble experience?

**Comment by jgmac1106** [comment]
It is not now. In fact I saw must of my first time users keep the step.

As a teacher though I would want the name later. I wonder if it is a better
feature for the gallery work down the road....If I care about a project I
can mark it as public, add a title,  and a description when ready to share.

**Comment by chadsansing** [comment]
The title is more important for meta. I would be happy with a remix button that expands into a box with the title, as well.

**Comment by flukeout** [comment]
I tend to agree with all the points here. I've seen lots of Untitled projects published, and often the title is redundant because the content has it's own title.

I'll create an option that is collapsed by default.

**Comment by flukeout** [comment]
I made some updates, there are now two different modes for the details bar

* **Desktop** http://flukeout.github.io/thimble-home/stay-calm-2/
* **Mobile** http://flukeout.github.io/thimble-home/stay-calm-2/mobile.html

**Comment by hannahkane** [comment]
Like!

**Comment by flukeout** [comment]
**Feedback from the team**
* Overlay it over a few different projects to see how it adapts to different colors
* Try reducing the overall size a little bit for both modes to make it feel less chunky
  * Especially the mobile button
* Try inverting the colors - white button with green text / icon

**Comment by flukeout** [comment]
Here's the latest version - http://flukeout.github.io/thimble-home/stay-calm-2/

Here's how it works
* For touch devices, it shows the round Thimble button
  * Tap it to show the project details & remix button
  * Tap the Remix button to remix
* For non-touch devices it shows a Remix button
  * Hover over it to expand and see the project details
  * Click to Remix

Additionally
* No longer dependent on jQuery
* Moved all of the JS that powers it into a script tag at the bottom of the document

@humphd @hannahkane Thoughts? Try on a mobile device too.

**Comment by flukeout** [comment]
I forgot to add a click handler on the smaller (touch) version - adding now.

**Comment by hannahkane** [comment]
Love it. Does feel kind of distracting on mobile, but I don't think we can go any smaller.

**Comment by flukeout** [comment]
@hannahkane yeah, we can also fade it out on small screens if you scroll. Let's look into that later though. We're getting analytics on published projects very soon so we'll see if we have a mobile audience.

**Comment by humphd** [comment]
I think fading it out when you scroll is all this needs, and it's good to go.  @flukeout, are you going to hack it into the code, or do you want one of us to?
