### ISSUE TITLE
Link line numbers in tutorial file

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#1110]
Many of my students got caught up in tutorials when they saw line numbers. They would go to the line number for the tutorial file not the index.html file.

-- Is there a way to link the line numbers in the tutorial file to the line numbers in the other file?

or

-- Can you maximize the tutorial file and hide the code editor when ever you click on the tutorial file? 

Not a huge deal. It might just be a mistake new users have to make a few times until they get the navigation down.

**Comment by hannahkane** [comment]
I think this is covered in the ticket about a new treatment for tutorials. OK to close?

**Comment by gideonthomas** [comment]
Closing since the discussion has been picked up here: https://github.com/mozilla/thimble.webmaker.org/issues/1246
