### ISSUE TITLE
Finalize creative brief for Thimble in the Classroom aka "Teacher's Pet"

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1111]
Our working draft is here:
https://docs.google.com/document/d/1j3-E30ST3bYexK0gbN2rHGQnx2QJBBXN9sj-ZNJDNW8/edit

I think we can improve this brief by including more evidence of these features being needed & wanted by teachers.

cc @LauraReynal @hannahkane

**Comment by hannahkane** [comment]
From @omnignorant:

"Tada! I'm the use case!
https://rfriedmanbsf.makes.org/thimble/MTQxMzY3NzU2OA==/2015-hack-shop-landing-page

NOTE: Google has deprecated some services that I used to host images and CSS files so this page and some of my kids pages will appear messed up. However, you still get the general idea.

This may be the best evidence that I am aware of RE: portfolio pages in Thimble. However, sites like DiscoverDesign.org, ForAll Rubrics, and Edmodo make strong use cases for portfolios of student work, or curated classroom environments."

**Comment by jgmac1106** [comment]
Here is how I set up portfolios. Not as cool as @ominignorant. I am stealing that for this year. But I just made one project for each page and linked them together: https://littlejrosa3015.makes.org/thimble/NjMyODgxNDA4/my-edu106-portfolio-new

The first thing I will be remixing when the multipage project is finalized is a portfolio (it will just now include @omnignorant 's way cool menu).

**Comment by hannahkane** [comment]
@flukeout - you might want to read @adamlofting's idea for Teacher Lesson Dashboards in this blog post: http://adamlofting.com/1037/whos-teaching-this-thing-anyway/

**Comment by humphd** [comment]
Github has something like this, fwiw: https://github.com/blog/2055-teachers-manage-your-courses-with-classroom-for-github

**Comment by hannahkane** [comment]
@flukeout - I think we can close this for now. Will pick up as part of larger Teach work. Reopen if you disagree. :)
