### ISSUE TITLE
Reduce timeout issues

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1112]
Tracking bug for https://github.com/mozilla/publish.webmaker.org/issues/153 to reduce Thimble's publish timeouts.

**Comment by gideonthomas** [comment]
The publishing timeout bug is https://github.com/mozilla/publish.webmaker.org/issues/152 while the general timeout issues are  https://github.com/mozilla/publish.webmaker.org/issues/153

**Comment by jbuck** [comment]
@cadecairos has a patch in https://github.com/mozilla/id.webmaker.org/pull/368 that I'm going to review and land, and we'll see if that improves things

**Comment by humphd** [comment]
This is *great* news, thanks to you two for pushing on this.

**Comment by jbuck** [comment]
Okay, so adding that patch definitely helped with response times to id.webmaker.org, but some projects, like [this 10MB project](https://d157rqmxrxj6ey.cloudfront.net/cabravoeco/12815), still cause issues when the server needs to pack a 10MB tarball within the request handler.

**Comment by humphd** [comment]
This is really interesting!  So letting people put files in a filesystem means they put lots of files in a filesystem!  We should figure out if we want to limit the total size of a project, whether we want to auto-reduce image files a user drags in, etc. in another bug

In the meantime, I think we should deal with the fact that we are going to have arbitrary sized data going in and out of Thimble + Publish, and not timeout.

I tried doing a patch to yield the tarball creation to the main event loop:

```diff
diff --git a/api/classes/base_controller.js b/api/classes/base_controller.js
index 746dea4..e116b23 100644
--- a/api/classes/base_controller.js
+++ b/api/classes/base_controller.js
@@ -87,27 +87,32 @@ BaseController.prototype.getAllAsMeta = function(req, reply) {
   reply(req.generateResponse(req.pre.records.toJSON()));
 };

+// NOTE: creating the tarball for a project can be a lengthy process, so
+// we do it in multiple slices of the event loop, so that other requests
+// don't get blocked.
 BaseController.prototype.getAllAsTar = function(req, reply) {
   var files = req.pre.records.models;
   var tarStream = Tar.pack();
-  var self = this;
-
-  function startStreaming(files, model) {
-    return Promise.map(files, function(file) {
-      return model.query({
-        where: {
-          id: file.get('id')
-        },
-        columns: ['buffer']
-      }).fetch().then(function(model) {
+  var model = this.Model;
+
+  function processFile(file) {
+    return model.query({
+      where: {
+        id: file.get('id')
+      },
+      columns: ['buffer']
+    }).fetch().then(function(model) {
+      process.nextTick(function() {
         tarStream.entry({ name: file.get('path') }, model.get('buffer'));
       });
-    }).then(function() {
-      tarStream.finalize();
     });
   }

-  startStreaming(files, self.Model).catch(errors.generateErrorResponse);
+  process.nextTick(function() {
+    Promise.map(files, processFile)
+      .then(function() { tarStream.finalize(); })
+      .catch(errors.generateErrorResponse);
+  });

   // Normally this type would be application/x-tar, but IE refuses to
   // decompress a gzipped stream when this is the type.
```

Which might make things better.  I assume the code that talks to postgres is already sufficiently async that it's not blocking on that, and it's actually the `Promise.map` or maybe even the `tarStream.entry()` (which I doubt, but I haven't measured).

Another thing we could consider is spinning off a second node process to act as a tarball service:
* requests come in for the tarball, and a call is posted to the `child_process` running the tarball service code
* tarball service code gets a message asking for a project to be "tar"ed, and it starts the process, using an `fs` stream to write the tarball to disk.
* when the tarball file is finished, the `child_process` posts a message back to the main process saying that it's finished, including the temporary filename for the generated tarball
* the main process then completes the response (via an async callback API so it won't block the request) by streaming the tarball file to the client, something like this:

```js
BaseController.prototype.getAllAsTar = function(req, reply) {
  tarballService.generate(someProjectDataToPassToService, function(err, tarballPath) {
    if(err) {
      return reply(500); // I don't know hapi, but whatever you do to send the error back
    }
    reply.file(tarballPath);
    // Maybe also remove the temp tarballPath when you're done...
  });
};
```

**Comment by humphd** [comment]
@cadecairos on publish, after your caching patch I see:

<blockquote>
Request timeouts. There have been 35 timeout errors in the last day. Try investigating slow requests, adding more dynos or running more processes per dyno.
</blockquote>

<blockquote>
Response time degraded. Compared to this day last week, your median response time has increased 68%, and your 95th percentile response time has increased 32%
</blockquote>

A.M.A.Z.I.N.G.

**Comment by cadecairos** [comment]
:+1: :tada: :tada: :tada:

**Comment by humphd** [comment]
@gideonthomas I'd like to discuss my plan above, esp. doing the simpler `nextTick()` yielding.

**Comment by humphd** [comment]
I landed a fix in publish for this, we just need to do staging/prod pushes.  @gideonthomas, can you help and then close this?
