### ISSUE TITLE
Thimble: CSS: case insensitive matching - class names / id names

### ISSUE THREAD

**Issue by Rdilorenzo73** [mozilla/thimble.webmaker.org#1113]
Issue - 
CSS class names and ID names match - even with differences in case

<pre>
id="subTotal"
</pre>
matches (style applied)
<pre>
#subtotal { }
</pre>

Even after a display preview refresh the style is still applied...

**Comment by humphd** [comment]
This is CSS being CSS: http://www.w3.org/TR/css3-selectors/#casesens.  The ID in the DOM will be case-sensitive, but CSS is case insensitive.

**Comment by Rdilorenzo73** [comment]
OK Thanks.  I'll study the spec a little closer.  Thanks for pointing this out.

**Comment by humphd** [comment]
Thanks for filing this.  It's an annoying thing, and I agree that it causes confusion, especially for people learning web development.  I'm going to close it, because we can't address it in Thimble directly.  But please file more things you think are broken or if you have ideas.
