### ISSUE TITLE
Design scalable solution for the curated projects list on the homepage

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#1122]
We'll be adding more projects to the homepage list. The first one is here: https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/10950/

It doesn't have an accompanying teaching kit, so we'll need a design that allows for that. 

Title: Three Things I <3
Instruction: Learn how to create a multi-page website about things you love!

**Comment by hannahkane** [comment]
cc @chadsansing
related issue: https://github.com/mozilla/learning-networks/issues/241

**Comment by chadsansing** [comment]
By kit, do you mean an activity page? I'm thinking of kits as collections of activities. I can make an activity page for this shortly and will need to, anyway, to finish the Back-to-School Write the Web kit. I can deliver that by EOD tomorrow for review.

**Comment by hannahkane** [comment]
By teaching kit I meant the equivalent of what we offer underneath each of the three activities featured on the Thimble homepage now.

**Comment by chadsansing** [comment]
I can do that.

**Comment by hannahkane** [comment]
Ah, that would be great for consistency, I think.

**Comment by chadsansing** [comment]
It's all happening.

![screen shot 2015-09-16 at 2 27 03 pm](https://cloud.githubusercontent.com/assets/4128600/9914276/0edc634e-5c7f-11e5-9f6d-159940223117.png)

**Comment by hannahkane** [comment]
:)

**Comment by chadsansing** [comment]
@hannahkane, see https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/11288/.

I can't get the Navigation WebLit skill button to display the right makerstrap color. Also, please text in Firefox and Chrome - layout seems broken on my machine outside Safari, but I can't tell why.

**Comment by ldecoursy** [comment]
Looks good! A few small edits:

* First learning objective missing a period
* Intro, 2nd paragraph, 2nd sentence – "play a sorting game" (game should be singular)
* This instruction is unclear: "Explain the rules: After you read each notecard, students who love that thing should all go far to your right, while students who don't love that thing should all go far to the left. Students who are neutral can stay in - or go to - the middle." Maybe we should specify that they should re-sort themselves after each card? 
* There's a stray exclamation point after 3 Things I <3 in the 2nd bullet in the Explore section
* 2nd to last item in the Explore section, I might add "Tell students that today we're going to remix the project to MAKE A SIMPLE WEBSITE THAT SHOWS three things that each of us loves.
* In Remix section, the word "sidebar" is misspelled 
* Under the Share section, the word "and" in the second sentence is misspelled
* After "Take it a step further," add "Invite YOUR STUDENTS to check out..."

**Comment by flukeout** [comment]
@hannahkane Might be tricky to add just one given the layout?  What bout adding another three, we've got some good ones courtesy of @chadsansing:

* Homework Excuse Generator
  * https://d157rqmxrxj6ey.cloudfront.net/chadsansing/4487/
* My Six-word-Summer
  * https://d157rqmxrxj6ey.cloudfront.net/chadsansing/4493/
* Remix my Schedule
  * https://d157rqmxrxj6ey.cloudfront.net/chadsansing/4498/
* Schools around the World
  * https://d157rqmxrxj6ey.cloudfront.net/chadsansing/4500/

I can take a stab at including 4 on the homepage though.

**Comment by hannahkane** [comment]
@chadsansing - want to pick two more to include on the homepage, for two rows of three?

**Comment by chadsansing** [comment]
@ldecoursy - thank you! Fixed the copy bugs.

**Comment by chadsansing** [comment]
@hannahkane - How about My Six-Word Summer and the Homework Excuse Generator?

**Comment by chadsansing** [comment]
For review:

Homework make: https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/11698/
Homework kit: https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/11701/
Six-Word make: https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/11703/
Six-Word kit: https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/11704/

cc @hannahkane, @flukeout, @ldecoursy

**Comment by flukeout** [comment]
@chadsansing @hannahkane Hey - I've got the following built locally, but I'll need each...
* Project description (under thumbnail)
* 3 Bullet points of learning

![image](https://cloud.githubusercontent.com/assets/25212/9942896/a05a84e6-5d32-11e5-96be-1ce3203d90cd.png)

**Comment by flukeout** [comment]
@chadsansing Also for me, the Teaching Kits aren't rendering properly... looks like they're not getting the correct stylesheets, same for you?

* https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/11288/

![image](https://cloud.githubusercontent.com/assets/25212/9942925/d343f860-5d32-11e5-9151-28333bad1498.png)

I'll dig into it.

**Comment by chadsansing** [comment]
@flukeout, how about this for copy?

**3 Things I <3**

Make a simple website to share what you love.

Use it to teach

- Navigation inside a website.
- Editing HTML content.
- Embedding media in webpages.

**Homework Excuse Generator**

Remix a basic JavaScript function to get out of trouble with your teacher.

Use it to teach

- Basic coding ideas.
- Editing JavaScript content.
- Creating an interactive button with JavaScript.

**My Six-Word Summer**

Tell us what you did last summer in just six words.

Use it to teach

- Searching for openly licensed images online.
- Editing HTML content.
- Editing for specific word choice.

Look okay, @ldecoursy?

I can't figure out the CSS issue yet; works in Safari when hosted on Thimble; works across browsers when hosted on gh-pages. Could definitely use a pair of fresh eyes on this. Thanks!

**Comment by ldecoursy** [comment]
Looks good to me. One suggestion for Homework Excuse Generator description: Remix a basic JavaScript function to explain why  your homework is late.

**Comment by chadsansing** [comment]
@ldecoursy's suggestion FTW.

**Comment by flukeout** [comment]
Thanks @chadsansing and @ldecoursy - I've submitted a PR with this stuff in #1127

I just need to figure out why the styles aren't loading for the teaching kits.

**Comment by flukeout** [comment]
In the **3 Things I <3** , the competencies don't render right:

![image](https://cloud.githubusercontent.com/assets/25212/9945849/92d435bc-5d44-11e5-8f2f-0ecf71ccad62.png)

**Comment by hannahkane** [comment]
I just went in an fixed @flukeout's bugs all three teaching kits. Ended up just removing the header entirely (with the Webmaker logo + link to Github, etc) because it just adds clutter.

**Comment by flukeout** [comment]
Awesome, thanks @hannahkane - as soon as the PR gets reviewed we can check it out in staging and push to prod if everything checks out!

**Comment by chadsansing** [comment]
@hannahkane & @flukeout: huzzah, you rock, and thank you! Exciting stuff!
