### ISSUE TITLE
Absolute stylesheet path broken

### ISSUE THREAD

**Issue by DanForever** [mozilla/thimble.webmaker.org#1124]
I put my .css file in a sub folder called "stylesheets", and then linked to it like so:
`<link rel="stylesheet" href="/stylesheets/style.css">`
Thimble can't find the file, but if I remove the preceding '/', so that it's relative, it works. But this is only because my html file is in the parent folder.

**Comment by humphd** [comment]
We're discussing this in https://github.com/mozilla/thimble.webmaker.org/issues/1007#issuecomment-140500118, if you want to weigh in there.

**Comment by DanForever** [comment]
Ah. My googlefoo failed me!

**Comment by humphd** [comment]
It's not you, it's that we got distracted in that other ticket.  We really need one dedicated to this, you're not alone in finding it a problem.  Thanks for filing.

**Comment by gideonthomas** [comment]
I don't think that we are going to end up supporting this; closing!
