### ISSUE TITLE
Clicking on Link to editor within editor

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#1125]
I was reviewing curriculum and clicked on a link to a project from within an existing project. This happened: 
![opening linked project](https://cloud.githubusercontent.com/assets/10534566/9921928/dfab0d32-5cb0-11e5-9b78-be586288f7f0.png)
Not sure if it needs or could be prevented. I recommended suggesting the target attribute to blank but wanted to file an issue in case there was a better way to solve this.

**Comment by humphd** [comment]
What was the url of the link you clicked?

**Comment by jgmac1106** [comment]
Here is a quick video. Sorry for audio. In iddle of podcast: https://goo.gl/VM0XCy

The link was:   <code><li>Once everyone has had a chance to respond, ask students to sit at their computers and go to <a href="https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/10950/">the webpage for today's activity</a>.</li><br></code>

**Comment by humphd** [comment]
You're using `https://thimble.mozilla.org`, correct?  I can't reproduce this.  I tried putting your code snippet in a new project, and in the preview, clicking the link opens a new window.  Do you have an extension installed that alters the action of opening links in new tabs?

We recently landed code to allow links to files in a project, such that clicking them in the preview opens them and changes the editor to point to that file.  For external links, we open them in a new window.  Can you try clearing your browser cache and testing again, to make sure you have this code locally?

Thanks for helping us figure this out.

**Comment by jgmac1106** [comment]
I erased my cache and tried in both Chrome 45 and Firefox 40. Here is a quick screen recording:
http://screencast-o-matic.com/watch/coQblYfKYa

In Firefox a second editor would not load. You got an error message. In Chrome the second editor opened. You can use back navigation to return to the original project.

**Comment by humphd** [comment]
This is a really interesting case.  The project in question is https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/11288/ and when I inspect the page in the preview, I note that all of the Bramble API (editor) is loaded into the head--that shouldn't happen.  So there is something about this page that's different.  I'll have to debug.

**Comment by humphd** [comment]
@gideonthomas if you have any time to look at this today, check this out:

![screen shot 2015-09-17 at 10 17 26 am](https://cloud.githubusercontent.com/assets/427398/9935573/632f0662-5d25-11e5-8bc7-aba545abc3b4.png)

That's the iframe's DOM, and for reasons that don't make sense to me, it's got everything you'd expect from Brabmle's `index.html` in there.  It's like our live doc injection code is putting the editor's JS in there.  That's going to cause all kinds of problems, beyond just this linking issue.

**Comment by humphd** [comment]
As an aside, whoever is working on that page should be escaping the `<3` (should be `&gt;3`) throughout so it doesn't break the page's markup.

**Comment by humphd** [comment]
I think I've fixed this.  I'l get you to test next week and report back.
