### ISSUE TITLE
Cloudfront invalidation on deploy

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1132]
When we deploy, our staging/prod boxes are still serving cached static assets, mixed with new web views rendered by nunjucks.  The result is that pages are a mix of new and old, and are almost always wrong, causing people concern who just pushed a change, or want to test something.

It would be nice if we automagically invalidated the cache when we deployed.  @jbuck thinks it's possible:

```
13:07 < jbuck> yeah, should be able to whip up something
13:07 < jbuck> there's an api for that(tm)
13:07 < jbuck> http://docs.aws.amazon.com/cli/latest/reference/cloudfront/create-invalidation.html
13:07 < jbuck> for doing it from the cli
13:08 < jbuck> you could also do it from the sdk
```

**Comment by humphd** [comment]
@sedge is this something that you'd be good at, or interested in trying?

**Comment by sedge** [comment]
Sure. I'll take this on as my next issue.

**Comment by sedge** [comment]
See also: https://github.com/humphd/brackets/issues/472

**Comment by humphd** [comment]
Where are we on this?

**Comment by sedge** [comment]
@humphd A [patch for thimble.wm.o](https://github.com/mozilla/thimble.webmaker.org/pull/1152) is in review. You can expect it to land this Thursday :+1:

**Comment by sedge** [comment]
We used to deploy to production by checking out to a production branch, merging changes from the `bramble` branch, and Travis-ci handle the deployment.

Now we use Heroku to promote staging to production, meaning the travis hook I was relying on to trigger the invalidation won't occur.

This means that this will have to be a two step process: First, someone promotes staging to prod, second they run the script in [this commit](https://github.com/mozilla/thimble.webmaker.org/commit/6b991dc9374539ad45d7054fb4e61d258c0d3c65).

**Comment by humphd** [comment]
@sedge what's the status of this?  It feels like it's been open for a long time...

**Comment by sedge** [comment]
We're really really close! The brackets part of this patch has landed but https://github.com/mozilla/thimble.webmaker.org/pull/1194 is breaking travis because of a dependency issue. There's only a couple of hours of work left on this, at most.

**Comment by sedge** [comment]
UGH so close. The patches have landed, and now I'm configuring the staging and production heroku apps to allow us to run this script as a one-off action. 

In short, this means the creds for the invalidation are stored on Heroku instead of on your local machine, and anyone with heroku access to the apps can run the invalidation script.

**Comment by sedge** [comment]
Blocked by https://github.com/MozillaFoundation/mofo-devops/issues/230

**Comment by sedge** [comment]
As soon as https://github.com/mozilla/thimble.webmaker.org/commit/e056fb7208183cdbd9d5d371ef69d9b28e12021a makes it to production this is ready for the production distribution of cloudfront. Details on how to use it are in the patch.

**Comment by sedge** [comment]
This is done! See [the README](https://github.com/mozilla/thimble.webmaker.org#invalidating-cloudfront) for the quick version of how to do this.
