### ISSUE TITLE
QA curated teaching kits

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#1133]
Ran the three new teaching kits through https://validator.nu (thanks, @Humphd), and, while I fixed all of the errors, it could really use some attention from someone with more skills than me. In some cases, fixing the errors made it look worse (e.g. unordered lists now look really bad).

Also, I didn't yet fix errors from the original three teaching kits because I realized we were using a different template/layout, and thought we ought to take the time to agree upon a single template to use moving forward.

@flukeout - would you be up for creating a new Teaching Kit template? I think the ones we've been using are a product of template telephone - they've been remixed so many times that they're now full of errors and weirdnesses. Would be nice to have a goodlooking, clean template to use.

**Comment by hannahkane** [comment]
cc @chadsansing

**Comment by humphd** [comment]
A couple more things I notice:

*Keep Calm, Postcard, Comic Strip*
* Links to https://thimble-beta.webmaker.org/resources/remix/index.js should use https://thimble.mozilla/org
* http://mofousers.s3-website-us-east-1.amazonaws.com/jess/mdkit/mobilekit-header.png is dead, it might be smart to just get whatever that image is and host it directly in the project

*Comic Strip teaching Kit*
* https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/32/dist/js/main.min.js is dead, once again, I'd recommend hosting that file in the project

**Comment by hannahkane** [comment]
Added a separate ticket about designing a new template, so as not to clutter this issue.

Not sure how to fix the issues humph mentioned. Have we lost the header image forever? cc @flukeout

**Comment by hannahkane** [comment]
@gideonthomas @flukeout - I think it's ok to push the homepage changes to production tomorrow. The errors listed in this ticket are already on production, and need to be resolved regardless of pushing the new changes.

**Comment by hannahkane** [comment]
I think we can close this now.
