### ISSUE TITLE
Custom Template for New HTML Pages?

### ISSUE THREAD

**Issue by my2iu** [mozilla/thimble.webmaker.org#1134]
When trying to rewrite some CoderDojo HTML lessons to use Thimble, there was one things that didn't port over well. In the original lessons, new HTML files were created by copying an existing HTML file (called "blank.html"). So when students start a new page, they automatically get links to certain external stylesheets etc. on their new pages. With Thimble, when you create a new HTML page, you get a page based on the Thimble template, so you have to manually type in the reference to the stylesheet etc.

It would be nice if Thimble offered a way to either make a copy of existing HTML files (e.g. an option on the right-click menu) or if a project could simply provide a template that Thimble would automatically use for new files (e.g. a "template.html").

Also, I'm worried kids might find it a little bit confusing how Thimble automatically chooses a name for new HTML files. They might create a new HTML page and not know where it is and how to find it again. It might be better if Thimble created a dialog to ask for the file name before creating it, or maybe when it creates it, it should immediately go into "file rename" mode with the expectation that you'll rename it.

**Comment by gideonthomas** [comment]
Don't think we'll be able to do this anytime soon. Can re-open later on.
