### ISSUE TITLE
Preview panel applies CSS selector matching as if in quirks mode

### ISSUE THREAD

**Issue by Rdilorenzo73** [mozilla/thimble.webmaker.org#1137]
(Clarification on closed issue #1113)

The preview panel in Thimble applies CSS selector matching as if in quirks mode - case insensitive. 

However, the HTML5 doctype declaration in the HTML should trigger standards mode.  

This seems to be an inconsistency - 
 
Quotes from:
(http://www.w3.org/TR/2014/REC-html5-20141028/disabled-elements.html#case-sensitivity)

*The Selectors specification leaves the case-sensitivity of IDs, classes, element names, attribute names, and attribute values to be defined by the host language.*

…

*Everything else (attribute values on HTML elements, IDs and classes in no-quirks mode and limited-quirks mode, and element names, attribute names, and attribute values in XML documents) must be treated as case-sensitive for the purposes of selector matching.*

So....

Test case in Thimble (attribute value matching):
HTML:
`<p class="foo">Make something <strong>amazing</strong> with the web!</p>`
CSS:
`.FOO {color:red;}`

**Preview** Panel shows red text - as if in quirks mode

**Published** page in Firefox (standards mode) show no red text

https://d157rqmxrxj6ey.cloudfront.net/mrdilo/12955/

**Comment by humphd** [comment]
cc @Pomax

**Comment by humphd** [comment]
You're exactly right, Brackets has stripped the `<!DOCTYPE html>`, which will indeed result in it being rendered in quirks mode.  The preview source ends up being:

```html
<html data-brackets-id="13"><head data-brackets-id="14"><base href="https://mozillathimblelivepreview.net/bramble/production
...
```

I'll look into why it's doing that.

**Comment by humphd** [comment]
@gideonthomas I bet this is the HTMLRewriter using `document.outerHTML`, which doesn't include the doctype.  We need to also get `document.doctype` and concat before we build the blob.

**Comment by humphd** [comment]
Confirmed, and I've got a fix up for review in https://github.com/humphd/brackets/pull/470.  @Rdilorenzo73, thanks for sticking with this issue and researching it so well.  This is a good fix to get into Thimble and Bramble.

**Comment by Rdilorenzo73** [comment]
@humphd Glad to contribute.  I'm eager to see Thimble evolve and succeed. I learning about the Git workflow and OS development from this.
