### ISSUE TITLE
Design new Teaching Kit template

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#1140]
Per #1133, we're now showcasing educator content using two different templates, both of which are a little bit broken.

It would be useful to have a new template that reflects @chadsansing's latest thinking on the format. Chad - if you agree, would you be able to add some requirements in a comment below?

**Comment by jgmac1106** [comment]
I hope we try to simplify the design. the formatted lists embedded in lists
make it hard for many community members like me who do not have the skill
set. I am all for leveling up people's skills but lets make the templates
remixable by the general public. Let the people who are good at
contributing curriculum worry about curriculum and not so much code.

**Comment by chrislarry33** [comment]
Agree we need to find the right balance here Btw the 2  skill, coding the remix and the curricular craft. 

Is this something we could test?

**Comment by jgmac1106** [comment]
I can test no-fi/lo-fi users and assign a lesson plan activity for my
students. Once teaching kit (which we are defining as a series of
activities?) is done they will use it. During #thimblechat make one of the
questions would you like test curriculum and templates? Maybe we can grab a
few users with a little more skill.

**Comment by chadsansing** [comment]
Let's lean toward the template we've used for Web Lit Basics & Protect Your Privacy to avoid inadvertent re-branding.

I would love a new banner/logo at the top w/ teach dot or MLN branding and a remix button or view on GitHub if we can commit to migrating stuff there. Thimble is still my preferred home for content until we have more user support for GitHub.

The two-column layout is okay; three gave us a bit more flexibility in parallel top-level sidebar placing content, but it made for a busy kit.

If we go two column, I'd include these things in the sidebar:

- Web Lit competencies.
- Learning outcomes.
- Materials.
- Commented-out, optional standards section.
- Commented-out, optional tags section.
- Link to Discourse. e.g. "Have questions? Ready to share a remix of this activity? Join us on our [community curriculum forum at Discourse] (https://discourse.webmaker.org)."

We can develop standards and tagging more later.

In the main content column, I dig the way things work right now for the most part. If we had the time to lighten and space-out list-items, that'd be cool - they often look bolder and more squinched than paragraph text. Key sections for the main content column would include

- Title
- Summary
- Attribution
- Suggested time
- Preparation
- Introduction + time
- Activity (to be remixed, added to by users) + time
- Assessment + time
- Reflection + time
- Closing link, e.g. "Congratulations on completing the activity! Looking for more ways to read, write, and participate on the Web? Check out [teach.mozilla.org] (https://teach.mozilla.org/activities0 for more ideas or create your own activity or lesson on [Thimble] (https://thimble.mozilla.org)." This could also point to a lesson template on cloud-front/Thimble.

We need to start pointing users toward assessment (and documentation) to support internal badge work, partners using badges, and classroom teachers.

Does that cover the basics? The more horizontal, the better (like, if in the main column we had tabs or Web-Lit-Map like expanding drop-down things).

Finally, quick note on how I am thinking of our terms. To me, an "activity" is a single lesson, sometimes associated with a Thimble "project" (trying to stop using "make" and to avoid overuse of "remix" or "activity"). A "teaching kit" collects, sequences, and frames a series of "activities" and may resemble an agenda - it looks like the landing page for Web Lit Basics or Protect Your Data from /activities.

Onward!

**Comment by jgmac1106** [comment]
+1 on curriculum on Thimble over GitHub first. Maybe it becomes part of
workflow. Community submits kits for consideration.

If these reach level two on the guidelines, and the content fills a need,
it gets added to a git repo (should curriculum have its own?) by the
original author or whoever submitted (we can mentor when needed.. github
and/or markdown>html>git will take 1:1 mentoring in many cases).

Then we work to get it up to canonical  curriculum using the normal QA
process on Git.

This way contributors that are not involved yet can keep remixing
curriculum while we use @chadsansig exploratory design approach to work
through the queue.

**Comment by hannahkane** [comment]
tagging @cassiemc because I think this might be a good learning project for an intern. I can write up a design brief if that would be useful.

thanks, @chadsansing for the detailed requirements and +1 on your terminology review.

**Comment by hannahkane** [comment]
Closing this here, because we're actually handling this in the teach.moz.org repo: https://github.com/mozilla/teach.mozilla.org/issues/1360
