### ISSUE TITLE
Fix up code collapsing arrows, they're too big.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1143]
![image](https://cloud.githubusercontent.com/assets/25212/10035204/7df157ae-614c-11e5-8118-ea94dbbe7f0e.png)

**Comment by humphd** [comment]
If you want to change this, they are defined in:

* https://github.com/humphd/brackets/blob/bramble/src/extensions/default/CodeFolding/main.less (requires a manual update to `main.css` if you change it)
* https://github.com/humphd/brackets/blob/bramble/src/extensions/default/bramble/stylesheets/lightTheme.css
* https://github.com/humphd/brackets/blob/bramble/src/extensions/default/bramble/stylesheets/darkTheme.css

It's likely just picking up our default font size, which we bumped to be pretty large.

**Comment by humphd** [comment]
So weird, here is what I see:

![screenshot 2015-09-23 16 10 39](https://cloud.githubusercontent.com/assets/427398/10057356/d63ff624-620d-11e5-8ee3-f41ce4a7bb36.png)

I wonder if it's just different fonts between our systems?

**Comment by flukeout** [comment]
@humphd Certainly looks that way! Interesting.

**Comment by jgmac1106** [comment]
Yes, my code collapsing arrows now cover up content
![code collapse](https://cloud.githubusercontent.com/assets/10534566/10073951/9654e2bc-629a-11e5-8f45-6d2053bae942.png)

**Comment by humphd** [comment]
@jgmac1106, what content are they covering?  In the screenshot you posted, they are to the right of the line numbers in their own gutter section.  It looks right to me.

**Comment by flukeout** [comment]
Looks like the whole line mumber column is too wide and is covering the first character of wrapped lined.

**Comment by flukeout** [comment]
@humphd Can you please inspect your editor in Firefox and click on the Fonts tab to see what font is actually being used to render the page for you? 

For me, it's using Courier, which is different than for you and @jgmac1106 

![image](https://cloud.githubusercontent.com/assets/25212/10148798/3cbee720-65fb-11e5-8efa-09605fe39e88.png)

**Comment by humphd** [comment]
![screenshot 2015-09-28 17 15 46](https://cloud.githubusercontent.com/assets/427398/10148980/98d2c802-6604-11e5-85ce-5b9a35bdffe3.png)

**Comment by humphd** [comment]
This has landed on staging.
