### ISSUE TITLE
Pomax can't find a project he wants to show me!

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1145]
@Pomax made a really cool thing in Thimble and can't find it in his projects list. He was clicking through each project in his My Projects list but couldn't find it. Let's explore ways to make things easier to find...

* Thumbnails
* Search inside projects from My Projects view
* Expose more meta data (like if it's published or not
* Not auto-save every untitled project?
* Prompt or suggest that you rename your project once you've made some edits?

@Pomax - want to weigh in?

**Comment by Pomax** [comment]
I noticed this on project https://thimble.mozilla.org/user/mopaxian/6831 which is supposed to have an index.html with a `<script>` element that tries to load in together.js, however the HTML source seems to have been reset to the default starter HTML

Two files: index.html, style.css

**Comment by Pomax** [comment]
I can vouch for the fact that having thumbnails for projects would be super helpful. Especially if there's a number of "untitled project" entries, it's very hard to weed through them, since you can't open them concurrently (project links are not actually links), so you spend a lot of time going through each project one by one.

**Comment by humphd** [comment]
The work on the Thimble Dashboard basically solves this, if we just expose the user page to a logged in user:

![screenshot 2015-10-31 11 32 19](https://cloud.githubusercontent.com/assets/427398/10864407/849d9758-7fc3-11e5-9f89-9db810deb4b6.png)

**Comment by hannahkane** [comment]
As discussed at today's stand, iirc, this solution works, but we'd need to add unpublished projects and related perms. Is that right?
