### ISSUE TITLE
Finalize teacher & student wireframe flows for use in a focus group.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1147]
Current set of wires need to be refined into two separate flows, one from the teacher's and one from the student's point of view.

https://redpen.io/p/xef6f02a9757d2dc22

**Comment by flukeout** [comment]
@hannahkane I've refined the wireframes based on the stuff we discussed. Please have a look.
https://dl.dropboxusercontent.com/u/109902/bramble/thimble-in-the-classroom.pdf

Let's chat later today when you have some time.

**Comment by flukeout** [comment]
I'm making some changes to these based on a review with Kristina and Sabrina, will post at EOD

**Comment by flukeout** [comment]
Here's an udpated version: 
https://dl.dropboxusercontent.com/u/109902/bramble/thimble-in-the-classroom-2.pdf

**Comment by hannahkane** [comment]
@flukeout - looking really good. I'd really like to get input from @chadsansing, since there's a lot of overlap with curriculum functionality here. Chad - maybe Luke and I can walk through this with you next week?

**Comment by chadsansing** [comment]
Yes! Let's set up a time. The wireframe/concept with the instructions & student project tabs is full of win.

**Comment by flukeout** [comment]
@hannahkane Do we want to incorporate some student profile design work into this? It makes sense to have a view where the student sees what classes they are enrolled in.

**Comment by hannahkane** [comment]
@flukeout - now I'm getting confused. Are we talking about the Teach profile or a Thimble profile? This is where they start to merge!

**Comment by flukeout** [comment]
@hannahkane Probably a Teach profile, in the same way that we have a space for teachers to see their classes, we need something for students. I'll add a wireframe for it just to complete the whole picture when we present, and we can decide where it will live later.

**Comment by hannahkane** [comment]
@flukeout - ok, sounds good

**Comment by flukeout** [comment]
Added to the redpen here - https://redpen.io/my97b7166348d208d6

**Comment by flukeout** [comment]
Changes to make based on discussions with @hannahkane and @chadsansing 
* [] Maybe change Enroll to “Join” to make it sound less formal
* [] Reveal some of the public discussion on the submitted projects page (stuff that isn’t feedback)
Student dashboard, should is show a view with some thumbnails? <- we could remove this altogether
Add a view or wireframe for choosing different lessons to run and make your own for teachers.
Stats for teachers?
Change the discussion / commenting systme on projects to be more around discussion and feedback, one of which is public and one of which is private.
Maybe put ‘unread’ submitted projects near the top of the students list
Call out the goals fo the lessons a bit better, and maybe list the competencies that it covers?

**Comment by flukeout** [comment]
@hannahkane @chadsansing I've updated the wireframes to account for all (well, like 99%) of the feedback from our call yesterday...

https://redpen.io/p/xef6f02a9757d2dc22

Next up, I'll work on putting these into a presentation / storyboard format. Please leave comments if you have them.

**Comment by hannahkane** [comment]
Nice job, @flukeout. Left just a couple of comments in the redpen.

**Comment by chadsansing** [comment]
+1000.

**Comment by hannahkane** [comment]
@flukeout - is this closeable?

**Comment by hannahkane** [comment]
This is done, and there's a related ticket in Teach repo, so closing.
