### ISSUE TITLE
"External Changes" warning updating style.css

### ISSUE THREAD

**Issue by emmairwin** [mozilla/thimble.webmaker.org#1150]
After updating style.css I received this message in popup:

"/5216/projects/15587/style.css has been modified on disk outside of Brackets, do you want to save the file and overwrite those changes"

Everything was fine, I didn't lose anything, but FYI.

**Comment by emmairwin** [comment]
![mozilla thimble](https://cloud.githubusercontent.com/assets/60618/10082256/ad38a29e-62ad-11e5-975b-d50098b0a128.jpg)

**Comment by gideonthomas** [comment]
Ah, thank you for reporting this! This is sorta a known issue that kinda slipped through the cracks.

@humphd we seem to have a timing issue when we auto-save for some reason. Brackets seems to detect that there are changes between the in memory version and the fs version.

**Comment by humphd** [comment]
The most likely explanation for this is that we call `writeFile` on the Filer filesystem vs. the Brackets FileSystem wrapper object, which means we don't hash/cache the contents in memory.  We should probably audit our `writeFile` calls so we can use the correct abstractions.

**Comment by humphd** [comment]
Fixed.
