### ISSUE TITLE
Creating new project (locally) doesn't have style.css file

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1156]
I'm not sure if this is just my local environment, or if this is a real bug, but when I create a new project, I'm getting the `index.html` file, and no `style.css`:

![screenshot 2015-09-28 19 11 42](https://cloud.githubusercontent.com/assets/427398/10151372/e7930906-6614-11e5-8d22-80a8e67188f0.png)

The tar file we send just doesn't include it, so it seems like a server-side thing?

![screenshot 2015-09-28 19 13 29](https://cloud.githubusercontent.com/assets/427398/10151385/0e5d6126-6615-11e5-8dc3-adba3fcbc5e7.png)

**Comment by gideonthomas** [comment]
I can't reproduce this :(

**Comment by humphd** [comment]
Let's close it then.  It must be just my env locally.
