### ISSUE TITLE
Improve editor font situation.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1158]
Currently, at least on my machine, the editor falls back to Courier, which is pretty much last on the list of what Brackets actually wants to use...

``'Menlo Regular', Consolas, Inconsolata, 'Vera Sans', 'Lucida Console', Courier, monospace, fixed``

Apparently, Inconsolata is very similar to Menlo Regular, and is offered via Google fonts so let's use that.

This will also let us address the code collapsing arrow size situation (#1143), since we'll be more certain that the editor is using the same font across a variety of browsers.

**Comment by humphd** [comment]
Fixing this in https://github.com/humphd/brackets/pull/475
