### ISSUE TITLE
Cancelling a project rename with changes via ESC key persists the new title in the UI.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1161]
**Steps to reproduce**
* Click the project title to rename it in the editor
* Make some changes to the title
* Hit the ESC key to cancel editing
* The UI reverts to the non-editable title, but with the changes you made

![title-bug](https://cloud.githubusercontent.com/assets/25212/10250178/f34159ce-68ee-11e5-9933-2289ef72f2c6.gif)

**Comment by humphd** [comment]
@errietta do you want to see if you can track down this regression?  Might be related to the change we did with title renames.

**Comment by errietta** [comment]
@humphd  love the gif and sure =)

**Comment by humphd** [comment]
I fixed this, forgot to close.
