### ISSUE TITLE
LESS files don't have CSS highlighting.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1162]
![image](https://cloud.githubusercontent.com/assets/25212/10256740/c362265a-6918-11e5-875d-e65abb4047b0.png)

We can just use whatever theme we use for CSS

**Comment by flukeout** [comment]
@humphd I'm going to sneak this into the pre mozfest milestone to get your take on the effort. It seems like a minimal change could improve this a lot - without the highlighting we're crippling an otherwise really useful feature.

**Comment by humphd** [comment]
This is actually fixed, just not landed on prod.  Closing.
