### ISSUE TITLE
Add ability to change the file you're editing with the keyboard.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1163]
I find it cumbersome to switch the file I'm editing by clicking on it, especially when jumping between a pair of HTML & CSS files. Desktop Brackets allows you to switch between files with Control + Tab, but that switches tabs in the browser, so we need a different approach.

In other editors, you can tab through your 'opened' files, but we don't really have that concept, so maybe just being able to navigate the file tree via some kind of (up / down) action like Option + Command + Up/Down might do the trick.

Brackets shortcuts for reference...
https://github.com/adobe/brackets/wiki/Brackets-Shortcuts

**Comment by humphd** [comment]
The way we've hacked up the tree view in Brackets makes this hard.  I looked into fixing it, but we can't (currently) do anything that will satisfy your request.  I'm going to close.
