### ISSUE TITLE
Get read access to the projects database(s).

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1165]
I'm not sure if we keep published and draft projects in separate databases, but it would be really helpful to have some kind of read access to those places to see what kind of content people are creating.

@jbuck Can you help?

**Comment by jbuck** [comment]
@flukeout Do you have access to the [publish-webmaker-org-prod](https://dashboard.heroku.com/apps/publish-webmaker-org-prod/resources) application on Heroku? You can use the database credentials in the app to view projects via any Postgres tool.

**Comment by hannahkane** [comment]
Is it possible for Lainie and I to have access / instructions as well?

**Comment by jbuck** [comment]
@flukeout can you help Hanna & Lainie?

**Comment by flukeout** [comment]
@jbuck @hannahkane @ldecoursy For sure
