### ISSUE TITLE
Can't use Thimble if I block trackers

### ISSUE THREAD

**Issue by panaggio** [mozilla/thimble.webmaker.org#1167]
I block every tracker that I know, including Google Analytics, and because Google Analytics can't be loaded, I can't even try new Thimble. I see the following message:

> There was an error loading your Project.
> Please refresh your browser.
>
> NOTE: if you are using Private Browsing mode, please reload in normal mode.

I also use DNT. So Mozilla isn't following a standard that it's pushing around?

**Comment by humphd** [comment]
The issue here is IndexedDB not working in Private Browsing Mode in Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=781982.  We can't fix it, but Mozilla is aware of it and working on a fix.

**Comment by panaggio** [comment]
I'm not using private browsing.

Here are my privacy settings:

![Screenshot of Privacy Settings](http://imgur.com/7tzbqF5)

Here are the logs:

	Content Security Policy: This site (https://thimble.mozilla.org) has a Report-Only policy without a report URI. CSP will not block and cannot report violations of this policy. <unknown>
	Content Security Policy: The page's settings observed the loading of a resource at self ("style-src https://thimble.mozilla.org http://mozorg.cdn.mozilla.net https://ajax.googleapis.com https://fonts.googleapis.com https://mozorg.cdn.mozilla.net https://netdna.bootstrapcdn.com"). A CSP report is being sent. XXX:77:0
	Content Security Policy: The page's settings observed the loading of a resource at https://mozillathimblelivepreview.net/bramble/production/dist/bramble.js ("script-src https://thimble.mozilla.org http://mozorg.cdn.mozilla.net http://*.newrelic.com https://*.newrelic.com https://ajax.googleapis.com https://mozorg.cdn.mozilla.net https://www.google-analytics.com https://mozillathimblelivepreview.net/bramble/production https://login.persona.org"). A CSP report is being sent. <unknown>
	The resource at "https://www.google-analytics.com/analytics.js" was blocked because tracking protection is enabled.[Learn More] XXX
	Filer error:  Object { name: "EINVAL", code: "EINVAL", errno: 18, message: "IndexedDB cannot be accessed. If pr…", stack: "e@https://mozillathimblelivepreview…" } bramble.js:3:4004

	UnknownError bramble.js:3:0
	Content Security Policy: The page's settings observed the loading of a resource at self ("style-src https://thimble.mozilla.org http://mozorg.cdn.mozilla.net https://ajax.googleapis.com https://fonts.googleapis.com https://mozorg.cdn.mozilla.net https://netdna.bootstrapcdn.com"). A CSP report is being sent. XXX:1:0
	[Bramble] Failed to load Project state, with Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:4:28248

	[Thimble Error] Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:4:18394

	Content Security Policy: The page's settings observed the loading of a resource at https://mozillathimblelivepreview.net/bramble/production/dist/index.html?locale=en-CA ("frame-src https://thimble.mozilla.org https://docs.google.com https://mozillathimblelivepreview.net/bramble/production https://login.persona.org"). A CSP report is being sent. <unknown>
	The character encoding declaration of the HTML document was not found when prescanning the first 1024 bytes of the file. When viewed in a differently-configured browser, this page will reload automatically. The encoding declaration needs to be moved to be within the first 1024 bytes of the file. index.html:27:0
	[Bramble] browser filesystem inaccessible (needs to be re-formatted, or permission denied due to private browsing mode. bramble.js:4:3478

	[Bramble Error] Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" } main.js:4:27923

	[Bramble] browser filesystem inaccessible (needs to be re-formatted, or permission denied due to private browsing mode. bramble.js:4:3478

	[Bramble] browser filesystem inaccessible (needs to be re-formatted, or permission denied due to private browsing mode. bramble.js:4:3478

	[Bramble] browser filesystem inaccessible (needs to be re-formatted, or permission denied due to private browsing mode. bramble.js:4:3478

**Comment by humphd** [comment]
If you're not in private browsing mode, you might be hitting https://github.com/mozilla/thimble.webmaker.org/issues/1136 which is another Firefox IndexedDB bug.  The fix seems to be using a "newer" Firefox (e.g., Developer Edition), but see that issue for more info.
