### ISSUE TITLE
Code in the editor is overlapped at higher font sizes.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1169]
**Steps to reproduce**
* Increase the font size of the text in the editor

![text-overlap](https://cloud.githubusercontent.com/assets/25212/10378665/f6d40918-6dbe-11e5-82e0-3cfeee717901.gif)

**Comment by humphd** [comment]
We think this is fixed, just going to confirm on staging...

**Comment by humphd** [comment]
Confirmed, this is fixed on staging.  Next time we do a prod push, it will be fixed there too.  Closing.
