### ISSUE TITLE
Track date_created and date_updated for published projects.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1170]
Sadly, we don't right now...

![image](https://cloud.githubusercontent.com/assets/25212/10380326/112fd9b4-6dc8-11e5-9574-289157a6622b.png)

We track them for the projects table, but we have no way of knowing when something was published or the published version was updated.

**Comment by flukeout** [comment]
cc @gideonthomas I'm assuming if someone unpublishes the project, then we remove the record from publishedProjects, right? Are there any other considerations before we can add these fields?

**Comment by gideonthomas** [comment]
I don't think so, just the unpublish case.
