### ISSUE TITLE
Font size increase means editor disappears behind line numbers

### ISSUE THREAD

**Issue by amlwwalker** [mozilla/thimble.webmaker.org#1178]
One making the text bigger

![image](https://cloud.githubusercontent.com/assets/2920180/10455680/8ff7b7cc-71b4-11e5-8d85-d6c7d3124ccf.png)

**Comment by humphd** [comment]
Thanks for filing this, it's something we have on our TODO list in the near future.  I'm going to follow-up in #1169 and dupe this bug on that.
