### ISSUE TITLE
h2 and h3 same font size in tutorial file

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#1181]
Not sure if this is deliberate but the font size seems the same for leevl two and three headers. I would like at least three levels.

**Comment by humphd** [comment]
They are *ever* so slightly different, but perhaps not enough?  See https://github.com/mozilla/thimble.webmaker.org/blob/bramble/public/resources/tutorial/tutorial.css#L29-L37  cc @flukeout

**Comment by humphd** [comment]
I'm going to close this. If there's some action we decide to take, let's do that in a follow-up PR.
