### ISSUE TITLE
Javascript: links in A tags don't work in editing mode

### ISSUE THREAD

**Issue by AndyForest** [mozilla/thimble.webmaker.org#1182]
Demonstration project that shows the error:
https://d157rqmxrxj6ey.cloudfront.net/dimentians/7549/

Steps to reproduce - Add this HTML to a Thimble page:

```HTML
<a href="javascript:alert('Here is the alert!');">An alert should pop up from this link.</a>
```

It does not work in the development mode for a Thimble project. It works fine in a published page. The Javascript console shows this error when you click the link:

[Bramble Error] unable to open path in editor /6584/projects/30576/javascript:alert('Here is the alert!'); NotFound

P.S. New Thimble beta is **awesome**! We love it!

**Comment by humphd** [comment]
Thanks for filing!  I've put a fix up in https://github.com/humphd/brackets/pull/483.

**Comment by humphd** [comment]
@AndyForest this fix should make it to production later this week.

**Comment by AndyForest** [comment]
Wonderful, thank you!
