### ISSUE TITLE
Error on Registration

### ISSUE THREAD

**Issue by emmairwin** [mozilla/thimble.webmaker.org#1187]
I had troubles logging in with my usual username (even after password reset), and so I decided to register a new name altogether, which gave me this error.
![errortitle_401_-_2015-10-20_18 06 55](https://cloud.githubusercontent.com/assets/60618/10625194/78e1eade-7755-11e5-9b08-43dee70c3044.png)

**Comment by humphd** [comment]
cc @cadecairos, @jbuck

**Comment by cadecairos** [comment]
@emmairwin did the request seem to hang for a while before showing you an error?

It seems to be working for my account. Maybe a spike in traffic caused a slowdown?

**Comment by emmairwin** [comment]
@cadecairos it happened when I tried to both register, and login with my second account emmairwin  , although it seems to be working OK now. No sure why, but it was repeatable last night.  Thanks

**Comment by humphd** [comment]
@emmairwin I strongly suspect this was a timeout issue on our ID server, which is a known issue, and there is some idea how to fix (just need time/resources).  I'm going to close this, but if you hit it again, let us know.
