### ISSUE TITLE
Option to Collapse Remix bar 

### ISSUE THREAD

**Issue by emmairwin** [mozilla/thimble.webmaker.org#1188]
Would it be possible to make the Remix Bar, collapsible?

Just looking at how it makes things look busy, and as a user I would want the option to collapse/close the top bar.

example:
https://d157rqmxrxj6ey.cloudfront.net/emmairwin/8398/

**Comment by humphd** [comment]
We've been discussing in https://github.com/mozilla/thimble.webmaker.org/issues/1107.  I'm going to dupe this bug on that, and if you want to jump in there, please do.
