### ISSUE TITLE
The Tutorial is not showing on some thimble activities - download offered instead

### ISSUE THREAD

**Issue by mickfuzz** [mozilla/thimble.webmaker.org#1195]
eg. 
https://thimble.webmaker.org/project/60766/remix

Tried on 2 browsers and 2 computers and I get the same result. 
![bug_thimble](https://cloud.githubusercontent.com/assets/3470500/10686574/554f828e-795d-11e5-84c5-579b0a39ffe4.PNG)

**Comment by humphd** [comment]
The issue here is that https://openmatt.makes.org/thimble/LTkyNDQ1MDgxNg==/tutorial-for-make-a-meme_ is being served with a content-type of `binary/octet-stream` vs. `text/html`, likely because it lacks an extension and the server doesn't know what it is so defaults to binary data.  @OpenMatt this is a file on your server, did you change something recently?

**Comment by OpenMatt** [comment]
@humphd ummm, not that I know of. possible to move that asset somewhere else? I have no idea why this is happening.

**Comment by humphd** [comment]
@OpenMatt it's not anything in the Thimble code--the browser is just trying to load what's at that URL, and your server is responding with a binary type, causing the browser to show a download dialog vs. rendering it.  Whoever owns this project could fix it by a) hosting that file somewhere and naming it with `.html`, and b) updating the project's metadata to point to the new URL.

@mickfuzz we're in the process of switching over to the new Thimble (thimble.mozilla.org) which works differently than the old one when it comes to tutorials.

**Comment by OpenMatt** [comment]
@humphd when you say it's a file on my server, I'm not sure what that means. " https://openmatt.makes.org" is not a server I control or have access to. (Sorry for the dumb question.) Not sure if @jbuck might be able to help.

**Comment by humphd** [comment]
@OpenMatt indeed, I missed the `makes.org` bit and assumed it was your blog or something.  Yes, this is a @jbuck thing: we need `makes.org` to detault to `text/html` vs. an octet stream (see above).

**Comment by jbuck** [comment]
This was totally my fault, fixed in https://github.com/mozilla/make-valet/commit/eb1623ec726003fe92dabf5b1639afae5e0f7aeb

**Comment by mickfuzz** [comment]
Thanks everyone. Just a super quick question seeing as you are here. Are old Thimble activities going to be migrated automatically. I ask because many activities linked from teach.mozilla.org/activities now no longer work.

**Comment by humphd** [comment]
Yes, auto-migration of current Thimble projects to the new system is being discussed and planned in https://github.com/mozilla/thimble.webmaker.org/issues/509.  No date has been set as yet, but it's coming.

**Comment by jgmac1106** [comment]
@mickfuzz I manually transferred many of the old makes into Thimble projects (including the one by @OpenMatt). 

We may want to do the same for activities that will now have dead links.

**Comment by humphd** [comment]
+1

On Oct 25, 2015 6:41 PM, Greg McVerry <notifications@github.com> wrote:

@mickfuzz<https://github.com/mickfuzz> I manually transferred many of the old makes into Thimble projects (including the one by @OpenMatt<https://github.com/OpenMatt>).

We may want to do the same for activities that will now have dead links.
