### ISSUE TITLE
Prevent this page from creating additional dialogues not present in Chrome

### ISSUE THREAD

**Issue by mickfuzz** [mozilla/thimble.webmaker.org#1196]
Hi there, 

I sometimes create activities that include javascript alert pop ups. Example at https://thimble.mozilla.org/user/mchesterman/35277

In the previous thimble both FF and Chrome had a box users could tick  "Prevent this page from creating additional dialogues not present in Chrome". 

FF is still working fine. 

![fff_thimb](https://cloud.githubusercontent.com/assets/3470500/10715663/54da8898-7b16-11e5-8856-47442791b624.png)

But this message never appears for Chrome which make remixing the activity impossible. 

Thanks for the great tool!

![chr_thimb](https://cloud.githubusercontent.com/assets/3470500/10715670/73f3b182-7b16-11e5-8976-a193fba20fe4.png)

**Comment by gideonthomas** [comment]
Hi @mickfuzz,

Thanks for reporting this! Can I ask which version of Chrome you are using? I can't seem to reproduce this on my version (46.0.2490.71).

**Comment by humphd** [comment]
I have been meaning to fix this for a while, so this morning I did! https://github.com/mozilla/thimble.webmaker.org/pull/1208.  I agree that we need an easy way to enable/disable scripts in the preview.

**Comment by mickfuzz** [comment]
Amazing! Great work
