### ISSUE TITLE
Renames do not update the currently open filename

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1197]
STR:
* Open the `index.html` file in the editor
* Rename it to `main.html` (make sure that it is still open in the editor)
* The bar just above the editor still shows "Editor - index.html"

This is what *will* happen once https://github.com/mozilla/thimble.webmaker.org/pull/1180 lands.

**Comment by gideonthomas** [comment]
It seems like this will have to be solved in brackets itself.
Here's what I think a fix would look like:
* The change will probably happen out here: https://github.com/humphd/brackets/blob/bramble/src/extensions/default/bramble/lib/RemoteEvents.js#L80
* Listen for the `fileRenamed` bramble event which should give you the `oldFilePath` and the `newFilePath`
* Check if the `oldFilePath` is equal to the `lastKnownEditorFilePath` and if it is, set `lastKnownEditorFilePath` to the `newFilePath` and send an active editor change event.

I think that should be enough to fix this issue (unless there are some event caveats that I have overlooked).

**Comment by errietta** [comment]
dibs

**Comment by errietta** [comment]
@gideonthomas is this still a thing? I can't reproduce it. I change the file name (by right-clicking the file on the left and clicking rename), and the name above the editor changes right away?

**Comment by gideonthomas** [comment]
@errietta I can still reproduce this. Do you have that file open in the editor when you are renaming it?

**Comment by errietta** [comment]
@gideonthomas yes, it's the currently open file when i try

**Comment by gideonthomas** [comment]
@errietta can you share a screen grab of your process?

**Comment by errietta** [comment]
@gideonthomas now that I have everything up to date i can finally reproduce :smile:

**Comment by errietta** [comment]
R? https://github.com/humphd/brackets/pull/507
