### ISSUE TITLE
Found a record with created_date in the future in the projects table.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1200]
![image](https://cloud.githubusercontent.com/assets/25212/10777390/465db45c-7cd8-11e5-83c1-7f374bbac67d.png)

**Comment by Pomax** [comment]
I am looking forward to seeing what we're doing that day that sends it back into the past

**Comment by humphd** [comment]
@gideonthomas is this due to us having sent dates from the client, and maybe someone's machine having the clock set incorrectly?

**Comment by gideonthomas** [comment]
Yeah that could be possible! https://github.com/mozilla/publish.webmaker.org/issues/165 will probably fix it.
