### ISSUE TITLE
Add more info to the publishedProjects table.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1202]
Right now, we've got the following (with date_created and date_updated coming up :+1:)

![image](https://cloud.githubusercontent.com/assets/25212/10805224/66c1ced4-7d89-11e5-9c81-b25efd49c8b8.png)

Is there a reason for why this table is so sparse? 

It would be great to have access to...
* published_url
* user_id
* id of the source project in the projects table

I find myself just querying the ``projects`` table whenever I want to get published projects because of this.

**Comment by gideonthomas** [comment]
@flukeout are you sure this is still necessary? Most of this can be accessed using slightly longer queries on the projects table. Adding these columns in will involve quite a bunch of migrations and code changes.  Not sure if the technical effort is worth it.

**Comment by gideonthomas** [comment]
Closing since all this info can be acquired from the projects table.
