### ISSUE TITLE
Create a Thimble stats dashboard

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1204]
Let's make a dashboard! Here's a brief outlining what we could show!

https://docs.google.com/document/d/1kp5mOnm0AxiDt5w7IVoq9V-W9F_F84Smo06zyhpONwY/edit

**Here's the current progress...**

**Overview**
* Number of projects created today as well as a 7-day trend
* Thumbnails of latest 10 projects that are live and being edited

![image](https://cloud.githubusercontent.com/assets/25212/10853762/03628e24-7ef5-11e5-8bd9-e111579128da.png)

**Daily Gallery**
* Number of projects published per day, for the last 30 days
* Thumbnails of random 10 projects published for the selected day, with ability to refresh them

![image](https://cloud.githubusercontent.com/assets/25212/10853772/170282fe-7ef5-11e5-839a-794cc8b9cb60.png)

**Slideshow**
* Cycles through the latest 20 projects published one at a time for 'ambient' viewing experience.
* Gets new projects when it has run out.

![image](https://cloud.githubusercontent.com/assets/25212/10853801/4e44338e-7ef5-11e5-9498-628479b6c15b.png)

**Images**
* Shows the latest images that have been uploaded into published projects
* Click an image to view the corresponding project

![image](https://cloud.githubusercontent.com/assets/25212/10853821/6b4632ca-7ef5-11e5-9f75-9f401ea94a7d.png)

**Search**
Searches and shows thumbnails of projects by..
* Title
* Description
* Author
* Thumbnails are clickable and load the corresponding project

![image](https://cloud.githubusercontent.com/assets/25212/10853833/88fa8dca-7ef5-11e5-88ae-8570e81032bc.png)

**Comment by hannahkane** [comment]
cc @ldecoursy @KevZawacki @adamlofting @chrislarry33 @chadsansing

**Comment by Pomax** [comment]
Are we high fidelity enough to see the "created" graph per hour, to get an idea when "the world" is most active on Thimble?

**Comment by flukeout** [comment]
@Pomax Not until we get the date_created field added to the publishedProjects table, right now we can only estimate when things were published.

**Comment by Pomax** [comment]
roger

**Comment by flukeout** [comment]
The Dashboard is live here...
https://thimble-dashboard-staging.herokuapp.com/

**Comment by humphd** [comment]
I'm seeing lots of pages with `alert` and other popups.  Can you add the `sandbox` attribute to your iframes?  It will block them:

```html
<iframe src="page.html" sandbox>
```

See https://developer.mozilla.org/en/docs/Web/HTML/Element/iframe

**Comment by Pomax** [comment]
as far as I can tell the dashboard iframes already have `sandbox` to prevent script execution. Is this on a specific part of the dash?

**Comment by humphd** [comment]
@Pomax, you're right.  I went and inspected all of the iframes, and they all have `sandbox` applied.  So why are there sometimes JS popups?  My understanding is that it should block them, and http://caniuse.com/#feat=iframe-sandbox makes it seem like it is well supported across the browsers we use.

**Comment by humphd** [comment]
Looks like your server is hurting (trying to load the dashboard):

```
https://thimble-dashboard-staging.herokuapp.com/count-created?date=2015+11+05
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
```

**Comment by flukeout** [comment]
I'm unable to connect to the database with Postico, and my app isn't able to fetch data either. Was anything changed about the db setup / authentication in the recent changes?

**Comment by gideonthomas** [comment]
@flukeout can you try again? maybe you accessed it at a bad time? If you're still unable to access it, I can pm you the creds (maybe try to re-type them in) and/or figure out what's wrong with you over video!
