### ISSUE TITLE
Get thimble working on node 4.2.x (LTS)

### ISSUE THREAD

**Issue by cadecairos** [mozilla/thimble.webmaker.org#1210]
It appears to be failing right now while compiling the Nan package for an unknown dependency.

**Comment by humphd** [comment]
@gideonthomas, @sedge, @Pomax, fyi.

**Comment by cadecairos** [comment]
This might be https://www.npmjs.com/package/js-dom

as the contextify package is what's using an incompatible Nan version, and jsdom uses contextify.

**Comment by humphd** [comment]
Do we even use `js-dom` anymore?  I bet we don't!

**Comment by humphd** [comment]
How important is this?

**Comment by cadecairos** [comment]
Pretty important, I'd wager. Node 0.12 isn't maintained anymore IIRC, and any new devs coming to work on this tool will most likely be running at least LTS(4.1.2). I'm running 5.1.0 myself.

**Comment by humphd** [comment]
http://www.infoworld.com/article/3001675/javascript/nodejss-release-cycle-hits-the-fast-lane.html
