### ISSUE TITLE
Thimble Bar Interferes With Top: 0px; CSS

### ISSUE THREAD

**Issue by theatomickiwi** [mozilla/thimble.webmaker.org#1220]
When using the css property <code>top: 0px;</code> the bar thimble appends to the html is covered by the content. I cannot think of any fixes other than using an iframe. Here is an example:
![mozilla thimble](https://cloud.githubusercontent.com/assets/13374049/11012901/ddcc9b20-84c9-11e5-960a-8fd842b3addb.PNG)

**Comment by humphd** [comment]
We've been discussing this in #1107.  You're right, and doing the iframe option (which we used to do) has other issues.

cc @flukeout, @Pomax

**Comment by flukeout** [comment]
Agreed - I think the approach we're honing in on in #1107 addresses this. Ultimately, I think it's okay that we will end up obscuring some small part of a project. I'm going to close this issue since we're already working on it.

Thanks for filing @theatomickiwi
