### ISSUE TITLE
[MozFest] Make markdown tutorial files more intuitive to use

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#1222]
There are a few problems with our current implementation:

1. `<div class="tutorial"></div>` must be manually wrapped around markdown content to get the correct styling, which defeats the main purpose of using markdown to avoid HTML
2.  Adding a `tutorial.md` file is a two step process (add `tutorial.html` and then rename to `tutorial.md`)
3.  If possible, the generated `tutorial.html` file should be hidden from the user (minor)

I'm not sure how much of this I can patch this weekend, but I'll try and tackle all three.

**Comment by humphd** [comment]
We're thinking about tutorials elsewhere, not sure this is a priority.  Closing for now.
