### ISSUE TITLE
[MozFest] Add a markdown cheatsheet

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#1223]
I credit GitHub's markdown cheetsheet for my mastery of it. We should provide the same opportunity to Thimble users!

**Comment by hannahkane** [comment]
I'm starting to think the Help link should actually be a dropdown menu with links to the FAQ and other resources, such as the cheatsheet.

**Comment by sedge** [comment]
@hannahkane +1

Is there an issue filed for this? If so I'll add this as a comment there and we can close this issue.

**Comment by hannahkane** [comment]
Just edited #1255 to be about this
