### ISSUE TITLE
Learn from #glcCodeDay + #MozFest spike, better scaling

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1225]
Today we had a lot of users hit us all at once.  I think it's a useful experience to reflect upon, and to try and learn from going forward.  Here's what the Thimble app looked like, followed by Publish:

**Thimble Node App:**

![screenshot 2015-11-07 22 32 40](https://cloud.githubusercontent.com/assets/427398/11018613/848efacc-859f-11e5-8244-b15b4b830a2b.png)

**Publish Node App:** 

![screenshot 2015-11-07 22 29 28](https://cloud.githubusercontent.com/assets/427398/11018614/8bb59072-859f-11e5-9219-aa91b60aa036.png)

Both apps were initially running on 2 dynos, and we were seeing a lot of timeouts.  I've recently landed changes in Thimble to mitigate this problem, and have network operations against publish get cached and restarted, so I don't think users would have noticed them, even though there were a lot.  At ~1:30 pm EST you can see it crash completely.  After this, @jbuck scaled both apps up (first to 8 I think, then to 20 dynos).

I want to dig into the logs a bit more, but already a few things occur to me:

* we knew about MozFest, but I'm not sure we knew about Thimble being used for glcCodeDay (maybe @hannahkane did?).  When we know we'll have big events, we might want to pre-emptively scale things up
* however, we often won't know, and users will appear in a big spike all at once (groups vs. individuals).  We need some kind of automated way to have the apps scale themselves up, or to trigger some warnings to alert our people.  When this happens on the weekend, like today, we need to think through how to deal with that, too.
* I want to try adding some back-off logic and retry jitter with the Thimble-to-Publish updates.  With autosaving, we send changes to publish a lot for a logged in user.  If the server is reporting 503s, we should back-off our next retry, and give it time to catch up, and then add some random delay so all clients don't follow the same pattern and continue to pound the server, such that it can't recover.

@jbuck might have other thoughts, since he was also watching this happen.

cc @simonwex, @Pomax

**Comment by humphd** [comment]
Another thing I noticed is that the GA numbers are totally bogus.  I watched the real-time stats for thimble.mozilla.org throughout the afternoon and it had zero correlation with what was actually happening on the servers or on Twitter--I could see more people using it via pics posted on Twitter than were ever showing on the GA dashboard.  If we're relying on these numbers in any way, I'd say you want to figure out why they don't reflect reality.  cc @adamlofting

**Comment by humphd** [comment]
Also, the continued cost of id.webmaker.org/login.webmaker.org for all authenticated routes is killing us.  Here's what it looks like to save files from Thimble to publish:

![screenshot 2015-11-07 22 54 33](https://cloud.githubusercontent.com/assets/427398/11018673/a4adb1a6-85a2-11e5-8e6b-ba571e27ff79.png)

Average times in the 267ms range, and taking 131% of the time, is a disaster.  I know @cadecairos's been working on a patch for this...it can't some soon enough.

**Comment by gideonthomas** [comment]
We might want to consider storing "sessions" on publish (probably as a table or by extending the "users" table with a mapping of username/id to "current oauth token") so that we only hit id.wm.org once and hit our local db instead for routes that require authz every time and are used often (like the PUT routes). I know this sorta defeats the oauth paradigm but this might give us some considerable savings wrt response times.

I agree that we should probably add "special handlers" on the client-side for dealing with 503 errors specifically since we know what they usually mean.

**Comment by humphd** [comment]
@gideonthomas, that's a great idea, I'll file it in publish.

Also, I filed https://github.com/mozilla/thimble.webmaker.org/issues/1241 to look at adding exponential backoff.

**Comment by humphd** [comment]
@jbuck btw, I notice that https://hourofcode.com is happening Dec 7-13, in term of another window of time where scaling might be wise.

**Comment by jbuck** [comment]
@humphd oof, good catch

**Comment by humphd** [comment]
#1283 deals with better offline support.
