### ISSUE TITLE
make "start from scratch" a real link

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.webmaker.org#1226]
Make start from scratch a link like "https://thimble.mozilla.org/new" and then link to that, so that it's easy to bookmark "starting something new" instead of only being able to go through loading a site, clicking a button, then loading thimble.

**Comment by gideonthomas** [comment]
This will be possible(I'm pretty sure) once https://github.com/mozilla/publish.webmaker.org/issues/165 lands

**Comment by flukeout** [comment]
:+1:
