### ISSUE TITLE
"intense" JS gets in the way of typing text

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.webmaker.org#1240]
If I have some JS that would auto-run as the page loads, and it's fairly processing heavy, I can't reliably type HTML and plain text anymore because the processing "steals" the time necessary to register keyboard input, causing me to lose letters and even full words.

example: editing index.html on https://d157rqmxrxj6ey.cloudfront.net/mopaxian/12751/

**Comment by humphd** [comment]
You know about the new thing we added to disable JS execution?

![screenshot 2015-11-08 11 06 47](https://cloud.githubusercontent.com/assets/427398/11021225/eca15132-8608-11e5-9860-0750be169a20.png)

Or do I misunderstand?

**Comment by flukeout** [comment]
We might want to look at moving this to the preview pane. Here it seems related to the Editor itself. I'll mock something up that we can discuss.

**Comment by gideonthomas** [comment]
Closing since there is a workaround.
