### ISSUE TITLE
Full-screen preview without publishing

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1242]
Watching the tweets for National Girls Learning Code day, I noticed this pattern happening a lot:

![image](https://cloud.githubusercontent.com/assets/427398/11045027/1a28de1e-86f3-11e5-9617-c384302809c2.png)

Here you see someone wanting to either see or show their work without the editor or file tree.  In Bramble we actually have code to do this, and open the preview in another tab.  I think we need a button to make this easy to do.  We might tell people to just publish their work, but if you're working anonymously, this isn't possible.

cc @flukeout

**Comment by flukeout** [comment]
Yeah, been thinking about this too. I'll take a crack at some wireframes, we can tackle this in a few different ways...

* Pop open in new tab
* Have the preview pane take over the editor pane
* Have the preview pop-over the rest of the editor as a sort of lightbox

It seems like the biggest problem is that the preview pane is too narrow.

**Comment by flukeout** [comment]
Here are some comps of the last two approaches I listed.

![image](https://cloud.githubusercontent.com/assets/25212/11135900/6f6a7dd4-895e-11e5-8b01-b0466904b7fe.png)

**Comment by jgmac1106** [comment]
I like the idea of a preview opening in a new tab. Not sure if that is
technically possible.

**Comment by humphd** [comment]
@jgmac1106 we wrote code that does this, but haven't exposed the UI yet--so yes, it's technically possible.

With what @flukeout has done above, you wouldn't totally "leave" Thimble (i.e., you'd still have some visual connection to the tool).  Would opening in a new tab cause some people to feel like they've lost their place (editor is still there, but in another tab)?

**Comment by jgmac1106** [comment]
Not sure I know I use the preview feature all the time when using the text
editor in WordPress.

In old Thimble when I wanted to preview before going live I would publish
but leave it unlisted.

I think when people are pulling the preview screen all the way over they
are try to see what it looks like on "the real web."

**Comment by flukeout** [comment]
Also add in ability to "Add UI to allow editor to go fullscreen" from a closed bug.

**Comment by flukeout** [comment]
@humphd I'm going to hold off on this until we get a stronger indication that it's a desired feature. It's hard to tell from the screenshot you pasted if the person using Thimble at that time wanted the tool to do anything differently than what it was already doing (making the preview wider for a bit).

**Comment by humphd** [comment]
There's one use case that we should consider that our current approach doesn't cover, and that's being able to separate cursor focus between the preview and editor.  When it's all running in the same tab, you can't easily do things that require special focus or keyboard shortcuts.  I know @Pomax has hit this elsewhere.  It's not our default case, but it's one to consider.  It would be made less problematic if you could click a button and have the preview live in a new tab.

**Comment by flukeout** [comment]
By editing a few rules in the inspector while using the editor, I was able to achieve this...

![image](https://cloud.githubusercontent.com/assets/25212/11257739/885341e2-8e08-11e5-980d-8397c6794ae1.png)

Which is essentially what we're after. To achieve this we'll need...

* A bit of UI in the Preview Bar with a 'fullscreen' icon
* Some CSS for Thimble to collapse the header and editor bars
* An event that is sent from Thimble to Brackets that tells it to go fullscreen
* Some CSS for Brackets to temporarily hide the file tree / editor pane and max out the Preview 
* A bit of UI overtop of the Preview (within brackets) for getting out of this view (or via Esc Key maybe)

**Comment by flukeout** [comment]
Here we go - some potential UI

![image](https://cloud.githubusercontent.com/assets/25212/11258810/6a6a3646-8e11-11e5-9571-bf5064fa7566.png)

Icon choices aside, what do you guys think @hannahkane @jgmac1106

**Comment by humphd** [comment]
I think it's fantastic!  I'd love to help you make this happen.  This would solve the printing case too.

**Comment by hannahkane** [comment]
Nice! Feels like a really good solution.

**Comment by flukeout** [comment]
Making some good progress here, PR incoming soon.

![fullscreen](https://cloud.githubusercontent.com/assets/25212/11285342/dcd38888-8ec3-11e5-92b5-89273ec3319d.gif)
