### ISSUE TITLE
Update home page video with new MDN docs shortcut key

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#1245]
The new binding is `alt-k` on all platforms, but the video mentions `ctrl-k`.

**Comment by flukeout** [comment]
Yeah, that's the trouble with videos, huh.

**Comment by sedge** [comment]
@flukeout As a simple fix, can I recommend we add an annotation during that part of the tutorial with the correct command? YouTubers do this all the time to correct small mistakes.

**Comment by flukeout** [comment]
@sedge Good call, i'll do that.

**Comment by humphd** [comment]
And/or I can just restore the keyboard shortcut for this? It only affects the search box in Firefox.

**Comment by sedge** [comment]
Wouldn't that take away the functionality for firefox users? I think it's better to keep it as is. 

@flukeout What do you think?

**Comment by flukeout** [comment]
I've updated the video with a little annotation...

![image](https://cloud.githubusercontent.com/assets/25212/11547560/bbe0e4a4-9909-11e5-8425-72b1347d7323.png)
