### ISSUE TITLE
Projects published before adding a 'date_created' field to 'publishedProjects' have a NULL 'date_created'

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1248]
@gideonthomas We'd talked about populating the ``date_created / date_updated`` field with the ``date_updated`` field from the associated project in the ``projects`` table. Is that still the plan?

![image](https://cloud.githubusercontent.com/assets/25212/11189235/eeb7bb8c-8c43-11e5-8922-10f76e0c86b5.png)

**Comment by gideonthomas** [comment]
I have a PR up for this: https://github.com/mozilla/publish.webmaker.org/pull/192

**Comment by flukeout** [comment]
Ah, cool - closing.
