### ISSUE TITLE
Refresh doesn't always load a preview based on current code

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/thimble.webmaker.org#1257]
Sync sometimes fell behind, causing a manual preview refresh to show prior code. 

**STR**
 - load a project
 - make a couple of quick edits
 - quickly hit refresh

**Expected**: See a preview based on current code
**Actual**: Occasionally saw a preview based on code a sync or two behind 

I had a moment or two when I tried a thing and thought it failed, but then discovered it worked but wasn't yet loaded. If I understand what's happening correctly...

**Possible solutions**: 
 - Add sync indication or lock to the refresh button
 - Generate preview from local build

p.s. I pulled a project of mine into thimble and reworked it a bunch. I found thimble very satisfying to use.

Project: https://d157rqmxrxj6ey.cloudfront.net/okfuture/14624/

**Comment by gideonthomas** [comment]
+1 to the first solution (let's allow refresh only when possible)

**Comment by humphd** [comment]
I suspect this is only going to happen for JS files, and is due to the file not being saved yet when you hit refresh.  We should probably save the current file in the editor before we refresh.

**Comment by gideonthomas** [comment]
This is an edge case and since there is a workaround for this, closing.
