### ISSUE TITLE
Forcing Title Change Before Save

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#1272]
I am seeing many of my students get lost in myprojects mainly due to user error. They simply do not title projects and either end up with Project (remix) or Untitled Project.

Thinking, once again, that maybe we should force a name change on first save.

**Comment by flukeout** [comment]
Yeah, this has bothered me a bit personally too - I have a ton of projects on my list and I have no idea what they were or how they got there. We save your projects pretty aggressively. This could be solved by either/or/both of...

* Asking for an explicit save action the first tim you want something saved (and auto-saving after)
* Asking users to rename a project before saving if it's "Untitled"

I'm not sure that "Some Project (remix)" is a bad titles - as it's pretty representative of the content generally. It's the Untitled ones that get me.

**Comment by flukeout** [comment]
Also, some kind of preview of the project might be nice on that list too.

**Comment by hannahkane** [comment]
If we require a save action the first time, could we do a warning if the user tries to close the window before saving? I'm especially concerned about people who have been using Thimble and expect their work to be saved automatically.

Also, would that apply to anonymous users as well?

Love the idea of adding a preview on the My Projects page. It's already a part of the conversation in #1106.

**Comment by jgmac1106** [comment]
Could it still autosave but then either before you publish or close the
window you are asked if you want to save a file name?

**Comment by flukeout** [comment]
Closing, as I've incorporated this into the thinking in #1284
