### ISSUE TITLE
Allow one to go from an element in preview pane to corresponding code (X-Ray Goggles like functionality for Thimble) 

### ISSUE THREAD

**Issue by asdofindia** [mozilla/thimble.webmaker.org#1274]
#### Problem ####
@jgmac1106: 
> In most Thimble projects tutorials start at line 1 and work their way down. Yet when teaching with Thimble I notice kids point not to code but to the preview and ask, "How do I change that?"

> Thimble is divided into two windows the editor and the preview. Novice users, when they get stuck point to the preview. They ask for help fixing a specific thing like an image or a text.

#### Solution ####
Mix X-Ray Goggles like functionality into Thimble.

#### Background ####

@humphd [commented](https://github.com/mozilla/thimble.webmaker.org/issues/573#issuecomment-121250653) in #573 
> Because we control the connection between the editor and the "web browser" (i.e., the Bramble iframe that renders content), we could even add an API for tutorials and other learning material to control the editor: highlight lines 150-155, switch to file style.css and line 76, create a new HTML file with a predefined set of elements to use for a section of the tutorial, etc.

@flukeout [commented](https://github.com/mozilla/thimble.webmaker.org/issues/1246#issuecomment-156509809) in #1246 
> A tutorial step bar is presented at the top of the editor. Clicking a step takes the user to the related file and line number. When the step is dismissed, the tutorial bar becomes visible again.

@jgmac1106 asks in #1110 for line numbers
> Is there a way to link the line numbers in the tutorial file to the line numbers in the other file?

#### Suggestions ####

* A button on the bar above preview pane which says enable X-ray mode
* Hi-jack right click in preview pane and show context menu to show the code that corresponds to the element clicked
* In X-ray mode clicking on an element in preview pane should show the code behind it
* The code can be shown in a pop-up like X-ray Goggles does, or
* Better, the code in the file pane can be highlighted and scrolled to.

**Comment by humphd** [comment]
There are some great ideas in here.  I've started working on some of it in #1276 and https://github.com/humphd/brackets/pull/506.

**Comment by jgmac1106** [comment]
+1 thank @humphd.

**Comment by humphd** [comment]
This has landed on production now, and I've documented it here:

https://github.com/mozilla/thimble.webmaker.org/wiki/Using-Thimble#inspector
