### ISSUE TITLE
Design UX for "inspector" feature in Bramble

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1276]
I've got a [PR up for Bramble](https://github.com/humphd/brackets/pull/506) that adds bi-directional inspecting (hovering in editor shows DOM element in preview; hovering in preview shows associated code).   It needs some thinking around proper UX:

* I think we need a button to turn it on/off, so it doesn't autoscroll your editor just by moving your mouse into the preview.  Maybe modelling it on the Inspector in dev tools
* I've got a "click-to-pin" feature, so if you hover over something, and click, it will stop jumping around to other parts of the code.  I'm not sure if I should still highlight other things, but not scroll you, etc.  Again, the Inspector probably gives us some models to follow.
* I use a flash effect on the background of the lines.  I need some better CSS to apply to the lines.
* I wonder if we should change the mouse pointer when you're in "inspector" mode?

**Comment by jgmac1106** [comment]
In tems of the on-off swith I wonder if this could be combined with
@flukeout's Ui around the help menu. Could the features people want to
toggle on and off (like this and auto-complete tags) be a check box in that
menu?

**Comment by flukeout** [comment]
Here are some thoughts...

The inspector tool is another item in the Preview bar. Click to Turn it on. 

![image](https://cloud.githubusercontent.com/assets/25212/11485517/743cf6e4-9768-11e5-8188-a4ec70204b0f.png)

Inspector icon is WIP

**When Enabled**

* Hovering over an element in the preview
  * Highlights that element
  * Highlights the relevant code and scrolls it into view in the Editor

![image](https://cloud.githubusercontent.com/assets/25212/11485534/8a737d16-9768-11e5-8aac-b96ffadba5a0.png)

* Hovering over code in the editor
  * Highlights the markup for the hovered element
  * Highlights and scrolls into view that element in the Preview

![image](https://cloud.githubusercontent.com/assets/25212/11485553/a841c5c8-9768-11e5-8802-e501e5a1b7b8.png)

* When an element is clicked (either in the Preview or the Editor)
  * The Inspector mode is turned off
  * The highlights persist until the document is modified in the editor, or the user clicks into the editor in a different place, at which point our regular highlighting takes back over.

**Comment by flukeout** [comment]
@humphd Let's discuss this proposal. In the meantime I'll be working on 

* Finalizing the icon
* Finalizing the dark and light theme Code highlights

**Comment by flukeout** [comment]
Let's try ``rgba(0,135,207,.3)`` as the background color for the highlighted lines in the Editor, as seen below...

![image](https://cloud.githubusercontent.com/assets/25212/11488561/60aaec80-977c-11e5-83d0-842367d41c7b.png)
