### ISSUE TITLE
Update "Using Thimble" doc with new features

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#1281]
https://github.com/mozilla/thimble.webmaker.org/wiki/Using-Thimble

**Comment by hannahkane** [comment]
@humphd - I just added some of the new features to the Using Thimble doc and *then* read the first paragraph and realized your original intention for this page was to only demonstrate non-Brackets features. I know some of the new features I added are probably native to Brackets (though I'm not sure which ones). I can either remove them, or edit the first paragraph to say this is just about useful features that users may not be aware of. I'm leaning towards the latter bc I think this page does such a good job of explaining Thimble features to new users. What do you think?

**Comment by humphd** [comment]
I think keep them, there's no point making people go looking at Brackets vs. Bramble for this stuff--no one other than me will care about the distinction :)  If you want to modify the first paragraph, go for it.

I'll add another section on the new Inspector when I land that later today.

**Comment by hannahkane** [comment]
Thanks, @humphd. Updated initial paragraph.

**Comment by humphd** [comment]
I added the inspector section: https://github.com/mozilla/thimble.webmaker.org/wiki/Using-Thimble#inspector
