### ISSUE TITLE
Improve Icons in the UI

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1288]
We have a bit of inconsistency in the icon set used in the UI, look below...

![image](https://cloud.githubusercontent.com/assets/25212/11545110/4c0ead64-98fa-11e5-9927-3c1ed9c354eb.png)

There are a few different stroke widths here. I'll tighten this up - no rush though.

**Comment by flukeout** [comment]
Nevermind! Looks pretty good.

**Comment by cassiemc** [comment]
fastest bug fix ever!
