### ISSUE TITLE
Safari doesn't remove `display: none` on remix details bar in published page

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1290]
From irc, @omnignorant noticed that Safari isn't showing the remix button.  I've confirmed with:

https://d157rqmxrxj6ey.cloudfront.net/chadsansing/17148/

It appears that our jquery to remove the `display:none` on the remix header bar isn't working for some reason.  I see various sites discussing issues with `elem$.css(...)` in Safari.

**Comment by flukeout** [comment]
Related to #1295
