### ISSUE TITLE
Always let a user work on a project, even if services are down

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#1302]
There was a period of time today when the id server was down for a few hours:

![screenshot 2015-12-05 22 24 13](https://cloud.githubusercontent.com/assets/427398/11611501/11f698c4-9b9f-11e5-9770-03ced9cd2f8c.png)

During that time, requests to the publish server, which depend on id, were returning 500s.  The result was that users could load thimble.mozilla.org (the homepage), but trying to open a project of any kind would fail.

What I'd like to see us do instead, is give the user an anonymous project when the remote services are down, so that as long as Thimble itself is up, they can work on something.  Basically, if our external services are returning 500s on startup, we shouldn't fail, but should provide a slightly less complete version of the editor (local saving only, no publishing) so that users aren't stuck.

**Comment by gideonthomas** [comment]
Probably not something we're gonna figure out anytime soon. Closing.
