### ISSUE TITLE
Can you tell us how many times someone has remixed one of our projects?

### ISSUE THREAD

**Issue by melissacrnic** [mozilla/thimble.webmaker.org#1307]
Specifically this one: https://d157rqmxrxj6ey.cloudfront.net/ytvholiday/14497/ 

Thanks!

**Comment by humphd** [comment]
I'll have to get @gideonthomas or @flukeout to help with remix numbers, since it will require a db query.  But here is GA data for that page:

![screenshot 2015-12-15 15 57 15](https://cloud.githubusercontent.com/assets/427398/11823902/aa620574-a344-11e5-9047-f4dab61f4586.png)

**Comment by melissacrnic** [comment]
Thanks! So fast!
ᐧ

--
Melissa (Crnic) Sariffodeen
Co-Executive Director,
Ladies Learning Code
647-922-6110
@learningcode @melsariffodeen
www.ladieslearningcode.com

**Comment by gideonthomas** [comment]
Unfortunately for the moment we will have to rely on GA data until https://github.com/mozilla/thimble.webmaker.org/issues/1172 is fixed

**Comment by hannahkane** [comment]
Closing this ticket. #1172 remains open to address the larger issue.
