### ISSUE TITLE
Changing File Name Should Save a New File

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#1315]
Feel free to close if dupe ticket.

I have lost quite a few projects (user error) given we are trained that changing a file name saves a new version of a file. 

If I change the project name of an existing project it should save a new project. 

At the very least I need a "remix" or "copy project" button on the "My Projects" page. I use many projects as templates for future work. Currently to remix my own project I have to go to myprojects, hit publish, click on link, and then hit remix.

That entire step should be handled by saving an existing file with a new file name. I accidentally saved over https://thimble.mozilla.org/user/jgmac1106/84247 when I was trying to use that project as a template. Shame as I really liked that project.

If there is anyway I can restore back a few saves on that project would be awesome.

**Comment by Pomax** [comment]
I'd think a "copy as new project" menu option would be quite useful, too.

**Comment by jgmac1106** [comment]
on a unrelated and positive note I found my overwritten project in earlier
draft form. Now I just need to update some links. But I agree with @pomax

**Comment by hannahkane** [comment]
Not necessarily a dupe, but adding a "Remix" button to the My Projects page is already a part of #1289. 

@jgmac1106 - what do you mean that we're trained that changing a file name saves a new version of a file? Curious to understand better.

**Comment by jgmac1106** [comment]
I meant there are usually two commands. Save and Save As. In retrospect
changing file name doesn't usually save a new file .

It was late so the rant probably doesn't make much sense. I am going to
close the ticket.
