### ISSUE TITLE
Thimble UI zoomed in on iOS

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1323]
Thimble looks like it's been zoomed in a lot on iOS 9.2 Safari and you cannot zoom out. I'm able to reproduce this on my iPhone. No idea if this is also the case on an iPad.

This probably bring up another issue about whether we want thimble (specifically the editor) to be useable on a phone or not and how much effort we should put into it if we decide that it should.

cc @chadsansing, @flukeout, @hannahkane

**Comment by hannahkane** [comment]
I think it's unlikely we can support editing on mobile soon. Perhaps we should say as much to users?

**Comment by gideonthomas** [comment]
This is also related: https://github.com/mozilla/thimble.webmaker.org/issues/1294

**Comment by gideonthomas** [comment]
Closing for now since we're not supporting editing on mobile. As for how we're gonna handle that: https://github.com/mozilla/thimble.webmaker.org/issues/1294
