### ISSUE TITLE
Staging - Tutorial doesn't remember its scroll position anymore.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#1340]
Since the changes to implement anchors within the tutorial, the tutorial stopped remembering its scroll position.

**Steps to reproduce**
* Create a new project
* Add a tutorial
* Scroll the the bottom of the tutorial
* Click the index.html file to edit it
* Click Preview
* Click Tutorial to go back to the tutorial

**Expected** - Tutorial stays scrolled to the bottom where you left it
**What happens** - Tutorial is scrolled to the top

cc @gideonthomas - as discussed.

**Comment by flukeout** [comment]
@gideonthomas is it ready to re-test on staging?

**Comment by gideonthomas** [comment]
@flukeout yep
