### ISSUE TITLE
Able to Log into Old Thimble

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#1341]
An FYI, feel free to close,

Tonight I was going through and pulling source code from old Thimble projects when I noticed I could log in and access the editor of old Thimble.

This worked in Firefox but not Chrome.

**Comment by gideonthomas** [comment]
Yeah, we're waiting on shutting that down until we localize new thimble so that we have at least one localized version up and running (it's weird that it does not work on chrome though O.o)

**Comment by jgmac1106** [comment]
Thanks it has actually been great. I when I needed an old project I would have to use source code. Now its a bit easier for me to get the projects I used for teaching and migrate them to new Thimble.
