### ISSUE TITLE
Decide whether or not we need locale in the URL

### ISSUE THREAD

**Issue by alicoding** [mozilla/thimble.webmaker.org#1343]
Example:

https://thimble.mozilla.org/en-US/anonymous/1ce97170-f9c9-47c8-b98c-dd80f3867936

Vs.

https://thimble.mozilla.org/anonymous/1ce97170-f9c9-47c8-b98c-dd80f3867936

It doesn't matter if we don't add the locale as long as we can switch it using the dropdown. The reason I raise the issue here is that adding the locale might add a bit more complexity to the URL itself because it's already long and we can easily make a mistake here.

**Comment by simonwex** [comment]
Hey @alicoding what are the advantages of adding it to the URL? The only one I can think of is that people sharing the URL can share the interface locale.

**Comment by alicoding** [comment]
Not much really based on my knowledge. Only people can share localized version of the app and knowing that this app is support localization. Other than that it adds complexity to the app really.

**Comment by gideonthomas** [comment]
Based on our discussion in today's stand, we decided to include the locale in the url. @simonwex is this good to close?

**Comment by alicoding** [comment]
Let's close this one since I believe we will stick with URL and browser
preferences for language for now.
