### ISSUE TITLE
Component list [Thimble] requiring L10n

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1345]
* Header/userbar for [editor](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/views/editor/userbar.html) and [homepage](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/views/homepage/userbar.html)
* The [homepage](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/views/homepage/index.html)
* [My Projects List](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/views/editor/projects.html)
* [Navigation bar](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/views/editor/nav-options.html)
* The publish dialog ([static](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/views/editor/publish.html) and [dynamic](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/public/editor/scripts/editor/js/fc/publisher.js#L8-L12)) content
* [Errors loading Brackets](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/views/editor/bramble.html#L121-L136)
* [Project renaming](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/public/editor/scripts/editor/js/fc/project-rename.js) UI
* [Remix bar for published projects](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/public/resources/remix/index.js)

**[id.webmaker.org l10n](https://github.com/mozilla/id.webmaker.org/issues/10)**

**Comment by humphd** [comment]
What about the starter content you get?  If you load a Russian version of Thimble, will you get a Russian starter page?  I think you should.  That doesn't have to be true of all the starter projects on the home page (i.e., you could localize those later, and change the URLs for that locale).  But for the initial content we give when you create a page (public/resources/default-files/*).

**Comment by simonwex** [comment]
RE: starter content #1344

**Comment by simonwex** [comment]
Redundant ticket.
