### ISSUE TITLE
Component list [Brackets] requiring L10n

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1346]
* Core (#1356) 
 * L10n already done
 * Need to figure out how to keep up with upstream translations (or rather if we even need to)
 * Apparently a bunch of extensions depend on the l10n resource files from the core
* bramble client api (#1357)
 * Mainly the [tutorial file name](https://github.com/humphd/brackets/blob/bramble/src/bramble/client/main.js#L40)
* Other Extensions
 * Selfie-taker ( #1358)
 * DnD of zip files (#1359)
 * WebPlatformDocs (#1360)
   * Probably not critical if we decide to stick to MDN
 * Moving files and folders ( #1361)
 * bramble (#1362)
   * Tooltips mainly (I think)
 * HTML linter (#1363)
 * MDN Docs (#1364)

**Comment by gideonthomas** [comment]
@humphd anything I might have missed?

**Comment by humphd** [comment]
This is a good start.  I think we'll uncover more as we go, but I can't immediately identify anything missing.

The only thing I'd call out specifically, which you might be considering elsewhere, is the need to get the locale choosing figured out between Thimble and Bramble.  I discussed this a bit in https://github.com/mozilla/thimble.webmaker.org/issues/1331

**Comment by simonwex** [comment]
Hey @gideonthomas I've broken the components out into individual issues we can triage during today's meeting. Do you mind taking a look to see if I've ham-fisted any of it?
