### ISSUE TITLE
Figure out flow between existing translation format and pontoon

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.webmaker.org#1349]
Existing brackets strings are held in a javascript string file. Pontoon doesn't currently support this format and it doesn't currently have the ability to hold descriptions of the text to be translated:

```JavaScript
define({
    /**
     * Errors
     */
    // General file io error strings
    "GENERIC_ERROR"                     : "(ошибка {0})",
    "NOT_FOUND_ERR"                     : "Файл не найден",
...
```
(from https://github.com/humphd/brackets/blob/bramble/src/nls/ru/strings.js)

Pontoon uses PO files which are more featured than what require i18n uses. For example, plural features:

```
#: src/msgcmp.c:338 src/po-lex.c:699
#, c-format
msgid "found %d fatal error"
msgid_plural "found %d fatal errors"
msgstr[0] "s'ha trobat %d error fatal"
msgstr[1] "s'han trobat %d errors fatals"
```

**Comment by simonwex** [comment]
Options could include:

a. A conversion process:
  1. Extract untranslated strings from the existing JS files into PO files
  2. Open JS NLS files and fill in results from pontoon's PO files
b. Convert brackets to use PO files
  * this would require discussions with the brackets team
c. ...?

**Comment by humphd** [comment]
Probably there is prior art we can use/steal here, if we decide to do a build step for reparsing, eg:

https://github.com/sinedied/gulp-po-requirejs-i18n/blob/master/README.md

**Comment by gideonthomas** [comment]
We should discuss this in today's stand (@humphd, I can comment in this bug after, if you are not able to attend today) since I just had a conversation with @alicoding re: a similar approach we might take in Thimble. Maybe we can use a common strategy.

**Comment by humphd** [comment]
One more thought...I think we should consider if we want to bother with the bulk of the strings in Brackets at all vs. just doing our own thing.  There's a ton of UI that we never use in Bramble that Brackets needs, and it might be easier to just dump it and start over.  This would free you from the burden of using their files/format. Food for thought.

**Comment by alicoding** [comment]
http://mozilla-pontoon.readthedocs.org/en/latest/ List of supported file format from Pontoon, but the one I've mentioned and it's not listed is `.properties` which we're using in donate.mozilla.org https://github.com/mozilla/donate.mozilla.org/tree/master/locales/en-US

**Comment by gideonthomas** [comment]
Note: figure out if requirejs i18n makes an xhr call to get the appropriate locale file or if all the locale files and bundled in the built file

**Comment by gideonthomas** [comment]
Here's what we have for the Thimble part so far (will iterate on it to add the Brackets component). @simonwex  let me know if it needs to be more detailed:
https://drive.google.com/open?id=0BwCd-6qteGa8bDhmT2RJUE1ydkE

**Comment by alicoding** [comment]
I also just set up a meeting with Mathjaz on Monday at 10AM EST to figure out how to setup with Pontoon here for Brackets and thimble.

**Comment by simonwex** [comment]
Closing and tracking in implementation ticket.
