### ISSUE TITLE
Link locale choosing between Thimble and Bramble

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.webmaker.org#1351]
From @humphd's discussion in #1331, we need both Thimble and Bramble to be on the same page when it comes to locale.

> Brackets/Bramble picks the appropriate string catalog to load at runtime, and we probably need to somehow fold this into the Bramble.init() api instead of using the URL:

* https://github.com/humphd/brackets/blob/bramble/src/main.js#L67-L69
* https://github.com/humphd/brackets/blob/bramble/src/thirdparty/browser-appshell.js#L29-L30

**Comment by gideonthomas** [comment]
For now, I think we're gonna stick with the URL method of setting the locale (fixed in https://github.com/humphd/brackets/commit/80d78ca838d4423a3bd56b5d5fe39b60f017a536).
Later on for extensibility, we can implement it in the `Bramble.init` call.

Closing for now!
