### ISSUE TITLE
Update nunjucks

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1378]
Coz the current version is problematic on Linux

**Comment by Pomax** [comment]
wait. nunjucks is platform-related?

**Comment by gideonthomas** [comment]
@Pomax apparently when we ran the previous version of nunjucks, it seemed to hold file watches on the templates (which for some reason we couldn't turn off) and would crash the server (on linux only so far, haven't tested on windows) with an `ENOSPC` error.
cc @cadecairos
