### ISSUE TITLE
Allow tutorials to communicate with editor and preview panes

### ISSUE THREAD

**Issue by toolness** [mozilla/thimble.webmaker.org#278]
The tutorial functionality is really awesome, and could be made even more awesome if it could be given a message-passing communication channel with the editor and preview panes.

The editor pane could simply broadcast a `change` message every time the source code is changed, which the tutorial pane could listen for. Possible applications of this include tutorial panes that analyze the user's source code and provide specialized, domain-specific feedback on it.

The preview pane could simply be given an arbitrary communications channel with the tutorial pane. The creator of a tutorial could then add a script in the page the user edits which communicates with the tutorial pane in any way. This could be used to create e.g. interactive tutorials that automatically move forward whenever the user has completed a task.

**Comment by humphd** [comment]
Probably this should get absorbed into #487

**Comment by hannahkane** [comment]
Closing this now, since it's a requirement of #487.
