### ISSUE TITLE
Add an option to insta-embed Firebug Lite

### ISSUE THREAD

**Issue by toolness** [mozilla/thimble.webmaker.org#427]
So I was [helping a student](https://github.com/toolness/toolness-teaches-coding/commit/625456195b3b13d036dc465d02e62a368d467ff3#commitcomment-6503574) debug their webpage's JavaScript problems and thinking about how weird it is to use a browser's built-in developer tools to debug a Thimble page, since it's hard (especially for novices) to distinguish between e.g. errors/warning/network requests coming from Thimble versus the ones coming from their page. 

But then I realized that [Firebug Lite](https://getfirebug.com/firebuglite) exists!

If the following is added to the very top of a Thimble page, the result is pretty nice:

```html
<script src="https://getfirebug.com/firebug-lite.js#startOpened"></script>
<script>
window.onerror = function(msg, url, line) {
  console.error(msg, "at", url, "line", line);
};
</script>
```

So I'm thinking about writing a teaching kit on debugging JS, and I'm going to put this snippet in there, but then I realized it might actually be really nice to just include a checkbox in Thimble that automatically embeds the snippet for you. Think of it as "Thimble Developer Tools".

Anyways, just a thought.

**Comment by humphd** [comment]
This is *such* a good idea.  Doing this as a Brackets extension is pretty easy. @flukeout, you should consider this with other UX you're doing.  It would be neat to figure out how to enable this for people who want it.

**Comment by flukeout** [comment]
Yeah, this is pretty sweet. Will think on it!

**Comment by humphd** [comment]
I've done more experiments with this, and I think we shouldn't do it.  The reason that it's not ideal is that with the Brackets live dev preview, we instrument the DOM a bunch in order to have editor highlighting work, live CSS updates, and a bunch of other stuff.  Also, dev tools are readily available in browsers now, if you really want this.  I'm going to close.
