### ISSUE TITLE
Drag and drop should work from preview to editor

### ISSUE THREAD

**Issue by ToonTalk** [mozilla/thimble.webmaker.org#444]
I can drag and drop text within the editor. I can also drag text from other browser windows to the editor. But I can't drag text from the preview area to the editor.

My use case is a bit odd but it seems like it should work generally.

**Comment by humphd** [comment]
In the new Thimble code, this will interfere the file drag-and-drop from working, since the whole editor is a dropzone.  I'm going to close.
