### ISSUE TITLE
Suggestions to strings

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/thimble.webmaker.org#462]
reload > Reload

**Comment by scootergrisen** [comment]
New > ?
It just says new, maybe it should say "New project" or "New page" or whatever it is called.

**Comment by scootergrisen** [comment]
You can change the font to small, normal, large, but what is normal.
Mabybe is should be called standard or default or reset og something else then normal.

**Comment by scootergrisen** [comment]
The string "tool settings" don't seem to be translateable.

**Comment by scootergrisen** [comment]
There is a string starting with:
"<p>The css property"...

Maybe change it to:
"<p>The CSS property"...

**Comment by scootergrisen** [comment]
There are two strings with "You can make this error disappear by logging into webmaker" in them.
Maybe change the small "webmaker" til "Webmaker".

**Comment by scootergrisen** [comment]
"dismiss" should be "Dismiss" with big starting letter. Or maybe better "Close".

**Comment by humphd** [comment]
I'm going to close this, since the new Thimble UI is in flux right now.  After it ships (end of summer), if you want to audit again, that would be great.
