### ISSUE TITLE
Check marks in "tool settings" are not places right

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/thimble.webmaker.org#463]
They are placed right of the box they are suppose to be in.

**Comment by scootergrisen** [comment]
Would it not be better to use standard ```<input type="checkbox">``` and then style it with CSS ?

**Comment by Pomax** [comment]
Now: yes. When Thimble was first made, there was no way to style a checkbox =)

However, given the work that Seneca/CDOT is doing, these settings will likely be moot as they're working on a brackets version, rather than codemirror, of Thimble, which will make things much nicer

**Comment by flukeout** [comment]
Closing this issue, as we've removed those settings from the current version.
