### ISSUE TITLE
code padding covers part of normal text

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/thimble.webmaker.org#465]
Go to https://thimble.webmaker.org/ and change &lt;/title&gt; to &lt;/something&gt; and press the red icon to see the error message.

Then it says:
`The closing </something> tag here doesn't pair with the opening <title> tag here. This is likely due to a missing </title> tag.`

But the markup code is using some CSS padding that covers part og the unstyling text.

    code {
        padding: 2px 4px;
    }

So maybe remove the padding og change the line-height so there are room for the padding without covering the above lines.

**Comment by Pomax** [comment]
I'm not sure what you're describing, I see this:

![image](https://cloud.githubusercontent.com/assets/177243/6066371/7a5042b6-ad21-11e4-8f32-1b1fb7d12093.png)

and clicking the "here" links shows the indicator arrows pointing to the correct things.

**Comment by scootergrisen** [comment]
Yeah notice how the "g" in "closing" is just covered a little bit. Same with "p" in "opening".
On my computer its like 1-2 pixels more.

**Comment by humphd** [comment]
We're not using this UI anymore, closing.
