### ISSUE TITLE
Tutorial title, resize, show, more not showned

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/thimble.webmaker.org#466]
In tutorialbar.html there are some stuff you can push to hide and show the left pane with tutorial and resize it and there are suppose to be a title and stuff.

But all of this does not show in the browser, i can hover the cursor to find where i can click, but i cant see any icons.

**Comment by Pomax** [comment]
Thimble's being reworked atm by Seneca/CDOT to have an improved interface and behaviour, so this is a thing that we should reexamine once they are done with that work. Closing for now.
