### ISSUE TITLE
Double scrollbars on tutorial iframe

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/thimble.webmaker.org#468]
I see thimble have double scrollbar in the tutorial iframe.

It can be removed with one of these CSS codes, depending on if we want the iframe element to be inline or block.
```
vertical-align: bottom;
display: block;
```

**Comment by Pomax** [comment]
no they can't - the problematic scrollbar you're seeing is caused by the make-valet wrapper (https://github.com/mozilla/make-valet) and is affecting more than thimble, unfortunately =(
