### ISSUE TITLE
Thimble.wm.o's webmaker-nav bar is broken

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#476]
Navigating to thimble.wm.o produces this lovely sight, with no (new) console errors or 404s to give a clue about why:

![](http://i.imgur.com/9cMQWMP.png)

It looks like the webmaker nav bar isn't loading correctly.

**Comment by secretrobotron** [comment]
Looks normal on staging: https://thimble.mofostaging.net/

**Comment by ScottDowne** [comment]
Woah, I'll see what happens locally.

**Comment by secretrobotron** [comment]
@ScottDowne might just need another prod push. Weird.

**Comment by ScottDowne** [comment]
Fine locally, but I removed the webmaker-login-ux bower folder, and I see the same breakage.

So for some reason that component is failing or not existing on prod.

**Comment by secretrobotron** [comment]
Closing. Thanks for the fix, @ScottDowne .
