### ISSUE TITLE
Empty box covering Thimble editing window

### ISSUE THREAD

**Issue by jvallera** [mozilla/thimble.webmaker.org#477]
Hello, a teacher reached out to Hive NYC to inquire about an issue using Thimble. There is an empty box that is covering the editing window. She tried various browsers and was having the same issue. Is this something related to network connection? Please advise. Thanks!

![mystery box](https://cloud.githubusercontent.com/assets/3729312/6869586/b0fe2a0a-d46b-11e4-84df-d74c6d2f2414.png)

**Comment by jbuck** [comment]
@jvallera Can you ask when they had this problem occur? We noticed it most recently yesterday (March 26) and fixed the problem as a side-effect of the server running Thimble running out of free disk space.

**Comment by jvallera** [comment]
@jbuck it was early yesterday. So sounds like the problem got resolved. I will check with the teacher to see if the problem continues, but I have not heard anything so assuming everything is working well. Thanks!

**Comment by jbuck** [comment]
Thank *you* for filing

**Comment by Pomax** [comment]
thanks for reporting that, I'll close this bug in the mean time, but if it happens again feel free to leave another comment here, or file a new bug!
