### ISSUE TITLE
CSS user-select goes CSS_INVALID_PROPERTY_NAME_ERROR

### ISSUE THREAD

**Issue by pamelafox** [mozilla/thimble.webmaker.org#481]
Attempting to use this non-standard property results in the invalid property name error:
https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

I can see where to add it in the code (cssProperties), but not sure if that'd conflict with philosophy about which properties "exist". Thoughts?

**Comment by Pomax** [comment]
this would be an issue with https://github.com/mozilla/slowparse, adding "user-select" to the list of known CSS properties should be all that's required (although adding a test case so that it's provably accepted would be good too of course!)

**Comment by humphd** [comment]
moved to slowparse.
