### ISSUE TITLE
Triage existing bugs in Bugzilla

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#482]
We have [41 bugs in the Webmaker : Thimble component in Bugzilla](https://bugzilla.mozilla.org/buglist.cgi?product=Webmaker&bug_status=__open__&component=Thimble&order=changeddate%20DESC&list_id=12223561).  Our goal is to move issue tracking into github issues for Thimble, so we should go through those bugs and either re-file here, or close them.  My guess is that a lot of these aren't going to matter going forward, but a few might.

cc @hannahkane

**Comment by Pomax** [comment]
Good idea, want to peg a date/time for this? @simonwex @thisandagain is there a way for us to lock down the thimble.webmaker.org component on bugzilla to point people to here, instead, once we're done with triage?

**Comment by hannahkane** [comment]
Would love to attend a triage. Will be a good way for me to get more up-to-speed on Thimble. (I'll be PM'ing from the Moz side starting now.)

**Comment by humphd** [comment]
We've gotten half-way through this, and will follow-up again soon.

**Comment by hannahkane** [comment]
Down to 18 issues, most of which I think we can close. Would be good for someone with more knowledge than me to review, though. @gideonthomas ? @Pomax ?

**Comment by gideonthomas** [comment]
I think @Pomax is in a better position to decide which bugs need to be closed. It seems like most of them are old-thimble specific requests and should all be closed. But I defer to @Pomax.

**Comment by Pomax** [comment]
zarro boogs.

**Comment by gideonthomas** [comment]
Thanks @Pomax much appreciated!
