### ISSUE TITLE
URL for Thimble on teach.mozilla.org

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#483]
Given https://blog.webmaker.org/whats-next-for-webmaker-tools I'm wondering what the URL is going to be for Thimble?  Are we leaving it at https://thimble.webmaker.org or moving it?  If we're moving it, we should update this repo so its name makes sense.

cc @hannahkane, @davidascher, @jbuck

**Comment by humphd** [comment]
cc @simonwex

**Comment by hannahkane** [comment]
Based on conversation with @simonwex earlier today, it sounds like it will remain thimble.webmaker.org. We'll just point to it from Teach.mozilla.org.

**Comment by humphd** [comment]
Sounds good.
