### ISSUE TITLE
Improve Tutorial Feature

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#487]
Requirements include:
* Improve UX for embedding a tutorial (and update user docs)
* Allow tutorials to communicate with editor and preview panes (see #278) 
* Allow linking to a specific slide (see https://bugzilla.mozilla.org/show_bug.cgi?id=1054690)

**Comment by humphd** [comment]
I've morphed this bug to be about improving Tutorials in general.

**Comment by humphd** [comment]
One possible thing we could do is unfolding in https://github.com/humphd/brackets/issues/307.

**Comment by humphd** [comment]
We're in the process of discussing this right now, and should probably use this bug to co-ordinate.

**Comment by humphd** [comment]
cc @flukeout

**Comment by humphd** [comment]
Duping on #573
