### ISSUE TITLE
Thimble is incompatible with node 0.12 at the moment

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.webmaker.org#491]
There are a lot of dependencies that are pegged to versions that are incompatible with node 0.12, meaning that people on modern setups cannot run Thimble.

Part of the uplifting process here can be done by updating the dependencies in the package, but some of those will result in needing to change the actual app code due to changes in express 4 (although from testing, express 3.22.2 seems node 0.12 compatible at least and so uplifting express can be done as followup)

**Comment by Pomax** [comment]
uplifting less-middleware requires a change in app.js because the syntax has changed.

**Comment by humphd** [comment]
How critical is moving to 0.12?

**Comment by Pomax** [comment]
as critical as when when Node went from 0.6 to 0.8, or 0.8 to 0.10, really. The change to 0.12 introduces API upgrades that are incompatible with 0.10 without global shims (like native promises), and older versions will of course no longer receive security updates.

I'd say updating the code so that it works on 0.12 is pretty much a critical concern if you want code that can keep moving forward.
