### ISSUE TITLE
Explore solutions for offline options

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#492]
As mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1041445, we ought to have an offline solution for Thimble, whether that's encouraging downloads of the desktop Brackets app or designing a full solution.

**Comment by humphd** [comment]
One way to do this would be to isolate our changes in Bramble such that they are doable as an extension for desktop-Brackets.  CC'ing @gideonthomas for thoughts.  Maybe we should be more aggressive about splitting our in-browser needs from UI changes that could also work in the context of Brackets proper.

I suspect this isn't a P1 for the summer, but others can correct me.

**Comment by arky** [comment]
Update: I managed to create a custom raspbian based image that serves Thimble (old codebase) offline. 
Project notes here: 
https://hackaday.io/project/4778-webmaker-tools-on-raspberry-pi

Will upload the image for testing shortly.

**Comment by humphd** [comment]
We're going to close this for now, and let's re-file if we decide to do a pure-offline solution.
