### ISSUE TITLE
Determine gallery solution for teach.mozilla.org

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#493]
We need a solution for displaying Thimble makes on teach.mozilla.org.

**Comment by humphd** [comment]
One issue that has been raised in other bugs is that we have no way to display what a Thimble Make is all about (e.g., no screenshot).  There are various DOM screenshot APIs we could try to use here, or we could do something based on an image; regardless, we are missing the right solution at present.

**Comment by hannahkane** [comment]
@simonwex - can you clarify what, if any, challenges there are to recreating gallery functionality on Teach?

**Comment by hannahkane** [comment]
Would this ticket be inclusive of finding a solution for the "My Makes" page as well, or do we need a separate ticket for that?

**Comment by hannahkane** [comment]
Closing this, and replacing with a comparable ticket in the Teach repo. https://github.com/mozilla/teach.webmaker.org/issues/895
