### ISSUE TITLE
Create a thimble parity list for bramble

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#498]
Our brackets-combined-with-thimble needs work done before it can replace the current thimble completely. We need a list of what's outstanding.

**Comment by hannahkane** [comment]
So far, these are the only things I've found that haven't already been filed:
* Code hints 
* Error messages

**Comment by humphd** [comment]
For the Error Messages, we've temporarily turned that off while @gideonthomas fixes a bug in the slowparse code.  It's working, though.

For the Code hints stuff, we should figure out what we want there, and whether to a) port what we have now; b) get the WebPlatformDocs extension working; c) make something new.  How much do people use it?

**Comment by hannahkane** [comment]
That's a good question. It just struck me as a key part of reaching parity, but I don't actually have data on how often people use hints. 

I would say porting what we have now meets the definition of parity, but I don't understand the WebPlatformDocs extension option.

@humphd - do you have a sense that code hints are more problematic than they are useful?

**Comment by sedge** [comment]
@hannahkane `WebPlatformDocs` is a default brackets extension that was built with roughly the same purpose as the code hints in thimble. We decided to drop it since the download size was so large, and we held off on replacing the code hinting because we didn't know if/how it was worth reimplementing. 

You can review the (largely technical) discussion we had about the extension itself [here](https://github.com/humphd/brackets/issues/87).

**Comment by hannahkane** [comment]
I think everything here has actually been addressed via other tickets. (As per discussion earlier, we'll decide on a solution for code hints as part of a Beginner Mode ticket.)
