### ISSUE TITLE
[META] Develop editor modes for users of various experience levels

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#500]
User modes would improve tutorials and user experience by fine-tuning the coding environment. These modes are for CSS editing, HTML-only, advanced, basic and more. They will be enable or disable extensions and features depending on the mode selected.

**UPDATE** (to be done):
* [ ] [UX Design for user modes, switching UI and advanced features for advanced modes](https://github.com/mozilla/thimble.webmaker.org/issues/528) 
* [ ] [Implementation of user mode switching](https://github.com/mozilla/thimble.webmaker.org/issues/513)

**Comment by humphd** [comment]
As a zero-UI way to start experimenting with this would be to use what I'm suggesting in #503.

**Comment by humphd** [comment]
Down the road we could support doing things like:
* Default URL based modes, either using query string directly, or with subdomains (basic.thimble.org vs. advanced.thimble.org, which could both redirect to URLs that specify query string params for loading/disabling extensions)
* UI to switch the editor at runtime (i.e., reload it) with new query string params.  Could be a dropdown for different modes to switch to.

**Comment by JordanTheriault** [comment]
+1 for the dropdown which allows the user switch between modes.
Changing the dropdown can reload the editor iframe with the new editorurl.

**Comment by humphd** [comment]
Let's tackle this in the linked bugs, this isn't adding much.
