### ISSUE TITLE
Polish the selfie-taker feature for launch

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#502]
In order to launch this feature we need to make sure it works across the board. This includes:

* Testing across all supported browsers
* https://github.com/humphd/brackets/issues/257

**Comment by gideonthomas** [comment]
Tested across IE, Chrome, Firefox, Safari, Opera
IE and Safari do not support the webcam API so it shows no `Take a selfie` hint, which is what we expect.
Everything works fine in the other three browsers.

All that's left is humphd/brackets#257 pending upstream merge

**Comment by humphd** [comment]
This is all done now, closing.
