### ISSUE TITLE
Tech Debt: Fix Localization

### ISSUE THREAD

**Issue by JordanTheriault** [mozilla/thimble.webmaker.org#504]
Both thimble and brackets have localization, but it is not enabled and they do not communicate with each other.

If the language is changed within Thimble, it should also change the language within Brackets.

**Comment by humphd** [comment]
I sketched out a solution in https://github.com/humphd/brackets/issues/245

**Comment by sedge** [comment]
Fixed in https://github.com/mozilla/thimble.webmaker.org/pull/516
