### ISSUE TITLE
[META] Create an "opt-in" solution for a gradual launch of the new thimble

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#505]
A hard deadline wouldn't leave us much flexibility in delivering the new thimble. We propose an "opt-in" system where the old thimble is the default, and users can choose to use the brackets version of thimble until we deprecate old thimble entirely.

This could be accomplished in a few different ways:

1.  A single node application that serves two different versions of thimble depending on the user's preference
2. Two node applications, with redirects handled by the web head (nginx) on separate subdomains

Two considerations should be login integration and storing the user's preference.

cc: @jbuck @Pomax @humphd 

**UPDATE** (to be completed):
* [ ] https://github.com/mozilla/thimble.webmaker.org/issues/519 (UX for this)
* [x] #532  (deploy thimble-beta on prod)

**Comment by humphd** [comment]
+ @simonwex 

My personal vote is that we host two apps on production, and use subdomains to sort it out, maybe something like:
* https://thimble.webmaker.org (default, points to old thimble until we decide to switch)
* https://thimble-beta.webmaker.org (points to new thimble with Brackets).

We'd add UI in each of these apps (static link) that lets you load the other one as desired.  Once we've ironed out all the wrinkles, we'd switch it like so:
* https://thimble.webmaker.org (default, points to new thimble with Brackets)
* https://thimble-old.webmaker.org (points to old thimble until we decide to switch).

Subdomain names TBD.  Thoughts?

**Comment by simonwex** [comment]
:+1: for this approach while we gain confidence in bramble. I don't think we need to support the ability to load old-thimble once we're happy, though.

**Comment by JordanTheriault** [comment]
Here is the idea of informing/switching from thimble-classic. We give a dialog which can inform the user about the benefits of trying the new thimble.

* For the first time loading thimble-classic on page load, the dialog appears asking the user if they want to try the new version.
* If they decline, it saves this decision in a cookie so on page load the dialog does not appear.
* If they accept, it saves a cookie remembering this decision and redirects to bramble.

* At any point the user is able to click on the top left banner to change their decision and be redirected.

![switchdialog](https://cloud.githubusercontent.com/assets/5931078/7619292/a767cdcc-f985-11e4-8d3a-3834bdd16af4.gif)

**Comment by sedge** [comment]
@hannahkane How does the mockup above look?

**Comment by hannahkane** [comment]
Looks great. If they choose to go to thimble-beta, does the text on the ribbon change?

**Comment by JordanTheriault** [comment]
@hannahkane We can do a blue ribbon (so less attention is drawn to it) which will pull up a similar dialog informing them that features would be lost if they switch back and giving them the same choice.

**Comment by hannahkane** [comment]
Sounds good. :)

**Comment by sedge** [comment]
@jbuck @simonwex This issue is overdue from our last heartbeat, and we're blocked on the deployment of the thimble-beta subdomain. Where are we at with this? Is there anything I can do to speed up the process?

**Comment by sedge** [comment]
This has been supplanted by #532
