### ISSUE TITLE
Tech Debt: Cross-browser Issues

### ISSUE THREAD

**Issue by JordanTheriault** [mozilla/thimble.webmaker.org#506]
Issues present themselves when using Internet Explorer which need to be fixed for for parity.

See [brackets/issue233](https://github.com/humphd/brackets/issues/233).

**Comment by humphd** [comment]
See also:
* https://github.com/humphd/brackets/issues/232
* https://github.com/humphd/brackets/issues/220 (fixed, waiting on rebase with upstream)
* https://github.com/humphd/brackets/issues/199 (UI, not critical, but annoying)
* https://github.com/humphd/brackets/issues/94 (UI, not critical, but annoying)

**Comment by gideonthomas** [comment]
Fixed humphd/brackets#232 and humphd/brackets#220
UI fixes not critical and hence will be fixed in later commits
