### ISSUE TITLE
[meta] Fix issues in Brackets related to Heartbeat 1

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#507]
Tracking bug for all the work we have in Brackets (some of which is referenced in other bugs, some of which isn't).  This is the complete list: https://github.com/humphd/brackets/milestones/Heartbeat%201

**Comment by gideonthomas** [comment]
Fixed all issues in  https://github.com/humphd/brackets/milestones/Heartbeat%201
