### ISSUE TITLE
Unexpectedly logged out

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#510]
One way I've been able to reliably reproduce this is to:
* log in on bramble.mofostaging.net
* click on "My Makes" in the profile menu
* that opens up https://webmaker.mofostaging.net/en-US/me in a new tab where I am not logged in
* go back to bramble browser tab
* click "New" from action menu
* opens new bramble tab where I am not logged in

Also, after all of the above:
 * back to original bramble tab, where I still appear to be logged in (page has not refreshed yet)
 * click Save, and receive this error:
`<!DOCTYPE html> <html lang="en-US" dir="ltr"> <head> <meta charset="utf-8"> <!-- New Relic RUM disabled --> <title>Oops, you&#39;ve found a 403</title> <link rel="stylesheet" href="/stylesheets/error.css"> </head> <body> <div class="container"> <img src="/img/webmaker-loose-thread.png" alt="Webmaker logo"> <p>403: Error: Forbidden</p> <p>Please try a <a href='https://webmaker.org/en-US/search'>search</a> or visit our <a href='https://webmaker.org/en-US'>homepage</a>.</p> </div> </body> </html> `

**Comment by sedge** [comment]
Now that I've dug into the new `id.wm.o` system I can say that this problem should disappear as part switching login systems. I'm going to close for now.
