### ISSUE TITLE
Implement editor mode switching

### ISSUE THREAD

**Issue by JordanTheriault** [mozilla/thimble.webmaker.org#513]
We'll need a UI element that allows users to switch "modes" on the fly.

**Comment by humphd** [comment]
If you want to do this in the context of the current UI without adding anything new, we *could* add modes to the hamburger menu at the top, since it's basically unused atm:

![screen shot 2015-05-14 at 8 43 47 pm](https://cloud.githubusercontent.com/assets/427398/7644878/04efd468-fa7a-11e4-9023-d2e45e7bd5db.png)

**Comment by sedge** [comment]
Since this wasn't in our original sketch of this heartbeat, I'm going to move this into a new milestone called *overflow*. I imagine we could throw stuff in there that's next in line if we have spare cycles towards the end of a sprint.

**Comment by sedge** [comment]
Related to https://github.com/mozilla/thimble.webmaker.org/issues/500

**Comment by JordanTheriault** [comment]
The hamburger is a good idea, since it doesn't add a component but I don't like where it's positioned. The menu, at the moment, looks as if it's a part of the locale functionality. Perhaps if we move it closer to the Thimble logo it would be more clear it's the menu for Thimble, rather than language.

Alternatively, I think it may be important to users to know what version they are currently using since the hamburger would hide that. Im thinking that it may be useful to put a colon beside the Thimble logo, with the version name like "Thimble: Advanced" or "Thimble: HTML-only", and the version name is also a dropdown dialog to switch between "modes". While adding another component, it may be visible enough to not confuse users on why functionality may be missing.

**Comment by sedge** [comment]
+1

**Comment by hannahkane** [comment]
Agreed that the mode ought to be visible to users. This might be one of the first tasks we give to a UX designer, once we've assigned those resources.

**Comment by sedge** [comment]
This is blocked by https://github.com/mozilla/thimble.webmaker.org/issues/528

**Comment by sedge** [comment]
I'm going to morph this into implementing the UI and technical bits for this layer in thimble.

**Comment by flukeout** [comment]
@JordanTheriault - What do you mean by modes here? File view vs no file view? In that case, I think we're well on our way and this is good to close?

**Comment by humphd** [comment]
We haven't gone the route of having different modes, so I'm going to close this.  If we decide to add that, let's file new bugs.
