### ISSUE TITLE
Develop UX for opt-in switch from thimble to thimble-beta

### ISSUE THREAD

**Issue by JordanTheriault** [mozilla/thimble.webmaker.org#519]
Separate from #505, this issue is for UI which switches user between versions and is to be implemented on both the existing thimble as well as bramble.

**Comment by JordanTheriault** [comment]
Added a location indicator triangle which is coming out from the thimble to give the impression that Thimble is trying to speak with the user.

![screenshot 2015-05-20 13 47 26](https://cloud.githubusercontent.com/assets/5931078/7732552/d2b21e8a-fef6-11e4-8acf-15fa5ff594bf.png)

**Comment by JordanTheriault** [comment]
Working copy: 
> We're bringing Thimble to the next level and we think you'll love all the new features we're working on. For now, you can switch between the new thimble and the classic thimble you may already know. Switching is as easy clicking on the banner in the top left of the window. You can test drive the the next level of Thimble while it's still being developed, and even give the team feedback or suggest a feature on Github.

**Comment by JordanTheriault** [comment]
Current working UI for classic Thimble on [this](https://github.com/JordanTheriault/thimble.webmaker.org/tree/versionSwitchMockup) branch. Awaiting confirmation of new URL for bramble & copy revision.

**Comment by JordanTheriault** [comment]
![screenshot 2015-05-27 14 52 18](https://cloud.githubusercontent.com/assets/5931078/7844671/12662a88-0480-11e5-8e88-36b7ed28c4d8.png)
![screenshot 2015-05-27 14 48 50](https://cloud.githubusercontent.com/assets/5931078/7844672/126e853e-0480-11e5-8264-de73026423ae.png)

**Comment by JordanTheriault** [comment]
This addition is awaiting visual changes by @flukeout and can be re-visited once the top bar is complete.

**Comment by hannahkane** [comment]
This seems MVP to me, no?
@humphd @sedge - our plan requires this, right?

**Comment by humphd** [comment]
@flukeout, @hannahkane this is what we had before.  Feel free to close this, but fyi.

**Comment by flukeout** [comment]
Closing this as we're working on a simpler solution in #921
