### ISSUE TITLE
Multi-file publishing

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#522]
We need to decide on the workflow of this as far as implementation and UX is concerned.
This includes figuring out:
* The best strategy for keeping old-thimble's single-file projects distinct from new-thimble's multi-file projects with regards to publishing (database storage of makes, etc.)
* The remix workflow for providing a single `p` url for a multi-file project that an then be loaded into the editor
* How to show multiple makes to the user in the filesystem

The brackets bugs relevant to this are:
humphd/brackets#305
humphd/brackets#304
humphd/brackets#303

cc @sedge @humphd

**Comment by gideonthomas** [comment]
We might even consider using makedrive or some of the makedrive code to sync makes to an S3 bucket so that they persist

**Comment by sedge** [comment]
See: https://github.com/mozilla/thimble.webmaker.org/issues/486

**Comment by sedge** [comment]
This is a better place to track this I think. We can file the brackets bits there when we clearly identify them, and track them here

**Comment by sedge** [comment]
Bah! Duplicates. Let's use #486.
