### ISSUE TITLE
[META] Allow import/export of projects and files

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#523]
Lot of UX work to do here:
* How do we allow users to upload/download files to/from their thimble filesystem
 * Drag an drop files, zipped files
 * Have an upload/download button
* File types?
 * Zipped files?

cc @humphd

**Comment by gideonthomas** [comment]
Brackets issue: humphd/brackets#306

**Comment by humphd** [comment]
This has been done and landed for the drag-and-drop case.  You can drag any number of files into the editor, and it will save them to the browser-filesystem, and open them.  I'm going to tackle the .zip import/export case in another heartbeat.  Closing.
