### ISSUE TITLE
Design the refresh of the top bar

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#526]
We need a new treatment of the top bar of the editor, keeping in mind the following themes: 
* We need feature parity with the "old" Thimble
* It should feel visually consistent with the [Teach Site](teach.mozilla.org)
* Jumping into the editor from [the tools page](https://github.com/mozilla/teach.webmaker.org/issues/887)  should feel natural

Additional thoughts
* Can we reduce how much vertical space it takes up?

**Comment by sedge** [comment]
@flukeout We should consider a more radical departure from what thimble does now. Dave had a [good idea](https://github.com/humphd/brackets/issues/248) that might help clean up the UI if we implemented it correctly.

**Comment by flukeout** [comment]
@sedge Thanks for pointing that out! I think what @humphd posted is an interesting concept we could push on when exploring UX around multi-file, found in #527 

To me, *this& particular issue represents cleaning up and adjusting the current top bar to match the visual style of the Teach site, and to maintain parity in both features and general layout so that existing Thimble users who move over to the new experience still feel at home. What do you think? That is the impression I got from our call this morning.

**Comment by sedge** [comment]
That makes perfect sense to me. Sorry if I misunderstood the scope here! I suppose I was also suggesting that some of the thimble top bar features (undo/redo, size etc) would make more sense grouped with other editor features in that side bar.

I suspect I'm jumping ahead a bit though :P

**Comment by flukeout** [comment]
**WIP**

![image](https://cloud.githubusercontent.com/assets/25212/7864276/fda49c88-0515-11e5-88ef-f1f190fcc39d.png)

**Comment by cassiemc** [comment]
+1 on reducing height. Could make the logo more of a single line as opposed to stacked to help accomplish this. Would also like to see the green more as a highlight color.
* On first blush I don't think the Editor / Preview distinction is high enough in the hierarchy. As a beginner user, you first scan all the elements to understand how the screen is laid out. @hannahkane do you have any feedback about this from test users?
* Is 'auto-run javascript' necessary to show initially or could it be a more advanced option hidden in a menu?
* Love the mobile / desktop preview icons. Makes a lot of sense.
* Undo / Redo icons & placement don't feel resolved somehow.
* Overall wondering if we can clean up and simplify any more elements and direct the user a bit more with emphasis on certain elements. Right now the emphasized element is 'reload' (in the lower direction) and that doesnt' feel intentional.
* As per Hannah, we need a bit more UI to show how you create a new file, also how you save or publish.

Great first direction Luke!

**Comment by flukeout** [comment]
@cassiemc Agreed on all fronts! Some notes...
* Auto-run only turns on when you've added a ```script``` tag, so it won't always be there.
* Agreed on Reload being too prominent, I don't actually think we need it down the road

**Comment by sedge** [comment]
Re: editor/preview, I wonder if this will be solved when the content is visible. A default make should make it pretty clear that one piece is the code and the other is the rendered version no?

**Comment by flukeout** [comment]
@sedge That was my feeling too, pre-filled with content, the distinction should be a bit clearer. Even so, the labels get a bit lost right now.

**Comment by flukeout** [comment]
**An update**
* Lighter theme
* Moved some editor config & functions to a dropdown near the Editor
* Changed Save to Publish
* Turned **Reload** button into Refresh icon
* Single-line Thimble branding

![image](https://cloud.githubusercontent.com/assets/25212/7867056/73e15e06-0528-11e5-8740-b17d6ebf40e9.png)

Thoughts
* I wanted to move the "New File" stuff closer to the editor
* I don't think we need to show font size as top-level setting
  * Looks like users often set it to the largest size, so we should consider a larger default

**Comment by humphd** [comment]
This is really cool to watch evolve.  A few comments on what I see:
* One thing we could do with the Editor/Preview distinction is make them more clear via what surrounds them.  Right now we just do the preview in a full white rectangle.  What if we made it look like a web browser, similar to what the Mobile Preview mode does, by wrapping it in the mobile phone shell UI.  Consider the two views looking something like the following:
![screen shot 2015-05-28 at 2 10 42 pm](https://cloud.githubusercontent.com/assets/427398/7867341/79afeae4-0543-11e5-8f5c-d0264468e96e.png)
![screen shot 2015-05-28 at 2 11 17 pm](https://cloud.githubusercontent.com/assets/427398/7867345/816210be-0543-11e5-8398-350927bd01da.png)
* One thing I want to avoid somehow is the horizontal split between Edtior/Preview, and it not matching up with what's in the Bramble iframe.  When the file tree is open, the space gets split in 3 vs. 2, and it doesn't line up right now:
![screen shot 2015-05-28 at 2 14 35 pm](https://cloud.githubusercontent.com/assets/427398/7867403/e84fec74-0543-11e5-8a90-ec95cbb267fd.png)
It would be good if the top-bar didn't look misaligned when the inner contents get shifted around.
* Another thing to note is that Brackets itself is easily themed.  So we can change the colours of the editor (fonts, gutter, background, filetree, etc).  Something to consider for later, so it all feels integrated.
* I love the Desktop vs. Mobile phone icons, very cool.  Do you think we should add a Tablet mode, or is that just getting cluttered an complicated?
* In your menu, I'd ditch the "Show code hints" and "Hightlight markup on hover" items, they are basically useless going forward.  However, I know we'll want to put other things on there, so having a place to attach option UI options is important, especially if it doesn't clutter the view.
* We're going to want some way to load your old projects; so in addition to "Start..." we're going to need some way to see a list of *my* old projects, and maybe some way to indicate another person's, so I can remix?  Not sure about the details of this yet.
* Do we want to expose Mode Switching in a similar way to how Languages are shown now?  Or do we want to hide this, and have it be something you opt-into via URL (e.g., some projects open in beginner mode, some in JavaScript mode, ...)?

**Comment by humphd** [comment]
Another thought on the Editor vs. Preview distinction...should we move to a "dark" theme in the editor, to call it out from what the browser preview renders? Recently code editors have been moving toward darker themes, (do a search for [code editor images](https://www.google.ca/search?q=code+editor&source=lnms&tbm=isch&sa=X&ei=pV1nVbWAIYKfyAT-noGYAQ&ved=0CAcQ_AUoAQ) for example).  @hannahkane, I wonder how Thimble users would respond to this?  Would it empower them, so they feel like they are doing what they see other programmers doing?  Would it isolate them, and make the tool feel too complicated and impenetrable?

**Comment by flukeout** [comment]
In response to @humphd's comments:
* I agree about trying out a dark editor, I was going to try that next - would help in keeping with current trends and expectations and reinforce edit & preview difference 
  * We could drop a light & dark theme toggle in the options dropdown for people who hate it
* Neat idea about wrapping the preview content in a mini browser, will try something with that (feels a bit inception-y)
* Was thinking that we'd still keep the list of *your* projects in the Username dropdown for now
* About *modes* - I'll begin exploring that in #527 - so far I'm just focused on parity and Teach branding
  * I expect that the columns are resizable, and the column headers will stay in sync

**Comment by flukeout** [comment]
@humphd Do you have any initial gut-level reactions on the amount of color in the UI? The first set of comps has three options with a decreasing amount of color - do you have a favorite?

**Comment by humphd** [comment]
RE themes, take a look at http://brackets-themes.github.io/ for some pre-made ones (there are hundreds), and it's easy to make new custom ones ourselves (it's just a LESS override file, basically).

In terms of colour in the UI, I feel like it's hard to discuss it separate from the colour that will bleed into things when you have content in the editor and preview.  Your experience can be very different depending on what you're coding and rendering.  That said, I think the darker green ones make it easier to see the top stuff vs. the white, when much of a basic web page in the preview will also be white, and it will look like it's part of the preview part.

**Comment by cassiemc** [comment]
Let's get some content in and try it out.

**Comment by JordanTheriault** [comment]
To redesign:
* Rather than having the hamburger menu contain the "show code hints" and others, which are in fact extensions, it could be among a left-hand menu (as Humph suggested, similar to https://code.visualstudio.com/) with the filesystem. Since changing these, along with the filesystem, is a more advanced feature.

To Humph's points:
* I think showing the browser preview is interesting, but should be a toggle feature rather than an default as it clutters the view (especially on smaller screens) and doesn't really provide a true representation of how it will look in a browser.
* Dark theming is popular, and good. But to keep in step with Mozilla's themes, again, it should be a feature rather than a default.

**Comment by flukeout** [comment]
Very rough stab at throwing in some existing thimble-made content, with a random dark theme that had some related colors. I'll tweak them to match the Teach palette.

The proximity of the preview to the content is a bit jarring, I'll explore ways to make a stronger separation.

![image](https://cloud.githubusercontent.com/assets/25212/7868232/6bfb73c8-052f-11e5-90d9-5350f1d904f8.png)

**Comment by humphd** [comment]
That last mockup really makes me feel like you need the top bar to have some different visual presence vs. the editor/preview.  The dark theme in the editor has achieved it; but the preview still has lots of white, which makes it feel connected, and it really should.

I agree about the need for space around the preview content.  The phone vs. browser UI wrapping it might provide that opportunity, too.

**Comment by sedge** [comment]
@flukeout As a heads up, we do want **Save** vs **Publish**. See https://github.com/mozilla/thimble.webmaker.org/issues/535

**Comment by flukeout** [comment]
**Continued Progress on Dark-Mode**
* These are feeling pretty cluttered, although they do have a slightly better separation of the parts.

![image](https://cloud.githubusercontent.com/assets/25212/7869443/a37da458-0537-11e5-83e6-6be815112a84.png)

**Comment by sedge** [comment]
For what it's worth, I ***love*** the heavy green with the dark editor and light preview.

**Comment by JordanTheriault** [comment]
Heavy green + dark editor is **awesome**. If we toggle between, it would be great to jump between the previous one with the largely white/green accents to this black/gray and mostly green.

**Comment by flukeout** [comment]
I think I like it the most too. I'll put some more work into it.

**Comment by JordanTheriault** [comment]
Although this is a top bar redesign, it it worth it to play with the idea of the pull-out tray file editor in this mockup since it will effect the aesthetics of this design?

**Comment by flukeout** [comment]
@JordanTheriault Yeah, soon! I'd like to spend a bit more time on these mockups and then explore the file dialog within the one(s) we most feel like pursuing.

**Comment by flukeout** [comment]
**Update**
* Added link back to Mozilla Teach
* Lighter links in the green bar
* Code Editor and Preview titles in ALL CAPS & ligher for contrast

![image](https://cloud.githubusercontent.com/assets/25212/7870275/14d29ea6-053d-11e5-8901-c78420b736f5.png)

**Comment by flukeout** [comment]
**UX Up Next**
* Can we ditch the hamburgler menu?
  * Move **Text Size** to top editor bar
  * Convert **Hamburger** to **New File** (which prompt if losing work)
  * Code hints & markup highlight are always one

**Comment by flukeout** [comment]
**Yet another Update**
Includes...
* Collapsable header & collapsed view
* Font Size controls are top-level again
* Hamburger menu converted to "new file" (will show dialog if it will cause to lose work)
* New undo & redo icons
* Ditched "Redo" label, as it is implied

![image](https://cloud.githubusercontent.com/assets/25212/7871912/15844470-0548-11e5-9795-2781b5fd0dc6.png)

**Comment by hannahkane** [comment]
Sorry I'm so late to the party. This is looking so, so great.
 * **Streamlined header** = awesome. (Minor note: If "Tools" becomes a top-level item on teach.mozilla.org, it will get its own color, and this should probably match. I suppose we can just decide now to make it green.)
 * I don't think it's clear that **"Mozilla Teach"** is a link to a different site. It's partly because "Mozilla Teach" sounds so meaningless, and partly because we don't have a logo. Would it be underlined on hover? Maybe that would make it clear. 
 * I prefer **"Publish" to "Share,"** which I think has social network connotations. I'd want to user test a flow where Publish is part of the Save dialog.
 * Like the **collapsible header.** Would also want to user test it.
 * My instinct is that the **dark editor** might be intimidating or unfamiliar to beginners, but I love the idea of making that a preference for users.
 * Is the **New File icon** meant to open a new file in the existing project, or a new project? It's sort of ambiguous.
 * Current Thimble has top level access to **Help documentation**. Did we ditch that on purpose?
 * Should we plan to do some **usability tests** with users soon, based on these mockups? @flukeout - maybe we can work on that together? 
 * **Bolding** for scanability - I'm also a fan

**Comment by cassiemc** [comment]
Yeah this is looking great! :+1:  to user testing, and **bolding** for scanability :smile_cat: 
Since this is going so quickly I think it's definitely worth it to imagine what the best first experience would be as well (default content, etc)

**Comment by xmatthewx** [comment]
This is looking great. 

 - The labels on editor and preview might be more visual clutter than helpful information
 - I think a visible share button adds a nice carrot. Publish sounds heavy and serious. 
 - A `New` button could be nice
 - Can you reduce the branding? Is the thimble icon helpful? Does login need a logo?
 - Can language be a setting on the user's account? Or can we guess it based on locale?
 - Is the Exit button truly useful? Or do we just think we need it. 

Maybe something useful in here: https://www.dropbox.com/sh/r7iagvy76u9tnia/AABBCkKWK6mVwqGPDd1c7lpEa?dl=0

**Comment by flukeout** [comment]
Because @humphd is jonesing, here's work in progress on the top bar + language picker.

In addition...
* Moved "Teach" closer to the Thimble branding
* Added help icon
* Added "New" to the new project button


![image](https://cloud.githubusercontent.com/assets/25212/7893055/b77ab7c0-060e-11e5-9494-4673133c90a4.png)

**Comment by hannahkane** [comment]
I am digging this.

Though this makes it longer, I'm realizing it should read "Thimble by the Mozilla Learning Network" as per recently agreed upon terminology on the Teach team.

**Comment by flukeout** [comment]
@hannahkane hmm - that seems reaaaaally long for the top bar branding area. Is there a shortened version MLN (like MDN) that we can use?

**Comment by flukeout** [comment]
Redpen link https://redpen.io/p/rj5cd35ca107d032dd

**Comment by hannahkane** [comment]
Good suggestion, @flukeout. I'll ask Claw if MLN is kosher.

**Comment by flukeout** [comment]
I've updated the redpen https://redpen.io/wx209df4403fafca16

cc @sedge @humphd @hannahkane @JordanTheriault

**Comment by flukeout** [comment]
@humphd Are we good to close this issue now? We can break out remaining work into other tickets.
