### ISSUE TITLE
UX for turning on Advanced Features

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#528]
It seems the team has ideas about a set of advanced features that could be turned on by expert users via something like a plugin or extension system. Let's use this ticket to explore what these features are and talk about how to expose them.

This work can fall into two main themes:
* Which features can we bake in to the browser
* What is a generic and easy way to add additional features (via extensions or add-ons)

@humphd Can you shed some more light on these features? Are they...
* Things we're planning to custom-build
* Stock Brackets features we've hidden from the UI
* Things in the [Brackets Extension Registry](https://brackets-registry.aboutweb.com/)

**Comment by sedge** [comment]
First on the list here should be multi-file projects IMO, and the UX around that. Under the hood the editor will always live in a multi-file environment, but we can conceal this by default and enable it with an extension.

**Comment by JordanTheriault** [comment]
We currently have a list of extensions that will work in Bramble, it's listed [here](https://github.com/humphd/brackets#optional-extension-loading). Which of these will be turned on/off will be part of determining these user modes. 

I think it may be valuable to be able to switch them on and off individually (checkbox style).

We are also able to hide/show aspects of the UI depending on the mode. Perhaps it's valuable to modify the app so it's easy to hide/show components.

**Comment by humphd** [comment]
This hasn't really sparked much interest.  I'm going to close and we can file new bugs if we decide to do it later.
