### ISSUE TITLE
Inconsistent auto-run JavaScript behavior

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#529]
In playing around with the auto-run JavaScript feature, I've noticed some inconsistencies:

**When auto-run is enabled...**
* Every keystroke inside of a ```script``` tag runs the JS
* Every "enter" press anywhere in the editor re-runs the JS
* Typing a tag and having Thimble autocomplete it runs the JS
* Typing stuff into anything but the ```script``` tag doesn't run the JS
* When I add an alert, JS runs when I finish typing ``` alert("hi")``` and then again when I add the semicolon to end the line ```alert("hi");```

Some of these behaviors don't seem useful and seem to be inconsistent.

**When auto-run is disabled...**
* There doesn't seem to be a way to run the JS at all
* Pressing the **Reload** button doesn't run the JS

It feels to me like JS should run after a **Reload** action even if it's not set to auto-run. Running JS when you reload a page seems like expected behavior, and toggling auto-run should affect how the JS is handled during the act of editing.

Curious to get the teams reaction to these experiences. I'll take some time to benchmark other auto-run editors and see how those feel.

**Comment by sedge** [comment]
I agree about the Reload running the javascript, unless we change "auto-run" to "enable javascript".

Some of the bizarreness you're encountering (`alert()` then `alert();` for example) is a consequence of how the editor parses and updates the code for live preview. I'm not sure this will be easy to change, though @gideonthomas or @humphd might know more.

An easier solution might be to completely disable automatic javascript running, and force it to run on reload. This seems a little restrictive though...

**Comment by flukeout** [comment]
Yeah, maybe we could just pick move obvious trigger points for the auto-updating. I can't think of any scenario where you'd really want to run some JS until you've at least finished typing your line of code.

So, within a ```script``` tag, we could at least wait for an enter press or a semicolon.

**Comment by flukeout** [comment]
Some rough thoughts and work here. Some questions I'd like to answer are...
* When do we try to auto-run code?
* How and when do we notify the user of errors?
* How do we handle infinite loops?
* How do we allow the user to re-run javascript on the page

![auto-run-javascript](https://cloud.githubusercontent.com/assets/25212/7872889/9b797ff2-0550-11e5-94c0-95ec8c7caf84.png)
