### ISSUE TITLE
Hitting "Reload" should run the JavaScript in a project, even if "auto-run JavaScript" is not enabled.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#530]
Auto-run is a behaviour that relates to what happens with JS as you edit your project, not wether JS runs when your project is reloaded, which is what it affects now.

**Comment by humphd** [comment]
We don't have this UI anymore, so I'm going to close this.  We do have backend support for enabling/disabling scripts in a page, but we don't currently have UX for using it.
