### ISSUE TITLE
[META] Create a project managment layer in thimble using makedrive 

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#531]
See previous discussion in https://github.com/humphd/brackets/issues/317 for context.

The key points are:
* Thimble will have an instance of `makedrive-client` on top of `filer` which we'll use to store local work in Indexdb. It also has to manage which project a user is opening. The filesystem will do the initial download of projects as they are opened through makedrive
* This layer has to connect the UX around projects (new, open, remix) to what gets put into the local filesystem, and to what gets loaded into brackets. It should lean on makedrive to persist project changes back to the server

Dependant issues:
* [ ] #527

**Comment by humphd** [comment]
We're not going this route, closing.
