### ISSUE TITLE
Give thimble tablet compatibility

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#533]
It would be a huge win if thimble had tablet compatibility. We need to talk about what this actually looks like.

I can think of:
*  Mobile responsiveness
*  Feature compatibility 

If we want a feature complete version of thimble on tablet then this provides a pretty compelling argument for unit testing thimble's front-end. Is that something worth considering? A combination of [Mocha](http://mochajs.org/) and [browserify](http://browserify.org/) for test logic and [Karma](http://karma-runner.github.io/0.12/intro/how-it-works.html) for reporting could be pretty potent.

**Comment by humphd** [comment]
We aren't ever going to work perfectly on tablets.
