### ISSUE TITLE
Build UX flow for simple and fancy version of saving, syncing & publishing.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#539]
Since we're in the midsts of discussions around this flow and it has technical implications, I'll create a few options for what a saving & publishing process might look like. Sounds like we're leaning towards a few of options at this point..

**Saving**
* **Explicit** - Project is only Saved when a user explicitly wants it to
stuff through a refresh? 
* **Live** - Project is auto-saved whenever there are changes

**Publishing**
* **Snapshot Publish** - At any point during editing, you can publish your project to a URL, which stays unaffected by subsequent editing to your project. If you want to publish changes to your work, you can do so by publishing again, which will create a new URL and instance.
* **Live Publish** - Once published, the public URL for a project shows the latest and live version of your project, like a Google doc. This makes it possible to have a published but broken project.
* **Updatable Publish** - Once published, the content is unaffected by subsequent edits until the user explicitly wants it to be.

These options mostly concern themselves with how **Publishing** works, but we also have to consider saving. Do we auto-save to the :cloud: as someone is working, or is saving an explicit action. This will probably change depending on the publish mode.

**Comment by humphd** [comment]
Added to this, or at least explicitly calling it out: do we want to send everything every time you save/publish to the cloud, or do we want to try do incremental diffs?  Said another way, do we care about bandwidth, and the time it takes to push stuff to the web from your browser?

Also, do we want that action to be manual (user initiated action to publish or save to the web), or automatic (we figure out when things are dirty, update the server for you).

**Comment by flukeout** [comment]
**Some benchmarking**
* **CodePen** - Explicit saving & Live Publish
* **JSBin** - Auto-save & Live Publish
* **JS Fiddle** - Explicit Save & Snapshot Publish

**Comment by sedge** [comment]
I like it! If we grey out `Publish` after the initial publish and reenable it when changes are made then we might not need `Update Published`.

**Comment by flukeout** [comment]
@sedge Indeed! The **Update Published** label I used is a bit lame, I just wanted to be really explicit about what was happening to get the point across.

I'm a bit wary of the UX implications of greying out Publish. Especially in cases where you return to an old project but haven't made changes yet. If on Wednesday we feel like this approach is a good one, we can fine-tune the UX.

I think there should also be a way to get the URL to the already-published version without having to **Update Published**, so it still need a bit of work.

**Comment by humphd** [comment]
I like this.  I think removing the `Publish` button, and changing it when necessary to `Update Published` is really good.  I also like the `Saving...` notification.

On the backend side of this, it would mean something like this:
* When we autosave, we keep track of what got changed in the fs (list of files to be published).  The first time this will be everything in your fs
* When the user clicks publish, we go through that list, and push each file up to the server (POST REST API), and clear the list of dirty files
* When the user changes something after a publish, we again start a list of dirty files, and wait for `Update Published`, wherein we send only those files that have changed.  We don't worry about DIFFs just send the entire file again, but not files that haven't got changes.

This would let us avoid MakeDrive.  @flukeout one more thing I think you need is a `Publishing...` notification or progress bar or something, since uploading a project will not be instant.  I think that needs some UI in your example above for discussion.

**Comment by humphd** [comment]
cc @simonwex, @jbuck

**Comment by hannahkane** [comment]
Agree with all of the assumptions, and I like this approach. 

Confused about one thing—has the user clicked "Publish" in the time between the fourth and fifth screenshot above?

(Outside the scope of this, but wondering if it will be possible to allow the user to revert to earlier published versions?)

**Comment by humphd** [comment]
There's another case to consider.  If a User does work, saves, but never hits 'Publish', when they come back to the app, their filesystem will have data in it that could be published.  I suppose the dirty-file-list could actually be stored in a file in the filesystem vs. memory, so that on app restart we can pick up where we were.

**Comment by flukeout** [comment]
@humphd Will update with "Publishing..." progresss.

@hannahkane No, 4th goes directly into 5th when Saving has finished. I should grey out the Publish button in the 4th step. I'll update.

**Comment by hannahkane** [comment]
@flukeout - at what point does the user click "PUBLISH"?

**Comment by flukeout** [comment]
@hannahkane Updating the diagram to include hitting Publish

**Comment by gideonthomas** [comment]
This looks simple and awesome!
Question for discussion though: For the first screen, we will probably have default content in there. Would it make sense to enable the "Publish" button in that case? Or do you need to make changes (however minimal) to see the "Publish" button?

**Comment by flukeout** [comment]
@gideonthomas Good catch! I left it off because in the mockup there wasn't any content so it wouldn't have made sense, but I think you're right - we should show it right away since our starting point will already be a "valid" project. I'll update the comps.

**Comment by flukeout** [comment]
Updated the diagram to address all of the comments and feedback so far...

![auto-save-and-updatable-publish-2](https://cloud.githubusercontent.com/assets/25212/7921295/639e9e08-0859-11e5-8f2c-27bdba51bb6f.png)

**Comment by hannahkane** [comment]
<3

**Comment by jbuck** [comment]
@humphd one detail I wanted to clarify: when the auto-saving happens, that's happening in the local filesystem in the browser right?

**Comment by humphd** [comment]
@jbuck yes, "save" is always a browser-filesystem operation, disconnected from the server.

**Comment by flukeout** [comment]
@jbuck @humphd I've updated the diagram with some annotations to clear up confusion. 

As we discussed...
* All **auto-save** operations are saved locally and remotely
* Publishing creates a publicly viewable copy of a project
* The Published version of a project is not affected by edits to the project until the author explicitly updates the published project, as pictured in the last step of the diagram.

Hopefully this clears things up, let me know if you have questions or if anything needs more clarity.

![auto-save-and-updatable-publish-3](https://cloud.githubusercontent.com/assets/25212/7946162/fdfb0506-0929-11e5-9c00-e3fed84d3fcc.png)

**Comment by flukeout** [comment]
We need to revisit this a little bit. The UX above is missing a couple of important features:
* Knowing if something has already been published
* Being able to share / obtain a link to the already-published without hitting *Update Published*

I've added some ideas to https://redpen.io/vo385a52d0ca40aa9f which I've also included here:

![new-project-ui](https://cloud.githubusercontent.com/assets/25212/7977384/2b9c2920-0a3f-11e5-90d0-ed385a624929.png)

@humphd Let's revisit first thing tomorrow, we've very close.

**Comment by simonwex** [comment]
This is great work. It's so nice to see progress on UI we've left unchanged for so long.

**Comment by flukeout** [comment]
@humphd I think we have a good handle on this, good to close? Do we have an implementation ticket?

**Comment by humphd** [comment]
@JordanTheriault, can you add your implementation ticket here, and let's close.

**Comment by flukeout** [comment]
@cassiemc @humphd I've updated the redpen to include the missing features we discussed today.

**I added**
* Tags
* Description
* Ability to "Unpublish"

Let's discuss this flow, as it adds an additional step to the publish process.

**Comment by hannahkane** [comment]
Looks great, @flukeout. I added a couple comments to the redpen. 

Leaning towards code snippet as thumbnail, at least for the personal view, though I'm not sure about the public view.

Agree that choosing a language for the project might be too granular.

**Comment by hannahkane** [comment]
Blocked on #566

**Comment by flukeout** [comment]
I'm going to close this - we're not referencing it anymore and have made a ton of progress on publishing!
