### ISSUE TITLE
Localize theme switching in thimble

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#542]
As part of humphd/brackets#334 we're adding a button to switch themes. This is really likely to be `wontfix` since so much of the UI will change, but in case this work sticks around the strings will need to be localized.

I'll update this issue when humphd/brackets#334 lands.

**Comment by gideonthomas** [comment]
See https://github.com/mozilla/thimble.webmaker.org/issues/475 for localization issues
