### ISSUE TITLE
[META] Re-implement thimble

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#544]
In the process of adding in brackets, we've hacked thimble's front-end to pieces and rather than auditing it, I suggest we throw it out and rebuild it during our design refresh. Meanwhile, the back-end is several generations of convention behind modern nodejs applications, and lacks test coverage.

Part of the work involved in the bramble switch involves cutting down the size of the application, and refining the load process. I think the easiest way to enable this is to restart from scratch.

**Front-end suggestions**
* [Reactjs](https://facebook.github.io/react/), possibly using [flux](https://facebook.github.io/flux/) ([reflux](https://github.com/spoike/refluxjs)?) application architecture if we need the extra scaffolding
* Browserified application logic
* Mocha + [Karma](http://karma-runner.github.io/0.12/intro/how-it-works.html) testing

*Why react?*
* Reactjs is already used by other MoFo products, which means there's a shared base of experience across our dev resources
* At least two of the CDOT team have experience with reactjs, and I have direct experience architecting a moderately complex front-end application with flux
* We could springboard into dev using my work as a basis for the workflow and build tools
* An MVP implementation would be quick to build using this technology
* Well implemented flux applications are readily testable

**Back-end suggestions**
* [HAPI](http://hapijs.com/)-based server architecture
* Mocha test coverage

*Why HAPI?*
* Clean, testable and quick to implement
* Again, two other MoFo applications use this technology ([id.wm.o](https://github.com/mozilla/id.webmaker.org/blob/develop/web/server.js) and [api.wm.o](https://github.com/mozilla/api.webmaker.org/blob/develop/server.js)) giving us more to work with as an experience base

This would be a really big shift, and take a fair amount of work. I really do think it's worth it though! I'd love some feedback on this idea.

cc: @humphd @simonwex @jbuck @cadecairos @Pomax

**Comment by jbuck** [comment]
If you want to do it, go for it. If you're testing hapi code, I'd recommend using [lab](https://github.com/hapijs/lab).

**Comment by humphd** [comment]
In terms of front end, remember that every byte matters in terms of size.  The "Thimble" part of this isn't where we want to innovate a lot, and it especially isn't where I want to see us spending download time.  We can't do much more to Brackets to make it smaller, but we can (and should!) make sure we don't make Thimble larger than it needs to be.  Ideally it's as close to a static, responsive web page as possible, with as little in the way of JS Frameworks as possible--we already load React once inside Brackets, and it's really not small!

I'd also caution that we aren't looking to innovate on the server side.  We're trying to bootstrap our work into Thimble.  If we need to rewrite or replace things, that's cool.  But I don't want to see us spending months solving the wrong problem.  It's always fun to throw everything away and start over.  It also gets you back to the exact same place you started, and with very little to show, especially for users who don't care what your code looks like.

**Comment by sedge** [comment]
@humphd +1

After mulling over this I think I've come to the same conclusion, particularly in regards to the front-end. This issue is probably a reaction I'm having to how difficult it's becoming to maintain either side of this application. 

It would probably make more sense to morph this into a few issues that require less of a time investment for most of the benefit:
 
*  auditing the front-end code to cut it down
*  writing front-end feature compatibility tests
*  refactoring the back-end to make it more modular

This is more reasonable I think, and more in line with our current roadmap.
