### ISSUE TITLE
UX for listing My Projects

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#549]
**MVP** - I want to..
* See a list of my projects, and from that list..
  * See a preview of the project
  * See the name of the project
  * Delete a project
  * Open a project for editing

**Enhanced** - In addition, I may want to...
* Determine if a project is published, and if it is...
  * Share the published URL
  * Open the published version
* Search for projects
* Sort my list of projects
  * Date created
  * Date modified
  * Alphabetically
* Remix a project

**Comment by flukeout** [comment]
Very rough first pass at a couple of options for viewing a list of **My Projects**
https://dl.dropboxusercontent.com/u/109902/bramble/project-explorer.pdf

**Comment by jgmac1106** [comment]
As a teacher I would also like to search the gallery by clear technical objectives

- formatting text with css
- add an image

This would require those designing makes for remix to somehow list these objectives but it would be a useful feature when trying to create a scaffolded curriculum.

**Comment by flukeout** [comment]
@jgmac1106 Thanks for the feedback! Will keep those in mind.

**Comment by flukeout** [comment]
Here's an update for the **My Projects** view:

![project-explorer-2](https://cloud.githubusercontent.com/assets/25212/8047485/e0ca763a-0dfa-11e5-8ded-cd492148607d.png)

I think if we want to keep things simple, we can limit the functionality on this view to...
* Open Project
* Delete Project

**Comment by humphd** [comment]
@flukeout, what if, instead of being a pop-up ligthtbox, this project view overtook the area that will be occupied by the editor+preview?  We can then load that in the background.  Or is this something you get to while you're in the editor?

**Comment by humphd** [comment]
Another thing regarding the project's preview: often there is little or nothing of value to show, unless you've made something that uses a lot of images.  Another thing we could do is use some kind of graphic that indicated the makeup of the item:
* html only
* html + css
* html + javascript
* html + css + javascript
* markdown
* ...
And each one of these could have some kind of compose-able icon, such that they snapped together to make a pattern.  Then you could look at a project and know if it was the type of thing you cared about.

**Comment by flukeout** [comment]
Another option for the Project Detail

![image](https://cloud.githubusercontent.com/assets/25212/8069887/5a9e0bb8-0eb2-11e5-8854-b505d6503356.png)

**Comment by hannahkane** [comment]
Nice work, @flukeout. I think the list view with the code excerpts could be really useful. Would love to get feedback from @jgmac1106 on this one.

**Comment by humphd** [comment]
cc @gideonthomas, see above with the idea of "Latest line of code edited is highlighted," which is going to present some challenges for the publishing backend (i.e., we'd need more metadata for each project or file), as well as Brackets saving logic, which would somehow need to record this data in the filesystem.

**Comment by gideonthomas** [comment]
This (the last line edited part) is definitely not possible for MVP. It can be quite complicated to implement. But things to consider re: this are:
* How to get the "line last edited" + context (2+ lines of code above and below). CodeMirror does provide a way to get this information, but we need to do some research.
* What is our strategy for generating the above snapshot? Is it even a snapshot? 
 * We **could** get the lines of code and persist it as project metadata (along with the line# and other info that brackets might need to move the cursor to that line). Then we might create a codemirror instance (with static styling) and populate the editor with those lines of code and highlight the middle line. All this will be done on the client side when we "request the project list" and will be done for each project, i.e. one codemirror instance per project.
* Another potential problem would be how to determine what the last edited line was. It gets complicated  because of how we autosave. It might not be a big issue if we decide that the "last line of code edited" is based on the last save that was performed but that is a UX consideration.

**Comment by flukeout** [comment]
I think the basing the last line edited on the latest auto-save seems like a pretty safe bet. Let's discuss this in stand tomorrow - I'd like to figure out if we need an interim solution that doesn't require as much development time.

**Comment by flukeout** [comment]
Here's a simplified version

![image](https://cloud.githubusercontent.com/assets/25212/8165973/8d860828-1349-11e5-9ada-9004d7fd3c7c.png)

**Comment by hannahkane** [comment]
So this version doesn't have a preview at all? Maybe a "last modified" date would be useful if that's the case. 

Are you imagining this is in reverse order by last modified date? Can the user sort or search?

**Comment by flukeout** [comment]
@hannahkane This is a bare-bones proposal that doesn't rely on a thumbnail preview or last-edited-code preview, since those are unknowns right now in terms of a dev effort.

This version puts the most recently edited project at the top and doesn't allow any sorting or searching. Lets put whatever features we want in this into the MVP feature list - #563

I'll update it with the last-modified timestamp

**Comment by hannahkane** [comment]
Got it. I think adding a timestamp is probably good for MVP. 

@adamlofting - can we get a breakdown of the # of projects per user? e.g. a count of how many users have 1 project, how many have 2, etc. I want to know how much of an edge case it is to have so many projects that sorting or searching would be necessary.

**Comment by flukeout** [comment]
@hannahkane Updated the comp.

@gideonthomas - are you in charge of the dev work for the project list?

**Comment by gideonthomas** [comment]
@flukeout Yeah I'm doing the dev stuff for that but @JordanTheriault is implementing the design I believe
