### ISSUE TITLE
Syntax error prevent preview pane to reload

### ISSUE THREAD

**Issue by alicoding** [mozilla/thimble.webmaker.org#550]
STR:

1. open thimble.webmaker.org

2. paste in this code

```
<!doctype html>
<html>
  <head>
  	<meta charset="utf-8">
    <title>Hello there</title>
  </head>
  <body>
    <p>Let's fix this bug</p>
    <ul>
      <li>This is fine</li>
      <li>This is not going to be cool</li>
    <ul>
    <p>can you see me</p>
  </body>
</html>
```

**Comment by alicoding** [comment]
cc @humphd

**Comment by humphd** [comment]
The DOM is broken for this page (unclosed ul), so it make sense.  What are you expecting it to do?

**Comment by alicoding** [comment]
@humphd I think I just don't know if it was intended since running the above code natively will still render it, but I guess this is a bit different here...
