### ISSUE TITLE
Consider adding auto-generated screenshots of projects into project management UI

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#552]
It might be cool to do auto-screenshots for Thimble projects, and leverage the code being used to do this in Webmaker App, see https://github.com/mozilla/webmaker-screenshot.

From demos: "it was actually originally created for thimble (the webmaker-screenshot service, that is - you can play w/ it at http://webmaker-screenshot.herokuapp.com/ though it whitelists stuff at makes.org and mofodev.net and andrew's funky thing.)*files* it's also been used by the webmaker discourse for over a year now - http://discourse.webmaker.org/t/webmaker-screenshots/331"

**Comment by toolness** [comment]
Rad! Let me know if you need any help w/ this one, and feel free to file issues on the github repository.

**Comment by flukeout** [comment]
Here are the 5 most viewed Thimble projects over the last month. 

* https://tjlee.makes.org/thimble/ODk0NDM1NTg0/fsa-beginners-guide
* https://dkgrewal98.makes.org/thimble/NjM3OTI3OTM2/javascript-takeover-bookmarklet
* https://ollie.makes.org/thimble/LTU1NTA4OTky/meme-maker
* https://jess.makes.org/thimble/MTA4ODU1Mjk2MA==/mobile-designing-kit
* https://webmaker.makes.org/thimble/keep-calm

@toolness Could you help us by running these through the Thumbnail generator and showing us the results?

cc @hannahkane

**Comment by toolness** [comment]
Hmm, I suspect this has something to do with jbuck's emergency fix to make the screenshot service work for webmaker app launch. it's currently an unmerged PR, as https://github.com/mozilla/webmaker-screenshot/pull/22, but i think that he pushed it to production for launch, and it's likely broken the front-end :disappointed: I'll look into it.

**Comment by flukeout** [comment]
Thanks @toolness - keep us posted, we want to see if we can use real screenshots for the gallery page.

**Comment by humphd** [comment]
This never got going, and I suspect that we can use @flukeout's work on the dashboard (#1204) to just use sandboxed iframes instead.  I'm going to close.
