### ISSUE TITLE
[Meta] Top Bar Refresh Implementation

### ISSUE THREAD

**Issue by JordanTheriault** [mozilla/thimble.webmaker.org#554]
Implementation of the top bar redesign by @flukeout as seen in issue #536. PDF of these designs located [here](https://www.dropbox.com/s/juk9et5fmvo7hya/ui-overview.pdf?dl=0). Redpen located [here](https://redpen.io/wo889e2e3abea83b34). Icons located [here](https://etherpad.mozilla.org/icons).

This is a meta issue which will point to many other smaller issues as they become defined for this heartbeat.

I've divided the design into distinct programming components. This allows the tasks to be divided between multiple contributors.

Components:
* Top 1" colour and icon implementation
* Project renaming enhancement
* User account menu
* Auto-save indicator
* Brackets theme
* Editor options menu (cog)
* File tree redesign implmentation
* Language picker redesign implementation
* New file + Import/Export button

**Comment by JordanTheriault** [comment]
WIP on [this](https://github.com/JordanTheriault/thimble.webmaker.org/tree/ui-implementation) branch.

**Comment by humphd** [comment]
Here's the basics of what I had to do in order to get my `standalone-and-iframe` working with this code:

```diff
diff --git a/public/friendlycode/css/editor.less b/public/friendlycode/css/editor.less
index 66444c6..5e08f93 100755
--- a/public/friendlycode/css/editor.less
+++ b/public/friendlycode/css/editor.less
@@ -10,7 +10,7 @@

 #webmaker-bramble {
     width: 100%;
-    height: 100%;
+    height: 100vh;
     border: 0;
 }

diff --git a/views/friendlycode.html b/views/friendlycode.html
index eefb70a..cba50ee 100644
--- a/views/friendlycode.html
+++ b/views/friendlycode.html
@@ -1,18 +1,10 @@
 {% block friendlycode %}
     <!-- friendlycode editor -->
-    <div id="bare-fc-holder" class="friendlycode-loading"></div>
-    <script src="{{HTTP_STATIC_URL}}friendlycode/js/require-config.js"></script>
-    <script src="{{HTTP_STATIC_URL}}friendlycode/vendor/require.min.js"></script>
-    <script id="friendly-code" src="/scripts/friendlycode.js"
-            data-localeInfo-lang="{{ localeInfo.lang }}"
-            data-make-url="{{ makeUrl }}"
-            data-make-endpoint="{{ MAKE_ENDPOINT }}"
-            data-preview-loader="{{ previewLoader }}"
-            data-page-to-load="{{ pageToLoad }}"
-            data-app-url="{{ appURL }}"
-            data-allow-js="{{ allowJS }}"
-            data-make-details="{{ makedetails }}"
-            data-editor-host="{{ editorHOST }}"
-            data-editor-url="{{ editorURL }}">
+    <div id="webmaker-bramble"></div>
+    <script src="http://localhost:8000/dist/bramble.js"></script>
+    <script>
+        var bramble = Bramble.getInstance("#webmaker-bramble", {
+            url: "http://localhost:8000/dist/index.html"
+        });
     </script>
 {% endblock %}
diff --git a/views/layout.html b/views/layout.html
index 41853a5..e73348f 100644
--- a/views/layout.html
+++ b/views/layout.html
@@ -15,7 +15,9 @@
     <link rel="stylesheet" href="{{ HTTP_STATIC_URL }}friendlycode/css/details-form.css">
     <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css">
     <link rel="stylesheet" href="{{ HTTP_STATIC_URL }}stylesheets/userbar-overrides.css">
-
+  </head>
+  <body style="margin: 0">
+    {% block body %}{% endblock %}
     {% if GA_ACCOUNT %}
     <script id="google-analytics-js" src="/scripts/google-analytics.js"
             data-ga-account="{{ GA_ACCOUNT }}"
@@ -23,8 +25,5 @@
             async>
     </script>
     {% endif %}
-  </head>
-  <body style="margin: 0" data-make-url="{{ makeUrl }}" data-make-endpoint="{{ MAKE_ENDPOINT }}">
-    {% block body %}{% endblock %}
   </body>
 </html>
```

I think we should dump the "friendlycode" naming eventually, since there is no more FriendlyCode in here.  There's also a lot of code we can remove.  But we can do it in stages.

I'm not sure the right place to put the `Bramble.getInstance()` call--it shouldn't be in the html file like I have it.  We'll want access to that instance in order to hook up all the buttons in the UI.

NOTE: I'm using a `url` option that points to my local copy of Bramble, since this iframe api hasn't landed upstream.

**Comment by flukeout** [comment]
@JordanTheriault I've started some work on defining the hover & active states below. Go ahead and try these, but I have a feeling that we'll have to tweak these in code as we play with the prototype. It's hard to anticipate how these feel when used.

![image](https://cloud.githubusercontent.com/assets/25212/8096540/0756944e-0f8d-11e5-85bf-ada204fb287f.png)

**Comment by flukeout** [comment]
@JordanTheriault I'm adding more icons as I go here - https://www.dropbox.com/sh/20n53ldeygimcom/AAAp__Tip0vidHV2jH5QOOsoa?dl=0

I'm using Sketch now to export these, so I'm curious if they will work better for you. I'm also exporting them at exactly the same size as they appear in the UI.

**Comment by JordanTheriault** [comment]
Still a few components such as positioning of some icons and the left but here is where as stand.

![topbarhover](https://cloud.githubusercontent.com/assets/5931078/8118410/af394e8e-105c-11e5-8a4a-85fa44c189d1.gif)

**Comment by JordanTheriault** [comment]
Updated functionality screencap. There are positonal issues with icons and the file tree bar that will be fixed in the coming days.

![topbar](https://cloud.githubusercontent.com/assets/5931078/8170886/e0bc9394-1381-11e5-8ae2-9df135092e74.gif)

**Comment by JordanTheriault** [comment]
Theme switch example

![themeswitch](https://cloud.githubusercontent.com/assets/5931078/8193727/de0c394c-1444-11e5-947f-66d543a26b06.gif)

**Comment by flukeout** [comment]
:sun_with_face: :full_moon: :+1:

**Comment by JordanTheriault** [comment]
Oddly satisfying.

![nameswap](https://cloud.githubusercontent.com/assets/5931078/8213749/27684b8c-14f2-11e5-9110-d67c28770e3e.gif)

**Comment by humphd** [comment]
This is done, closing.
