### ISSUE TITLE
Can we interact with the user's stored language preference?

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#556]
The Language is part of each user's setting stored on the webmaker login server. 

**Can we...**
* Use this setting to set the Language when that user is in Thimble?
* Change this setting when a user changes their Language preference in Thimble.

cc @sedge

**Comment by sedge** [comment]
@simonwex @jbuck @cadecairos Would it make sense to store this preference in `id.wm.o`? It could then be shared with other teach/wm apps.

**Comment by cadecairos** [comment]
prefLocale is already a part of login.wmo/id.wmo

**Comment by sedge** [comment]
@cadecairos Does `id` have an API for updating user data?

**Comment by humphd** [comment]
This is needed for l10n on new Thimble.

**Comment by sedge** [comment]
@flukeout This question has already been answered right? Can I close?

**Comment by flukeout** [comment]
@sedge do it!
