### ISSUE TITLE
Launch first round usertesting.com experiments  

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#558]
To check in on some of changes we're making, we'll test the prototype we're building with usertesting.com. 

I've outlined some of the areas to test and questions in the **[Draft Testing Plan](https://docs.google.com/document/d/1E8YpRV0jx8Z-To-upVzHmcwPfUXf1IhHU0X_jZAeemE/edit?usp=sharing)**.

**Comment by hannahkane** [comment]
Great start! I've added some comments to the doc.

**Comment by flukeout** [comment]
**Blockers**
* [ ] Fix sign in flow #627 
* [ ] Need a URL to hit that essentially remixes [this Thimble make](https://thimble.webmaker.org/project/21939/remix)

**Comment by flukeout** [comment]
@humphd Here are the files for the Stay Calm project - https://dl.dropboxusercontent.com/u/109902/bramble/stay-calm.zip

Is it possible that they are included in the repo so that we can make changes to them easily?

**Comment by flukeout** [comment]
First batch of tests has been launched. Will update feedback ticket when they're done.

**Comment by hannahkane** [comment]
@flukeout - we can close this ticket, right?

**Comment by flukeout** [comment]
Yep, closing.
