### ISSUE TITLE
File Rename UX

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#560]
Here are some thoughts on file renaming. I think for the most part, we can just use the stock Brackets functionality here. I've included an enhancement for inline filename validation, which we can nix initially in favor of the stock Brackets error dialog.

![renaming-file-ux](https://cloud.githubusercontent.com/assets/25212/8089333/22adf34e-0f5c-11e5-80fb-8d7779d0b002.png)

**Comment by flukeout** [comment]
@JordanTheriault Thoughts on implementing this?

**Comment by humphd** [comment]
We've got a rename flow in now that's working.  Let's file new bugs if we decide it needs to be enhanced.
