### ISSUE TITLE
Implement client-side communication with the publish server

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#561]
This will allow us to save/publish/load to/from the server.
https://github.com/mozilla/publish.webmaker.org/pull/46 will give us a list of things that we need to implement on the client-side.

For now, I think we are going to have the client communicate with publish.webmaker.org via the Thimble node server so that the client can make simple RPC like calls to the Thimble server and the Thimble server can process the request and send RESTful request(s) to the publish server to accomplish the specified task.

@simonwex does this sound like a good idea?
cc @humphd

**Comment by humphd** [comment]
This is done in various other bugs, I'm going to close and we can deal with specifics in other bugs.
