### ISSUE TITLE
Design Project Details bar for published projects

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#562]
When published, current Thimble projects have a details bar that is shown along the top, like so...

![image](https://cloud.githubusercontent.com/assets/25212/8119616/b561a0ce-104b-11e5-8e75-d22ac9ff208f.png)

When expanded, the following details are shown about the Project...

![image](https://cloud.githubusercontent.com/assets/25212/8119629/ca8d7680-104b-11e5-952a-b7956312e80f.png)

* Project title
* Project author name and avatar
  * Name is linked to gallery of projects
* Date made
* Sharing options
  * Google+
  * :bird: Twitter
* Number of likes
* Button to "Like"
* Number of times Remixed
* Remixed from

Which of these do we want to keep?

I think we should have a bar that is specific to Thimble, I've started some ideas below. It would be cool if the bar faded away when the page is scrolled, but still retained the key actions of **Remix** and **Back to Thimble Home**

![image](https://cloud.githubusercontent.com/assets/25212/8119603/9a404228-104b-11e5-90cf-c7eb8613d6ed.png)

I'm a little wary of using a strong bar of color, so I think I'll try something more neutral as well.

At a minimum I think we should provide:
* Project name
* Ability to Remix
* Thimble home link
* Author + link to author gallery

I think if the bar fades away when the page is scrolled, we can put in a lot of this information without needing an "expanded" view for this.

Thoughts @hannahkane @cassiemc

**Comment by hannahkane** [comment]
Agree on the minimum, though I think the Likes will be useful for the gallery algorithm, right? @simonwex - would we have to rebuild that feature if we want it?

Also, is there any way to find out how often the social share feature is used now? @adamlofting

**Comment by cassiemc** [comment]
Love the idea of hiding the bar as it scrolls. We wrestled with that in the original UX – how to do keep functionality and send users back to Webmaker, but also not dominate someone's work. Your solution is elegant.

**Comment by flukeout** [comment]
Here's an option that contains some of the key info without needing to be expanded...

![image](https://cloud.githubusercontent.com/assets/25212/8120189/63693196-1051-11e5-8eae-d70b274c3fb7.png)

**Comment by humphd** [comment]
I want to suggest that we consider dumping this completely, and just serve the content the user created.  There are serious technical and security implications to having user hosted content being connected in any way to our servers (e.g., having buttons that let a user like or remix mean we have to know who you are).

cc @jbuck

**Comment by hannahkane** [comment]
@humphd - are you suggesting we don't have remix functionality at all?

**Comment by humphd** [comment]
@hannahkane the ability to remix something is fine, it's when we mix our UI with what the user created that we get into issues.  For example, on a gallery, where we might show a thumbnail or some other project icon/description/title, we can let you do it from there, since we aren't running untrusted code.

There are ways to do this, but it's hard to do it well, and safely.  I'm not saying "no," just consider whether we actually need a remix button when you look at the thing someone made.  I'm challenging our UX folks to consider other ways :)

**Comment by hannahkane** [comment]
Ah, I see. I'd like to explore our options, then. It does seem like the content itself would be an obvious starting point for the Remix workflow. Could we include a way for someone to get from the user's content to a place where they can remix it, even if there's a step in between?

**Comment by flukeout** [comment]
No Remix!?!? Get the :trident::trident::trident: (pitchforks, obviously)

**Comment by flukeout** [comment]
Just going to spam some designs into this issue for now
![image](https://cloud.githubusercontent.com/assets/25212/8120713/536e2930-1057-11e5-9470-66f4cf5ff094.png)

**Comment by humphd** [comment]
If you look at github.io vs. github.com, it's helpful.  Consider this page: http://philipwalton.github.io/solved-by-flexbox/  He's added his own stylish button to go view the source on his Github project page.  Github hasn't done this for him, although they do provide a template that has a static link to get you back to their site, but no user log-in state is used.

Part of what I like about this is that it's on us to provide enough value that you'd want to say, "Hey, you can go remix this yourself too, just click here".

**Comment by flukeout** [comment]
Github is an interesting comparison - I think we should set the bar a little lower. For contrast, Codepen opens everything in an editor right off the bat so you can just tinker immediately. Let's continue this discussion in a meeting - I'll hold off on additional designs for now, but I'm happy we got the conversation rolling.

**Comment by cassiemc** [comment]
Ooo juicy. Looking forward to today's stand! Will bring my :baseball: :fork_and_knife:

**Comment by flukeout** [comment]
Update - we are going to hold off on any design and implementation around this feature until we can determine if having a details bar with a Remix feature is useful and important to our current and future aspirational users. 

To that end, I'll continue having discussions with educators who have used Thimble and attempt to gather some metrics with @adamlofting's help.

**Comment by flukeout** [comment]
My current Google Analytics sleuthing reveals that, during the last month...

* Thimble makes have been viewed 9193 times
* Remix has been clicked 1238 times
* So, roughly 13.5% of the time a Thimble make is viewed, it gets remixed via the Details bar

@adamlofting Can you confirm this?

I compared the total pageviews of content that matched "makes.org/thimble" and the number of times the "Remix clicked" event has been fired with an event label that also contained "makes.org/thimble"

**Comment by flukeout** [comment]
Feedback from Mick Fuzz - " I think the remix button is important for my context. As that is a big part a lot of my teaching instructions - "go to this page and hit the remix button"

**Comment by adamlofting** [comment]
@hannahkane we don't have analytics instrumentation on those links in the banner, but we can [search twitter like this to see how many people are using this](https://twitter.com/search?q=%23Webmaker%20makes.org&src=typd&vertical=default&f=tweets) - At a glance it's a couple per week.

@flukeout that method is good for understanding the `view > remix` conversion rate. Just a note for awareness: That % could be skewed down if a random make hosted on makes.org was popular/viral with another audience.

I took a look at the database of Thimble Makes from the last 12 months:

* 94k Thimble projects were started
* 55k of those were started by remixed an existing project 

So, **~60% of projects were started by remixing**. This is likely because that's how we tell people to use Thimble.

**Comment by jgmac1106** [comment]
I would have to agree with Mick Fuzz. No new learner wants to be faced with
the tyranny of the blank page. We tell people to use Thimble this way
because remixing content is the best way to #teachtheweb.

These conversion rate data are awesome. Just to hear 94K makes were
published last year is great.

**Comment by flukeout** [comment]
@adamlofting Thanks for the additional data!

**Comment by hannahkane** [comment]
Thanks, @adamlofting. 

It sounds like we know that remixing is an important starting point, but, iiuc, we don't actually know from where people are starting their remixes, right? We know that 13.5% of those who are viewing a make remix it, but we don't know what % of the total remixes that represents. IOW, if we removed the remix from the make itself, but added more prominent entry points elsewhere (e.g on an improved landing page gallery, or perhaps on specific landing pages for our most popular activities - a la https://webmaker.org/en-US/madewithcode-meme), we don't know how that will affect people's ability to find content to remix.

I'm leaning towards an MVP without the Remix button on the make (which is the opposite of where I was leaning last week), but watching the numbers and collecting feedback from users.

Totally open to being persuaded, though.

**Comment by flukeout** [comment]
@hannahkane Very roughly, if 55K project were made by remixing - let's say that roughly 55k/12 = 4600 projects are made via remixing per month. The data I pulled said that last month, 1238 projects were created by hitting the details bar remix button, which would represent roughly 1238/4600 = **26%** of all remixes in our roughly estimated math.

**Comment by hannahkane** [comment]
@flukeout - You are very persuasive! :) We're changing other things, though, including, notably, the landing page experience, so we might "gain" some of that 15% that way. Also, I still don't think we know enough—a large % of those remixes might be from students of people like MickFuzz ("go to this page and hit the remix button"), which may not be "lost" as long as we provide another way to give those easy instructions to learners. We don't know how many of those remixes are organic, for lack of a better term.

@humphd - realized I don't understand something about the original flag - why do we need to know who the user is to show a Remix button?

Also, we haven't talked about the loss of the Like button, but that could also be problematic. Again, don't have numbers, but I imagine a lot of the Likes originate on the make itself, and Likes are a useful part of any popularity algorithm we use.

**Comment by flukeout** [comment]
I will spec out the bare-bones non-authenticated version of this feature so we can estimate the technical effort and decide if we will pursue it for MVP.

**Comment by hannahkane** [comment]
Closing this. Covered in #570.
