### ISSUE TITLE
Can a user have two projects with the same name?

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#566]
Our database doesn't key on the project name, so it's possible to make this go either way. 

cc: @flukeout @hannahkane @humphd

**Comment by humphd** [comment]
I don't think it's helpful to have duplicate names, since it will lead to confusion, either the user's or our code's.  Let's just not have dupes.

**Comment by flukeout** [comment]
@humphd Do you mean no duplication across all Thimble projects? 

Since we're auto-saving work, we'd have to increment the name of new projects... "My Project, My Project 2.. etc" which seems pretty lame.

I vote that we treat the name as a purely cosmetic attribute, and even a user can have two projects named the same thing.

**Comment by jgmac1106** [comment]
I would agree with @humphd Not sure how it happens, if I am remixing, or re-publishing but I end up with multiple copies of the same project all the time. I know its user error, but hopefully you folks can develop an interface that reduces my own stupidity. 

![thimblepics](https://cloud.githubusercontent.com/assets/10534566/8165513/03bf1ca4-135f-11e5-9cb0-7aeaa8fb7975.png)

**Comment by hannahkane** [comment]
I tend to agree with @flukeout that incrementing names on auto-saved new projects is kind of weird. To solve the remix problem, perhaps when a user remixes the project name is, by default, "[name of project] (remix)". Would that solve it?

**Comment by flukeout** [comment]
Need to thikn through a few cases here before we make any decisions
* If we include the project name in the url, what happens if you rename and update published
...

**Comment by flukeout** [comment]
Currently, Thimble publishes a project to a URL that includes the project name, but also some randomized characters...

![image](https://cloud.githubusercontent.com/assets/25212/8216273/5e024b46-14ea-11e5-905e-0a9d5dedd8d4.png)

**Comment by humphd** [comment]
I think it will help us a bit if we understand how we're doing published URLs in general.  @jbuck am I right that we still want to do `<user>.makes.org/*`?

@flukeout: one thought: why not default to a hash or some other unique string, but give the ability to provide a slug, which only needs to be unique-per-user, or maybe even unique globally?  It would require some UI, but might be the best of both worlds, if https://humphd.makes.org/thimble/as32asdf and https://humphd.makes.org/thimble/slug-name both pointed at the same thing?

**Comment by flukeout** [comment]
@humphd Yeah, I like the idea of letting the user set a unique-to-the-user slug. We could default it to the project title but make it be editable - we could check for uniqueness before publishing. I'll mock something up.

**Comment by flukeout** [comment]
Here's a UX that lets you choose your URL

![image](https://cloud.githubusercontent.com/assets/25212/8261872/c5388b1a-1682-11e5-9c89-0e963088f643.png)

**Comment by hannahkane** [comment]
+1 to this solution

**Comment by flukeout** [comment]
Closing this because the original question of the ticket has been resolved. I will move the 'vanity path' UX into another ticket, though.
