### ISSUE TITLE
Update Help FAQ (Thimble)

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#567]
The Help link in the user bar should likely continue to go to a support FAQ, though we'll need to make updates to the questions and answers.

/cc @thisandagain  and @xmatthewx - wondering if you guys have a plan for https://support.mozilla.org/en-US/products/webmaker.

**Comment by xmatthewx** [comment]
We haven't discuss this yet, but here's my perspective: 
 - Short-term plan is to retire content that is no longer relevant. 
 - Long-term, @secretrobotron might want to think about how support intersects with community management when we add social in the fall. 
 - In between, we will build an FAQ as those questions get asked. I'd prefer that those live on Webmaker.org for a coherent experience. Maybe there are advantages to using SuMo that I haven't seen yet.

**Comment by hannahkane** [comment]
Thanks, @xmatthewx. That sounds like a good plan. 

Started a doc to edit some of the existing Thimble questions and answers and started a list of add'l questions we'll want to add re: bramble. https://docs.google.com/document/d/1wQf9WpG8ouJaVNTEdGnOgH9rGBJijWmM-3KRrzfJOoM/edit?usp=sharing

**Comment by hannahkane** [comment]
@ldecoursy - wondering if you can take a look at the Thimble Help section I've drafted so far, and edit it for clarity.

and @flukeout - can you take a look and add any other features/concepts that you think require an FAQ?

https://docs.google.com/document/d/1wQf9WpG8ouJaVNTEdGnOgH9rGBJijWmM-3KRrzfJOoM/edit#heading=h.xvjc686dxh8a

**Comment by ldecoursy** [comment]
This looks awesome to me! I had a few small edits in the GDoc.  Also would love a walk-through of the tutorial process - that was the only thing that seemed like it might use more detail, but only bc I'm not exactly sure how it works yet ;)

**Comment by hannahkane** [comment]
Thanks, @ldecoursy. Great edits. I'll ping you at some point today for a tutorial walk-through (though not all the UI elements are in place yet).

**Comment by hannahkane** [comment]
FAQs are finalized: https://docs.google.com/document/d/1wQf9WpG8ouJaVNTEdGnOgH9rGBJijWmM-3KRrzfJOoM/edit#heading=h.xvjc686dxh8a

Just need to get them onto the Support forums, which I'm not sure how to do. Emailed SUMO staff to find out.

**Comment by hannahkane** [comment]
OK, all set to make these changes after go-live on Monday.

**Comment by hannahkane** [comment]
This is done, though I'll likely add more in the next few days based on Dave's "Using Thimble" doc
