### ISSUE TITLE
Investigate error message options!

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#572]
We want Thimble to have useful and informative error messages that help people succeed!

With that in mind...
* What are we currently using? Stock brackets error reporting?
* What are our current options for displaying error messages for HTML, CSS & JS
  * Are there different Brackets plugins we can use?
* What are good benchmarks?
  * Firefox dev tools
  * Other code editors
* What errors do we want to highlight?

What does our audience need help with?
* Have heard that forgetting closing tags is very common

**Comment by hannahkane** [comment]
I think it's a P1 to have *some* kind of error messages, but I'm unclear on what's in place already. @humphd - can you explain what we can have for free?

**Comment by flukeout** [comment]
@hannahkane I've started some very rough work on this near the bottom of https://docs.google.com/document/d/1yk799F2OCzcrHLG_DQGlJO-X6cWAHTolULs71K8F14s/edit?usp=sharing

**Comment by hannahkane** [comment]
hey @flukeout - is this ready for me to look at?

**Comment by flukeout** [comment]
@hannahkane no - i'll put in some more work on it later today and ping you!

**Comment by hannahkane** [comment]
@flukeout and I just discussed over email - taking this out of MVP. Will adjust roadmap accordingly.
