### ISSUE TITLE
Investigate ways to help authors add comments and tutorials to their projects.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#573]
This issue is now about investigating ways to help people create tutorials and leave more effective comments in their projects because..

* Current tutorial solution clutters the interface and is often ignored
* There's no clear UI for creating a tutorial or attaching it alongside your project
* Code comments can be messy when used extensively throughout a project

This ticket will be a UX / UI brainstorm dumping ground as we discuss and iterate on possible solutions.

**Comment by flukeout** [comment]
Brainstorming "folded" inline comments...
![image](https://cloud.githubusercontent.com/assets/25212/8221093/11554008-150f-11e5-8cf6-3dbefab62b7f.png)

**Comment by hannahkane** [comment]
I like this UX a lot.

Are code hints the same as comments? I thought code hints were, for example, brief explanations of tags automatically pulled in from a data source like MDN, whereas comments are more like...code comments that an author or reviewer adds themselves.

**Comment by flukeout** [comment]
Here's an option for converting inline code comments into fancy, tutorial like comments.

![image](https://cloud.githubusercontent.com/assets/25212/8237129/f5953056-15a1-11e5-9ac0-aa7a121530a1.png)

**Comment by jgmac1106** [comment]
I like this option. I don't think we would need a ton of formatting but this works better than the tutorial frame or the inline commenting overload.

For example here is a make being shared as part of #clmooc https://thimble.webmaker.org/project/155281/remix it is just full of comments being used as a tutorial. 

Being able to navigate through the comments would be really nice and allow learners to actually see the relationship in the code.

**Comment by flukeout** [comment]
Here's a fancier version of the approach above that supports **markdown** and also **multiple highlighted lines* - all of this would be optional, but would offer additional functionality.

![image](https://cloud.githubusercontent.com/assets/25212/8238413/5951f0d6-15aa-11e5-8533-2eea22d427c3.png)

**Comment by hannahkane** [comment]
This looks great. Still confused about code hints v. code comments. Aren't they different things?

**Comment by flukeout** [comment]
Yeah so, in my mind..
* **Code Hints** pop up as I'm typing various HTML or CSS properties and help me auto-complete, this is a feature of the editor, and not something the Project author has control over
* **Comments** are bits of text added by the Project author to explain and annotate parts of the code

**Comment by hannahkane** [comment]
Agreed. So this ticket is about comments, right?

**Comment by jgmac1106** [comment]
I like that distinction. I think part of the confusion was the way users hacked together the comments to embed tutorials....but yes maybe the ticket shoudl be renamed to code comments.

**Comment by flukeout** [comment]
@hannahkane Correct - I'll update the issue title, as it's too broad! My apologies.

**Comment by xmatthewx** [comment]
There is definitely simpler and more elegant the current tutorial system. 

You might have it display fancy comments by default to make it more user-friendly. You could add a setting behind your gear icon to turn off fancy comments for more advanced users.

**Comment by flukeout** [comment]
Here's a rough idea of how this might behave once the comments are already fancy..
http://flukeout.com/examples/code_comments/

**Comment by xmatthewx** [comment]
Demo is excellent. This is great. 

Rather than an extra closing tag, you might just highlight any continuous code blocks below, and stop when it reaches a blank line.

**Comment by hannahkane** [comment]
@humphd - what can we do to get an estimate on the work imagined in these mock-ups? I'd like to understand how realistic these ideas are for MVP, or if we need to come up with something simpler.

**Comment by hannahkane** [comment]
@sedge @gideonthomas - are either of you able to help estimate the work implied in this ticket? Just trying to get a sense of whether @flukeout should be mocking up a simpler solution.

**Comment by sedge** [comment]
@hannahkane Neither of us are front-end developers, so it's hard to judge that piece. The more technical parts are non-trivial, since we'd be:

* Parsing the html for comment blocks
* Parsing those blocks for markdown
* Rendering that markdown into HTML
* Stuffing that HTML into some sort of inline comment section per comment
* Hooking up navigation between the comment sections

It's definitely doable, but would take some time IMHO.

**Comment by hannahkane** [comment]
Given that, I think we probably need to spec out a simpler solution. We need some sort of method for educators to create tutorials for their learners. @flukeout - what do you think?

**Comment by jgmac1106** [comment]
The inline comments as is along with a tutorial doc would be fine.

We could build a tutorial template in Thimble for educators to use. They
already have a few. This would mean users would have to toggle between two
open tabs or windows.

I actually like that method over having them trying to create the teaching
kits in GitHub.

**Comment by jgmac1106** [comment]
That being said if @flukeout rich comment system is something that can be
tabled for the down the road it is awesome.

**Comment by hannahkane** [comment]
@jgmac1106: what does a "tutorial doc" mean? Is that a separate doc that an educator might create using another tool? And I'm a bit confused about your comment about teaching kits in GitHub. Teaching Kits are different from tutorials, aren't they?

**Comment by hannahkane** [comment]
@flukeout - let's talk about this at stand-up tomorrow, or afterwards if we need to. Would really like to figure out an MVP solution for allowing educators to create useful guides for their learners.

**Comment by jgmac1106** [comment]
Sorry for confusion. Let me explain my madness:

Tutorial-meant for single learner working by herself.
Teaching kit-A set of learning activities focused on one or more
competencies. Require multiple session. Meant for club captain or educator
teaching others.
Learning Activity- A single session event focused on one or more skills
under a competency(ies).

We used Kits and Activities as the language du jour for the Thimble remixes
used as lesson plans.

**Comment by humphd** [comment]
One of the problems with this approach, similar to what we did with the previous tutorials, is that it's a bespoke UI addition that has to be created and maintained along with the rest of the UI.  From @hannahkane's question above, and @sedge's reply, you can already see that we're talking about a lot of work.

However, notice how quickly @flukeout made an actual working demo of his fancy comment system when it was done as a standalone web page--it was less than a day.  This is no coincidence, since anything that can be built as a standalone web page will always be more flexible, faster to create, and possible for people other than the core developers to to imagine/design/implement/test.

I say this because I think we're repeating a mistake with inline comment UI vs. allowing learning material to be its own thing.  With the previous version of Thimble, we were hamstrung by the fact that we had a single file, and had to jam everything we wanted into that one page; we no longer have this constraint.  With the new Thimble, it's possible to have an entire book of html, css, images, in a separate directory from the content you're working on.

The thing that's needed, and I desperately want to see us figure out, is how to do a UX that enables one to switch between a preview and a set of learning material, both of which are rendered HTML/CSS/JS web pages.

Because we control the connection between the editor and the "web browser" (i.e., the Bramble iframe that renders content), we could even add an API for tutorials and other learning material to control the editor: highlight lines 150-155, switch to file `style.css` and line 76, create a new HTML file with a predefined set of elements to use for a section of the tutorial, etc.

There's no reason anymore for us to artificially limit what people can do with learning materials in Thimble: we have a full filesystem, web server, and web browser built into the page--let's use it!

**Comment by jgmac1106** [comment]
I have a question and apologize for my ignorance ahead of time. Could there
be two html files in the File system? So could I have index.html which is
the file I am working on and tutorial.html which has all the learning
materials?

This way a user could toggle between the file they are editing and the file
that contains the how-to.

**Comment by humphd** [comment]
@jgmac1106 you've got it exactly.  It opens whole new opportunities for us.  Imagine you want a page that mixes YouTube videos, code snippets, diagrams, etc.--it can all go in `tutorial.html` and we can render that for you, and allow the user to switch back and forth between viewing that on the right and whatever they are doing in tandem with `index.html`.

**Comment by hannahkane** [comment]
Notes from convo with @flukeout and @humphd earlier - Luke is going to mock up the way Humph is suggesting, and we'll do some testing on it. Will surface any UX issues this way, as well as be able to derive an estimate.

**Comment by flukeout** [comment]
Here's one quick stab at a possible layout / structure of the tutorial view and files.

![image](https://cloud.githubusercontent.com/assets/25212/8685772/d4ec35ea-2a35-11e5-88b9-d75f1b4cbc10.png)

**Comment by hannahkane** [comment]
Looks nice, @flukeout. If we go with this model, we'll definitely need to provide a template for educators, so they're not starting from scratch.

**Comment by flukeout** [comment]
@humphd I'm curious about using the inline editor feature that we use for the documentation & colorpicker features. Would we be able to load information into the inline expandable area dynamically depending on what is in a tutorial.txt (for example)?

Our tutorial.txt file could have a structure like...
```
index.html 30 
This is a paragraph, add some text content.
index.html 35
This is an unordered list, it will automatically get bullet points when you add items.
```

Each of these would then inject or add an expandable comment to the related file at that line number. Just a though, curious about how that stuff works.

**Comment by humphd** [comment]
@flukeout I think it's possible for the inline editors to work this way, yes.  We'd have to write a custom doc provider in Brackets, and have it get its data from the tutorial somehow, perhaps we can have a JSON format we support, and if you have files like that in a tutorial directory, we automatically do this for you:

```json
{
  "/index.html": {
    "30": "This is a paragraph, add some text content",
    "35": "This is an unordered list, it will automatically get bullet points when you add items."
  }
}
```

**Comment by flukeout** [comment]
Here's a potential solution for the tutorial feature we discussed during our last meeting...

**Full version** - https://dl.dropboxusercontent.com/u/109902/bramble/tutorial-ux.pdf

![image](https://cloud.githubusercontent.com/assets/25212/8834009/b18db8e4-3066-11e5-922b-2cc3359b6ebc.png)

**Questions**
* Should all new projects start with a blank tutorial template or is it something an author can add?

**Comment by flukeout** [comment]
Concept for "bright comments" - basically an author-controlled toggle that lets you make inline code comments brighter & more prominent. They remain editable.

![image](https://cloud.githubusercontent.com/assets/25212/8835775/5f3fa510-3071-11e5-8486-60e9326eb255.png)

**Comment by jgmac1106** [comment]
I don't think blank tutorial should be a default. Sometimes I am just
working on a project for myself.

I also think the value proposition for Thimble could move beyond MLN. The
more I play with the brackets version of thimble the more I like it when
compared to other spaces like fiddle,  w3school, or codepen tools. I am a
broken record but the team deserves accolades.

If it is possible to have a template for tutorials added on an individual
basis that would be better than default IMO.

**Comment by hannahkane** [comment]
Thanks, @flukeout. Nice work.

<3 the tutorial piece. I think the "Add Tutorial" button might warrant some kind of explanation. Maybe a "What's this?" link that opens a relevant FAQ. And perhaps the default html file has some context/tips for creating a good tutorial. Otherwise, if you don't already know what it is, it might not be intuitive what you're supposed to do, or how it will be interacted with by learners.

Agree with @jgmac1106 that loading one by default isn't necessary.

Really like the Bright Comments toggle concept, but worried that the user won't always have immediate feedback about what it does. If the screen they're looking at doesn't have any comments, enabling it will look like it has no effect, and that could be confusing.

**Comment by flukeout** [comment]
@hannahkane Agreed, we can put some explanation content at the top of the tutorial.html page that we generate that the author can delete, or add some kind of info popup to explain how to use it.

Agreed on the second part too, maybe we can expose the UI near existing comments when someone scrolls them into view - we'll have to review the feasability of other approaches with @humphd, but I can create another design to get that going.

**Comment by humphd** [comment]
I'm doing the backend parts of this within Brackets in https://github.com/humphd/brackets/pull/392

**Comment by flukeout** [comment]
@humphd I didn't get very far with the tutorial content today, so I think you should just go ahead and include a basically-blank tutorial.html file that we can link to an external tutorial.css file.

So far I've just started working on a rough tutorial style guide, which is here:
http://flukeout.github.io/thimble-home/tutorial/tutorial-style-guide.html

@hannahkane Let's discuss what the starting content of a tutorial would be. I think it should be some informative content that helps people create something useful. I was thinking of modeling it after... https://mozteach.makes.org/thimble/make-your-own-teaching-activity

**Comment by jgmac1106** [comment]
I like the old teaching kits as well but I would simplify the list items. I
saw many mentors (including myself) mess up the nested lists within  <div
class="well example">. I would just simplify the code to reduce the chance
of error. Though that does mean sacrificing pretty. That hurts a little.

**Comment by hannahkane** [comment]
+1 on using that teaching kit make as a template

**Comment by hannahkane** [comment]
@flukeout - we might want to create two different implementation tickets. One for the tutorial and one for the comment highlighting.

Started drafting copy for the tutorial here: https://etherpad.mozilla.org/thimbletutorialcopy

**Comment by flukeout** [comment]
Okay, I think the files are pretty much ready to go.
* **Tutorial** - flukeout.github.io/thimble-home/tutorial/tutorial.html
* **Style Guide** - flukeout.github.io/thimble-home/tutorial/tutorial-style-guide.html

Once the content is finalized, I'll update the tutorial.

**Comment by hannahkane** [comment]
okay, @flukeout - final copy here: https://etherpad.mozilla.org/thimbletutorialcopy

**Comment by flukeout** [comment]
Thanks @hannahkane - btw I started an implementation ticket for this - #737 
I'll file another for the 'bright comments' so we can close this.

**Comment by flukeout** [comment]
Closing as both concepts have their own implementation tickets now:
* Tutorial - #737
* Bright Comments - #738
