### ISSUE TITLE
New UI broken in Safari, IE and Edge

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#574]
![screen shot 2015-06-17 at 7 12 24 pm](https://cloud.githubusercontent.com/assets/427398/8220776/db88ec02-1524-11e5-8714-3afa7ee1afc8.png)

We have some CSS issues with Safari and the new UI :)

cc @JordanTheriault

**Comment by humphd** [comment]
And in Opera...

![screen shot 2015-06-17 at 7 14 35 pm](https://cloud.githubusercontent.com/assets/427398/8220799/239f1106-1525-11e5-9d01-b614c36f7ac6.png)

**Comment by humphd** [comment]
And IE...

![screen shot 2015-06-17 at 7 17 36 pm](https://cloud.githubusercontent.com/assets/427398/8220835/91747a5e-1525-11e5-8fcc-66ad8dafdef8.png)

**Comment by humphd** [comment]
In the IE case, it seems to abort downloading the iframe script almost instantly.  A bit of reading indicates it might be that this is happening because the DOM hasn't fully loaded before we try to mess with it.  It might be useful to play around with load ordering in the iframe api.

**Comment by JordanTheriault** [comment]
Opera is working, Safari fix is nearly complete as per #578

**Comment by humphd** [comment]
I've fixed the `trimRight` bug, and filed https://github.com/MozillaFoundation/mofo-devops/issues/107 on the rest of IE's loading issues.

**Comment by sedge** [comment]
@humphd Is this fixed now?

**Comment by humphd** [comment]
Safari is mostly good.  I'll check IE and report back.

**Comment by humphd** [comment]
![bramble-ie](https://cloud.githubusercontent.com/assets/427398/8708602/081dce12-2b0b-11e5-84ab-bec677fd7648.png)

IE is still badly broken in a few ways, including it not wanting to load the Bramble script at all.

**Comment by humphd** [comment]
IE can mostly load the app now, but still a bunch of brokenness, and Safari is just needing some UI tweaks:

![screenshot 2015-08-27 16 23 38](https://cloud.githubusercontent.com/assets/427398/9532261/8035be52-4cd8-11e5-8618-a559f3d2fc1d.png)

**Comment by gideonthomas** [comment]
continuing discussion in https://github.com/mozilla/thimble.webmaker.org/issues/892
