### ISSUE TITLE
Transfer our front-end logic and styling into our build system

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#581]
We'd like to clean up thimble's front end to make it easier to reason about and maintain. The main steps will be:

* [x] Set up a browserify & LESS build step for our resources
* [ ] Isolate the different programmatic front end features and refactor for simplicity

**Comment by humphd** [comment]
We need a build step for our JS and CSS in Thimble, morphing this.

**Comment by sedge** [comment]
@humphd AFAIK we *have* a build step for [JS and CSS](https://github.com/mozilla/thimble.webmaker.org/commit/d7c11ebcb8e3280b20904352c4ba66b95d59110b). Can you elaborate on what you want to see?

**Comment by humphd** [comment]
We've done this now.  We could improve it later, but it's good enough for the moment.
