### ISSUE TITLE
Experiment with svg-optimizer

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#584]
https://simon.html5.org/tools/js/svg-optimizer/ let's you shrink SVGs.  Can we get any download savings from this with all our buttons?

**Comment by JordanTheriault** [comment]
Some starting info - Our largest icon is 2kb, our smallest clocks in at 748 bytes.

I've tested this with a few of our images, and the resulting quality makes most icons unrecognizable and distorted. The savings are approximatley 30-35%.

Resizing the icons is worthwhile, as the original assets are quite large in terms of their original render size before we resize them with html/css. We could do this in Adobe illustrator.

**Comment by JordanTheriault** [comment]
![screenshot 2015-06-22 10 12 19](https://cloud.githubusercontent.com/assets/5931078/8283775/3db2e87e-18c7-11e5-9d26-83e6dade654d.png)

Resulting sun icon on full quality.

**Comment by humphd** [comment]
Great, thanks for experimenting.  Sounds like this is a no-go.  Closing.
