### ISSUE TITLE
Need to have downloadable presentations 

### ISSUE THREAD

**Issue by shirishag75** [mozilla/thimble.webmaker.org#588]
Hi all, 
Is there a way that thimble can make downloadable presentations, from chat :-

Shirish - I do wish there was someway to also remix to be a presentation that could be gone through rather than the online part, the reason is simply because of linearity while in the teaching kit I see there are various ways that people go back and forth

Akshay - I'm not sure thimble allows presentation style things. 
We should ideally create remixable presentations too so that people can download them and use. It's all subject to finding people to do it.

**Comment by jgmac1106** [comment]
There is this presentation code I found floating around somewhere on Git that I started to move into a Thimble Make. https://jgmac1106.makes.org/thimble/LTE2MjU3NTEwNDA=/walkmyworldeventten 

Somebody in this repo may be able to point you the source on Git.

**Comment by humphd** [comment]
We're working on fixing tutorials, and also making things downloadable in other bugs.  I'm going to close this here, and we'll follow-up in other bugs.
