### ISSUE TITLE
bramble.mofostaging.net must be in working state June 23 5PM EDT

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#589]
There are some internal demos happening with Thimble/Bramble tomorrow (June 23) and @flukeout has asked that we make sure bramble.mofostaging.net is in working order by 5PM EDT--their demos are later than this.

Please make sure that anything we land is tested properly, and that we back out anything that's busted by 5PM.

cc @sedge, @gideonthomas, @JordanTheriault

**Comment by sedge** [comment]
Since it seems to be stable right now, why don't we put a freeze on merging into bramble?

**Comment by flukeout** [comment]
:+1: I'll bat it around a little bit to make sure everything is on the up and up but that sounds pretty good to me (unless we're planning to land a cool piece of functionality)

**Comment by sedge** [comment]
@flukeout Do you know when you'll be demoing? It would be great to unfreeze when you're done.

**Comment by sedge** [comment]
Unfrozen!
