### ISSUE TITLE
Refreshing the browser shouldn't cause the editor settings to reset

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#590]
When using the dark theme, refresh the browser. It resets back to the light theme, which is a little jarring. 

**Let's remember**
* Editor font size
* Editor theme
* File tray open vs closed

When I reload, the editor should look the same. 

The only conflict here is that we already have some functionality around determining the file tray state based on the number of files in a project. Is there a way to solve this gracefully?

Maybe we only do the number-of-files detection when...
* You remix a project
* Load up one of your existing projects

Possible?

cc @JordanTheriault

**Comment by humphd** [comment]
Let's clarify what reload means here.  Do you want it to remember your editor state for any project you were in last, or just *this* project if you reload it?

Brackets has a whole state management system that uses the filesystem.  As you alter aspects of the app, it writes it out to json files.  Right now we have this turned off, but it's easy to use it.  It would mean that we'd need to have the UI in Thimble check more state when it starts up.

**Comment by flukeout** [comment]
Let's keep track of state independently of projects - so, if I turned on the dark theme, the editor stays dark until I change it back to light and not because of opening a project that was last edited in the light theme.

**Comment by humphd** [comment]
@gideonthomas: where do you think we should be dealing with state?  Should we have Thimble remember this (localStorage) and pass it into `Bramble.load()` as options?  Or should we turn on Bracket's `state.json` stuff?

**Comment by humphd** [comment]
I did an experiment with Bracket's state management in the filesystem, but I think we should do our own.  So to be clear, you'd like:
* Editor font size
* Editor theme
* File tray open vs closed
* Width of file tray, editor, and preview columns
* Preview mode: desktop or mobile

I can probably also do last open file.

**Comment by flukeout** [comment]
Those sound good for now, last open file will be represented in editor & preview correct?

How does the preview logic work by the way? What if I have two HTML files in my project? Does it show the last-edited / opened on?

**Comment by humphd** [comment]
It looks for something called "index.html" unless told otherwise.

**Comment by flukeout** [comment]
Do we have a mechanism in place for telling it otherwise right now? Maybe it's something I can spec the UX for.

**Comment by humphd** [comment]
When we call `Bramble.mount("/path/to/project", "filename-to-open.html")` in Thimble we can control it programmatically.

**Comment by humphd** [comment]
FYI - I've got a fix for this underway in https://github.com/humphd/brackets/pull/362

**Comment by humphd** [comment]
This is landed now, closing.
