### ISSUE TITLE
Dark Theme makes top bar shadow way darker than Light Theme

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#592]
**Dark Theme**
![image](https://cloud.githubusercontent.com/assets/25212/8290092/9919d41c-18d5-11e5-8d5a-4d925a1a17a8.png)

**Light Theme**
![image](https://cloud.githubusercontent.com/assets/25212/8290104/aa002556-18d5-11e5-9602-4a0a4c623104.png)

cc @JordanTheriault

**Comment by JordanTheriault** [comment]
This was done as a fix, but can be changed back.
When the shadow is light while the dark theme is active, the drop shadow was lighter than the background of the editor window, creating a strange appearance.

There is a fix at #594 which attempts to make this shadow more appealing. Though I suggest we consider trying a non-transparent lines to see if this can be remedied differently.

**Comment by JordanTheriault** [comment]
As per #598 the shadow change will be removed.

**Comment by JordanTheriault** [comment]
I personally prefer no shadow, with the preview bar darkened, what do you think @flukeout we can darken it further.

![screenshot 2015-06-24 16 06 24](https://cloud.githubusercontent.com/assets/5931078/8340234/32cb5958-1a8b-11e5-99cf-3093ff8531a6.png)

**Comment by humphd** [comment]
Shadow is gone, closing.
