### ISSUE TITLE
I can close the editor settings popup by tapping anywhere on the top bar, but not the preview or the editor.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#593]
**For Reference**
![image](https://cloud.githubusercontent.com/assets/25212/8290139/eb190094-18d5-11e5-98c0-a787c9c2f010.png)

I should be able to dismiss this by tapping anywhere outside of it. Is there a technical limitation here because we're iframing in the editor & preview?

cc @JordanTheriault

**Comment by humphd** [comment]
Correct, it's the iframe eating the click event.  However, our thought is to put a `div` over the entire body of the page that is transparent, and any click on that vs. the popup will dismiss.

**Comment by flukeout** [comment]
The old disappearing phantom underlay div trick! Classic

**Comment by humphd** [comment]
This is fixed.
