### ISSUE TITLE
Update express

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#600]
We are using an ancient version of express that has been deprecated. Initially, this was not a big problem but we recently ran into an issue: 
The built-in body parser in express (which no longer exists in later versions) enforces a limit on HTTP message body sizes which has no easy way of being overridden. Hence, uploading images > 100kb is practically impossible. Updating express will allow us to specify the limit on message body sizes.

**Comment by humphd** [comment]
Fixed.
