### ISSUE TITLE
Move filesystem operations to a worker

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#601]
Since filesystem operations are pretty intensive (including persisting them to `publish.webmaker.org`), we should move all that code into a web worker

**Comment by humphd** [comment]
I spent some time thinking about this a few weeks ago, and one issue we'll have to contend with is that not all browsers allow access to databases in worksers (Safari), and not all browsers allow access to WebSQL in a worker, see:

* https://developer.mozilla.org/en-US/docs/Web/API/Worker/Functions_and_classes_available_to_workers#APIs_available_in_workers

For sure we'll need to have a non-worker way, then add a runtime test to see if we can open a db in a worker, and if so, switch to the worker.  The design of this needs some thought, but it's likely worth it.

**Comment by humphd** [comment]
We're discussing this in https://github.com/filerjs/filer/issues/363.

**Comment by humphd** [comment]
If we do this, I'll re-open.  I don't think it's overly necessary, performance is great for fs operations as is.
