### ISSUE TITLE
Deal with file-less projects

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#602]
Consider a signed-in user who creates a project with default content and then removes all files in that project (this will be persisted). When the user reloads the project again, brackets will not be able to load anything to preview. Currently, if there are no files associated with a project, we throw. We need to determine a better way to deal with this situation.

**Comment by humphd** [comment]
I wonder if we should just have Bramble create a file (basic HTML) if it can't find something to open?

**Comment by JordanTheriault** [comment]
Yes, having a simple visual tutorial all inline in a default HTML file that appears when a project is empty would be very useful.

**Comment by humphd** [comment]
This is similar to the bug @flukeout filed about trying to remove the `index.html` file.  I'm not sure what the right action is here.

**Comment by gideonthomas** [comment]
Closing and continuing discussion [here](https://github.com/mozilla/thimble.webmaker.org/issues/702)
