### ISSUE TITLE
Determine what the default file will be opened when a user opens a project

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#603]
Which file will be chosen to be previewed when a user initially opens a project?

**Comment by gideonthomas** [comment]
Right now, we choose the last html file that was loaded in the project

**Comment by humphd** [comment]
I think this is already solved via the client API, which uses whatever was open last, or `index.html` in the project root.  Isn't that enough?

**Comment by gideonthomas** [comment]
so the `filePathToOpen` value that is passed when we call `Bramble.mount` is optional?

**Comment by humphd** [comment]
Correct.

**Comment by flukeout** [comment]
We also need to figure out what to open intially when a Project is remixed. Are we keeping track of the last-edited file on published projects? 

We also need UX to tell the Preview window which file to show when there are more than one HTML pages. I'll file a separate issue.

**Comment by humphd** [comment]
I'm going to close this, we can do more in follow-ups if we want.  For now we automatically track the file *you* had open last time, and re-open, or we look for your `index.html`.
