### ISSUE TITLE
Project title fixed or variable length. Where is the cut-off?

### ISSUE THREAD

**Issue by JordanTheriault** [mozilla/thimble.webmaker.org#605]
The project title editor could be fixed-length, variable length, or variable to a maximum length. 
We can set a maxLength on the input, which will need to be decided upon.

**Comment by humphd** [comment]
We have a bug about doing validation on that field, this can be part of that.

**Comment by Pomax** [comment]
as a user, I'm going to always run into your title length, no matter which "reasonable" value you settle on (especially if I live in a non-western country with lots of diacritics in my language). Having unbounded length, but having the UI discourage overly long titles by simply showing them as cut off at render length (not character length, but physical, visible length) encourages people to pick titles that fit, without interfering with their freedom to experiment.

**Comment by flukeout** [comment]
@Pomax has askethed and he has receiveth, for we haveth no maximum.
