### ISSUE TITLE
add an extensions panel so that we can pick what to use

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.webmaker.org#608]
It would be nice to see a section in the gear icon that lets you button-toggle each of the extensions that are under development or available already, so that there's no more need to load things "from a specific url", you just click the buttons, those values get localStorage tied to your login, and thimble/bramble can do an additional check for localStorage in the same place it already checks the URL right now

**Comment by JordanTheriault** [comment]
cc @flukeout

**Comment by humphd** [comment]
See also #513, #528
