### ISSUE TITLE
publish.svg is 578K compressed!?!

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#619]
Hilariously, the single largest file we ship right now is the publish.svg icon.  I'd like to suggest that we reduce this...

cc @JordanTheriault

**Comment by flukeout** [comment]
Insane! Sorry I didn't catch that earlier, here's a 2kb version:
https://dl.dropboxusercontent.com/u/109902/bramble/icons/share-green.svg

**Comment by flukeout** [comment]
Fixed and merged by @humphd
