### ISSUE TITLE
Housecleaning in the repo

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#622]
We have a few outstanding pull requests from ages past, and the `bramble` branch has largely supplanted `master`. We should go through the PRs and see if there's anything we can salvage, and do the necessary work to put old thimble on a non-master branch in favour of `bramble`. It would nice to see our changes reflected in the repo's stats!

I'm not sure what this means for any automagic deploy systems in place for the `master` branch, so we'll need a little guidance from @jbuck on this one.

@humphd What do you think?

**Comment by humphd** [comment]
I think we're past the need for this, closing.
