### ISSUE TITLE
add support for multipart uploads

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.webmaker.org#626]
Right now the upload limit is set to 3mb (in brackets) and 5mb (in express's body parser), but these are set up in a way that causes a network hiccup during upload to require resending the entire file. It would be a good idea to switch over to multipart uploads, so that a network hiccup won't require resending the entire file, but only the most recently failed part.

**Comment by humphd** [comment]
I'll take a shot at this.

**Comment by flukeout** [comment]
@humphd I don't think this is a P1 - seems more like an edge case fix. Maybe we can jump impose a smaller file size limit on uploads to get around this for the time being?

**Comment by humphd** [comment]
@flukeout code is all done already, we're in the process of getting it all landed.

We need this or uploads from the browser are 3x the size.

**Comment by sedge** [comment]
This was closed in #726 and #727
