### ISSUE TITLE
Need UX for telling Preview window which file to show.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#629]
Right now we're defaulting to the index.html file, but when a project has more than one HTML file, we don't have a way to tell Thimble which one to edit.

**Comment by humphd** [comment]
I don't know what you mean.  If you click on another html file, it will switch to that one in the preview.

**Comment by flukeout** [comment]
@humphd Yeah - i just wonder if that is good enough. I think it might be - I'm going to close this and see what testing shows when users have to switch between the file that is being previewed.
