### ISSUE TITLE
Strange rectangle shape next to selected file in file tray

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#635]
Whatever file is selected adds a black rectangle overtop of the editor near the line numbers...

![image](https://cloud.githubusercontent.com/assets/25212/8436937/9fc320d4-1f10-11e5-8629-8a5664134259.png)

**Comment by humphd** [comment]
This is an artifact of it needing to resize the selection rectangle.  In #637 I'm suggesting we stop highlighting at all, which would have the side effect of fixing this.

**Comment by humphd** [comment]
Was this while you were dragging, or after?  For sure there's a bug in Brackets on drag, which I've filed upstream, https://github.com/adobe/brackets/issues/11341.  But if it's happening just when you click on a file, that's another bug that I think we caused, by changing the size of the sidebar programmatically without also updating the size of the selector div.  I have a patch for Bramble that I'll do in addition.
