### ISSUE TITLE
Create testing activities to test Thimble

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#642]
*Note - this ticket is a work in progress.*

We need some ways to gather feedback about the work we're doing, specifically from two types of users:

* **Educators** who use, or might use Thimble as a teaching tool in classrooms
  * Does Thimble work well in a teaching environment
* **Learners** who want to improve their web authoring skills
  * Does Thimble facilitate learning

To do this, we can create some activities script that participants can follow along with while using the tool. Along the way and after, they can fill out a feedback form and leave their comments and impressions.

Here's our [Usertesting.com testing so far](https://www.usertesting.com/dashboard/folders/5830-thimble/studies) for reference. We'll need something similar.

**Observing in Person**
Whenever participants are willing, we can follow along over a screen share as they complete it to ask questions and observe.

**We'll Need**
* [ ] Two scripts or activities
  * [ ] Teacher focused
  * [ ] Learner focused
* [ ] A list of features & concepts that we're interested in
  * [ ] Editor-focused
* [ ] A good script in an easy to use format
  * Web page?
  * Wiki?
* [ ] A good way to ask questions and receive feedback (when remote testing)
  * [ ] Google forms?
* [ ] 5 potential participants from each group

**Discussion & Questions**
We need to identify what the main needs of educators and learners are in order to make sure that Thimble is fulfilling them. We've had some interviews with educators already (#577), but should compile a list of priorities and needs from both of these audiences.

cc @hannahkane @cassiemc

**Comment by hannahkane** [comment]
Would love to ask educators about how they'd evaluate/measure learning outcomes for students using Thimble. Will think on this more.

**Comment by jgmac1106** [comment]
Do mean make an assessment using Thimble or assessing Thimble? I could see
a possibility for doing both.

I would usually assess Thimble makes as a portfolio. In the past I created
a portfolio Template and asked students to add links back to previous makes
along with reflection of knowledge growth.

If we wanted to do some more formal performance assessment there could be a
simple  page that listed the requirements for different levels for example:

HTML One

Your goal is to make a website on any topic. It must include:
-At least two images. One image must be resized.
-At lteast two hyperlinks. One hyperlink must open in a new window.
-Use two different header tags.

CSS One
Your goal is to make a website on any topic. It must include:
-At least one image. This image must have a fixed size using hyperlinks.
-At least two hyperlinks. You must style the hyperlink using CSS
-Use two different header tags. Each header tag must have different inline
styling.

Now that I think about it we could develop a series of these quick
assessments at different levels for html, css, and js. We could also create
a portfolio template and portfolio assesement rubric/guidelines.

**Comment by hannahkane** [comment]
Thanks, @jgmac1106. I really like the idea of portfolio templates and assessment rubrics. Going to open up another ticket to address that specifically, since I'm realizing it's probably out of scope for the original ticket.

**Comment by hannahkane** [comment]
The content/features that I'm most curious to get feedback from educators on are:
 * new commenting UX (#573)
 * errors and code hints
 * the Teaching Kits that we need to create that will supplement the featured makes on the landing page

Since those aren't code complete yet, wondering if it's best to just do a very similar exercise as what's currently running on usertesting.com.

**Comment by hannahkane** [comment]
@flukeout - Is this ticket still needed?

**Comment by flukeout** [comment]
Yeah - let's keep it around, maybe backlog it if we have a backlog.
