### ISSUE TITLE
Tell the story of the new Thimble

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#643]
Notes from conversation with @humphd: 
 * create video or some other story format
 * generate enthusiasm and awareness for new features (could be part of release, or to create pre-release interest)
 * target audience: teachers
 * see this example: https://www.youtube.com/watch?v=Y7aEiVwBAdk
 * perhaps useful metaphor: "it's like we're taking a professional grade cooking tool that a chef would use in a restaurant, and saying to home cooks: 'here's a version of this...you can also make amazing food at home'"

/cc @humphd @cassiemc @flukeout @hpauljohnson @kevZawacki @ldecoursy @chrislarry33

**Comment by KevZawacki** [comment]
Re: video, you may want to take a peek at a storyboard we developed for the Webmaker video. It might offer some inspiration. https://etherpad.mozilla.org/webmaker-launch-video

It'd also be neat to promote the new Thimble via a Webmaker make, for some nice inter-product love.

I can definitely promote the new Thimble via Twitter.com/Mozilla, but our secret weapon will likely be Twitter.com/MozTeach. @amirad has cultivated a community of 13.5K very active teachers and learners.

**Comment by jgmac1106** [comment]
I would also suggest looking at the referral Adam Lofting posted earlier
that went to the webmaker channels. That my be a good place to send out the
links. Other hashtags include #edtechchat, #edchat, #clmooc,
#connectedlearning.

I would also do a #teachtheweb live Twitter  chat possibly and a
TeachTheWeb podcast.

IMO the new Thimble is really special. It is the first html/csss editor
thatis as robust as the others out there with the teaching tools built
right in. I can't wait to see it.

**Comment by ldecoursy** [comment]
So excited for the new Thimble! 

Might be good to tie outreach to a back-to-school theme, if the timing works out.

**Comment by hannahkane** [comment]
All great ideas!

Started a list of the new features at the bottom of this etherpad, for reference: https://etherpad.mozilla.org/thimbleroadmap

Wondering who should drive this? @hpauljohnson? @KevZawacki?  @ldecoursy?

**Comment by chrislarry33** [comment]
+1 to excitement on the new Thimble! A few thougts

- @mozteach should definitely be the definitive channel with @mozilla being secondary, @webmaker tertiary 

- Love the idea of  > 2 Min video that relaunches and highlights new features. Would love for it to be fun and funny, maybe a riff on 70s/80s New and Improved dish soap ads: https://www.youtube.com/watch?v=IeFo-ym1IDE

- We will/should definitely do a TeachTheWeb podacast also. This means a live conversation with twitter chat and then an edited and produced follow-up podcast. See here: http://mozilla.github.io/ttw-podcast/

**Comment by cassiemc** [comment]
Yay this is so awesome to see. I'd love to help with this and do some brainstorming with @flukeout, @hpauljohnson and team. We could also create some lighter-weight poster concepts (social share material).

**Comment by humphd** [comment]
Coming back from Canada Day to an inbox full of bugmail, this is by far the best one.  Thanks to all of you for your positive energy and ideas.  I've added some things to the List of New Features in https://etherpad.mozilla.org/thimbleroadmap and can work with anyone on getting more details.

**Comment by jgmac1106** [comment]
I just checked out https://bramble.mofostaging.net/ and pre-loading the
content with the mobile view and the most popular thimble project was
brilliant. I think you should go for the meme and selfie bandwagon.

Something to show the new features and tell the story of features, like a
close up of people from all over the world remixing the home screen. It
could go from group of kids, cut to close up of code>, selfie next to
finished "keep calm," rinse, repeat.

**Comment by hannahkane** [comment]
This feels like a dupe of https://github.com/MozillaFoundation/plan/issues/485, so I'm closing this one, though the conversation is good.
