### ISSUE TITLE
Create portfolio template and portfolio assessment rubric

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#644]
This is an idea to support educators who are using Thimble with their learners, and want to assess learning outcomes.

From @jgmac1106 in #642:

I would usually assess Thimble makes as a portfolio. In the past I created
a portfolio Template and asked students to add links back to previous makes
along with reflection of knowledge growth.

If we wanted to do some more formal performance assessment there could be a
simple page that listed the requirements for different levels for example:

HTML One

Your goal is to make a website on any topic. It must include:
-At least two images. One image must be resized.
-At lteast two hyperlinks. One hyperlink must open in a new window.
-Use two different header tags.

CSS One
Your goal is to make a website on any topic. It must include:
-At least one image. This image must have a fixed size using hyperlinks.
-At least two hyperlinks. You must style the hyperlink using CSS
-Use two different header tags. Each header tag must have different inline
styling.

Now that I think about it we could develop a series of these quick
assessments at different levels for html, css, and js. We could also create
a portfolio template and portfolio assesement rubric/guidelines.

**Comment by humphd** [comment]
Let's migrate this to the curriculum repo.

**Comment by flukeout** [comment]
Migrated to https://github.com/mozilla/webmaker-curriculum/issues/223 and closed.
