### ISSUE TITLE
Weird preview header styling observed in usertest

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#646]
Not sure what the deal is, will try to reproduce later

![image](https://cloud.githubusercontent.com/assets/25212/8484570/488aa8c0-20ad-11e5-867c-4686a9b6578f.png)

**Comment by humphd** [comment]
No one has ever been able to reproduce this, so I'm going to close.  Please re-file if you do in fact manage to get it to happen.
