### ISSUE TITLE
Add UI for changing line wrap setting 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/thimble.webmaker.org#648]
It'd be nice to turn word wrap on/off in the settings (alongside text size and theme).

**Comment by humphd** [comment]
We just need UI to trigger this now, the backend function is all in via https://github.com/humphd/brackets/pull/378

**Comment by humphd** [comment]
I'm morphing this to be about adding the UI.  To whoever implements this, we just need to call `bramble.enableWordWrap()`, `bramble.disableWordWrap()`, and `bramble.getWordWrap()` for state info.

**Comment by flukeout** [comment]
Here is some UI, we already have the little toggle built because we were using it in the Publish dialog to toggle the "Show in public gallery" setting.

![image](https://cloud.githubusercontent.com/assets/25212/8964243/57361c24-35d9-11e5-886f-ec3bdf953e5f.png)

**Comment by humphd** [comment]
@flukeout can I get you to do a PR that adds this select widget, and I'll hook up the backend.

**Comment by flukeout** [comment]
Will do.

**Comment by humphd** [comment]
Fix is happening in https://github.com/mozilla/thimble.webmaker.org/pull/1189

**Comment by flukeout** [comment]
Done
