### ISSUE TITLE
Usertesting feedback - Round 1

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#649]
I reviewed 3 usertesting.com sessions that asked users to perform some basic HTML & CSS editing tasks as well as interact with basic parts of the new UI.

**Videos**
* https://www.usertesting.com/videos/t-cDhAT6lavtU51v7rIRdg
* https://www.usertesting.com/videos/l2w6h9-v5N1aBa8MOqMYmg
* https://www.usertesting.com/videos/kHhr5NLSk7rxO8F9B6Kwzw

## Summary
Overall - everyone enjoyed using Thimble and completed the basics tasks easily. I've referenced some existing issues and added some new issues to account for what I've found. I'd like to refine the questions that I asked and run the test again with 5 users.

## What worked
* For the most part, users naturally right-clicked items in the file tray and were able to add and delete files without the additional UI (but I think we should still include it)
* Theme toggle was well liked, one user preferred light for day and dark for night, and one just straight up preferred the dark theme
* Users really liked the blue preview highlighting for HTML & CSS
* Most users identified the project name as the place to rename it
* Most people identified the Publish button as a way to share their content
* Switching between files was easy
* One user in particular *really* enjoyed the inline code hints when editing the CSS for the background-color
* All users were comfortable making changes to the code and liked seeing their changes reflected immediately in the preview
* Everyone found the mobile preview toggle easily and liked it

## What tripped people up
* *New Project* as a default project name made one user think that's how you start a new project
* Refresh icon bug made one user think that it was undo button since it reverted a change - #647 
* Refresh icon seemed useless since the preview auto-updated anyway, clicking on it has no visual effect
* File expand & collapse icon was mis-clicked a few times because it changes position when used - #630 
* The entire theme toggle should be clickable, not just the option that is inactive, lots of missed clicks when using this feature - #650
* Gear menu stuck around way too often, too hard to dismiss
* For the most part, users weren't able to find a way to resize the preview area by changing the column sizes, we should make this more clear - #651

## Feature requests
* To show different projects in the file tray so they could switch between them easily 
* Pop-up CSS editor when editing HTML
* PHP syntax highlighting
* A plus button for adding new files (already have UX for that)
* To see the caret blinking in the Preview window when editing HTML
* Should add tooltips to the editor and preview UI

## Answers to Post-test Questions
**What did you like most about using Thimble?**
* The light, easy to use platform. Easy to edit your workspace and has most if not all the useful tools necessary to make coding a bit better.
* I liked the ease of use for this HTML and CSS editor. It's pretty sweet.
* Ease of access and reference boxes
 
**What would you change about Thimble?**
* Maybe its colorpallet and the addition of readied PHP and Javascript codes. Like a sort of template to start working with. I understand how this is an editor. However thise could easily be a nice platform to write codes in.
* Overall I would change just a few things. Since the rename project is not available yet I would definitely like to see that implemented where on the Left Side I can select the Project and then Have it pull up the corresponding files that go with that project. I'd normally have multiple projects going on at one time so it'd definitely be useful to have that. Also I would probably share the page via Twitter or Facebook...
* Preview window

**Would you use Thimble in the future to learn and experiment with creating your own web pages by editing HTML & CSS?**
* Yes I would love to continue testing this platform. It would definitely a new alternative to what I want to use from the old fashioned notepad ++ and dreamweaver.
* I would definitely use Thimble as a possible editor in the future. I've worked with Dream Weaver in the past and this is in some ways easier.
* Yes I would!

**Would you recommend Thimble to friends or colleagues? Why or why not?**
* Yes! This shows a lot of potential and I'm sure the people I work with would appreciate parttaking in this kind of platform
* I would definitely recommend thimble as it's easy to use and would easily save friends and colleagues money :)
* Yes, very easy to use

## Test improvements
The test worked fairly well overall, but I need to be more specific in some questions about what I'm asking about. As well, I'd like to include some questions about more advanced features since the users we tested turned out to be fairly comfortable with HTML & CSS
* One of the questions had weird formatting that made people only read the first sentence and miss the task that asked them to expand inline HTML help via Command + K
* The question about changing the theme color and font size was interpreted as being asked to change those aspects of the Stay Calm poster, and not the editor itself
* "Look around the page and describe the parts" was interpreted as looking at the HTML code and interpreting that as opposed to the parts or the editor
* Add task related to Undo and Redo feature
* Add question about what kind of files and from what sources they'd like to add them
* Update question asking to change the background-color to a hex value to a color word instead, so participants don't have to copy and paste
* Add questions about more advanced features (inline CSS editor, inline colorpicker etc.)
* Include the crown image as a file in the starting project, and reference that file in the HTML
* Include another, similar image in project and ask users to change the poster image to this one

cc @humphd @hannahkane @cassiemc

**Comment by cassiemc** [comment]
Awesome feedback. Lots of small actionable things to change in the implementation and some solid learning about test questions themselves. Nice work @flukeout.

**Comment by JordanTheriault** [comment]
This was extremely interesting to read, good work. Time to get to work on some of those things to fix!

**Comment by JordanTheriault** [comment]
re: refresh icon
Perhaps moving the refresh to the right and adding "Refresh" text would make it's function more clear?

**Comment by cassiemc** [comment]
@JordanTheriault Good to see you here! =)

**Comment by hannahkane** [comment]
@flukeout - and can we close this one, too?
