### ISSUE TITLE
Make the entire editor theme toggle element clickable

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#650]
Right now you can only toggle a theme if you click the part of the toggle that is not currently selected. Users had trouble using the toggle because of this.

This guy...
![image](https://cloud.githubusercontent.com/assets/25212/8486739/c6b23b2e-20bb-11e5-8c9e-ffeb52291ec0.png)

**Comment by JordanTheriault** [comment]
This toggle is on my list to redo since this version of the toggle breaks on Safari. #657 fixes this for now.

**Comment by humphd** [comment]
Fixed.
