### ISSUE TITLE
Thimble instrumentation

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#653]
Let's start a discussion about what we'd like to measure in the new Thimble. We can add google analytics events to track a variety of actions. It would also be good if we had an easy way to run a report or get some basic details about project information too, listed at the bottom.

## User actions
Just some basic idea of various things that users are doing within the interface.

**File Tray**
* [ ] New file
  * [ ] Added via UI
  * [ ] Dragged to tray
* [ ] File deleted
* [ ] File renamed
* [ ] File tray expanded
* [ ] File tray collapsed

**Preview**
* [ ] Refresh icon clicked
* [ ] Desktop preview toggled
* [ ] Mobile preview toggled

**Project**
* [ ] Project renamed
* [ ] Project published

**Editor Settings**
* [ ] Editor settings opened
* [ ] Editor setting closed
* [ ] Theme toggled to dark
* [ ] Theme toggled to light
* [ ] Editor font size increased
* [ ] Editor font size decreased

**Editor**
* [ ] Undo clicked
* [ ] Redo clicked
* [ ] Editor resized & final width when finished 
* [ ] Use of advanced features
  * [ ] Incline colorpicker opened
  * [ ] Inline CSS editor opened
  * [ ] Inline documentation opened + what tag or rule

## Errors while editing
* [ ] Javascript error encountered + which error
* [ ] HTML syntax error encountered + which error
* [ ] CSS error encountered + which error

## Project details
It would be good to have a way to check in on what kinds of things people are making in thimble. Maybe an easy way to query for, or run a report that would tell us (for some given amount of time)...
* [ ] How many projects have been started / created
* [ ] How many projects have been published
* [ ] Average number of projects per user
* [ ] Which projects got remixed the most
* [ ] Average number of files per project
  * [ ] Which file types are the most common
* [ ] Average length of files per project, per type (JS, HTML, CSS)

@adamlofting @hannahkane @cassiemc @humphd

**Comment by hannahkane** [comment]
I would like to have metrics that can serve as proxies for learning. For example, I'd like to see if people's projects become more complex over time, where "more complex" might mean "more files." Would welcome other people's ideas about how to measure learning.

**Comment by cassiemc** [comment]
Nice, thanks for putting this together @flukeout! (FWIW I find the title of this issue a bit opaque. @flukeout is it to identify and/or implement the learning metrics?)

+1 on @hannahkane's thoughts, like getting more specific in regards to measuring learning. 

I like in particular these measures:
* length of files (presumably length would increase as users become more advanced)
* *finished* or *unfinished* files (if we identify projects that are abandoned but have been changed in a noticeable way, that could indicate the playground nature of thimble)

From Hannah's strategy document:
* the number of users who advance from “beginner” to “advanced” projects (defined by number of files) - demonstrates learning
* the number of lessons/project templates created - demonstrates educator engagement
* average # of times a make is remixed - helps us identify popular content; demonstrates adaptability of content

cc @thisandagain who probably has ideas here too.

**Comment by humphd** [comment]
I think we should split this bug into two: 1) things we can do GA events on in response to user actions; 2) data-mining activities on projects.

**Comment by cassiemc** [comment]
wfm.

**Comment by humphd** [comment]
How does MoFo want metrics done these days, is it still https://github.com/mozilla/webmaker-analytics or something else?

**Comment by cassiemc** [comment]
^^ @adamlofting @flukeout

**Comment by adamlofting** [comment]
Excuse the slow reply - I'm just back from holidays...

> I think we should split this bug into two: 1) things we can do GA events on in response to user actions; 2) data-mining activities on projects. 

I agree completely.

For `1)`, Luke's list of interactions to add event tracking to looks amazing. Let's keep this bug and file a new one for data-mining / learning analytics work.

> How does MoFo want metrics done these days, is it still https://github.com/mozilla/webmaker-analytics or something else?

Yes, that module still works great (thanks @humphd for writing V1!). 

However, if the project has been written in React, we have a new module here: https://github.com/adamlofting/react-ga/

**Comment by hannahkane** [comment]
Notes from meeting here: https://etherpad.mozilla.org/thimblemetrics

**Comment by flukeout** [comment]
@humphd Since this was written, we've added tutorials, so let's try some instrumentation around that. It might be a good starting point. We can track...

* Clicks on each of "Preview" and "Tutorial"

It would be cool to track time spent in the tutorial too. I don't have experience with that kind of tracking, but I imagine we could keep a 'timer' running and send the time spend in each mode as a separate event when you switch...  so if you toggle to Preview we could send two events..

* User switched to Preview
* Time spent in Tutorial

Thoughts?

**Comment by flukeout** [comment]
@humphd In addition to the above, it would be good to track if someone edited or created a tutorial file.
