### ISSUE TITLE
Design Thimble homepage

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#655]
Reduced scope from #555 

**Homepage content**
* Thimble logo
* Tagline & description of why it is awesome
* Short list of features
* Short intro video that shows off new features
* Links to remix 3 starting projects, each including:
  * Title
  * Description w/ learning outcomes or themes
  * Thumbnail
  * Link to accompanying
* Link to start a project from Scratch
* Footer
  * Link to Twitter
  * Link to Github
  * Link to teach.mozilla.org site
  * Mozilla logo + link

**Possible homepage projects**
* Meme maker - https://thimble.webmaker.org/project/60766/remix
* Movie poster: https://thimble.webmaker.org/project/60767/remix
* Keep calm - https://thimble.webmaker.org/project/21939/remix
* Comic strip - https://thimble.webmaker.org/project/3995/remix 

@hannahkane Is this what we agreed on?

**Comment by flukeout** [comment]
Draft UX

![image](https://cloud.githubusercontent.com/assets/25212/8489722/bcce5a58-20d3-11e5-91fc-c280a30aa886.png)

**Comment by flukeout** [comment]
An update with some more content.

![image](https://cloud.githubusercontent.com/assets/25212/8503061/fdf91a32-216d-11e5-8165-6f4caa66aa2d.png)

**Comment by flukeout** [comment]
Updated version...

Redpen - https://redpen.io/or0f6e3e18912fc780
Dropbox - https://dl.dropboxusercontent.com/u/109902/bramble/thimble-homepage-3.png

![image](https://cloud.githubusercontent.com/assets/25212/8505317/789f618c-2197-11e5-81aa-2b930774133a.png)

**Comment by hannahkane** [comment]
@flukeout - this is looking great!

Want to make sure @ldecoursy @chrislarry33 and @omnignorant have a change to weigh in as well.

**Comment by ldecoursy** [comment]
+1 So exciting! 

I'd just point that that I'm not sure we have "teaching kits" for each of these basic activities - these were some of the early self-serve activities with step-by-step instructions either in the code or in tutorials. 

Here's the tutorial for the poster project in case it's helpful: https://openmatt.makes.org/thimble/LTEzOTQwODE3OTI=/tutorial-for-make-a-movie-poster

**Comment by hannahkane** [comment]
@ldecoursy - those are the teaching kits I was going to work on this heartbeat, with input from you and @omnigorant and others. It feels important to have supplementary teaching materials for each of the starter makes we want to promote on the landing page.

**Comment by jgmac1106** [comment]
I have a teacher who was going to do some of the Web Lit Basics curriculum this summer. I could easily swap some of the activities for a new "teaching kit" from one of the three projects if you wanted to test any in the wild. 

She and the students would have little to no html/css experience. 

If you are still sticking with the back to school theme here are some ideas:
-Keep Calm and learn On(add a message about learning)
-Movie Poster-Summer read or favorite book
-Comic-Call to Action, an argumentative or political stance on an issue of the day.

**Comment by hannahkane** [comment]
@flukeout - do you think we can close this design ticket, and open up another for implementation (that ticket will be dependent on finishing up those teaching kits, but won't be dependent on design)?

**Comment by flukeout** [comment]
@hannahkane Sounds good, I'll do that and close this one.

**Comment by flukeout** [comment]
Closing, moved to #697 for implementation.

**Comment by hannahkane** [comment]
@flukeout - just realized we'll need a version of this page for authenticated users. Should include the user menu, so users can access their project list. Maybe we already have this and I just missed it.
