### ISSUE TITLE
Change file-switching event from mouse-up to mouse-down

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#656]
When you click a file in the file tray...

![image](https://cloud.githubusercontent.com/assets/25212/8490055/d03d0036-20d7-11e5-812c-4fb85d395b12.png)

It only starts to open when you release the mouse click.

Lets change it so that the file switches when you press down.

**Comment by humphd** [comment]
This will mess up their double-click vs. right-click vs. single-click vs. drag-event logic.  I don't think it's worth re-engineering their entire tree view for this, since you're going to eventually release the mouse button anyway--no one will be confused if it requires a full click/release.

**Comment by flukeout** [comment]
Okay - no biggie, closing!
