### ISSUE TITLE
Develop educator-specific content

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#660]
When looking at @flukeout's awesome work on the landing page (#655), I realized that we might be able to do more to specifically speak to educators who arrive at Thimble. (In addition to including teaching kits for each of the recommended starter makes).

At a minimum, I'd like to signal that Thimble is a useful tool for educators. Perhaps a "What educators are saying about Thimble" section? Or perhaps a link to a separate "For Educators" page that provides additional context and best practices, as well as the portfolio template and assessment rubric discussed in #644).

cc @chrislarry33 @ldecoursy @jgmac1106

**Comment by humphd** [comment]
I wonder if the recent effort to add more teaching kits to the homepage satisfies this?  Can we close now?

**Comment by hannahkane** [comment]
Yes, we can close. Similar themes will come up in future tickets, but this one is not very useful.
