### ISSUE TITLE
Hook up ID language preferences to thimble 

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#662]
This should be a simple fix. Make thimble load the locale specified in a user's id account preference.

**Comment by flukeout** [comment]
We don't actually localize anything in the UI right now though, do we, @humphd?
If that is correct, then we can deprioritize this until we have a localization strategy / plan?

**Comment by humphd** [comment]
Localization is filed in #475

**Comment by humphd** [comment]
Moving out of PreMozFest milestone.

**Comment by simonwex** [comment]
I'm closing this issue as the future for id.wm.o is uncertain and this ticket will likely be stale by the time we revisit it.
