### ISSUE TITLE
Markup highlighter doesn't resize when img source is changed.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#663]
The crown image, highlighted...
![image](https://cloud.githubusercontent.com/assets/25212/8552531/910abe94-2492-11e5-8c9a-438c8276853e.png)

When I change it to the Thimble logo, the highlight doesn't resize
![image](https://cloud.githubusercontent.com/assets/25212/8552584/de4c1072-2492-11e5-9cb2-04c79fd01c59.png)

**Comment by humphd** [comment]
This is deep inside Brackets.  I'm not sure how we fix it.

**Comment by flukeout** [comment]
It's not a huge deal - straight to the backlog with this one.

**Comment by humphd** [comment]
No idea how to fix this, it's deep in Brackets.  Closing.
