### ISSUE TITLE
Usertesting feedback - Round 2

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#669]
I reviewed 5 usertesting.com sessions that asked users to perform some basic HTML & CSS editing tasks as well as interact with basic parts of the new UI.

**Videos**
* https://www.usertesting.com/videos/7G01FCy9egMkyjajgbYYFg
* https://www.usertesting.com/videos/-5pqNnpTm2y3c3PdOBxJCQ
* https://www.usertesting.com/videos/O3ZeciLzTXur_PB245HufA
* https://www.usertesting.com/videos/hzx3CbnwanUwIij9V8v8Yg
* https://www.usertesting.com/videos/8Tux0p49gCoLD3kg30TqRA

## Summary
Overall - everyone enjoyed using Thimble and completed the basics tasks easily.

Main improvements we can make are...
* Clean up the right-click menu in the file tray - #674 
* Add a "new file" UI
* Make resizing the editor and preview windows more obvious - #651

People really love...
* Instant preview of code changes
* The inline colorpicker
  * Should we expose it better?
* Preview highlighting when clicking on markup & styles
* The dark theme
  * Make it the default?

## What worked
* Users liked the dropdown of colors when editing the "darkred" color value in CSS
* Users really liked the **inline colorpicker**, one of the most liked features
  * Should we expose this better by adding some UI to open it?
* Most users identified the project rename UI correctly, even though it doesn't work
* Most users liked the dark theme better - let's make it the default?
* Everyone loves **markup highlighting** for HTML & CSS
* Everyone understood and liked the mobile / desktop preview toggle
* Most people had no problems right-clicking into the file view to discover features.
* People enjoyed the inline HTML help, and one user in particular liked the CSS help because it was more informative and CSS has more options & complexity

## What tripped people up
* Need to add the UI for adding files. Most people ended up finding it via right-clicking eventually though.
* Need to clean up the file tray right-click menu actions, some of them are not necessary.
* Some users didn't see why there was a reload button if the preview was always already up to date
  * It also doesn't appear to actually do anything, we should figure this out
* Resizing the editor window was tricky, not everyone figure out how to adjust it
* The expand / collapse file tray icon moves after being clicked, need to keep it one place for easy opening & closing of the file view
* A few users mentioned wanting to use **PHP** and **Java** - do we need to communicate better that this is for client-side coding?
* User felt they were doing something wrong when re-clicking the same CSS rule, and the preview highlight wasn't strobing but only had the blue border
  * Should we strobe the highlight every click?
* User felt the expand file tray UI was a bit hard to understand when the file tray was closed, maybe this UI works well only because the files are opened by default. Maybe we should always keep it open by default?
* Inline help feature doesn't work on ```<img/>``` tag, but works on other elements
* Refresh icon seemed useless since work is already auto-udpated

## Feature requests
* Limit the minimum and maximum values of the text editor font size. It's possible to make them way too small or large to be useful.
* Collapse tags in the editor
* If one inline help is already open and you open another one, close the previous one
* Close already-opened inline colorpicker when opening a new one
* Toggle text-wrapping in the editor
  * Let's add it to the editor settings?
* Preview improvements (I think we should explore this more)
  * Tablet preview
  * Specific devices / dimensions preview
  * Full screen preview
* Go to a specific line in the code

## Bugs Observed
* Some strange visual bugs in the top of the editor when it's made really narrow (icons spilling into preview top bar area)
* Inline code hint feature doesn't work with ```<img/>``` tags

## Answers to Post-test Questions
**What did you like most about using Thimble?**
* I really like how there is no delay between the code and the preview panel. That, along with the highlighter makes editing really easy and natural. The colour picker and dropdowns are also really nice touches. I am not a web developer so often have to spend a fair bit of time when making websites googling css parameters but all of this means I should spend a lot more time looking at my code instead.
* The feature I like most about Thimble is the highligting of elements in the Preview pane whenever you select an element in the open file in the editor window.
* It was easy to use and user friendly
* It is a progrmer's dream. I can see the changes hat I would make live on the preview windown. The help options on the different tags is very helpful. The design is very user friendly and I felt a if I had used the website before becuase everything was logical and I did not need much time to figures things out.
* It's fast, easy, intuitive and I like the interface

**What would you change about Thimble?**
* I would like to know how it handles JavaScript. In terms of the file handling, it was not possible to work out how to move files into folders. If I was moving to Thimble, I would also need to know that I could upload files of code from my computer, rather than copying all the text.
* I'm not sure if there is anything to change right now. The application works great and I can see the potential. I also am not sure if this application is web only or if they will release a desktop version but I would like to have it as a desktop version.
* Maybe add more customization options to add sidebars and footers?
* Add a second preview window to compare changes to an original state that I choose. Add a full view button.
* I'd like to add a button to watch my work in full screen, or in another navigator tab, because if I'm doing a wider job, it would be very useful

**Would you use Thimble in the future to learn and experiment with creating your own web pages by editing HTML & CSS?**
* I would definitely use Thimble as my primary editor for creating web pages. I don't do much web development so it is really useful to have something this fully functional.
* I would use Thimble in the future. This application is especially useful in situations wherein you want to make changes to your website on the fly, say when there is a bug that needs to be addressed ASAP but you don't have your computer with you at that time. I would use Thimble as my goto application for creating and editing HTML and CSS files if it allows me the ability to connect to my own server.
* Yes, it is very much easier to use than many other softwares like Dreamweaver
* Definaley! I can't wait for it to become live 
* Yes I do! I like it a lot! I think that is faster than have separatelly the editor with the page

**Would you recommend Thimble to friends or colleagues? Why or why not?**
* Yes I would. It is a great way to dynamically edit. If it was possible to upload existing projects, the preview screen might actually be better than the standard Chrome dev tools for making changes to CSS.
* I would recommend Thimble to friends and colleagues because this application is very useful especially in emergency situations like you need to edit a bug in your website but you don't have your machine with you. I will use Thimble from time to time to see when the application has matured and is ready to be used for production ready websites.
* Yes, I have friends who like to code and I will definitely let them know about this!
* I do not have many friends who are into programming and honeslty it is really hard to convert established programmers from the platform they are accustomed to using
* Yes, because I find it easy, I also like the option for whatching the mobile version of my page. I'd like to test it with some acvanced code like other kind of styles (responsive), but in general I would recomend it to my frieds

## Test improvements
* The file tray question mentions two files, but there are now more - fix it up.

## Up Next 
I think the next step would be to continue testing once we have a few more features available. In particular, I'm curious about:
* The publishing process, and updating the published version with new changes
* Editing Javascript
* Code hints & errors for HTML, CSS & JS
* My projects UI
* UX of having the project auto-save and expectations around that

cc @humphd @hannahkane @cassiemc

**Comment by sedge** [comment]
This is great stuff. It's nice to see everyone's work getting recognition

**Comment by hannahkane** [comment]
Awesome work, @flukeout. I definitely think it would be useful to expose some of the shortcuts - e.g. for code hints and for the color picker. Maybe that stuff is exposed in "beginner mode," and hidden for advanced users?

**Comment by sedge** [comment]
@flukeout I also want to call out that some of the requested features (cold folding) are already there, living beneath the surface. If you translate those asks into issues, I think we could probably address some of them really quickly.

**Comment by flukeout** [comment]
@sedge Definitely - I'll go through this report early tomorrow and file appropriate issues. Or maybe we can look through in stand and discuss which ones we feel are important.

**Comment by hannahkane** [comment]
@flukeout - can we close this ticket? Will open a Round 3 ticket.

**Comment by sedge** [comment]
Make sure to let us know when staging must be fully functional so we can make sure we don't break it when you need it :)

**Comment by flukeout** [comment]
@hannahkane sounds good! I'm going to comb through Rd 1 & 2 and make sure all of the big findings are reflected in individual tickets.
