### ISSUE TITLE
Can't leave the projects page in FF

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#670]
Using Firefox 39, I can't seem to access my projects. When I go to https://bramble.mofostaging.net, it redirects to https://bramble.mofostaging.net/projects/. I seem to be authenticated, because it's showing me two project names in the "My Projects" view. But when I click on either project name, the browser spins, and then resolves to the current page.

Cannot reproduce on Chrome.

**Comment by gideonthomas** [comment]
"the browser spins, and then resolves to the current page"...i'm not sure I follow, can you maybe provide a screenshot or, I would be happy to follow up with you on vidyo if you prefer to screenshare this.

**Comment by hannahkane** [comment]
er....now I'm getting a 500 error when I try to view bramble.mofostaging.net on Firefox. Note: I can't actually view bramble.mofostaging.net because it automatically redirects to bramble.mofostaging.net/projects/, so the 500 error is on the projects page.

Feels like this is both browser-specific and perhaps specific to my account. Any suggestions for troubleshooting?

**Comment by gideonthomas** [comment]
Hmm...maybe try clearing your cookies....that way you'll need to sign in again, but it should fix stuff! I think the 500 is because we had to reset the database and firefox cached the `/projects` page

**Comment by hannahkane** [comment]
Hey @gideonthomas. 500 error seems to be resolved, but original bug persists.

Here's a screencast showing two things:
1) When I go to http://bramble.mofostaging.net/, it redirects to /projects
2) When I click on the project file, the page refreshes, but stays on the same page

http://g.recordit.co/FSluZZ0iwG.gif

**Comment by flukeout** [comment]
I'm also not able to access my actual project, just keep seeing the Project List

**Comment by gideonthomas** [comment]
@hannahkane so this seems to be a firefox caching issue...I'm gonna put up a quick fix for this in a bit but for resolving the real issue, refer to https://github.com/mozilla/thimble.webmaker.org/issues/641

**Comment by gideonthomas** [comment]
Actually, there doesn't seem to be an easy way to fix this because it happens on a redirect request :/

**Comment by gideonthomas** [comment]
@hannahkane if you want to actually edit your project on FF, you probably will need to keep the dev tools open while going through the STR

**Comment by hannahkane** [comment]
OK, thanks!

**Comment by hannahkane** [comment]
I think this is resolved, but would be good for @gideonthomas to confirm.

**Comment by sedge** [comment]
I can't get past the `/projects` page.

**Comment by sedge** [comment]
In fact, it won't go the the home page at all for me.

**Comment by gideonthomas** [comment]
@sedge even with dev tools open?

**Comment by sedge** [comment]
Yup.

**Comment by sedge** [comment]
@gideonthomas This is still an issue, and it's pretty bad. Did you have any clues about what causes this?

**Comment by sedge** [comment]
Fixed in @gideonthomas remix patch.
