### ISSUE TITLE
Project list opens after signing in, but shouldn't

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#673]
Steps to reproduce (in Chrome)
* Make sure you're not signed in
* Make some changes to the starting project
* Sign in
* You're presented with your project list
* You've lost the edits you made before you signed in

What should happen
* You return to the editor in the state you left it before you signed in

**Comment by gideonthomas** [comment]
Dupe of https://github.com/mozilla/thimble.webmaker.org/issues/627
Closing so that we can look at the chat history in that bug
