### ISSUE TITLE
Right click menu on file area shouldn't change colors depending on theme.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#676]
When right-clicking the file area while the dark theme is selected, the menu inverts colors:

![image](https://cloud.githubusercontent.com/assets/25212/8560429/6dd1d41e-24cc-11e5-8990-091229d67d74.png)

Let's keep the menu consistent. I think it's confusing that it changes colors and it's also hard to make out against the file tray. Let's keep the light theme version.

**Comment by gideonthomas** [comment]
Closing since the discussion has moved to https://github.com/mozilla/thimble.webmaker.org/issues/1100
