### ISSUE TITLE
Create "Intro to Thimble" video(s)

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#677]
**Latest Progress**
*  Video - https://www.youtube.com/watch?v=dBPqtz5rSwA
* Script - https://docs.google.com/document/d/1kfQGYv-k0lqksVdzaB4cOWDPte4GTObmUgxybgVDz9c/edit?usp=drive_web

**Blockers & To-dos**
* [x] Rig up the homepage with the remix link.. will this be too slow?
* [x] Create opening & closing screen.
* [x] Make sure the Command + K feature is baked in
* [x] Standardize the Green color between the homepage and video - #805 
* [x] What is the title of the video?
* [ ] Update script to address closing screen links

**Opening & Closing Screens**

![image](https://cloud.githubusercontent.com/assets/25212/9123452/856413a0-3c44-11e5-9670-e2998afd8011.png)

![image](https://cloud.githubusercontent.com/assets/25212/9124433/a7f2b758-3c4b-11e5-8e5a-c2088a89f9b9.png)

**Comment by hannahkane** [comment]
this ticket blocks #697

**Comment by hannahkane** [comment]
@flukeout - wondering if you have thoughts on the outline in the etherpad: https://etherpad.mozilla.org/thimblehowtovideo

**Comment by flukeout** [comment]
@hannahkane Video progress is happenin' here:
https://docs.google.com/document/d/1kfQGYv-k0lqksVdzaB4cOWDPte4GTObmUgxybgVDz9c/edit

Let me know what you think about the script.

**PS** - I've also done a very bad first draft of the recording just to see how long the script takes:
https://dl.dropboxusercontent.com/u/109902/bramble/rec.wav

**Comment by hannahkane** [comment]
Nice! Left some comments on the doc.

**Comment by flukeout** [comment]
Latest version of the video is here https://www.youtube.com/watch?v=HWqkEjnLh-U
Script - https://docs.google.com/document/d/1kfQGYv-k0lqksVdzaB4cOWDPte4GTObmUgxybgVDz9c/edit

**Blockers**
* Rig up the homepage with the remix link.. will this be too slow?
* Create an opening screen
* Make sure the Command + K feature is baked in

**Comment by hannahkane** [comment]
Purple. Alright! :)

One tiny edit - near the beginning when you're introducing the file tree, you mention all of the files except for tutorial.html. Could be a little confusing. Might be ameliorated just by saying, "This last file, tutorial.html, is special, and we'll get back to it in a little bit." Or something like that.

Like the addition of the "Others can remix your project" at the end (at least, I think that's new).

I'd say #792 is a blocker, too.

**Comment by flukeout** [comment]
+1 on mentioning the tutorial file.

**Comment by flukeout** [comment]
@hannahkane Here is the opening and closing screen of the video. The links on the closing screen will have annotations in youtube so you can click them. Thoughts?

**Opening**

![image](https://cloud.githubusercontent.com/assets/25212/9123452/856413a0-3c44-11e5-9670-e2998afd8011.png)

**Closing**

![image](https://cloud.githubusercontent.com/assets/25212/9123458/8de54c06-3c44-11e5-87e5-d3d762201955.png)

**Comment by hannahkane** [comment]
Nice. Seems like a link to the Thimble homepage would be important to include.

**Comment by flukeout** [comment]
Updated closing...
![image](https://cloud.githubusercontent.com/assets/25212/9124433/a7f2b758-3c4b-11e5-8e5a-c2088a89f9b9.png)

**Comment by flukeout** [comment]
@hannahkane Thoughts on the video title in you tube? 

* "Get to know Thimble"
* "Introduction to Thimble"
* "Welcome to Thimble"

...or something more strategic? 
* "Thimble - an online code editor!"
* etc..

**Comment by hannahkane** [comment]
My vote would be Welcome to Thimble. Sounds so...welcoming. :)

**Comment by ldecoursy** [comment]
+1

**Comment by flukeout** [comment]
+1
