### ISSUE TITLE
Ye Olde Thimble loads with broken styling and no sign-in UI

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#678]
Steps to reproduce
* Load thimble.webmaker.org a few times
* About half of the time, it loads looking like this...

![image](https://cloud.githubusercontent.com/assets/25212/8600884/4b341ee2-261d-11e5-9bac-d4ecb56e79ba.png)

cc @cadecairos

**Comment by humphd** [comment]
Last time this happened it was a failed build/missing CSS file.  Someone should retrigger the build and see if that fixes.  CC @jbuck, @ScottDowne

**Comment by cadecairos** [comment]
I'm pretty sure one of the two production instances has a bad CSS file, I just don't know which one. I don't have the right key to ssh into the instances though. I'll try to contact jp

**Comment by cadecairos** [comment]
Alright, I took a look at the two instances running thimble and one indeed had a different userbar-overrides.css file than the other.

I played (this song)[https://www.youtube.com/watch?v=6qFrY4VcbMU] as per @jdotpz's instructions and put that instance out of its misery. A new instance was brought in, and I confirmed it had the complete userbar-overrides.css file.

Shall we close this?

**Comment by jgmac1106** [comment]
It is still happening. Hopefully one of you [Ninjas](https://www.youtube.com/watch?v=NGsbCcoSegI) can figure it out.

<img src="http://goo.gl/MGjohY">

**Comment by cadecairos** [comment]
I put yet another instance out of its misery, and watched to make sure it loaded up properly and built the CSS file, but I can't be sure if it will disappear again.

**Comment by jgmac1106** [comment]
Thanks. I tried loading a bunch of times and it worked.

**Comment by cadecairos** [comment]
It's doing it again. thimble is cursed.

**Comment by notklaatu** [comment]
This is also occurring for me on Slackware and Linux Mint, Firefox versions 31.7 and 39 respectively.

**Comment by jbuck** [comment]
Okay, it *should* be cleared up now. Are you still seeing it @notklaatu?

**Comment by notklaatu** [comment]
@jbuck that did it! Cheers, man, that saved our Maker Party. As far as i'm concerned, this bug is closed (aside from not having opened it ;-) )
