### ISSUE TITLE
Should be able to click Enter to create a new project

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#679]
I have to click the "Submit" button to create a new project; I would expect to just be able to hit Enter.

Also, the field for the project name exceeds the length of the lightbox.

![screen shot 2015-07-09 at 2 44 13 pm](https://cloud.githubusercontent.com/assets/8389648/8607613/08c97742-2649-11e5-94dd-da901af249fe.png)

**Comment by gideonthomas** [comment]
After https://github.com/mozilla/thimble.webmaker.org/pull/709 lands, this will no longer be an issue

**Comment by gideonthomas** [comment]
cab767b6d4d8cdb7358702e55cb4a1c8cbd72e38 fixes this
