### ISSUE TITLE
Publishing doesn't publish the same version of the project as in the editor & preview window

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#681]
Steps to reproduce
* Start a new project
* Make a small text change to the Carry On poster
* Immediately hit Publish
* Follow the link
* The changes you made are not reflected in the published version

Why? Probably because we don't auto-save except every 30 seconds and when you change files in the editor. 

Solution: Fire the auto-save call right before publishing to make sure we get the latest changes.

**Comment by sedge** [comment]
@flukeout Can you confirm if this is still happening?

**Comment by flukeout** [comment]
This has been resolved - closing.
