### ISSUE TITLE
Design & implement a 404 page to replace current 403 page

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#682]
When you attempt to load a project that has been unpblished, you see...

![image](https://cloud.githubusercontent.com/assets/25212/8607860/d28d08cc-264a-11e5-9169-52d97cd44312.png)

Let's redirect all 403 requests to a new 404 page.

**Basic 404 Page**
* Standard header & footer from homepage
* Page not found Messaging
* CTA
  * Create a new project
  * Remix 3 projects

**Assets**
Latest work - http://flukeout.github.io/thimble-home/404.html
Repo - https://github.com/flukeout/thimble-home

cc @hannahkane

**Comment by gideonthomas** [comment]
https://github.com/mozilla/thimble.webmaker.org/issues/688#issuecomment-120459880

**Comment by flukeout** [comment]
Some benchmarks...

**Codepen**

![image](https://cloud.githubusercontent.com/assets/25212/8626871/05388be6-26fc-11e5-874e-797652b2d5ab.png)

**Tumblr**

![image](https://cloud.githubusercontent.com/assets/25212/8626889/1bdc5aee-26fc-11e5-91e0-73365c7cd273.png)

**JS Fiddle**

![image](https://cloud.githubusercontent.com/assets/25212/8626916/427f4e22-26fc-11e5-8239-cb9cf24d29f3.png)

**Github**

![image](https://cloud.githubusercontent.com/assets/25212/8626939/695ccaec-26fc-11e5-90b1-0b4357253720.png)

**Instagram**

![image](https://cloud.githubusercontent.com/assets/25212/8626965/84e97fd0-26fc-11e5-9f29-7915c67d4bb3.png)

**PicCollage**

![image](https://cloud.githubusercontent.com/assets/25212/8626975/962ad0c8-26fc-11e5-9c17-b7cd0a1bc85a.png)

**Twitter**

![image](https://cloud.githubusercontent.com/assets/25212/8627046/1f0d8822-26fd-11e5-8599-7f4f813e22f7.png)

**Comment by hannahkane** [comment]
A bit confused. Will this be a normal 404 page (comment in #688 implies we can't distinguish)?

I like the mockup in the first comment of this ticket.

**Comment by flukeout** [comment]
@hannahkane I think we're going to go with just one "Not Found" page, for both pages that were never there and unpublished projects. I think maybe in the future it's worth looking into wether we want different types of 'not found' pages depending on the context.

**Comment by hannahkane** [comment]
Cool. Then I think what you have at the top of this ticket works really well.

**Comment by flukeout** [comment]
:+1:

**Comment by flukeout** [comment]
@sedge the 404.html page in https://github.com/flukeout/thimble-home is what you need. Let me know if you have any questions.

**Comment by sedge** [comment]
Perfect ^.^

The styles and images can be served from thimble.wm.o, but the actual source code will live in the S3 bucket.

**Comment by sedge** [comment]
This has been implemented. @flukeout [Try this](https://d157rqmxrxj6ey.cloudfront.net/sedge/10345) and we can close if it works
