### ISSUE TITLE
Publish doesn't work if the project title contains a space

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#684]
Steps to reproduce:
 * Click Publish in header
 * Fill in description
 * Click Publish in lightbox
 * Transitions to "Publishing..." state, but then resolves to previous "Publish" state and url doesn't appear

I cleared cache and cookies and tried again - same result. I tried in Firefox and Chrome.

Screencast: http://recordit.co/O0k9LLjvEw

**Comment by sedge** [comment]
If you could redo the screencast with the developer console open, that would be really helpful in tracking this down!

In FF get your project to just before publishing, then: 

**Click the hamburger:**
<img width="156" alt="screen shot 2015-07-09 at 9 17 40 pm" src="https://cloud.githubusercontent.com/assets/1616860/8610447/20224400-2680-11e5-9582-5cc8593feaa4.png">

**Click "Developer":**
<img width="295" alt="screen shot 2015-07-09 at 9 17 55 pm" src="https://cloud.githubusercontent.com/assets/1616860/8610451/2b73b97e-2680-11e5-9f35-d36e3237a294.png">

**Click "Web Console":**
<img width="282" alt="screen shot 2015-07-09 at 9 18 02 pm" src="https://cloud.githubusercontent.com/assets/1616860/8610452/2b75afa4-2680-11e5-87ca-870d040eb8aa.png">

**Make sure '*Net*' '*CSS*' '*JS*' '*Security*' and '*Logging*' are all selected:**
<img width="1437" alt="screen shot 2015-07-09 at 9 18 20 pm" src="https://cloud.githubusercontent.com/assets/1616860/8610445/1a5e84b6-2680-11e5-9321-5805b8937c11.png">

And finally take the screencast.

**Comment by hannahkane** [comment]
Here you go: http://recordit.co/2YAcKH5cIK

**Comment by sedge** [comment]
Thanks! Unfortunately that wasn't as helpful as I'd hoped :( 

Are you still encountering this issue?

**Comment by sedge** [comment]
We've identified that this occurs when a project has a space in the name. A fix is incoming.

**Comment by gideonthomas** [comment]
@hannahkane can you confirm if this is still an issue?

**Comment by flukeout** [comment]
@gideonthomas I can publish projects that have spaces in their names now!
