### ISSUE TITLE
Published project is not found after unpublishing and re-publishing it

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#688]
Steps to reproduce
* Start a new project
* Publish it
* Follow the link, it's there
* Unpublish it
* Refresh the old link, it's gone
* Publish it again
* Click the link 
* The project 404s

For reference, here's a url after re-publishing an unpublished project...
![image](https://cloud.githubusercontent.com/assets/25212/8623808/6bcdcd8a-26e8-11e5-95d0-260775b3b6ca.png)

But it doesn't show a published project: http://bramble-staging.s3-website-us-east-1.amazonaws.com/7/Boop

**Comment by sedge** [comment]
@flukeout When I visit the link you provided I see the published project. @gideonthomas I wonder if we need to force the cache clear?

**Comment by gideonthomas** [comment]
This is a browser cache issue! We probably need S3 to send a header to disable cache.
@sedge any thoughts?

**Comment by sedge** [comment]
After discussing with @cadecairos I'm going to upload a custom 404.html page to the s3 bucket itself. It just means we have to tolerate the 403 ugliness until the error page is complete.

**Comment by flukeout** [comment]
@sedge Is there a way to distinguish between projects that have been unpublished / deleted and regular old 404 pages?

**Comment by sedge** [comment]
Not easily :(

**Comment by sedge** [comment]
@flukeout Can you confirm if this is still a problem? I can no longer reproduce this error.

**Comment by flukeout** [comment]
@sedge No longer a prob.
