### ISSUE TITLE
Updating a published project causes it to revert to starting state

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#689]
Steps to reproduce
* Create a new project
* Make a change to the Stay Calm poster
* Make sure it is saved and Publish it
* Published version reflects changes
* Make another change to the poster, make sure it auto-saves the change
* Updated the published version
* Follow the link

The poster shows as the original version before the first publish even happened.

**Comment by sedge** [comment]
@flukeout Can you confirm if this is still a problem? I can no longer reproduce this error.

**Comment by flukeout** [comment]
@sedge Still a problem for me right now.

**Comment by flukeout** [comment]
@sedge And, now it seems fixed - I'll keep batting it around.

**Comment by flukeout** [comment]
@sedge It's happening to me right now - but not always. I'm trying to figure out how to reproduce it reliably.

For reference, this project is currently 'out of sync' - the saved version is different from the currently published version at http://bramble-staging.s3-website-us-east-1.amazonaws.com/7/Boingo/

I'll leave this one alone in case it helps you investigate the discrepancy.

**Comment by sedge** [comment]
@flukeout To confirm: If you follow the STR now, sometimes it displays this behaviour and sometimes it doesn't? Or are old projects the only ones that break like this?

**Comment by flukeout** [comment]
Just to follow up on our video and convo, this happens seemingly at random with new projects, about 20% of the time or less. Let's keep it open for now so that we don't re-file it later.

**Comment by sedge** [comment]
The cause of this issue is the thimble server "creating" a second `index.html` file object on publish.wm.o instead of updating the old one. When Thimble tries to publish a project to S3 after this, publish.wm.o sometimes confuses the original (default) `index.html` file with the user-updated one. 

@gideonthomas Thinks his remix patch will address these issues.

**Comment by sedge** [comment]
@flukeout Now that remix has landed, can you see if you can reproduce this?

**Comment by flukeout** [comment]
@sedge will try

**Comment by flukeout** [comment]
@sedge seems like it's all good now! Not running into this anymore! :pineapple:
