### ISSUE TITLE
New Projects item in the User dropdown menu doesn't work and has a typo

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#690]
![image](https://cloud.githubusercontent.com/assets/25212/8626283/d86c0d66-26f8-11e5-8a90-0246cedf8c15.png)

* Change "New Projects" to "New Project"
* If you tap that option, you should end up in the Editor, starting a new project

**Note** - currently we seem to require a project name as part of creating a new project, so I've filed #692 to address this.

**Comment by hannahkane** [comment]
If we don't do this for MVP, we should at a minimum remove this from the menu.
