### ISSUE TITLE
Creating a new project shouldn't require a project name up front.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#692]
Currently, if you attempt to create a project (from the My Projects view), you're prompted to specify a project name, like this...

![image](https://cloud.githubusercontent.com/assets/25212/8626377/9c1ce62c-26f9-11e5-8bc8-8918ae4f00d2.png)

Since (according to @sedge - plz confirm) we don't need unique project names, let's default the new project name to "Untitled Project" and just, drop the user off in the editor right away.

Fixing this will unblock #690

**Comment by sedge** [comment]
Currently there is no restriction on a projects name. Duplicates are allowed for a single user and between users.

**Comment by flukeout** [comment]
:+1:

**Comment by gideonthomas** [comment]
Actually, not exactly...on thimble itself, we do not allow you to create a new project with a name that already exists, and in terms of publishing, if you have two projects with the same name and you publish them, one will overwrite the other and you'll end up with a weird amalgamation of the two projects.

**Comment by sedge** [comment]
@flukeout Sorry! I was talking from the perspective of the `publish.wm.o` server. @gideonthomas is totally right - thimble has a hard restriction of no duplicates per user.

**Comment by gideonthomas** [comment]
We should revisit this when we start implementing the anon to signed-in transition workflow

**Comment by gideonthomas** [comment]
https://github.com/mozilla/thimble.webmaker.org/pull/709 should fix this

**Comment by gideonthomas** [comment]
cab767b6d4d8cdb7358702e55cb4a1c8cbd72e38 fixes this
