### ISSUE TITLE
Add links to TOS and Privacy Policy to Thimble footer

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#696]
When Thimble users create a Webmaker account (required for publishing), they agree to the Terms of Service. We should make this easily accessible directly from the Thimble homepage.

TOS is here: https://beta.webmaker.org/#/legal 

We should also link to the Privacy policy here: https://www.mozilla.org/en-US/privacy/websites/

**Comment by flukeout** [comment]
@hannahkane Is it okay if it's just available from the Thimble homepage?

**Comment by hannahkane** [comment]
yes. Will update ticket description.

**Comment by flukeout** [comment]
@hannahkane Do we also have a privacy policy we need to link to?

**Comment by hannahkane** [comment]
Good point. Yes, we should link to https://www.mozilla.org/en-US/privacy/websites/. Just updated first comment.

**Comment by hannahkane** [comment]
Adding this to the Pre MozFest milestone, because we ought to do it soon. @flukeout to determine how to include these links.

**Comment by humphd** [comment]
@flukeout assigned this one to you.
