### ISSUE TITLE
[Implemenatation] Thimble homepage

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#697]
**Homepage content**
* Thimble logo
* Tagline & description of why it is awesome
* Short list of features
* Short intro video that shows off new features
* Links to remix 3 starting projects, each including:
    * Movie poster: https://thimble.webmaker.org/project/60767/remix
    * Keep calm - https://thimble.webmaker.org/project/21939/remix
    * Comic strip - https://thimble.webmaker.org/project/3995/remix 
  * Title
  * Description w/ learning outcomes or themes
  * Thumbnail
  * Link to accompanying
* Link to start a project from Scratch
* Footer
  * Link to Twitter
  * Link to Github
  * Link to teach.mozilla.org site
  * Mozilla logo + link

Latest redpen - https://redpen.io/xcd2bfcadef6878b3c
Latest work - http://flukeout.github.io/thimble-home/
Repo - https://github.com/flukeout/thimble-home

**Blocked by**
* Video
* Teaching Kits

cc @hannahkane

**Comment by hannahkane** [comment]
OK, the homepage makes and teaching kits are here:
 * https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/26/ [Keep Calm make]
 * https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/28/ [Keep Calm teaching kit]
 * https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/40/ [Comic Strip make]
 * https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/32/ [Comic Strip teaching kit]
 * https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/61/ [Postcard make] 
 * https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/62/ [Postcard teaching kit]

We'll probably continue to polish these, but should no longer be a blocker to building the homepage

/cc @flukeout

**Comment by flukeout** [comment]
Thanks @hannahkane - I'll update the homepage with this content.

**Comment by flukeout** [comment]
@hannahkane What about the bulleted copy in these sections...

![image](https://cloud.githubusercontent.com/assets/25212/9452384/be71dea2-4a68-11e5-83ef-4601c1b7ddd5.png)

**Comment by hannahkane** [comment]
Keep Calm:
* How to design a poster
* Editing HTML content
* Editing CSS styles

Postcard:
* Editing HTML content
* Editing CSS styles
* Creating an interactive element with JavaScript

Comic Strip:
 * Editing HTML content
 * Finding Creative Commons-licensed images
 * Editing CSS styles

**Comment by flukeout** [comment]
Shoot, there is also the copy underneath the thumbnail, as seen here. 

![image](https://cloud.githubusercontent.com/assets/25212/9453054/a1932008-4a6c-11e5-8866-c9adef5e8be2.png)

**Note** - I added the bulleted copy you listed above already.

**Comment by hannahkane** [comment]
Change the design of this poster to make it your own

Add your own content to this interactive postcard 

Create your very own version of this comic strip

**Comment by flukeout** [comment]
@hannahkane I've made all the requested changes, can you please QA http://flukeout.github.io/thimble-home/

**Comment by hannahkane** [comment]
Everything looks good except the "Remix this project" button on the comic strip is going to the wrong make.

Also, on my browser, the title of that make wrapping to a second line, pushing the entire section down. Can we just call it "Current Events Comic"?

**Comment by flukeout** [comment]
Updated.

**Comment by hannahkane** [comment]
woohoo! +1

**Comment by chrislarry33** [comment]
Looking AWSM!

**Comment by flukeout** [comment]
@humphd This is good to go...

Latest version - http://flukeout.github.io/thimble-home/
Repo - https://github.com/flukeout/thimble-home

**Comment by flukeout** [comment]
Actually - let me make sure the 404 page is good to go before we implement.

**Comment by humphd** [comment]
@sedge is going to land what @flukeout has done so far in the Thimble node server, and serve it from the `/` route, updating the current `/` route to be `/edtitor`.

We still need to have @flukeout add a dropdown to the homepage for the authenticated state.

@hannahkane is going to update the FAQ to indicate how to access the old Thimble/makes.

**Comment by sedge** [comment]
I'll be adding the 404 page too, for #682
