### ISSUE TITLE
Project doesn't know it's been changed when I want to update the published version.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#699]
Steps to reproduce
* Start a new project
* Make some changes
* Publish it
* Make another change
* Before the auto-save has kicked in, press the Publish button again
* The publish dialog doesn't realize your project is different than the published version, and doesn't give you the option to Update Published

This is just a problem with the auto-save not kicking in before I hit publish - so we need some kind of workaround.
* Maybe we fire the auto-save when I open the publish dialog to check for changes then
* Maybe we change the UI in the publish dialog as soon as the project is published initially

cc @sedge

**Comment by sedge** [comment]
Let's see...

* Maybe we fire the auto-save when I open the publish dialog to check for changes then

Hmm. The auto-save takes time, so there's no guarantee that it will be done before the user clicks through the publish dialog flow. I prefer your second solution.

Assuming all `Publish` buttons change to `Republish` as soon as the editor detects that it's working with a published project, as a user I would read that as "If I click republish, whatever is in my editor will overwrite what's already published." This is also exactly what happens now that @gideonthomas's save-before-publishing patch has landed.

Also, what do you think about adding a confirmation dialog if "Republish" is clicked? It could warn that the action will overwrite what's already published with what the user has now.

**Comment by sedge** [comment]
@flukeout Where have you landed with this UX wise? This isn't a technical problem, since thimble will save your changes for you if you click 'Publish'.

**Comment by flukeout** [comment]
@sedge I think the right solution would be to attempt an auto-save as soon as the Publish dialog is open, and update the UI if and when the auto-save determines that there are changes to be published.

**Comment by sedge** [comment]
Okay, sounds good! I'll get on it.

**Comment by sedge** [comment]
CLosed in https://github.com/mozilla/thimble.webmaker.org/pull/747
