### ISSUE TITLE
Ensure file deletions persist to publish.wm.o

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#700]
I deleted the crown.svg image from my project...

![image](https://cloud.githubusercontent.com/assets/25212/8704826/77bf5d0c-2ada-11e5-896c-e6fa1594a4a2.png)

then saved and published my project, it still exists in the published version...

![image](https://cloud.githubusercontent.com/assets/25212/8704844/89e9fd7a-2ada-11e5-8bb2-ebbabc5c0b50.png)

It shouldn't.

cc @sedge

**Comment by sedge** [comment]
This root of this is in https://github.com/mozilla/publish.webmaker.org/issues/110

**Comment by gideonthomas** [comment]
https://github.com/mozilla/publish.webmaker.org/pull/114 should fix this

**Comment by humphd** [comment]
Can we confirm that these have fixed it?

**Comment by sedge** [comment]
The `publish.wm.o` side of this has been resolved, and this works as expect most of the time.

We're noticing that deleting a file doesn't always persist to publish, with thimble returning a `400: No file representation found for /file.name` on the delete call.

**Comment by humphd** [comment]
Can you either morph this bug into being about that delete issue, close this, or file a new one?

**Comment by sedge** [comment]
When #733 lands we should retest.

**Comment by sedge** [comment]
@flukeout Unblocked! Is this still a problem?

**Comment by flukeout** [comment]
@sedge Looks fixed! Deleted files are no longer available in published projects. :apple:
