### ISSUE TITLE
Files that aren't found in a project should throw a 404 not a 403

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#701]
This file doens't exist and resolves to a 403, but should throw a 404...
http://bramble-staging.s3-website-us-east-1.amazonaws.com/7/Zinger/nope.html

**Comment by sedge** [comment]
This isn't a problem we can solve, since this is the heroku default. We can mask the error by redirecting to a 404 page though!

**Comment by flukeout** [comment]
Yeah, let's redirect to a 404 page. I'll create another issue for a 404 page and reference this over there.
