### ISSUE TITLE
Deleted HTML file continues to show in preview

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#702]
Steps to reproduce
* Start a new project
* Delete the index.html file
* It should disappear from the preview window
* Hit the refresh icon on the preview 
* It should **definitely** disappear now
* It's still there

**Comment by gideonthomas** [comment]
@humphd might be able to explain this a bit better! But I think it's because bramble always needs an html file to preview.

**Comment by flukeout** [comment]
Maybe we can add an invisible file for it to point to when it has nothing else.

**Comment by humphd** [comment]
The problem here is that the live dev preview, if we want it to automatically show preview content, needs to have a valid HTML file to render.  With a bunch of work I could support the case that there is no HTML file at all, but is this really necessary/useful? What's the use case for removing the main `index.html` file?  It feels like an edge case to me.

**Comment by sedge** [comment]
@flukeout I'm with @humphd on this one. How important is this?

**Comment by flukeout** [comment]
Not very - we can de-prioritize from MVP and throw it into a backlog.

**Comment by humphd** [comment]
Not sure if this is related or not, but I tried deleting some files tonight, and I saw:

```
[Bramble] Failed to send request to delete the file to the server with:  Bad Request(anonymous function) @ filesystem-sync.js:87n.Callbacks.j @ index.js:2n.Callbacks.k.fireWith @ index.js:2x @ index.js:4n.ajaxTransport.k.cors.a.crossDomain.send.b
```

Which is pointing at:

```js
  function pushFileDelete(url, csrfToken, fs, path) {
    var context = this;
    var error;
    var request = $.ajax({
      contentType: "application/json",
      headers: {
        "X-Csrf-Token": csrfToken
      },
      type: "PUT",
      url: url,
      data: JSON.stringify({
        path: path,
        dateUpdated: (new Date()).toISOString()
      })
    });
    request.done(function() {
      if(request.status !== 200) {
        error = request.body;
        console.error("[Bramble] Server did not persist ", path, ". Server responded with status ", request.status);
      }
    });
    request.fail(function(jqXHR, status, err) {
      error = err;
      console.error("[Bramble] Failed to send request to delete the file to the server with: ", err); <--------- here
    });
```

**Comment by humphd** [comment]
Related to #1101

**Comment by humphd** [comment]
We're discussing adding the ability to show dir listings in #1203.  I'm going to dupe this on that.
