### ISSUE TITLE
User testing Round 3 (Publish flow)

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#704]
Pending resolution of critical publishing bugs

**Comment by flukeout** [comment]
A draft of some of the new features to test & questions to ask...

* Renaming a project
  * Is it weird that you can have multiple projects with the same name?
* Publishing a project
  * Ask about the type of URL users would like here
* Unpublishing a project
  * What do you expect to see at the URL that the project used to be at?
* Updating published project
* Auto-saving
  * Are you aware that it is auto-saving?
  * If the project is already published, do you think the auto-save will affect the published project?
  * Do you always want your changes saved?

**Comment by flukeout** [comment]
Started a draft plan here:
https://docs.google.com/document/d/1UGASEU5IpYxEyOdhEywM-EhLH3ttyDg9u-ydsdVPbhw/edit

I'm assuming we won't have a homepage - and if we do, we can always run other tests with it later.

**Comment by hannahkane** [comment]
Added some comments. Looks good!

**Comment by flukeout** [comment]
I've updated the testing plan, once all of the issues listed in the blockers section are addressed, we can go ahead an launch.

[Test plan](https://docs.google.com/document/d/1UGASEU5IpYxEyOdhEywM-EhLH3ttyDg9u-ydsdVPbhw/edit) & [Testing Blockers](https://github.com/mozilla/thimble.webmaker.org/issues?q=is%3Aopen+is%3Aissue+label%3Atesting-blocker)
