### ISSUE TITLE
I'm able to create a lot of projects at once

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#706]
If I click the submit button on the new project popup a lot of times I'm able to create a project for each time I do so all in one go...

![image](https://cloud.githubusercontent.com/assets/25212/8735117/44970256-2bc3-11e5-9c3a-654e8076484b.png)

This will go away when we change the UX of creating a project, but I'll lave it here until it does.

**Comment by gideonthomas** [comment]
https://github.com/mozilla/thimble.webmaker.org/pull/709 should fix this

**Comment by gideonthomas** [comment]
cab767b6d4d8cdb7358702e55cb4a1c8cbd72e38 fixes this
