### ISSUE TITLE
UX for setting a "vanity path" for published projects.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#707]
Here's a publish dialog that lets you choose your own URL

* Users can now have multiple projects with the same project title
* Users have more freedom over their project URLs
* We can default to names that won't conflict
  * If you already published a ```/my-project``` and are publishing another project with the same name we can default the next one to ```/my-project-2``` 
  * We cannot show this dialog with an error state right off the bat ever!

![image](https://cloud.githubusercontent.com/assets/25212/8261928/3ab793ea-1683-11e5-880b-2c57cfa40ff0.png)

**Comment by hannahkane** [comment]
just making sure I understand. Once this is set, the user can't change it, right? Does that field become uneditable the next time they're in this lightbox? If so, should we warn them that they can't change it?

**Comment by flukeout** [comment]
I'll give this some more thought and update the ticket. But my assumption is that you pick the path once at the beginning when you first publish.

**Comment by humphd** [comment]
Is this part of MVP?  If so, please add it to the MVP milestone.  My vote is that vanity URLs are not MVP.

**Comment by hannahkane** [comment]
I vote not MVP as well.

**Comment by gideonthomas** [comment]
This is a pretty big change that we probably won't be able to implement anytime soon.
