### ISSUE TITLE
Remove "show in public gallery" toggle from the Publish dialog.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#708]
Are we keeping track of this setting at all?

Even if we are, we should remove / hide this UI as it doesn't have any effect on the published product since we don't have a gallery.

**Comment by hannahkane** [comment]
+1 to removing this UI. We are not using it yet, though a gallery will be a critical part of phase 2.

**Comment by humphd** [comment]
This is in and landed.
