### ISSUE TITLE
When editing the Project Title, "enter" key should save the edits.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#711]
Referring to this state here...

![image](https://cloud.githubusercontent.com/assets/25212/8781648/2435a6fc-2ec5-11e5-90e5-5e55ac2dff0c.png)

If I hit **Enter**, Thimble should attempt to save my changes.

**Comment by flukeout** [comment]
We could also have the Escape key cancel the edit.

**Comment by humphd** [comment]
I'll take this, since I did the esc handling for the other bugs.

**Comment by humphd** [comment]
Fixed now.
