### ISSUE TITLE
Add "Delete this Project" item to the dropdown menu.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#712]
Users should be able to delete a project while they're looking at it in the editor, so let's give them that option in the dropdown.

Let's add it under the "New Project" action.

When a project is deleted in this fashion, let's show the user the My Projects list.

cc @gideonthomas

**Comment by flukeout** [comment]
Here's the garbage can icon...
https://dl.dropboxusercontent.com/u/109902/bramble/icons/garbage-can.svg

![image](https://cloud.githubusercontent.com/assets/25212/8785987/5a3cd8b8-2ee0-11e5-812f-9331f54b276d.png)

**Comment by flukeout** [comment]
I'd throw in Remix here too. We have remix & delete on the projects list, but they're more useful if you can perform those actions while looking at the actual project.

**Comment by errietta** [comment]
@flukeout look at https://github.com/mozilla/thimble.webmaker.org/pull/1126 ! lthough i copied that function from another file, I think we should put it somewhere both places ccan access it so we don't copypasta

**Comment by flukeout** [comment]
@errietta Awesome! Will take a look!
