### ISSUE TITLE
Tricky User Flows

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#714]
**Signed out user signing in**
When a signed out user Signs In while in the editor, we:
* Save whatever was in the editor as a new project for that user
* After signing in is complete, return them to the editor

**Signed in user deleting a project**
When someone is editing a project and they decide to delete it via the dropdown, we...
* Delete the project
* Present them with the My Project List where they can...
  * Open an existing project
  * Start a new project from scratch

*Note* - we're keeping the project list as a separate page for now, not as a modal, so we don't have to worry what's underneath it. However, we could just show a project with no files in it.

**Signed in user remixing a project**
When a signed in user remixes a project (theirs or someone elses), we automatically save the remix to their Projects list.

cc @gideonthomas Can you list out whatever other scenarios are troubling, from our discussion earlier today?

**Comment by gideonthomas** [comment]
RE: **Signed out user signing in**:
We only create a new project for that user **if and only if** there were changes in the editor, otherwise, we show them the "My Project List". 
Is that right @flukeout?

**Comment by gideonthomas** [comment]
Also, maybe another exception for the above case would be if a signed in user has no projects, even if there are no changes in the editor before signing in, we create a new project?

**Comment by flukeout** [comment]
@gideonthomas No, let's always return the user to the Editor after signing in with whatever stuff they were editing (even without any changes).

**Comment by gideonthomas** [comment]
Ok
