### ISSUE TITLE
I shouldn't be able to rename a project to a blank string.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#715]
Currently, I'm able to save the project title even when the input is blank and I end up with this.

![image](https://cloud.githubusercontent.com/assets/25212/8785324/c5b9f1fc-2edb-11e5-8c2e-a8cda6c8c0d0.png)

Let's at least force this basic validation. If someone tries to Save a blank project title, we just don't let them and the field stays editable until they type in some kind of name.

We should probably also determine if we want any restrictions on the project name
* Allow special characters?
* Max / min length?

I'm not too concerned, as long as we don't allow saving blanks.

cc @gideonthomas

**Comment by flukeout** [comment]
It seems that this behaviour has changed since I created this issue.

If I try to save a blank project name, it won't let me, but subsequently it won't let me change the the project name to something valid as well.

**Steps to reproduce**
* Open a project
* Click the project name to rename it
* Erase the current name, so the input is blank
* Hit save
* Nothing happens
* Type something in and hit save
* It won't Save the new name and the input field remains

If you don't first attempt to save a blank name, then the rename works as expected.

Can you confirm @gideonthomas

**Comment by gideonthomas** [comment]
Yeah that's the case so this is still a bug!

**Comment by humphd** [comment]
@gideonthomas what are the DB restrictions on project title, in terms of length?

**Comment by gideonthomas** [comment]
yeah it doesn't allow an empty string

**Comment by gideonthomas** [comment]
we should have front-end validation for this!

**Comment by Pomax** [comment]
just to make life harder, what about titles that don't actually contain "letters" but only unicode diacritics?

For instance:  ̛̟̞̝̜̙̘̗̖̀́̂̃̆̅̄̇̈̉̊̋̌̍̎̏̔̓̒̑̐̚̕

**Comment by errietta** [comment]
Can someone mentor me on this pls? :heart: @flukeout ?

**Comment by humphd** [comment]
@errietta thanks for offering to take this bug.  I'll get @gideonthomas to help you get started.  He's gthomas in #thimble on irc if you want to chat there, or you can ask things here, too.

**Comment by errietta** [comment]
@gideonthomas so, where would we catch the title size? I saw persist() and save() and was thinking to set the input box back to the old value and do the necessary gui magic to make it back to a non-editable string.. Orr maybe just show an error and let them continue editing?

**Comment by errietta** [comment]
after @gideonthomas advice, i was able to produce https://github.com/mozilla/thimble.webmaker.org/pull/1159
Is there some design on what the error message should be like? kind of ugly atm
![1](https://cloud.githubusercontent.com/assets/134585/10179699/9bb80f86-66ff-11e5-867f-567900422f80.png)

**Comment by errietta** [comment]
Also, any other checking we should  do apart from empty string?

**Comment by flukeout** [comment]
Hi @errietta how about instead of adding the error message when the length is 0, we...
* Lower the opacity on the Save button to .5
* Make it so that clicking the Save button has no effect

**Comment by errietta** [comment]
sounds good. Will have to catch it onchange, right?

On Wed, Sep 30, 2015 at 6:46 PM Luke Pacholski <notifications@github.com>
wrote:

> Hi @errietta <https://github.com/errietta> how about instead of adding
> the error message when the length is 0, we...
>
>    - Lower the opacity on the Save button to .5
>    - Make it so that clicking the Save button has no effect
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/thimble.webmaker.org/issues/715#issuecomment-144488390>
> .
>
-- 
Errietta Kostala
<errietta@errietta.me>

**Comment by flukeout** [comment]
@errietta Yeah - I always forget which event makes sense, does onchange fire every keystroke? That's the one we want - maybe jQuery's "keypress" will work.
