### ISSUE TITLE
Can't rename project to the name it already has

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#720]
**Steps to reproduce**
* Open a project
* Tap the project name to edit it
* Don't change the name
* Tap Save
* The project name won't save and is in an editable state

**What should happen** - The project renaming UI switches back to the display mode of the project name.

**Comment by flukeout** [comment]
cc @gideonthomas

**Comment by humphd** [comment]
@gideonthomas, what if we always call `editingComplete()` in the callback to `persist()`?  There's really no way for the user to handle the error here:

```js
  function save(context) {
    persist.call(context, context.titleBar.val(), function(err) {
      if(err) {
        console.error("[Bramble] Failed to rename the project with ", err);
        // <------------------ I think we should call editingComplete() here too
        return;
      }

      editingComplete(context);
    });
  }
```
If you think that's sane, I'll do a PR.

**Comment by gideonthomas** [comment]
@humphd yeah thats a good idea!

As far as this bug is concerned, this is part of a publish.wm.org bug filed [here](https://github.com/mozilla/publish.webmaker.org/issues/94)

**Comment by flukeout** [comment]
@gideonthomas In addition, once you try to save the same name the project already has you're not able to save a different name either. The UI is stuck.

**Comment by sedge** [comment]
This was fixed in https://github.com/mozilla/publish.webmaker.org/commit/4a62d1764054b41c5ca3a19879bae110483af632
