### ISSUE TITLE
UX for adding new files to a project

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#723]
Here's a spec that tackles...

* Adding the three common file types (HTML, CSS & JS) directly from UI
* Uploading files from your computer by selecting from file system
* Uploading files from your computer by dragging
* Taking a selfie - *I don't remember how this works exactly, but would be cool to expose it here too*

![image](https://cloud.githubusercontent.com/assets/25212/8814009/db96d9f4-2fbc-11e5-9bf9-4a649f0b0319.png)

cc @humphd

**Comment by hannahkane** [comment]
I believe when the selfie extension is enabled, just typing "<img src=" is enough to prompt a "Take a selfie" dropdown. I like the idea of having UI for that as part of this flow as well.

Should we have UI for if the user uploads an unacceptable file type? (Are there other errors? Do we have size limits, for example?)

**Comment by flukeout** [comment]
Let's discuss the technical limitations when we have the gang together tomorrow morning and we can come up with error states etc.

**Comment by flukeout** [comment]
File upload dialog markup & styles...
http://flukeout.github.io/thimble-home/file-dialog/dialog.html

Assets in...
https://github.com/flukeout/thimble-home/tree/master/file-dialog

cc @humphd

**Comment by humphd** [comment]
@flukeout I need the `+` sign you want me to use, too, for the green add file button in Thimble.

**Comment by flukeout** [comment]
White plus - https://dl.dropboxusercontent.com/u/109902/bramble/icons/plus-white.svg

**Comment by flukeout** [comment]
@humphd I've updated the dialog copy here http://flukeout.github.io/thimble-home/file-dialog/dialog.html

Also, for the actions in the bottom bar, let's drop the "..." from the "From your Computere" and "Take a Selife" buttons.

**Comment by sedge** [comment]
Closed! In #723
