### ISSUE TITLE
Deploy the new thimble to thimble-beta

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#732]
We've avoided a production deployment because the database schemas have been rapidly changing in development, and we didn't want to cause our users to lose data or waste time on migration scripts. 

When remix functionality lands on publish.wm.o our schema will be pretty much finalized and we can get this running in the wild.

**Comment by sedge** [comment]
Being tracked in devops here: https://github.com/MozillaFoundation/mofo-devops/issues/133

**Comment by hannahkane** [comment]
Is this unblocked now?

**Comment by sedge** [comment]
And closed! see: http://thimble-beta.webmaker.org
