### ISSUE TITLE
Implement Tutorial Feature

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#737]
![image](https://cloud.githubusercontent.com/assets/25212/8834009/b18db8e4-3066-11e5-922b-2cc3359b6ebc.png)

**Full version** - https://dl.dropboxusercontent.com/u/109902/bramble/tutorial-ux.pdf

**Concept Description**
To make creating tutorials easier for educators, we'll make it easy to add a tutorial.html file to each project. When a tutorial is present, we'll expose a special UI in the preview area that makes it easy to toggle between the content of the project and the tutorial. In addition, Thimble will automatically apply a nice set of styles to the tutorial so the author only has to worry about the content.

**How it works**
* By default, new projects start without a tutorial, and include the "Add Tutorial" button in the file view
* When "Add Tutorial" is pressed...
  * We add a tutorial.html file to the project
  * We add the "Preview" toggle UI to the top of the Preview area
  * We switch the Editor view to tutorial.html
  * We switch the Preview to display the tutorial.html file
  * We toggle the Preview / Tutorial UI toggle state to "Tutorial"
* The tutorial.html file is fully editable and deletable
* At any time, the Preview can be toggled between the Preview and Tutorial
* When the Tutorial view is opened, opening an HTML file doesn't switch the Preview to show the edited file
* The tutorial.html file is linked to an "invisible" CSS file

**Assets**
Okay, I think the files are pretty much ready to go.
* Tutorial HTML - http://flukeout.github.io/thimble-home/tutorial/tutorial.html
* Tutorial CSS - http://flukeout.github.io/thimble-home/tutorial/tutorial.css
* Style Guide - http://flukeout.github.io/thimble-home/tutorial/tutorial-style-guide.html
  * I think we should host this somewhere and link to it directly, we don't want to have it open in the editor Preview pane though, as that might cause problems.

Assets live in https://github.com/flukeout/thimble-home/tree/master/tutorial

**Tutorial Copy**
https://etherpad.mozilla.org/thimbletutorialcopy

**Comment by humphd** [comment]
The tutorial files above are landed in Thimble now: https://github.com/mozilla/thimble.webmaker.org/pull/740/files, and the Tutorial feature is in Brackets.  I just need UI in Thimble to create these.

**Comment by flukeout** [comment]
@hannahkane Can you please look over my latest edits to the tutorial and let me know if it's good to go?
http://flukeout.github.io/thimble-home/tutorial/stay-calm-tutorial.html

I made some edits and simplifications to the copy in the google doc.

**Comment by hannahkane** [comment]
Nice, @flukeout! I like the edits you made, but wondering if you intentionally left out the part about changing font styles.

**Comment by flukeout** [comment]
@hannahkane Yeah, I did - I wanted to keep it nice and simple for our usertesting. I think the edited version covers the bases pretty well. 

I'd like to roll with this one for now since we're still starting in the Keep Calm project as a default "New Project". I'll update the tutorial later to include the font step once we have it linked from the homepage. Let me know if that is cool.

**Comment by hannahkane** [comment]
Ah, I understand. Yes, totally fine as is for user testing. Thanks!

**Comment by flukeout** [comment]
@sedge Okay, the tutorial is ready to go.

The files are available here:
https://github.com/flukeout/thimble-home/tree/master/tutorial
