### ISSUE TITLE
Preview stops showing the correct preview after previewing the tutorial.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#739]
Steps to reproduce
* Open a project that has a tutorial file (the starting project should)
* Click on the "Tutorial" link in the Preview bar
* Click the "tutorial.html" page in the file tray
* Click the "index.html" file
* Click the "Preview" link in the Preview bar
* The Preview still shows the tutorial

It should show a preview of the "index.html" file.

**Comment by humphd** [comment]
Fixed in https://github.com/humphd/brackets/pull/395
