### ISSUE TITLE
Use new Google Analytics Account Details

### ISSUE THREAD

**Issue by adamlofting** [mozilla/thimble.webmaker.org#749]
As it no longer makes sense to treat a Webmaker.org visitor and a Thimble user as people engaging with a single web property, I've setup a new GA account for tracking Thimble data independently of Webmaker.

The new property ID is: `UA-49796218-33`

See also: #653

**Comment by humphd** [comment]
This probably needs to happen in the `.env`, so I guess it's on @sedge or @jbuck?

**Comment by humphd** [comment]
I've landed the GA bits in the homepage, and update the editor.  We need that new account added to the server's env, and I don't have rights.  One of @sedge or @jbuck needs to do this.

**Comment by sedge** [comment]
@adamlofting Do we need to worry about [this value](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/views/homepage/index.html#L16)?

**Comment by sedge** [comment]
I've set the account number. When we find out about the domain part we can close this.

**Comment by adamlofting** [comment]
> @adamlofting Do we need to worry about this value?

No, we don't need to set the domain, as the new version of the GA tracking deals with that out of the box. I've filed a new ticked and PR to upgrade to the newer version of the GA code:

https://github.com/mozilla/thimble.webmaker.org/issues/1012

Also, I'll close this ticket as that .env var is set correctly.
