### ISSUE TITLE
Renaming a project is not counted as a "Update Publish"-able change.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#751]
**Steps to reproduce**
* Create a new project and publish it
* Change the project name
* You're not able to update the published version with the new name if that's the only change you made

You should be able to.

**Comment by humphd** [comment]
@hannahkane P1 or P2?

**Comment by hannahkane** [comment]
Hmm...gonna go with p2. I'd argue it's not essential functionality and there is a workaround. I'm trying to keep p1 as narrow as possible,

**Comment by flukeout** [comment]
Agreed.

**Comment by humphd** [comment]
Dupe of #719
