### ISSUE TITLE
Add "disabled/in-progress state" to the Create New project button

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#753]
When you click **Create New** on your project list, you get no indication that Thimble is trying to do something, the button looks like it's still clickable. We need to make the label say something like "Creating..." and grey it out.

![image](https://cloud.githubusercontent.com/assets/25212/8991107/43c87808-36ab-11e5-84c4-cc529aa3ab65.png)

I'll provide a spec.

**Comment by humphd** [comment]
Another thing to consider is having the publish process kick off an indeterminate throbber, maybe like we've done with the Upload Files dialog and drag and drop.
