### ISSUE TITLE
Renaming the index.html file in the default project causes some weirdness

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#754]
**Steps to reproduce**
* Create a new project or open an existing stay calm project
* Rename index.html to something else (in my case, staycalm.html)
* Refresh the preview

What happens

![image](https://cloud.githubusercontent.com/assets/25212/8991181/c9882286-36ab-11e5-84d1-a18f915ba589.png)

**List of Problems**
* Strange filename listed at the top of the Editor window
* The page no longer gets the styles specified in style.css
* In my case, editor is stuck showing the "saving..." message at the top

**Also**
* If you refresh the browser, the index.html file is back and the staycalm.html file previews and renders correctly.

After refreshing...

![image](https://cloud.githubusercontent.com/assets/25212/8991216/1f46468a-36ac-11e5-84d9-0d4dd266d02b.png)

**Comment by humphd** [comment]
Looks to me like the file rename is using an absolute vs. project-relative path, and the HTMLRewriter or CSSRewriter is probably using that path and not finding assets relative to it.

**Comment by humphd** [comment]
For the rename path being too big, I need to do what's in https://github.com/mozilla/thimble.webmaker.org/pull/795/files#diff-9748587150ca9269d951b5b55c578dc8R283 and strip off the project root.

**Comment by humphd** [comment]
@flukeout one thing I should also point out, we haven't written the code yet to persist renames to the publish server (i.e., it will work locally but not save it).  So I'd avoid having people rename files for MVP.

**Comment by sedge** [comment]
This has been fixed AFAIK. @flukeout Can you confirm?

**Comment by flukeout** [comment]
Renamed "index.html" to "blam.html", refreshed, and everything works great.

![image](https://cloud.githubusercontent.com/assets/25212/9364928/a30331d8-4663-11e5-9d91-0ecdb16a3448.png)
