### ISSUE TITLE
When refreshing the editor with an HTML file open, the first tag is highlighted.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#755]
Note the ```<html>``` tag, it's highlighted in the same fashion as a tag that has a cursor on it.

![image](https://cloud.githubusercontent.com/assets/25212/8991400/4212dd1c-36ad-11e5-944f-5ca05d62535f.png)

The entire document is also outlined in blue in the preview by default. 

Let's not do this, it's not useful and potentially confusing because it feels like you're able to start editing by typing. 

*note* - not a huge deal

**Comment by humphd** [comment]
No idea how I'd fix this, closing.
