### ISSUE TITLE
Update project root on project rename for unauthenticated user

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#756]
For an authenticated user this isn't an issue because the project root is based on project id. But since this is not the case for unauthenticated users, renaming the project will not change the root from "/Untitled Project", but we should to make https://github.com/mozilla/thimble.webmaker.org/issues/627 easier to solve

**Comment by humphd** [comment]
We're going to use a solution based on UUIDs for anonymous projects, so this is no longer needed.
