### ISSUE TITLE
Clean up the user dropdown menu

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#757]
The current menu has a few problems
* New Projects - doesn't work and has a typo - #690
* Settings - 404
* Profile - 404

![image](https://cloud.githubusercontent.com/assets/25212/8992157/eb555a40-36b1-11e5-8e04-2e2e86a6e83e.png)

@hannahkane Do we need profile & settings? Are they supposed to link somewhere?

**Comment by hannahkane** [comment]
No, for now, let's remove those items.

**Comment by gideonthomas** [comment]
https://github.com/mozilla/thimble.webmaker.org/issues/712 is also relevant to this

**Comment by JordanTheriault** [comment]
In regards to #712, is now a proper time to add a delete in addition to Remix or is that out of scope?

**Comment by humphd** [comment]
This is done and landed.
