### ISSUE TITLE
Create a version of the Stay Calm project that has a tutorial baked into it for remixing.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#760]
For one of the usertesting tasks, we'll need to have a project load with a step-by-step remixing tutorial.

@hannahkane Add a link to the tutorial that you wrote and I'll convert it to tutorial markup.

**Comment by hannahkane** [comment]
Sorry for the delay. Tutorial instructions are here: https://docs.google.com/document/d/10_Uq-iI3cQ2arZge3btnc1mzX-P8SourBJTlP_MyRIo/edit#heading=h.xgecmc16vsfj
