### ISSUE TITLE
When previewing an image, the editor bar doesn't display the previewed filename.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#761]
Steps to reproduce
* Open a project with an image
* Click on the image so that it is previewed in the Editor
* Observe the editor bar, it's not showing the name of the previewed image file

![image](https://cloud.githubusercontent.com/assets/25212/8993816/2b0a79cc-36bc-11e5-91cc-77f23e9fcff0.png)

**Comment by humphd** [comment]
This is due to how Brackets handles "editors" internally.  The image viewer isn't an editor, so I must need to listen for some other event than just using the `EditorManager`.  I'm not totally sure how to fix, but I'm sure it's fixable.

**Comment by humphd** [comment]
The answer is likely to use something in `src/view/MainView*.js`
