### ISSUE TITLE
Add warning if there is unsaved work when a user closes thimble

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#763]
To prevent loss of data, let's warn users before they close thimble if they've made file changes that haven't been saved yet. For authenticated users, this should also include a warning if the data has been saved but not persisted to publish.wm.o.

**Comment by sedge** [comment]
@flukeout Hey Luke! What kind of UI do you want for this?

**Comment by humphd** [comment]
Stealing, I'll do this.
