### ISSUE TITLE
Use symlinks for project roots

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#768]
Currently for an unauthenticated user, our project root looks something like `/<project name>`. This makes renaming a hassle because we need some way to tell Bramble that the mounted path has been renamed (which is complicated to implement). Instead, we should have a symlink with the name of a uuid which will link to the real project path. We will mount the symlink in Bramble so that renaming the real project root will not affect anything.

**Comment by humphd** [comment]
I'd use a dir like `/mnt` (http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/mnt.html) to hold the symlinks you use.

**Comment by humphd** [comment]
I'll take a shot at this.

**Comment by humphd** [comment]
@gideonthomas, this is fixed now.  Just to catch you up, prior to calling `Bramble.mount()` we create a symlink to the project root dir in `./mnt/<uuid>` and give that to Brackets.  We put this new dir path on the `config` object as `mountPoint` and leave `root` untouched.  If you have to move/rename the actual `root` folder (anonymous to signed in, for example), you can just re-write the symlink file with the new path, and Brackets will keep working as normal.

At some point we might want to add a garbage collection step to clean out old mount symlinks and old project folders.  I was thinking we could do it with a `.lock` file or something in the project folder, which we'd update on a `timeout` every N minutes, and then have some other process that deletes anything older than some amount of time.  That can be a problem for another day, though.
