### ISSUE TITLE
Sort projects by last edited in the projects page

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#770]
The projects page aren't sorted intelligently at the moment.

**Comment by humphd** [comment]
Yeah, this really sucks.  We should fix.

@errietta, this might be one for you to try?

**Comment by errietta** [comment]
sure, nom nom nom.

**Comment by errietta** [comment]
@humphd so hopefully i changed the right thing here.. https://github.com/mozilla/publish.webmaker.org/pull/161

**Comment by errietta** [comment]
@humphd https://github.com/mozilla/thimble.webmaker.org/pull/1144 :dancers:
