### ISSUE TITLE
Publish button and Publisher.prototype.publish being called too many times

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#772]
When using the zip file at https://www.dropbox.com/s/08bf9ubcauzvgyo/templated-retrospect.zip?dl=0, we're seeing a case where publish kicks off a ton of parallel requests to publish.  We're fixing this now in a temporary way by making the `publish` call bail if it's in progress.  We need to figure out a better long term solution.

**Comment by humphd** [comment]
One thought I have is that we stop adding/removing click handlers on the publish and unpublish buttons as we manage state. We should only have a single click handler for both, and disable/enable things with css and `disabled=true` on the element, etc.

**Comment by humphd** [comment]
Temp fix in https://github.com/mozilla/thimble.webmaker.org/commit/45abaf6be95be6f8fb38be846e81aa3659935bc1

**Comment by sedge** [comment]
Is this still an issue? cc: @humphd @gideonthomas

**Comment by humphd** [comment]
I don't think we care, no.
