### ISSUE TITLE
Make the size of a thimble cookie smaller

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#775]
For a temporary fix for https://github.com/mozilla/thimble.webmaker.org/issues/774, lets make the size of the session cookie smaller by doing the following:
* Remove the `project_id` from each file representation and use it from `project.meta.id` instead
* Change the files object from:
```js
files: {
  "/a/b": {
                 path: "/a/b",
                 id: 1
             }
}
```
to
```js
files: [id1, path1, id2, path2...]
```

**Comment by humphd** [comment]
This is due to Heroku HTTP validation restrictions on cookie size, https://devcenter.heroku.com/articles/http-routing#http-validation-and-restrictions
