### ISSUE TITLE
Migrate published projects to a prettier domain

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#782]
When production launches it'll be on an amazon domain. @hannahkane What do you want the domain to end up looking like?

**Comment by hannahkane** [comment]
I filed a separate ticket to discuss that: https://github.com/MozillaFoundation/plan/issues/519

**Comment by hannahkane** [comment]
Looks like it's going to be thimble.mozilla.org.

**Comment by sedge** [comment]
@hannahkane Are you talking about the app itself, or where published projects live?

**Comment by hannahkane** [comment]
Oh, the app itself. I think I don't understand what this ticket is about.

**Comment by sedge** [comment]
Sorry! Let me clarify.

If you publish a project on [thimble-beta](thimble-beta.webmaker.org) it ends up with a url like this: https://d157rqmxrxj6ey.cloudfront.net/sedge/24

Is that something we want to change at some point?

**Comment by hannahkane** [comment]
Ah, I understand. (The title of this is clear, I just didn't get it for some reason.)

@xmatthewx  -  do you know what your solution for Webmaker project urls will be?

**Comment by xmatthewx** [comment]
Webmaker project URLs currently follow this form: https://beta.webmaker.org/#/project?user=446905&project=4072. We won't be able to drop the beta here until we finish the site transition.
