### ISSUE TITLE
My project should publish as soon as I hit Publish.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#784]
Right now, if I want to publish my project, I have to click publish twice. Once to open the publishing dialog, and the second time to actually publish. I think we should publish as soon as I click Publish. We can open the publish dialog and have the published link immediately available for the user.

Updating the published project would be a two-step interaction however, just like it is now.

@hannahkane @humphd Thoughts?

**Comment by hannahkane** [comment]
Does this mean the project would be published without the description initially?

**Comment by flukeout** [comment]
@hannahkane Yeah - it would. Right now, we don't even use the description anywhere and are planning to remove it for MVP though, so I think that would be OK. Down the road, we could always just update the description when someone fills it in without having to publish explicitly.

**Comment by hannahkane** [comment]
:+1: Sounds good.

**Comment by humphd** [comment]
How do you unpublish?

**Comment by sedge** [comment]
This seems like an enhancement for further down the line.

**Comment by flukeout** [comment]
Def - let's not worry about it for now.
