### ISSUE TITLE
Published project shows a 403 error.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#789]
Project shows as published in the UI...

![image](https://cloud.githubusercontent.com/assets/25212/9093886/96da836c-3b63-11e5-8327-2591bb1b6c7f.png)

But resolves to 403...
http://bramble-staging.s3-website-us-east-1.amazonaws.com/flukeout/129

This is after a first-time publish of this project.

**Comment by sedge** [comment]
We have a lead on this. @jbuck is investigating for us

**Comment by jbuck** [comment]
Fixed! I added the appropriate bucket policy. For the interested it is:

```
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "",
			"Effect": "Allow",
			"Principal": "*",
			"Action": "s3:GetObject",
			"Resource": "arn:aws:s3:::bramble-staging/*"
		}
	]
}
```

**Comment by sedge** [comment]
@jasonthomas
