### ISSUE TITLE
Open `index.html` if it exists, or the last non-tutorial html file when remixing a project

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#797]
Steps to reproduce
* Open http://bramble-staging.s3-website-us-east-1.amazonaws.com/flukeout/144/
* Click Remix
* Thimble opens and the Tutorial is shown

Is this on purpose?

If it is, there's a bug where the Preview is shown as 'active' but the tutorial should be.

@hannahkane What do you think of this behaviour? Show the tutorial when we have one?

I feel like it might be pretty good, but then you sort of lose the connection to the project because you don't see the project in the preview that you were just looking at before remixing.

**Comment by gideonthomas** [comment]
@flukeout just to clarify, is the tutorial.html file the active file when you are seeing the tutorial rendered in the preview? 
**Context**: Currently, we select the last html file that was written to the filesystem (which usually ends up being the tutorial file) as the file that bramble loads initially. We should probably change that!

**Comment by hannahkane** [comment]
This is definitely something I'd like to do user testing on. If we don't show the tutorial by default (which makes sense to me - to NOT show it initially), are people *aware* of the tutorial?
