### ISSUE TITLE
Switch to streaming file-by-file to the client

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#798]
Our current method of retrieving project files from publish.wm.o isn't sustainable, since it pulls each file en-mass into memory. We've already maxed out the heroku instance's memory capacity with a single user and a single project, meaning this won't scale.

Since we have a production deployment, we expect to see just how bad this is soon. User feedback will help prioritize this.

**Comment by humphd** [comment]
We've moved to single tar file, this is fixed.
