### ISSUE TITLE
Deleting projects from My Projects list UX is cumbersome.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#799]
Steps to reproduce
* Try to delete a lot of your own projects fast
* The slowness of the delete action makes it hard
* Things jump around a lot as the "deleting" indicator finishes

What we should do instead
* Immediately delete projects from the list, or with a really quick animation at least

I'm guessing maybe there's a call back we're waiting for to make sure the delete went through? I don't think we should bother. Let's just get rid of it from the UI right away and hope for the best. If it doesn't actually delete due to a server error, we can just display it again next time.

**Comment by sedge** [comment]
I can get behind that.

**Comment by humphd** [comment]
We've fixed this.  Please file again if you find it problematic.
