### ISSUE TITLE
Let's QA Thimble!

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#807]
Please visit https://thimble-beta.webmaker.org/ and help us test out the brand new Thimble!

Please log issues you find in this repo, and be sure to include:
 * what browser and version you're using
 * the "QA" label (we'll assume if you're using this label that you're testing on https://thimble-beta.webmaker.org, so you don't need to include that info)
   
**You do not need to test on mobile or tablet**

## Homepage (NOT READY FOR TESTING) ##
 * Any typos?
 * Broken links?
 * Did the video work?
 * When authenticated, can you access the user menu?

## Editing ##
* Can you rename the current project? 
* Can you save the name of the project with no characters? (KNOWN BUG; PLEASE DON'T TEST)
* Can you undo work?
* Can you redo work?
* Can you see changes in the Preview pane as you modify code?
* When hovering over HTML & CSS markup, does the Preview pane show the corresponding areas?
* Do you see the auto-saving indicator when you make changes?
* Can you press Command/Control + K after clicking on a tag to get inline help?
 * Can you press Command/Control + E when editing a CSS color to use the colorpicker?
* Close the project or the tab while the project is auto-saving. Do you see a warning that you’ll lose your work?

## Adding files ##
* Can you open and close the file tray?
* Can you rename a file?
* Can you delete a file?
* Can you add an HTML, CSS, or Javascript file from the + button?
* Can up upload a file from your machine?
* Can you drag a file from your desktop to the file tree?
* Can you drag a zip file from your desktop to the file tree?
* Does it unzip properly?

## Tutorials ##
* Can you add a tutorial using the + menu?
* Does the default tutorial content appear?
* Can you edit the tutorial content?
* When you click to view a different file while the right pane is in Tutorial mode, does the Tutorial stay visible?
* If you change to Preview mode, does the selected file render in the right pane?

## Preferences ##
* Can you change the theme?
* Can you change the text size?
* Does the mobile preview render correctly?

## Publish your project ##
* Can you follow the link to see your published project?
* Were your recent changes saved?
* Can you update your already-published project with additional changes in the editor?
* Can you unpublish your project?
* If not signed in, are you prompted to sign in to publish?

## My Projects list (access this from the user menu, when authenticated) ##
* Do your projects appear in the correct order—most recently edited at the top?
* Can you open a project?
* Can you delete a project?

## View a Published Project ##
(for example, this one: https://d157rqmxrxj6ey.cloudfront.net/hannahkane/25/)
* Can you see who authored the project?
* Can you see the project title?
* Can you remix the project?
* Can you get back to the Thimble homepage from the published project?

## Start a new, blank project ##
* From user menu
* From “My Projects” page
* From landing page
* Does it have appropriate starter content?

## Performance ##
* Did you notice any slowness?

**Comment by hannahkane** [comment]
@flukeout @humphd - does this ticket look ok to you? Once I get the OK from you both, I'll send an email asking people to take some time this week to QA for us.

**Comment by flukeout** [comment]
Adding a tutorial via the + menu hasn't landed yet.

**Comment by hannahkane** [comment]
It hasn't? I've seen it working. ??

**Comment by flukeout** [comment]
This seems pretty thorough, what about adding...
* Can you press Command/Control + K after clicking on a tag to get inline help
* Can you press Command/Control + E when editing a CSS color to use the colorpicker
* Can you update your already-published project with additional changes in the editor

**Comment by flukeout** [comment]
The section that says "Publish your remix" - should it just say "Publish your project"?

**Comment by hannahkane** [comment]
Yup, just noticed that, too. OK, all updated. Feel free to make add'l updates if you notice anything else.

**Comment by jgmac1106** [comment]
Feedback from today's session: https://etherpad.mozilla.org/EeGlOE6nNX

**Comment by hannahkane** [comment]
Thanks, @jgmac1106. Super helpful. I responded to each of the points in the pad; there are a couple follow-up questions for you if you have time. Thank you!

**Comment by hannahkane** [comment]
Going to close this ticket, as the tool has been thoroughly tested at this point, but we'd of course welcome additional bug reports if anyone finds them.
