### ISSUE TITLE
Thimble isn't publishing my changes again

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#816]
Project in editor...
![image](https://cloud.githubusercontent.com/assets/25212/9146865/3ffe56aa-3d15-11e5-9cf8-c9f166e79442.png)

Published project here...
http://bramble-staging.s3-website-us-east-1.amazonaws.com/flukeout/158/

![image](https://cloud.githubusercontent.com/assets/25212/9146885/7f1db75e-3d15-11e5-8069-3a01fcb6b41e.png)

It published the correct project name though. :cake:

**Comment by humphd** [comment]
Sucks.  Also, you're doing amazing QA work for us, @flukeout.  I'm loving all the bugs you're finding and filing.  Thank you!

When I remix this project, I actually do see your changes, but they've been put in the wrong folder.  Notice the addition of the `157/` folder, which now holds your updated files:

![screenshot 2015-08-08 11 35 12](https://cloud.githubusercontent.com/assets/427398/9151014/be20b580-3dc1-11e5-8376-2decb19ad9cc.png)

We're doing something odd with paths when we save to the server, and not properly stripping the project/user info.

**Comment by gideonthomas** [comment]
So from what we see when we access published projects on staging vs. prod., here are the headers:
* Staging: 
```
Cache-Control:private max-age=0
Content-Length:444
Content-Type:text/css
Date:Mon, 10 Aug 2015 16:36:24 GMT
ETag:"a5dee1f68dd5b33363c086a65ac272f8"
Last-Modified:Mon, 10 Aug 2015 16:36:04 GMT
Server:AmazonS3
x-amz-id-2:9IzBwr++dhV13m9jvNaQi7W3dt6bCURgWdD2QAuQSA6fews0wasHYP0cN9yCpx3l
x-amz-request-id:64AB14836FED4419
```

* Production:
```
Age:302
Cache-Control:private max-age=0
Connection:keep-alive
Content-Length:444
Content-Type:text/css
Date:Mon, 10 Aug 2015 16:32:17 GMT
ETag:"a5dee1f68dd5b33363c086a65ac272f8"
Last-Modified:Mon, 10 Aug 2015 16:32:15 GMT
Server:AmazonS3
Via:1.1 3cb030c2071409e70d1a614b5820d9e9.cloudfront.net (CloudFront)
X-Amz-Cf-Id:oNmidGYaHARXHu0dxfmuToR0Ec-9VtDYjaHxykhrGnf820am_v-n7Q==
x-amz-version-id:DYrjVgL3odEc76SQ37GX4n4cgTE.Q3vB
X-Cache:Hit from cloudfront
```

@jbuck any thoughts regarding the differences between the two? Currently, we think that prod. is giving us a cached version of the project.

**Comment by jbuck** [comment]
@gideonthomas You are spot on, staging is using the s3 bucket directly and production is using the cloudfront distribution

**Comment by jbuck** [comment]
@sedge and I investigated and found [the docs say](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html#expiration-individual-objects):

> **The origin adds a Cache-Control max-age directive to objects**
> CloudFront caches objects for the lesser of the value of the Cache-Control max-age directive or the value of the CloudFront maximum TTL.
> **Origin adds Cache-Control: no-cache, no-store, and/or private directives to objects**
> CloudFront caches objects for the value of the CloudFront minimum TTL.

The solution here seems to be removing the `private` directive from the `Cache-Control` header.

**Comment by sedge** [comment]
![screen shot 2015-08-10 at 4 04 57 pm](https://cloud.githubusercontent.com/assets/1616860/9182891/f7feb248-3f79-11e5-944a-eaa0fca279be.png)

**Comment by flukeout** [comment]
Just because I accidentally tried to record a screencap again, here's the bug in action
https://www.youtube.com/watch?v=yscyCLmpZ2k&feature=youtu.be&t=130

**Comment by humphd** [comment]
I think we can close this, right?

**Comment by sedge** [comment]
@flukeout Can you confirm this is no longer happening?

**Comment by humphd** [comment]
I'm going to close, please re-open if we start seeing this again.
