### ISSUE TITLE
User-menu should open when clicked, not hovered.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#817]
Currently, the user dropdown opens when hovered. This can be jarring and unexpected, as all of our other menus / dialogs open when something is clicked. It's also too easy to mouse off of it by accident while trying to pick an option.

![image](https://cloud.githubusercontent.com/assets/25212/9176810/54de15b8-3f42-11e5-9219-884399879c73.png)

**New Behaviour**
* User menu opens when the user name or avatar is clicked
* User menu closes when...
  * A click happens outside of it
  * Something in the menu is clicked

**Comment by flukeout** [comment]
Alternatively, we can have a bigger 'invisible' hover area around the menu so you have a bit of leeway before you've 'hovered off' the menu. Imagine a transparent div with like 15px padding around the menu.

**Comment by humphd** [comment]
Fixed by https://github.com/mozilla/thimble.webmaker.org/pull/1141#issuecomment-142452656
