### ISSUE TITLE
Add a google verification page to bramble.mofostaging.net

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#821]
So, if we want to link from a Youtube video to our site, we need to "Verify" that we own that site. It's weird, I know. To do so, we need to add this file to our codebase...

https://dl.dropboxusercontent.com/u/109902/bramble/google3479be6196d04fac.html

So that it will be available at http://bramble.mofostating.net/google3479be6196d04fac.html

@humphd Can you help?

**Comment by humphd** [comment]
@flukeout question: can this file be the same on `bramble.mofostaging.net` and `thimble-beta.webmaker.org`?  They share the same code, so if I need it to be different somehow on prod vs. staging, we need two files.

**Comment by gideonthomas** [comment]
@humphd I think @jbuck is trying to solve this issue from a
