### ISSUE TITLE
Testing Thimble-Beta

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#822]
I will be at #EdCampCT Friday the 14th and will do a session on Thimble. 

Is there any questions or feedback the Design team would be interested in me exploring?

**Comment by hannahkane** [comment]
Thanks @jgmac1106.

We'd definitely appreciate you filing any bugs you find. Started a QA checklist in #807 if you want to approach systematically, but feel free to just file any bugs you run into.

Are you planning to make use of the tutorial feature during your session? I'd love to get feedback on that specifically.

Would also welcome any general feedback about usability and learners reactions. Will your audience be educators? Would love to know their ideas for how they might use Thimble in their classrooms/learning environments.
