### ISSUE TITLE
Update export icon

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#824]
I'd love some kind of simple MVP solution that lets me call `bramble.export()`, which will create a `project.zip` file for you of all your files/folders, and download it to the browser.  Can we come up with something simple for MVP?  Maybe in the user's options at the top?

Now that I've done the code for this in Brackets, I think it's kind of a killer feature to support for MVP, since it lets users work totally anonymously and completes the import/export story.

cc @flukeout

**Comment by humphd** [comment]
@flukeout I did this in https://github.com/mozilla/thimble.webmaker.org/pull/840/files, and it just needs you to add a proper icon.

**Comment by sedge** [comment]
This seems to be fixed. @flukeout Can you confirm?

**Comment by humphd** [comment]
It's still missing an updated icon.  I'd morph this bug to be about fixing that.

**Comment by sedge** [comment]
Closed in #880
