### ISSUE TITLE
Project meta data and Remix button not showing up correctly on beta.

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#826]
This is in Chrome.

![screen shot 2015-08-11 at 10 32 39 am](https://cloud.githubusercontent.com/assets/8389648/9204974/6db2d8e4-4014-11e5-8af9-f2d11771a257.png)

**Comment by hannahkane** [comment]
More importantly - when I click the Remix link, I get a 404.

**Comment by humphd** [comment]
@hannahkane I've landed a fix for this.  If you can test with that same project (you'll need to republish it) some time after 15 mins from now (while it gets deployed), that would be good.

Also, give me the link to this project so I can debug.

**Comment by hannahkane** [comment]
@humphd - Is it deployed? Should I republish now?

**Comment by humphd** [comment]
Should be, hit it!

**Comment by hannahkane** [comment]
Republished; still no good. (This is on beta.) Project is here: https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/28/
