### ISSUE TITLE
Add link for View Published to My Projects list

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#834]
This may have been discussed earlier and nixed, I can't recall, but I find myself wanting direct links to remix my projects and to view published projects from the My Projects page. It feels clunky to view the editor and click "Publish" in order to access the url of a published project.

/cc @flukeout

**Comment by gideonthomas** [comment]
Instead, let's just expose a link to the published project in this view.

**Comment by hannahkane** [comment]
duped by #1106
