### ISSUE TITLE
Often seeing a flash of a white square on the bottom right of the page in Chrome.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#835]
![image](https://cloud.githubusercontent.com/assets/25212/9255728/0817de84-41a0-11e5-86aa-03c724bae36c.png)

Happens fairly often, and usually goes away but sometimes sticks around. For example, switch between files in a project in quick succession and you should be able to see it.

**Comment by humphd** [comment]
Weird, I can't reproduce.

**Comment by flukeout** [comment]
Me neither.
