### ISSUE TITLE
Uploaded image not being published with project on Staging.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#836]
In staging, an image I uploaded to a project isn't showing up in the published version.

Project...
![image](https://cloud.githubusercontent.com/assets/25212/9255799/7845ba3c-41a0-11e5-9449-1c92726b5d40.png)

Published version...
![image](https://cloud.githubusercontent.com/assets/25212/9255792/6fc67ce8-41a0-11e5-80e2-d1114e6b1d53.png)

Link to published project: http://bramble-staging.s3-website-us-east-1.amazonaws.com/flukeout/182/

**Comment by hannahkane** [comment]
This is the same problem I'm seeing on beta.

**Comment by humphd** [comment]
Weird.  I tried, and it works http://bramble-staging.s3-website-us-east-1.amazonaws.com/humphd/185/

Can you give me exact steps you're doing?

**Comment by humphd** [comment]
Working for me too on Beta: https://d157rqmxrxj6ey.cloudfront.net/humphd/38/

Can you confirm that you're not running an old version of the code (cached?).

**Comment by hannahkane** [comment]
I cannot reproduce reliably, but I can reproduce, even after updating the cache.
These are the steps I'm following:
 - on beta
 - click + button in file tree, then Upload from computer
 - added a png file
 - linked to png file in index.html
 - image appears correctly in preview
 - wait for "Saving..." to complete
 - click "Publish"
 - view published project (https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/28/) - image does not appear (see right col under "Additional Resources")

This is the same file I'm having problems with the meta data on, so maybe it's something wrong with the project itself, but @flukeout's example above seems like good code.

**Comment by humphd** [comment]
On staging this is working great for me.  I grabbed an image, dragged it in, renamed it, changed the html, and published: http://bramble-staging.s3-website-us-east-1.amazonaws.com/humphd/196/

Beta is pretty far behind staging at the moment, so until we push out these updates, I'd say test this on staging.

**Comment by humphd** [comment]
@flukeout I remixed your project, renamed the file `e31418b9a37663526c0958cdc181fce7.png` to `bike.png`, hit `Publish`, and I get http://bramble-staging.s3-website-us-east-1.amazonaws.com/humphd/198/.  I think the issue was that rename wasn't working yet.

**Comment by gideonthomas** [comment]
@flukeout and @hannahkane are you able to still reproduce this on staging (which should have the rename patch)?

**Comment by hannahkane** [comment]
Can not reproduce on staging now, even after renaming project. yay.

**Comment by sedge** [comment]
@flukeout How about you?

**Comment by flukeout** [comment]
Image published correctly on staging...

![image](https://cloud.githubusercontent.com/assets/25212/9364718/a06f8652-4662-11e5-8d5b-9115572df128.png)
