### ISSUE TITLE
Editor remembers font size but not theme color after a refresh.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#837]
Before...
![image](https://cloud.githubusercontent.com/assets/25212/9255912/2f27b70a-41a1-11e5-9e8f-6c3b3ab1a05e.png)

After refresh...
![image](https://cloud.githubusercontent.com/assets/25212/9255916/3a07ccfa-41a1-11e5-9771-1648c9504b88.png)

**Comment by humphd** [comment]
Fixed in https://github.com/mozilla/thimble.webmaker.org/pull/909
