### ISSUE TITLE
Staging stuck in "Saving..." after renaming an uploaded file.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#838]
I uploaded a png of a bike, and renamed it to bike.png - notice a couple of things...

* Thimble stuck in "Saving..."
* Path to bike.png file in the Editor is strange...

![image](https://cloud.githubusercontent.com/assets/25212/9256002/c998a236-41a1-11e5-892e-b405d7d13a31.png)

**Comment by humphd** [comment]
Try it again, I just fixed renaming on staging.

**Comment by gideonthomas** [comment]
@flukeout this should be fixed, can you make sure?

**Comment by sedge** [comment]
@flukeout Ping

**Comment by flukeout** [comment]
Confirmed,  uploaded a file and renamed. Not stuck on saving and after refresh rename appears correctly.
