### ISSUE TITLE
On Staging, after renaming an uploaded file, the original and the new file are in the file tree.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#839]
I uploaded that 'e3141...png' file to renamed it to 'bike.png' and refreshed, now they're both there, see below...

![image](https://cloud.githubusercontent.com/assets/25212/9256053/1845b996-41a2-11e5-898f-764f09897a0f.png)

**Comment by humphd** [comment]
As I said in your other bug, renames don't yet persist.  I'm going to try and fix that today.

**Comment by humphd** [comment]
I just landed rename logic.  Renames should work now.  NOTE: I'd blow away old projects that you did before and rename failed on.  Test and see how things work.

**Comment by gideonthomas** [comment]
@flukeout is this still an issue?

**Comment by sedge** [comment]
@flukeout Haha we gotta stop meeting like this. Ping

**Comment by flukeout** [comment]
Confirmed fixed on staging, uploaded an image and renamed it. It was fine after reloading.

After uploading, renaming to "jammers.png" and refreshing, appears as it should...
![image](https://cloud.githubusercontent.com/assets/25212/9364537/afebbd86-4661-11e5-8952-7f2ef781a8e2.png)
