### ISSUE TITLE
Remix button on unscrolled published project is invisible.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#844]
Here's a published project just after loading it in Chrome
![image](https://cloud.githubusercontent.com/assets/25212/9257670/b170b518-41ab-11e5-9f6a-d72dfcc07648.png)

When scrolled slightly the button is visible again.
![image](https://cloud.githubusercontent.com/assets/25212/9257682/c5822ac8-41ab-11e5-826e-2925816409cf.png)

Not sure what's changed, but looks to be some kind recently-introduced markup or CSS issue?

**Comment by humphd** [comment]
Fixed and landed on staging.
