### ISSUE TITLE
Staging - very slow performance when creating a new project.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#845]
With a stopwatch in hand, I clicked "New Project" in the user dropdown menu.
It took 21.67 seconds for Thimble to create a new project and get to a point when I can start editing.\

I'm adding a bug label just so this issue gets noticed, but feel free to remove it. Overall performance seems to have taken a hit lately.

**Comment by humphd** [comment]
We fixed a bug where Heroku was sleeping the server after a period of inactivity, then it would spin up the server again when you requested something.  I found it was as bad as 27s.  We've fixed it now, closing.
