### ISSUE TITLE
Staging: Added files persist in the blank project when not signed in.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#846]
Steps to reproduce
* Load up thimble on staging
* Add some files to the file tree
* Make some changes to the stay calm poster
* Refresh
* Changes on poster are gone
* Files you added persist
* They stick around anytime you load thimble as an unathenticaed user

**Comment by humphd** [comment]
The way we do uuid based anonymous projects now means that we always create a fresh project dir, so this won't be an issue any more, closing.
