### ISSUE TITLE
Create promo video for new Thimble 

### ISSUE THREAD

**Issue by cassiemc** [mozilla/thimble.webmaker.org#847]
Drawing from the conversation in https://github.com/mozilla/thimble.webmaker.org/issues/643, filing this new bug to narrow the scope.

Suggestions:
* somewhere around 30sec (definitely less than 2min)
* back-to-school theme if this can be completed by Aug 31
* another theme suggestion was a funny retro vid. https://www.youtube.com/watch?v=IeFo-ym1IDE

**Comment by cassiemc** [comment]
The original inspiration for Github Atom: https://www.youtube.com/watch?v=Y7aEiVwBAdk

**Comment by flukeout** [comment]
Done!
