### ISSUE TITLE
Staging: Projects not deleting on my projects view

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#848]
**Convoluted steps to reproduce**
* Go to My Projects list
* Delete a Project
* Immediately after, as the project is deleting, click where it says "Deleting..."
* This time click "Cancel" on the popup
* Sometimes, this causes the project to get stuck "Deleting..."
* Even if completes deleting and removes itself from the page, it's back when you refresh
* Additionally, you can't delete this project now
  * If you do, it's always back again when you refresh 

@humphd Thoughts on what might be happening? Can it be alleviated by not making the "Deleting..." indicator clickable?

**Comment by humphd** [comment]
Things to do: 
* Make the `Deleting...` non clickable while delete is in progress.

**Comment by flukeout** [comment]
Things to do:
* Never show ``Deleting...``` and just delete the project immediately.

**Comment by humphd** [comment]
We also need to stop storing "file to open" in local storage -- it should go in the project metadata, or not be stored at all.

**Comment by humphd** [comment]
I think this is fixed now, please re-file if you find other edge cases.
