### ISSUE TITLE
Staging: I can't open any of my projects

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#849]
When I try to open any of the projects from the My Projects list, the editor opens and gets stuck like this...

![image](https://cloud.githubusercontent.com/assets/25212/9258717/ebc54746-41b1-11e5-8f64-243ed084fa80.png)

**Comment by humphd** [comment]
@flukeout I need to see what's to the right of that error message, specifically which file/line.

**Comment by flukeout** [comment]
@humphd - I can no longer reproduce this bug on staging.
