### ISSUE TITLE
I don't know how to dismiss the Find box

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#852]
I clicked command + F and it opened what looks like a brackets-specific Find tool. Now I don't know how to dismiss it.

![screen shot 2015-08-13 at 2 29 34 pm](https://cloud.githubusercontent.com/assets/8389648/9262229/27d7d0c6-41c8-11e5-92c7-bb59d0eaf212.png)

**Comment by humphd** [comment]
Use `esc`

**Comment by hannahkane** [comment]
lol. of course. :)

maybe not obvious to everyone? (Wasn't to me)

**Comment by humphd** [comment]
Yeah, figuring out how to guide people on how to use this stuff is something we should ponder. Maybe we need a project that's about learning the tool vs. making something with it (i.e., tutorial that guides you through things like this)?

**Comment by humphd** [comment]
@hannahkane there are good docs at https://github.com/adobe/brackets/wiki/How-to-Use-Brackets on how to use everything.  Maybe we should distill that down, and put it on the thing you get when you click "Help"

**Comment by hannahkane** [comment]
yup, i'll add it to #567
