### ISSUE TITLE
Keyboard Text increase/decrease don't work as expected

### ISSUE THREAD

**Issue by cassiemc** [mozilla/thimble.webmaker.org#855]
The control + and - keyboard actions to increase and decrease the type size of the UI do not work as expected. It seems that the sizes change the code text size and the UI text sizes independently, which is frustrating when moving between large and small text in order to figure out the perfect size.

So you end up with something like this:
![mozilla_thimble](https://cloud.githubusercontent.com/assets/1186326/9275869/3a3efa22-426e-11e5-8cc7-91c8a29959d6.png)

The UX of the + and - buttons for manually changing the text size could also be improved. They need hover states at minimum.

**Comment by flukeout** [comment]
Seems like a Firefox bug, behaves as expected in Chrome.

Hover & actives states have been added to the plus / minus controls - do you have additional enhancements to the UX in mind?

**Comment by cassiemc** [comment]
That works for now @flukeout, thanks.

**Comment by humphd** [comment]
Fixed now.
