### ISSUE TITLE
Fix clunky text rendering in the UI

### ISSUE THREAD

**Issue by cassiemc** [mozilla/thimble.webmaker.org#857]
The Open Sans type in the top green bar looks okay, but the all-caps type in the editor (and the ‘undo’ button text) looks super clunky. It should ideally be a  bit smaller and match the weight and letter-spacing of the other UI text. I am happy to work with someone on this to get it looking right.

![thimble-text-render](https://cloud.githubusercontent.com/assets/1186326/9275923/95411590-426e-11e5-9617-4f4325111683.png)

I'm using FF40 mac.

cc @flukeout

**Comment by k88hudson** [comment]
I'm also seeing this (Firefox). Looks like the correct fonts are not being loaded for the weights specificied

**Comment by flukeout** [comment]
Fixed!
