### ISSUE TITLE
Streamline icon sizes

### ISSUE THREAD

**Issue by cassiemc** [mozilla/thimble.webmaker.org#858]
The icons are at varied sizes and weights, giving the UI a non-uniform look. We need to adjust the sizes of the the thimble icon (larger), and the publish, undo/redo, settings, and phone/mobile icons (smaller).

![thimble icons](https://cloud.githubusercontent.com/assets/1186326/9275938/bdc2043e-426e-11e5-92eb-78af1a646524.png)

FF40 mac. cc @flukeout

**Comment by humphd** [comment]
@flukeout is there more to do on this one, or is it covered by your other UI fixes?

**Comment by flukeout** [comment]
Done!
