### ISSUE TITLE
Sidebar scrolls to the righthand edge when a file title is very large 

### ISSUE THREAD

**Issue by k88hudson** [mozilla/thimble.webmaker.org#859]
STR: Add a file with a really long name

Expected: The sidebar cuts of the end of the name, the other files are still visible
Actual:
![image](https://cloud.githubusercontent.com/assets/1455535/9283991/1a7b527a-42a6-11e5-8fa3-bda957ca39a8.png)

**Comment by humphd** [comment]
I think this is "don't use really long file names".  Closing.
