### ISSUE TITLE
Can't open thimble-beta.webmaker.org, file format error

### ISSUE THREAD

**Issue by k88hudson** [mozilla/thimble.webmaker.org#861]
When I first load the page (in Firefox), I get this error:

![image](https://cloud.githubusercontent.com/assets/1455535/9284088/d5a74eb4-42a6-11e5-9aac-2972a8418e8e.png)

Followed by this error:

![image](https://cloud.githubusercontent.com/assets/1455535/9284094/e1427b5e-42a6-11e5-9d79-09a9e06d935e.png)

After that, I get an endless loading state, and this in the console:

````
[Thimble error] couldn't extract file for tar" Object { name: "EFILESYSTEMERROR", code: "EFILESYSTEMERROR", errno: 1001, message: "unknown error", stack: "e@https://mozillathimblelivepreview…" }


not well-formed QuickView.less:1:1
not well-formed styles.less:1:1
not well-formed WebPlatformDocs.less:1:1
not well-formed style.less:1:15
not well-formed main.less:1:1
```

**Comment by humphd** [comment]
Well done, @k88hudson, you corrupted your (filer) Filesystem.  I've never seen it happen.  Do you know what you were doing before this?  Also, which browser is this?

I'm working on a fix for this in https://github.com/humphd/brackets/pull/426

**Comment by k88hudson** [comment]
Firefox stable (39.0) on Mac OSX -- this happened immediately the first time I tried to load https://thimble-beta.webmaker.org. It's likely/possible that I've loaded earlier versions of it a long time ago, although I can't remember specifically what I was doing.

I haven't cleared/deleted anything in case you wanted me to look something up -- are you interested in seeing anything else?
