### ISSUE TITLE
Publish link extends past the UI

### ISSUE THREAD

**Issue by k88hudson** [mozilla/thimble.webmaker.org#863]
The link goes off the screen, which makes it hard to select/see

![image](https://cloud.githubusercontent.com/assets/1455535/9284770/b4870796-42ac-11e5-9d6a-4ecd3f017473.png)

**Comment by humphd** [comment]
![screenshot 2015-08-27 12 24 13](https://cloud.githubusercontent.com/assets/427398/9526319/a2f18736-4cb6-11e5-8bef-500613a1dcec.png)


Fixed by @flukeout's publish dialog restyling.
