### ISSUE TITLE
Fonts missing on published project bar

### ISSUE THREAD

**Issue by k88hudson** [mozilla/thimble.webmaker.org#864]
It looks like there are fonts missing:

![image](https://cloud.githubusercontent.com/assets/1455535/9284805/113dbac0-42ad-11e5-8136-384be007ca33.png)

![image](https://cloud.githubusercontent.com/assets/1455535/9284812/16d32344-42ad-11e5-9505-0d8d63887517.png)

**Comment by humphd** [comment]
This is cross origin violation:

```
Font from origin 'https://thimble-beta.webmaker.org' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://d157rqmxrxj6ey.cloudfront.net' is therefore not allowed access.
```

**Comment by humphd** [comment]
@sedge and/or @jbuck, can one of you fix this cross-origin issue?  Perhaps http://kennethjiang.blogspot.ca/2014/07/set-up-cors-in-cloudfront-for-custom.html ?

**Comment by jbuck** [comment]
@humphd You'll need to add the CORS headers to the thimble server, so this should be a small PR
