### ISSUE TITLE
UI Cleanup

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#868]
There are lots of parts of the UI that can use a little polish and TLC. I've listed them all here.

**Tutorial toggle**
* [x] Update preview & tutorial toggle UI

**Refresh Icon**
* [x] Move the refresh icon to the right side
* [x] Update hover & active states
* ~~[ ] Add animation animation after it’s clicked?~~

**Icon Buttons**
* [x] Adjust size and position of all icons, many are too large
* [x] Remove the slow transition to the hover state, makes the editor feel slow
* [x] Make sure they all have hover & active states

**Editor theme colors**
* [ ] Finalize the editor theme colors for both the dark and light themes

**Button Cleanup**
* [ ] Fix the styling, hover and active states of a bunch of buttons.
  * [x] Main Publish button
  * [ ] Buttons in the Publish Dialog
  * [x] Rename Button
  * [x] New Project button on My Projects page

**User Menu**
* [x] Remove the 2px border above the sign out option
* [x] Update the "export" icon with something that connotes a download
* [x] Make sure the hover state background color for menu items in this menu matches the Add File menu
* [x] Change the green background to match the rename UI hover state when the menu is open
* [x] Adjust icon size & positioning

**Publish Menu**
* [x] Button Styling
  * [x] Active & Hover states
  * [x] Rounded corners
* [x] Fix spacing on the description label and textarea
* [ ] Nicer styling on the published project link
* [x] Sort out the 2px borders, they don't look nice.
* [x] Fix padding on the popup heading to match the contents

**Add File Menu**
* [x] Remove green hover effect

**Gear Menu**
* [x] Center + and - icons in the Text Size changer
* [x] Hover & active states for the plus and minus icons
* [x] Fix the styling of the theme toggle
  * [x] Borders are uneven when light theme is on
  * [x] Add cursor:pointer style to the theme toggle
* [x] Make the menu appear instantly instead of fading in
* [x] Center the arrow and the dialog below the gear icon

**Mobile Preview**
* [x] Different styling for the mobile preview toggle
* [x] Different background for the mobile mode (match the grey in the top bar)

**File Tray**
* [x] Expand Tray  and Add File icons need…
  * [x] Hover states
  * [x] Active states
  * [x] Consistent rounded corners
  * ~~[ ] Change the file tree expand / contract UI so that it’s in the same place for easy expanding and collapsing.~~
* [ ] Font size of the filename is too small when renaming

**Header Thimble Logo**
* [x] Add hover & active state

**Project renaming**
* [x] Adjust Save button styling and position
* [x] Project rename pencil icon position
* [x] Tooltip for hovering over the name
* [x] Add additional padding on the project title hover state so it looks even

**Misc**
* [x] Get rid of the white padding under the editor that lets you scroll the editor no matter the window size.

**Tutorial**
* [ ] Reduce padding at the top of the tutorial, we don't need that much.

**Comment by cassiemc** [comment]
awesome ticket! cc me @cassiemc

**Comment by flukeout** [comment]
@sedge @gideonthomas Do you guys know what controls the positioning of the Editor options popup? I can't find it in the markup.

This guy...

![image](https://cloud.githubusercontent.com/assets/25212/9318374/e813ebae-44f7-11e5-8505-0a4d72f3cc5f.png)

It gets a "left" css position that seems to be dynamic, but I can't find where...

![image](https://cloud.githubusercontent.com/assets/25212/9318379/fd50570a-44f7-11e5-8c45-079ab7f8f871.png)

**Comment by sedge** [comment]
@flukeout Here ya go:

https://github.com/mozilla/thimble.webmaker.org/blob/bramble/public/scripts/editor/js/fc/bramble-menus.js#L8

which uses

https://github.com/mozilla/thimble.webmaker.org/blob/bramble/public/scripts/editor/js/fc/bramble-popupmenu.js

**Comment by flukeout** [comment]
* [ ] Tooltip for the "Save" action when renaming your Project

**Comment by flukeout** [comment]
* [ ] Make the gear icon clickable area bigger, not just on the image itself.

**Comment by flukeout** [comment]
Closing this pre-launch checklist, will move to new, separate issues.
