### ISSUE TITLE
Put information about maximum file size in upload prompt or error message

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#869]
I saw some users try to upload images they just took from their phone but they got an error message about file size. Can we list the maximum file size on the upload UI or in the error message?

![image error message](http://goo.gl/9bqUMV "File Size Error Message")

**Comment by humphd** [comment]
Good idea, cc @flukeout for UI thoughts in our uploader.

Also, this raises the question about what our upper-limit should be on the size of a file you can drop on Thimble/Bramble, and we'll allow.  Right now it's set at:

```js
    // 3M size limit for imported files
    var byteLimit = 3 * 1024 * 1000;
```

But that number is totally arbitrary.  It also currently applies to an image you drag in, or a ZIP archive, and we might want different sizes for each?  From a Mozilla/S3/Publish server/Postgres/etc point of view, what should we set it to? cc @davidascher, @simonwex, @jbuck

**Comment by davidascher** [comment]
I would start by understanding what is a reasonable size for an asset that
makes sense as a web project.  In particular, we should probably allow
images that are as large as people would reasonably want to use in a web
page, but provide disincentives for storing huge images (and offer to
downsample larger images on upload).  The primary driver to me isn't cost
savings as much as helping people make pages that will load fast for their
users.

**Comment by humphd** [comment]
I'm conducting some research here: https://twitter.com/humphd/status/636252594202124288.

**Comment by humphd** [comment]
So after months of speculation, we have some data on what users will do if you give them a filesystem that lets you drag-and-drop files from their OS.  As discovered in https://github.com/mozilla/thimble.webmaker.org/issues/1112#issuecomment-143029386, this project is **10M** in size, due to massive images:

https://d157rqmxrxj6ey.cloudfront.net/cabravoeco/12815

We should ponder whether we want to further impose any limits, and/or do some work to reduce image sizes on upload.  Right now, the *only* restriction we have is that you can't upload a file that is larger than **3M**.  But, your project can contain any number of files under **3M**, which can add up.

**Comment by davidascher** [comment]
Three questions:

Does the large project feel like it's a reasonable one or an abusive one?

Would the project work as well if e.g. we facilitated compression on upload?

What does our distribution of sizes look like?

I don't think we need to set policy based on worst case scenarios if users
are being responsible and the average cost stays low.

**Comment by humphd** [comment]
1) Does the large project feel like it's a reasonable one or an abusive one?

It's a totally reasonable project, they just made a complete web site with lots of images.  No abuse here, but if I were doing it, I'd have probably shrunk the images down a bit.  This is honest web work :)

2) Would the project work as well if e.g. we facilitated compression on upload?

I'm not sure how we could do it automatically and have it do the right thing all the time.  This project has a dozen images in the 400K-600K range, which I think is pretty normal.  It also includes a few in the 2M range, like this one https://d157rqmxrxj6ey.cloudfront.net/cabravoeco/12815/AAT_01_1024.png (scan of a page in a book, I think).  We could consider adding some kind of warning for image files over a certain size (>500K and < 3M) that give you info about how to shrink things, and use it as an educational moment? 

3) What does our distribution of sizes look like?

I don't have access to the production database, so I'm not sure.  But I strongly suspect that this is an outlier, and mostly in a good way (someone trying hard to build something they think is important).

**Comment by davidascher** [comment]
Thanks Humph. This all seems like "everything OK".

**Comment by humphd** [comment]
I have a fix for this in https://github.com/humphd/brackets/pull/502.  r? @gideonthomas
