### ISSUE TITLE
+ button does not appear in file tree menu in Safari

### ISSUE THREAD

**Issue by hannahkane** [mozilla/thimble.webmaker.org#878]
This means there's no UI for adding files for Safari users

**Comment by humphd** [comment]
See https://github.com/mozilla/thimble.webmaker.org/issues/574

**Comment by hannahkane** [comment]
Is this a dupe? Should I close it?

**Comment by hannahkane** [comment]
Sorry, to be clearer, I'm not sure if this particular issue is covered in #574 or not.

**Comment by gideonthomas** [comment]
@hannahkane I think #574 is a meta bug that refers to all safari/IE UI issues which I guess would mean that it includes this issue too

**Comment by hannahkane** [comment]
OK, thanks. I'll close this one as a dupe.
