### ISSUE TITLE
Local environment: Unable to edit projects when Signed In

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#883]
Steps to reproduce
* Get your local environment up and running
* Sign In
* Open the thimble editor
  * The starting projects loads correctly
* Refresh
* The editor 'hangs' on the brackets loader

This blocks some of the UI work that I want to do that needs me to be authenticated.

**Comment by flukeout** [comment]
cc @sedge since he's been trying to help me resolve this stuff.

**Comment by gideonthomas** [comment]
@flukeout is this still an issue?

**Comment by flukeout** [comment]
@gideonthomas still is - are you guys running the full thimble locally without this issue?

**Comment by flukeout** [comment]
1. Console error right after signing in
![image](https://cloud.githubusercontent.com/assets/25212/9774372/ebcd4580-56fc-11e5-96fa-0e12c4c138a1.png)

2. Console error after refreshing after step 1 - this is where it gets stuck on the green loading screen
![image](https://cloud.githubusercontent.com/assets/25212/9774384/fee8dfbc-56fc-11e5-947c-5dc7a0461ea6.png)

**Comment by humphd** [comment]
@gideonthomas I watched him do this on appear, and it's like it all worked with the local filesystem, but nothing went to the remote publish server.  Also, we should be showing the "Failed to load your project..." screen vs. spinning forever in this case.

**Comment by humphd** [comment]
Moving this to P1 because @flukeout is blocked on Safari and IE UI fixes without being able to see the whole UI.

**Comment by flukeout** [comment]
Cured by the magical powers of @gideonthomas and the dark art of... "Using git pull to make sure your publish server is up to date".
