### ISSUE TITLE
Crazy URL in address bar when not-signed in

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#884]
This happens when you refresh the browser when you're not signed in...

![image](https://cloud.githubusercontent.com/assets/25212/9343230/953f8f78-45b5-11e5-8a74-f259dc1f07ae.png)

Is it necessary? Is there a way to achieve whatever this is doing without storing it in the address bar?

**Comment by gideonthomas** [comment]
cc @humphd

**Comment by humphd** [comment]
We can change what it has in the URL, but we can't remove it.  The reason this is there is to support multiple tabs being open at the same time, and each one open to a different project.  The only place we can put a unique identifier for *this* tab vs. *that* tab is in the URL.  So if we want to have project-per-tab, we're going to have to use the URL--literally everything else is shared across tabs.

**Comment by humphd** [comment]
Closing, we can't not do this and still support multiple tabs.
