### ISSUE TITLE
Typing cursor invisible in the first possible spot for a cursor on each line in the editor.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#885]
Cursor on position 1...
![image](https://cloud.githubusercontent.com/assets/25212/9343419/bacff5ba-45b6-11e5-887e-d395ee6822c1.png)

Cursor on position 0... gone!
![image](https://cloud.githubusercontent.com/assets/25212/9343423/c301f5e4-45b6-11e5-8c89-e3f756be5d53.png)

Happens on every line.

**Comment by humphd** [comment]
It's something in our theme, I think.  The `margin-left` for `CodeMirror-sizer` is `72px` which is not quite enough (maybe due to use bumping the font size up to `15px`?).  If I set it to `75px` it works as expected.

Adding this to our themes fixes it:

```css
.CodeMirror-sizer {
	margin-left: 75px !important;
}
```
