### ISSUE TITLE
Test UX across browsers

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#892]
We need a final list of fixes to make on Safari, IE (that explorer and edge) and Firefox.

**Comment by gideonthomas** [comment]
See https://github.com/mozilla/thimble.webmaker.org/issues/574

**Comment by hannahkane** [comment]
Note: we can't retire old Thimble until we resolve this ticket; because without it, we don't have parity

**Comment by humphd** [comment]
We have #1096 for this, closing this bug.
