### ISSUE TITLE
Thimble title bar behaves bizarrely on occasion

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#895]
This is what I've seen:

![screen shot 2015-08-19 at 5 12 41 pm](https://cloud.githubusercontent.com/assets/1616860/9369209/b4327ef0-4695-11e5-9663-82c3de0b3b46.png)

I can't tell you STR because it doesn't seem to happen a lot. Refreshing solves the problem

cc: @flukeout 

I've set this as p2, but it might be worth escalating.

**Comment by flukeout** [comment]
@sedge Yeah - I've seen this too, it goes away after refreshing most of the time, so I've gotta check into it.

**Comment by gideonthomas** [comment]
Closing this to continue the conversation in https://github.com/mozilla/thimble.webmaker.org/issues/931
