### ISSUE TITLE
Sometimes deleted projects appear on the project page

### ISSUE THREAD

**Issue by sedge** [mozilla/thimble.webmaker.org#902]
This is a caching issue, and I'm not sure how to approach it.

**Comment by gideonthomas** [comment]
https://github.com/mozilla/thimble.webmaker.org/commit/338f15676aafb44adfded5e9474653a4171d4780 and https://github.com/mozilla/thimble.webmaker.org/commit/3f483e0a008bc66264fee6c66a5465e73239209a seem to have fixed this! We can re-open if this happens again!
