### ISSUE TITLE
Usertesting Watch-a-Thon

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#910]
I've prepared a doc that assigns each of us some usertesting videos to watch and report on:
https://docs.google.com/document/d/1Z3EovRGnyT-tLSp4L7tF-hcVp5uVCajyyp_lg8XUdsU

Let me know if you guys have any questions or if something isn't working right.

cc @humphd @gideonthomas @sedge @hannahkane

**Comment by hannahkane** [comment]
Thanks for this, @flukeout. I just watched my two tests, and left notes on the doc. No critical bugs, though there are some usability concerns we might want to address post-MVP.

**Comment by humphd** [comment]
I think this is done now, right @flukeout?  Can you close this if so?
