### ISSUE TITLE
When signed in, https://thimble-beta.webmaker.org/ redirects to My Projects page

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#912]
Looks like if you just hit the base thimble URL on staging and production beta, you just go to the My Projects page when you're signed in. This is different than how it used to work - is this expected behaviour? 

Now it looks like the username and project ID is in the address bar all the time ``https://bramble.mofostaging.net/user/flukeout/205``.

**Comment by humphd** [comment]
All of this is correct.  In order to have things work in multiple tabs, you have to have the URL be pegged to a project, either an anonymous one or one you own.  In both cases we have to redirect you to something that identifies the project you're opening.

**Comment by humphd** [comment]
We're changing this to be the homepage, and `/projects` for your project page.  Closing.
