### ISSUE TITLE
Project CSS overriding Details Bar CSS

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#913]
Note the styles of the text in the Details Bar.

![image](https://cloud.githubusercontent.com/assets/25212/9448220/558902f2-4a50-11e5-8201-588b01afa43c.png)

Solutions?
* Make a more 'defensive' stylesheet for the details bar with a lot of explicit values and important! declarations.
* Make sure the details bar styles load after the project styles.

**Comment by humphd** [comment]
I'd do the first, since the project might inject styles dynamically via JS, and break whatever ordering you do.

**Comment by flukeout** [comment]
@gideonthomas Are you able to publish locally? I'm unable to and it makes it hard to implement the changes from https://github.com/flukeout/thimble-home/commit/25e296bf80a0f3d99ac22a6ce9de4c8345b979ec
