### ISSUE TITLE
Ensure the most recent metadata for a published project is used in the remix bar

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#917]
In the editor...

![image](https://cloud.githubusercontent.com/assets/25212/9451628/aa32d8dc-4a64-11e5-8987-d48335a40ca6.png)

In the details bar after publishing...

![image](https://cloud.githubusercontent.com/assets/25212/9452059/0fd705b2-4a67-11e5-8b20-3d2f33ef1c8b.png)

Published project url: https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/62/

**Comment by humphd** [comment]
Looking at that page's markup, I see:

```html
<meta name="data-remix-projectTitle" content="Back-to-School Postcard Teaching Kit">
<meta name="data-remix-projectAuthor" content="mozillalearning">
<meta name="data-remix-dateUpdated" content="2015-08-24T20:32:20.794Z">
<meta name="data-remix-host" content="https://thimble-beta.webmaker.org">
<meta name="data-remix-projectId" content="20">
<meta name="data-remix-projectTitle" content="Keep Calm Meme Teaching Kit">
```

Both the old and new titles are in there, and the second one overrides.  Why is it double injecting?

**Comment by humphd** [comment]
Actually, other stuff is repeated, too.  Here's the entire meta block:

```html
<meta name="data-remix-projectId" content="77">
<meta name="data-remix-projectTitle" content="Back-to-School Postcard Teaching Kit">
<meta name="data-remix-projectAuthor" content="mozillalearning">
<meta name="data-remix-dateUpdated" content="2015-08-24T20:32:20.794Z">
<meta name="data-remix-host" content="https://thimble-beta.webmaker.org">
<meta name="data-remix-projectId" content="20">
<meta name="data-remix-projectTitle" content="Keep Calm Meme Teaching Kit">
<meta name="data-remix-projectAuthor" content="mozillalearning">
<meta name="data-remix-dateUpdated" content="2015-08-13T21:16:33.705Z">
<meta name="data-remix-host" content="https://thimble-beta.webmaker.org">
```
NOTE that `data-remix-projectId` is also there twice, and with different values!

**Comment by flukeout** [comment]
If it helps, this project was Unpublished - and immediately republished.

**Comment by hannahkane** [comment]
Could be user error. Maybe a c/p mistake?

**Comment by sedge** [comment]
@flukeout Did you copy/paste the published markup for this project? That would explain this behaviour.

**Comment by flukeout** [comment]
@sedge Ah yes - that's exactly what happened.

**Comment by humphd** [comment]
We're going to solve this by making sure the script that runs uses only the *first* set of metadata in the head.
