### ISSUE TITLE
Add "Try the new Thimble" banner to the old Thimble.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#921]
@hannahkane Here's a take on this, let me know your thoughts.

![image](https://cloud.githubusercontent.com/assets/25212/9477518/c266e538-4b27-11e5-91da-24150938ebfd.png)

The message is dismissible via the small "x", but would come back on refresh.

Let's figure out the wording.

**Comment by hannahkane** [comment]
Design and behavior is great.

/cc @KevZawacki for copy edits. My suggestion would be something like "We've launched a new version of Thimble! Want to [take it for a spin]?" I don't know that this is the right place to describe the future migration, but I defer to @KevZawacki.

**Comment by KevZawacki** [comment]
I think it's a good idea to address migration in the banner -- users often ask about it on social and help@, so it's a nice way to get ahead of those questions.

The copy in the banner above works for me. (But should rearrange to "...migrating over all old projects.")

Can we include a specific date for the shutdown/migration?

**Comment by hannahkane** [comment]
We don't have a specific date, unfortunately. Also, can we avoid saying "old" projects? What about, "migrating existing projects to the new version"?

**Comment by KevZawacki** [comment]
+1. So, "There's a new Thimble! Soon we'll be shutting down this version and migrating over existing projects. Try out the new Thimble!"

**Comment by flukeout** [comment]
Okay - I'll make the changes and provide markup for @sedge to implement.

**Comment by flukeout** [comment]
@sedge Here are the things...

Banner - http://flukeout.github.io/thimble-home/thimble-banner/
Assets - https://github.com/flukeout/thimble-home/tree/master/thimble-banner

Let me know if you have any questions or need help.

**Comment by sedge** [comment]
This has landed. All we need to do now is push this to production when the time is right and set the new environment variable to point at our new thimble production url.

cc: @jbuck
