### ISSUE TITLE
Horizontal alignment of editor toolbar wrong on startup

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#924]
![screenshot 2015-08-26 10 39 21](https://cloud.githubusercontent.com/assets/427398/9496600/1bfa7184-4bdf-11e5-8fa4-506b0aaed121.png)

A recent CSS change in Thimble has broken how the editor toolbar looks on startup, making it bump down to the next line.  Once Brackets finishes loading, it fixes itself; but looks messy while we start.

@flukeout, can you fix?

**Comment by flukeout** [comment]
@humphd It looks like this is happening because we're showing the file tray while Brackets is loading, which we weren't doing before, and the 'resize bars' code isn't firing. We can keep the file tray hidden until Brackets loads, in which case it should work fine.
