### ISSUE TITLE
Project name not persisiting

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#927]
I rename a project and see..
![image](https://cloud.githubusercontent.com/assets/25212/9502987/4840f0ec-4be9-11e5-9044-d708c7e46bbb.png)

Then I refresh and see..
![image](https://cloud.githubusercontent.com/assets/25212/9503000/5899e1f6-4be9-11e5-95cf-9dd93c4166e0.png)

On project https://thimble-beta.webmaker.org/user/flukeout/39

It shows up currectly in the project list however..

![image](https://cloud.githubusercontent.com/assets/25212/9503435/caa65840-4beb-11e5-9bf6-5c265504e039.png)

**Comment by flukeout** [comment]
In addition, I can publish this...
![image](https://cloud.githubusercontent.com/assets/25212/9503476/fdbd3da2-4beb-11e5-9377-529f24599642.png)

But on refresh it shows as not published again...
![image](https://cloud.githubusercontent.com/assets/25212/9503482/0ad92ffa-4bec-11e5-8d77-b401caf1b920.png)

**Comment by gideonthomas** [comment]
Project rename persisting: I can reproduce the error on staging but not prod.
Publish link vanishing: I can reproduce on both staging and prod.

I can't reproduce either locally :/

This issue is weird

**Comment by flukeout** [comment]
I've also noticed this bug in one of the usertests.

**Comment by humphd** [comment]
I can't reproduce the rename/reload bug on staging or prod.

**Comment by humphd** [comment]
The publish link vanishing, I can only hit on staging, prod is working fine for me.

We should probably get the 3 of us on appear and try to reproduce these.  There must be more steps one needs to do.

**Comment by gideonthomas** [comment]
So this is definitely a cache issue where cloudfront is sending a cached version of the page (hence why we can't reproduce locally).

Here's a GIF of what's happening on staging:
![cache-issue](https://cloud.githubusercontent.com/assets/5816130/9527763/e0918bc4-4cbe-11e5-8c8d-c24dfd656efd.gif)

STR:
* Create a new project (you see the project title as "Untitled Project")
* Rename the project to something
* Refresh the page and it shows "Untitled Project" as the title
* Refresh the page with a cache bust querystring attached to the url...you see the correct title

@jbuck any ideas as to how we can fix this?

**Comment by jbuck** [comment]
@gideonthomas is that page sending a Cache-Control header? If not, then add one and your problems should be solved
