### ISSUE TITLE
Editor "Stuck" after creating a New Project (via Usertesting)

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#930]
User attempted to create a new project and got stuck with Brackets not ever loading...

![image](https://cloud.githubusercontent.com/assets/25212/9507346/6d150e1c-4c02-11e5-888f-a4c9d78e5757.png)

Additionally, preceding this, the project rename feature wouldn't stick. Maybe they're related?

For reference, the URL in the screenshot is ``thimble-beta.webmaker.org/user/codex73/67``

**Comment by humphd** [comment]
It's hard to know, but it could be a corrupt filesystem in the browser, similar to https://github.com/mozilla/thimble.webmaker.org/issues/861.

Let's discuss this one in standup today.

**Comment by humphd** [comment]
I've landed a fix for the filesystem getting wedged.  If a user refreshes, it will fix it.  Let's open again if we see this happen.  I'll need more data to fix it, though, if it's not that.
