### ISSUE TITLE
Editor bar is out of place sometimes after a refresh.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#931]
Noticed during a usertest here...
![image](https://cloud.githubusercontent.com/assets/25212/9509036/2f9ef5c6-4c10-11e5-8fd8-661e855c5a03.png)

Might be some kind of error in the resize code. It resolves itself when you change the column widths.

**Comment by humphd** [comment]
I've seen this in another user testing video, too.  I've never been able to reproduce it, but it kind of looks like the problem we saw with the file tray being open on startup.  If you see this again, screenshot the entire window so we can see what's going on.

**Comment by gideonthomas** [comment]
I can't reproduce this anymore (I feel like we fixed this recently).

**Comment by flukeout** [comment]
Fixed
