### ISSUE TITLE
When adding a new file, it's hard to see where it went after you rename it.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#935]
If you have a project with a lot of files and you add a new file, it gets placed in the UI according to it's name (Untitled), then when you rename it, it jumps into a different place based on the alphabetical ordering. It's really easy to lose sight of this when it happens. 

This can be solved by having the selected file highlighted in the UI. We already do this when a file is clicked, can we also do it programmatically?

**Comment by humphd** [comment]
See discussion in https://github.com/humphd/brackets/issues/435#issuecomment-134304465.  We need to do some surgery on the file tree in Brackets for this to work.

**Comment by flukeout** [comment]
Noted, just keeping it here for later - it's a good case to consider when prioritizing improvements later.
