### ISSUE TITLE
Reduce horizontal space taken up by line numbers in the Editor.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#945]
See below.. that's a lot of space we're losing...

![image](https://cloud.githubusercontent.com/assets/25212/9531130/0ccb0770-4cb9-11e5-891f-8f8d098516d6.png)

**Comment by humphd** [comment]
Show/hide line numbers is just a pref you can toggle.  The code is in https://github.com/humphd/brackets/blob/bramble/src/editor/EditorOptionHandlers.js, and we could expose a way to call it from Thimble easily.

**Comment by flukeout** [comment]
I don't mean hiding & showing, that would be handy too - I mean when showing, it has room for probably 5 or 6 digits, which is too many.

**Comment by Rdilorenzo73** [comment]
I agree with @flukeout .  The relative size of the line numbers / code folding area in the editor is too large.  I think it would be better to have be around 5-7% of the space in the editor area.
