### ISSUE TITLE
[Production] When you unpublish a published project, and then publish it again - it 404s

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#949]
**Steps to reproduce**
* Create a new project
* Publish it
* View the project link, project is there
* Unpublish it
* View the project link, it's a 404
* Publish it again
* View the project link, it's still a 404

Reference project https://d157rqmxrxj6ey.cloudfront.net/flukeout/155/

Shows as Published in the UI
![image](https://cloud.githubusercontent.com/assets/25212/9531983/bd4203b6-4cbd-11e5-9d0b-fa79a85f221b.png)

**Comment by sedge** [comment]
I've confirmed that republishing occurs correctly, meaning this is a cache issue.

cc @jbuck

**Comment by humphd** [comment]
I saw this in user testing, too, and have confirmed it myself on thimble-beta.

My project is at https://d157rqmxrxj6ey.cloudfront.net/humphd/177/, and I get this:

```
Age:116
Cache-Control:max-age=0
Connection:keep-alive
Content-Length:4432
Content-Type:text/html
Date:Fri, 28 Aug 2015 13:54:37 GMT
ETag:"09b038013f74779f346a0d8a77d1b6c6"
Last-Modified:Fri, 28 Aug 2015 00:41:56 GMT
Server:AmazonS3
Via:1.1 d1745c8d38a4f982b7d526bda072bbcf.cloudfront.net (CloudFront)
X-Amz-Cf-Id:cdMcC6LTmOCtPk-19SmCOMVqae0SRu1LA30glCKSjF5PHSmI-lfVfw==
x-amz-delete-marker:true
x-amz-error-code:NoSuchKey
x-amz-error-detail-Key:humphd/177/index.html
x-amz-error-message:The specified key does not exist.
x-amz-version-id:DhxWZtFY2tiTTZ_TCPws8HpbgJVkHgh9
x-amz-version-id:EVTOvPSid41QzlejtXTTirwwMclAUDLs
X-Cache:Error from cloudfront
``` 

Are we sending cache control on the 404?

**Comment by sedge** [comment]
@flukeout Can you confirm if this is fixed?

**Comment by flukeout** [comment]
Looks good! Closing!
