### ISSUE TITLE
Missing image in Keep Calm teaching kit.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#953]
![image](https://cloud.githubusercontent.com/assets/25212/9532900/4dbfc306-4cc3-11e5-8035-6ea2ef0087dd.png)

https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/28/

**Comment by hannahkane** [comment]
Added

**Comment by flukeout** [comment]
Thanks @hannahkane
