### ISSUE TITLE
Preview stops working if you press Enter outside of a tag.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#957]
Steps to reproduce
* Edit some copy in a tag
  * Preview shows changes
* Click outside of the tag and hit enter
* Click back into the tag and edit the copy some more
  * Preview stops working

![preview-fail](https://cloud.githubusercontent.com/assets/25212/9535396/b26265d6-4cd5-11e5-8ded-eaf58bec91aa.gif)

**Comment by gideonthomas** [comment]
I cannot reproduce :(

**Comment by humphd** [comment]
@flukeout is this still happening?  We can't reproduce.

**Comment by flukeout** [comment]
I can't reproduce it anymore, let's close.
