### ISSUE TITLE
Increase visibility of Remix so users can find it more easily

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#959]
We don't do enough to help users find the Remix flow for a project.  He should consider adding some/all of these:
* on Projects page, beside each project's title and delete button
* in user menu near "New Project..." so that they can remix the current project from the editor
* in the Publish dialog, we should give 2 links: one to view the project, another to use if you want friends to be able to remix what you made

**Comment by flukeout** [comment]
Good ideas!

We used to have a remix button on the My Projects page but it went away. I feel like the way things have been changed to allow for remixing from the homepage, we could easily implement this again.

Not that sure about bullet point 3, if you send a link to the project, the remix button is right at the top.
