### ISSUE TITLE
Add ability to link to a specific page in the browser player.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#970]
I'd like to be able to link to a specific page of a project when sharing a link. Could we keep track of the current page in the address bar when viewing? Then I can share that link with someone and they would start on that page.

Kind of like how youtube lets you link to a specific point in the timeline, which is handy.

Also, it's webby (tm) :ant: <- closest I could get to a spider

cc @vazquez @xmatthewx

**Comment by xmatthewx** [comment]
Interesting. Our current buttons don't expose an anchor URL, but maybe they could. Then I could like to /user/project/page or /user/project#page

**Comment by xmatthewx** [comment]
Wait @flukeout - this is the thimble repo. Either way: https://github.com/mozilla/webmaker-core/issues/601#issuecomment-135854041

**Comment by humphd** [comment]
@flukeout can you move this to the right repo?

**Comment by flukeout** [comment]
Oops! Closing.
