### ISSUE TITLE
Mobile view container div shouldn't scroll horizontally

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#974]
![screenshot 2015-08-28 17 56 17](https://cloud.githubusercontent.com/assets/427398/9557934/254483da-4dae-11e5-947e-24e9ac82fcae.png)

You can scroll the mobile view up and down, it should be locked in place. (cc @Pomax).

**Comment by flukeout** [comment]
@humphd What do you mean? If the content is taller than the phone, you don't want it to scroll?

**Comment by humphd** [comment]
I think the phone needs to be stationary, and we shouldn't have 2 scroll bars that depend on focus (on OS X it's really bad, because it means you have to click to get this right).

![scrollbar-bug](https://cloud.githubusercontent.com/assets/427398/9621298/e64d3364-50f2-11e5-8bf8-bc80d193da4d.gif)

**Comment by humphd** [comment]
@flukeout fixed this, closing.
