### ISSUE TITLE
Thimble doesn't remember my theme settings.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#975]
Steps to reproduce
* Switch to dark theme
* Refresh the browser
* Reverts to white

![theme-forget](https://cloud.githubusercontent.com/assets/25212/9558181/70384afa-4d97-11e5-80a0-e2342fe994c2.gif)

**Comment by humphd** [comment]
Are  you in an incognito tab when this happens?  That's the only time I see it, and I think it's due to storage rules being different.  If not, I'll dig into it.

**Comment by flukeout** [comment]
No, not incognito. Just opening the editor from thimble.mozilla.org puts it in a weird state...

Light theme visible, dark theme selected in UI
![image](https://cloud.githubusercontent.com/assets/25212/9586251/7ebd1750-4fd0-11e5-9ffe-1c55311f4bc9.png)
