### ISSUE TITLE
Automatically remix a linked project if the current user doesn't own it

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.webmaker.org#979]
If I link someone to https://bramble.mofostaging.net/user/monkeymagic/270, they are redirected to the default thimble project, instead of the project I wanted them to see. This seems to violate the promise that the URL I gave them sets up.

I'd recommend *always* loading up the remix version of a project for bramble project URLs, unless the user is both authenticated, and it is their own project.

**Comment by sedge** [comment]
The idea here is that links to projects should be sharable. The other option is to make it clearer that only published projects can be remixed. We could show the remix link as well as the published link in the publish dialog?

**Comment by gideonthomas** [comment]
Maybe we should consider changing the url too. Maybe something like:
`/user/monkeymagic/private/270` and `/anonymous/private/<uuid>`
That might help?

And once we settle on a domain for published projects, it might be even clearer!

**Comment by humphd** [comment]
We're dealing with this in #1120, closing here.
