### ISSUE TITLE
"new tab" and "url bar" keyboard mappings are not honoured

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.webmaker.org#980]
Based on https://github.com/humphd/brackets/issues/421, the new thimble intercepts keyboard shortcuts for new tab and URL bar, which is a problem both for accessibility and for ease of use - intentional universal browser shortcuts are, ideally, not overruled. 

Current support matrix:

- [ ] ctrl/cmd-T (new tab)
- [ ] ctrl/cmd-L (url bar)
- [x] alt/option-left (force-navigate to previous page)
- [x] alt/option-right (force-navigate to next page)

I'd strongly recommend remapping (or disabling) the interception of those first two.

**Comment by humphd** [comment]
https://github.com/adobe/brackets/wiki/User-Key-Bindings

**Comment by humphd** [comment]
This has landed on staging, and we'll be on prod soon.  Closing.
