### ISSUE TITLE
Clean up artifacts from old-thimble in the new-thimble codebase

### ISSUE THREAD

**Issue by jbuck** [mozilla/thimble.webmaker.org#983]
There's some MakeAPI cruft in the codebase still, think about how good it'll feel to do some cleanup! Just `git grep MAKE`

**Comment by sedge** [comment]
There's a lot left over that needs to be pruned. I'm morphing this into a more general purpose cleanup issue.

**Comment by gideonthomas** [comment]
Most of this is already done. We can work more on this later on, but for now, closing.
