### ISSUE TITLE
Postcard starter project is broken

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#984]
Not sure how this is supposed to look but it doesn't seem right:

**In the preview**
![postcard 1](https://cloud.githubusercontent.com/assets/5816130/9582817/aea762e0-4fd5-11e5-8065-99ce589f0b64.png)

**Published**
![postcard 2](https://cloud.githubusercontent.com/assets/5816130/9582829/bda94786-4fd5-11e5-8d43-a61717a6f89c.png)

**Comment by chadsansing** [comment]
cc @hannahkane, maybe we can scrub out the address lines on the right side/button side of the postcard? Not yet set up for image editing on my machine, but will be by the end of the week. The postcard-back template is an image, so editing that is probably the fastest way to ship a cleaner-looking make.

**Comment by hannahkane** [comment]
@chadsansing - can I assign this to you?

**Comment by chadsansing** [comment]
@hannahkane - yes; I can do this soon.

**Comment by chadsansing** [comment]
Done.

![postcard1](https://cloud.githubusercontent.com/assets/4128600/9632010/82ff5368-5152-11e5-8280-4ed736663399.png)

**Comment by humphd** [comment]
Can we close this now?
