### ISSUE TITLE
the "publish" button should ask me to log in or sign up

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.webmaker.org#985]
Right now the button looks perfectly functional, and just makes the login/signup div flash. This means nothing to me. If it wants me to log in or sign up first, it should inform me that is what I need to do, as well as disable itself (perhaps even change its label) so that I get a clear signal that I cannot keep doing what I was doing.

(pressing a button multiple times because it didn't work the first time is probably the most common button behaviour)

**Comment by gideonthomas** [comment]
cc @flukeout and @hannahkane

**Comment by sedge** [comment]
From my observations of user testing, the flashing has been effective in guiding the user to sign-up to publish.

**Comment by Pomax** [comment]
Never let "effective" get in the way of "making things more effective". Especially for accessibility purposes (think population cross sections in the classroom), not everyone can even see the contrast difference that happens when you click publish. Prevent people from trying to even click a second time before they notice the flashing is probably worth looking at. (A notice that actually has the text "you need to log in or sign up before you can publish" in addition to flashing is going to make life for people with imperfect vision a lot better, for instance)
