### ISSUE TITLE
Share user preferences (theme, pane sizes, etc.) between browsers

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.webmaker.org#986]
if I log in on a different browser, my theme choice is clearly not saved along with my files. It would be a useful thing for that to carry over so that if I log in, all my personalised settings are used.

**Comment by gideonthomas** [comment]
@Pomax do you have a suggestion for how to solve this? We kinda have the same issue with a couple of different pieces of info that we need to share between browsers, but we're not sure how to approach the problem!

**Comment by gideonthomas** [comment]
Going to change the issue title to reflect - sharing prefs between browsers. 
Remembering theme prefs in the same browser is filed [here](https://github.com/mozilla/thimble.webmaker.org/issues/975)

**Comment by humphd** [comment]
Personally, I'd WONTFIX this.  You're going to need to implement 2-way browser sync for this to work properly.  Like @Pomax, I'd like this as a power user; but I can't imagine our core users needing it.

**Comment by humphd** [comment]
I'm going to WONTFIX as promised.  Great idea but not in scope.
