### ISSUE TITLE
Sign-up Redirect 400

### ISSUE THREAD

**Issue by jbflowers** [mozilla/thimble.webmaker.org#995]
I got a 400 after trying to sign up. Steps I took were: 

1. Go to sign up and get sent to Webmaker sign up
2. Find out there's an account with my email already
3. Try to log in with my email
4. It says I need to make a password
5. Make password and get redirected to this URL:

https://id.webmaker.org/login/oauth/authorize?client_id=wm_id_wMvw9BSwq2AITV480dxr&response_type=code&state=7e66c3b1-308d-43df-8406-1808c003cb1b&scopes=user%20email&uid=spadros&email=justinisflowers%40gmail.com&token=fogig-mosuz

And get a page with this JSON:

{"statusCode":400,"error":"Bad Request","message":"\"uid\" is not allowed. \"email\" is not allowed. \"token\" is not allowed","validation":{"source":"query","keys":["uid","email","token"]}}

I went back to Thimble and I successfully logged in so I imagine this is just a redirect problem.

**Comment by gideonthomas** [comment]
cc @cadecairos @jbuck

**Comment by jbuck** [comment]
This is https://github.com/mozilla/id.webmaker.org/issues/364

**Comment by raphaelbastide** [comment]
Same here.

**Comment by jbuck** [comment]
Okay, this is fixed on staging, pushing the fix up to production

**Comment by jbuck** [comment]
All fixed up. Thanks for reporting this bug @jbflowers and @raphaelbastide !
